- CONTRIBUTING.md
As discussed in Issue: https://github.com/transloadit/transloadit-js-client/issues/14.
> Added CSS coding standards.

- classes.es6
I probably got a lot wrong in this as I haven't studied ES6 much yet beyond a few *classes are wrong* outcries. But here are 80loc that work well as a structure for me.
It demonstrates 2 usable plugins (DragDrop and Tus10) of different plugin types (selecter and uploader) that each have access to core to update progress, as well as can modify each others files (uploaders can only use selects, the order of plugin types is important).
It's missing async nature and callbacks. Classes should be split out into different files.. etc etc. But in terms of structure this 'works for me'
> 'working' ES6 classes example

- package.json
- src/core/Transloadit.js
- src/plugins/DragDrop.js
- src/plugins/Tus10.js
Thanks to:
http://trevorburnham.com/presentations/flow-control-with-promises/#/16
http://bluebirdjs.com/docs/coming-from-other-libraries.html#async.waterfall
and personally Roman Liutikov @roman01la
> Second crack at reimplementing async.waterfall and async.parallel in Promises

- src/plugins/GoogleDrive.js
- src/plugins/Modal.js
- website/src/examples/fakemodal/app.es6
Here's what I have so far.  Wanted to merge in.
> Feature google refactor

- src/locales/pt_BR.js
good luck with your project! looks good so far
> pt_BR localization

- src/locales/pt_BR.js
You guys should set up something simple on Crowdin, they have an application for FOSS projects :)
Makes everyone's life easier as you can use variables, proper file encoding and such.
Keep up the good work on uppy!
> Translated the most recent strings

- website/src/guide/contributing.md
See https://github.com/transloadit/uppy/pull/133
> Add steps to install node modules

- src/generic-provider-views/AuthView.js
- src/generic-provider-views/index.js
- src/plugins/Dropbox/index.js
- src/plugins/GoogleDrive/index.js
- src/scss/_provider.scss
I assume there might be better ways to go about this. Please review and let me know your thoughts @arturi 🙂
> feature: smoother auth process

- .babelrc
- bin/build-js.js
- package.json
- website/build-examples.js
It solves same problems as #163 and `yo-yoify-standalone`, but simpler and better.
> Switch to babel-plugin-yo-yoify

- src/plugins/Transloadit/index.js
- test/unit/Transloadit.spec.js
I forgot to update them after changing a few things in the last PR :see_no_evil:
> Fix Transloadit plugin tests.

- website/src/_posts/2017-05-0.16.md
> Some polish

- src/plugins/Tus10.js
ref transloadit/uppy-server@011dadbe476cd1a1d21fff5557cc2cf20c8d19dd
> tus: support metadata in remote uploads

- example/main.js
- src/plugins/Dashboard/index.js
- website/src/examples/dashboard/app.es6
> Move StatusBar and Informer install into the Dashboard (bundle them)

- CHANGELOG.md
- package-lock.json
- package.json
- src/core/Utils.js
- src/generic-provider-views/Browser.js
- src/generic-provider-views/Table.js
- src/generic-provider-views/TableRow.js
- src/generic-provider-views/index.js
handleFileDoubleClick, handleFolderDoubleClick --> handleFileClick,
handleFolderClick
> Fix provider mobile

- .gitignore
- examples/bundled-example/index.html
- examples/bundled-example/main.js
- examples/cdn-example/index.html
- package.json
Inline with [documenting uppy for the transloadit website](https://github.com/transloadit/content/pull/371), I wrote a non-bundled version of the example so it's more concise for new users.
> docs: non bundled example

- src/core/Core.js
> Add simple reset() method to core that clears files and totalProgress

- src/generic-provider-views/AuthView.js
- src/generic-provider-views/Breadcrumb.js
- src/generic-provider-views/Breadcrumbs.js
- src/generic-provider-views/Browser.js
- src/generic-provider-views/Error.js
- src/generic-provider-views/Loader.js
- src/generic-provider-views/Table.js
- src/generic-provider-views/index.js
- src/plugins/Dashboard/FileItem.js
- src/plugins/Dashboard/Tabs.js
- src/plugins/Dropbox/index.js
- src/plugins/GoogleDrive/index.js
- src/plugins/Instagram/index.js
- src/scss/_dashboard.scss
- src/scss/_provider.scss
- Added type="button" to buttons, to prevent submitting forms
- Added `isSearchVisible`, search bar now appears after click on search
icon (up for debates ;-)
- Grid and list views, list by default
- Root directory is named by the provider title (Instagram, Dropbox),
instead of `/`
- If file size is unknown, it is not shown, as opposed to showing `?`
- Headers hidden just for now, since we only had name, and sorting by
name is not something you toggle often when selecting a file. Once we
have size and creation date there (and whatever else), let’s restore
headers
> Provider UI overhaul

- src/plugins/Transloadit/index.js
Previously, the initial assembly data was reused in the complete event…
:see_no_evil:
This patch fetches the assembly status again when the socket emits
`assembly_finished`, so we're always up to date.
Ref #240
> transloadit: Retrieve completed assembly for `complete` event

- src/plugins/Multipart.js
- src/plugins/Tus10.js
> tus: return immediately if no files are selected, fixes #214

- src/core/Core.js
- src/plugins/Transloadit/index.js
- src/plugins/Tus10.js
I think I got all the uses of `state.files[fileID]`.
> core: Add `getFile` method.

- src/plugins/Transloadit/index.js
Refs
https://github.com/transloadit/uppy/pull/244#issuecomment-313845617
https://github.com/transloadit/uppy/pull/244#issuecomment-314021188
> transloadit: Rename `:assembly` event to `:assembly-created`

- CHANGELOG.md
- src/plugins/Instagram/index.js
this PR flattens IG carousels, and displays them as individual files. Please review :)
> Instagram carousels

- src/index.js
These were missing, see https://community.transloadit.com/t/unable-to-get-to-work-the-awss3-plugin/14477/2
GoldenRetriever is also not in it--but we can't do the serviceWorker thing from the unpkg bundle anyway.
> Add missing plugins to the unpkg bundle.

- src/core/Core.js
- src/plugins/Dashboard/FileCard.js
- src/plugins/Dashboard/index.js
> Submit FileCard on enter key

- .travis.yml
> Bump node version to `6.11.3` for Travis builds

- src/core/Core.js
- src/core/Core.test.js
Adds remaining tests.
Fixes bugs:
- hideInfo (this method didn't work as it pointed to this.core.state instead of this.state)
> [WIP] Remaining tests for src/core.js

- src/core/Core.test.js
- src/core/Utils.js
- src/core/Utils.test.js
> Better `generateFileID`

- src/core/Core.js
> Fix calculateTotalProgress - NaN

- src/core/Core.js
- src/core/Core.test.js
Fixes #344
I’m wondering if I’m missing something. Unit tests and my manual tests pass.
> Adjust checkMinNumberOfFiles

- examples/bundled-example/sw.js
- src/plugins/RestoreFiles/IndexedDBStore.js
- src/plugins/RestoreFiles/ServiceWorker.js
- src/plugins/RestoreFiles/ServiceWorkerStore.js
- src/plugins/RestoreFiles/index.js
Fixes #348 by renaming things a little internally
> restore: Fix restorefiles with id

- src/plugins/RestoreFiles/index.js
This patch makes sure only blobs that are referenced by the localStorage
state are actually restored. Blobs that are returned from the persistent
serviceWorker or IndexedDB stores, but aren't referenced by the `files`
state object restored from localStorage, will be deleted.
<strike>Should fix #348.</strike>
Part of #324, but we need to do more before we can call that fixed :)
> restore: Clean up blobs that are not related to a file in state

- package-lock.json
- package.json
- src/core/Utils.js
- src/core/Utils.test.js
- src/plugins/Tus10.js
- src/plugins/XHRUpload.js
For now, rejecting the upload if all file uploads failed.
Todo:
- maybe work on resolving with, and emitting, an object with `successful` and `failed` uploads? or do that in another followup?
> upload resolution changes, followup to #323

- src/plugins/AwsS3/index.js
consistency with other plugins.
> s3: Use Translator for localised strings

- src/plugins/Transloadit/index.test.js
No new tests added, just rewritten the old ones from tape to jest.
> transloadit: Port old tests from tape

- CHANGELOG.md
- examples/aws-uppy-server/.gitignore
- examples/aws-uppy-server/aliasify.js
- examples/aws-uppy-server/index.html
- examples/aws-uppy-server/main.js
- examples/aws-uppy-server/package-lock.json
- examples/aws-uppy-server/package.json
- examples/aws-uppy-server/readme.md
- examples/aws-uppy-server/server.js
- website/src/docs/server.md
companion to https://github.com/transloadit/uppy-server/pull/43
> uppy-server docs for s3 `getKey` option

- src/plugins/Tus.js
> fix: handle remote upload error events #446

- src/core/Utils.js
adding more extensions to map mimetype so the thumbnails of these image types can be previewed
> add more extensions for mimetype detection

- website/src/docs/fileinput.md
- website/src/docs/informer.md
- website/src/docs/plugins.md
- website/src/docs/progressbar.md
- website/src/docs/webcam.md
Not a whole lot to say about these plugins, but good to have some official reference anyway :)
> Add docs for remaining plugins

- src/plugins/FileInput.js
- website/src/docs/aws-s3.md
- website/src/docs/dashboard.md
- website/src/docs/fileinput.md
- website/src/docs/uppy.md
Here are a bunch of documentation fixes and improvements that I gathered while trying out Uppy for the first time.
> Documentation fixes and improvements

- examples/cdn-example/index.html
Informer is already included in the Dashboard plugin.
> Removed Redundant Plugin Inclusion

- src/locales/fi_FI.js
Added locale for Finnish language. Would love to use this tool in my personal projects and projects in my current company, but can't use it unless there's a locale for Finnish. :)
> Add locale for Finnish language

- src/locales/cs_CZ.js
I have added Czech localization.
> Added Czech localization

- package-lock.json
- package.json
- src/plugins/XHRUpload.js
- test/.eslintrc.json
- test/endtoend/specs/uppy.test.js
- test/endtoend/src/index.html
- test/endtoend/src/main.js
The fix turned out to be quite simple. The test doesn't quite work yet, I'm mostly writing it to try to figure out how to webdriver :)
> Fix progress with `limit`ed XHRUploads

- src/plugins/Webcam/PermissionsScreen.js
- src/scss/_webcam.scss
Styling made similar to rest of dashboard options such as of Google Drive, Instagram, etc.
> Font styling for Webcam option

- src/plugins/StatusBar/index.js
This will make sure the upload button is also hidden when files are
still processing, but not uploading any bytes.
Fixes https://transloadit.slack.com/files/U4D4GMZ5H/F8T0A8XA9/image.png
> statusbar: Account for processing in `newFiles` prop

- website/src/docs/progressbar.md
> Fix documentation error

- src/scss/_variables.scss
I'm using uppy with bootstrap, I need to override zIndex value to make sure uppy dashboard is on the top.
> allow user to override sass variables.

- README.md
** Just suggestions none of the fixes are major grammatical mistakes and can be ignored if preferred, thank you for reading ** 
1.  It appears that you are missing a comma after the introductory phrase In that case. Consider adding a comma.
2.  An unnecessary comma before the dependent clause marker when. Consider removing the comma.
3. Your sentence contains a series of three or more words, phrases, or clauses.
4. You have used the compound adjective more plain. Consider using the comparative form of this adjective.
> Updated README, with minor grammar fixes.

- src/plugins/Instagram/index.js
- src/plugins/Provider/view/Browser.js
- src/plugins/Provider/view/Table.js
- src/plugins/Provider/view/TableRow.js
- src/plugins/Provider/view/index.js
- src/scss/_provider.scss
- website/src/docs/uppy.md
- ul/li instead of table
- remove old styles and excess containers
- larger grid images
- hide checkboxes when items are not selected in grid view (selected checkboxes should be more apparent, another color, add black tint to the selected image background?)
- less apparent checkboxes in list view
- attempt to fix flexbox issues on the last line in the grid
> Refactor provider views

- src/core/Core.js
As detailed in https://github.com/transloadit/uppy/pull/553
> Adds uploadID to complete event

- src/core/Core.js
- src/core/Core.test.js
- src/core/__snapshots__/Core.test.js.snap
Fixes the bug described in https://github.com/transloadit/uppy/issues/551
> Prevents files from being uploaded multiple times in separate uploads

- bin/upload-to-cdn.sh
PRing from a repo on my own account to test.
> Only try CDN sync on branch builds

- src/plugins/Dashboard/FileCard.js
- src/plugins/Dashboard/FileItem.js
- src/plugins/Dashboard/index.js
- Pass Dashboard i18n options to StatusBar
- Add more locale strings, fixes #515 and fixes #529
> Fix more i18n strings

- website/src/docs/xhrupload.md
Show how to handle uploads on the server using PHP.
Copied mostly from here.
https://github.com/transloadit/uppy/issues/535#issuecomment-359266478
> docs: Add PHP snippets to XHRUpload docs

- src/locales/pl_PL.js
Hello
I would like to add Polish locale to uppy.
I have some questions, maybe I'm doing something wrong, but when I test it and set Dashboard's locale to Polish, only the "Place files here (...)" string is translated. Other elements like "Upload", "Upload \<number\> selected files" is not translated. If I understand correctly, every plugin needs to have it's locale set. Couldn't the plugins inherit locale from it's parent?
> Add Polish locale

- src/plugins/XHRUpload.js
This PR enables responses to be received for remote multipart uploads
> feature: receive remote multipart upload response content

- src/plugins/ThumbnailGenerator/index.js
- src/plugins/ThumbnailGenerator/index.test.js
> [wip] Fix Safari image previews by using a slightly different step scaling

- website/src/docs/form.md
`strigified ` => `stringified`
> FIXED spelling error

- website/src/docs/uppy.md
Added undocumented events to the docs: https://github.com/transloadit/uppy/issues/610.
> Added undocumented events to the docs.

- website/src/docs/xhrupload.md
Mentioning some ways to set metadata.
> doc: Talk about metadata in XHRUpload docs, closes #466

- CHANGELOG.md
- src/plugins/AwsS3/index.js
We didn't update this after #591.
> s3: update XHR response handling, fixes #624

- website/src/docs/aws-s3.md
> doc: Document AwsS3 pass-thru options.

- website/src/examples/dashboard/app.es6
- website/src/examples/transloadit/app.es6
- website/src/examples/transloadit/index.ejs
Seems this should get the Transloadit example on its feet, instagram wise. Also made some text changes, but feel free to iterate over them!
> Improve Transloadit example. Enable instagram via TL Uppy Servers

- src/plugins/StatusBar/StatusBar.js
- src/plugins/StatusBar/index.js
Must've missed these previously. 🤷‍♀️
> statusbar: Use translations for Uploading / Paused text, fixes #629

- src/plugins/ThumbnailGenerator/index.js
- src/plugins/ThumbnailGenerator/index.test.js
Addresses https://github.com/transloadit/uppy/issues/636
Also removed a console.log that I'm guessing wasn't meant to go live?
> Upsize image if smaller than thumbnail size, fix infinite loop

- src/plugins/Tus.js
Allows uploading to a tus endpoint if you don't actually get to create your own upload.
> tus: Configure uploadUrl for uppy-server uploads

- examples/aws-uppy-server/server.js
So you get progress events too!
> examples: Add missing uppy.socket call to S3 example

- src/core/Core.test.js
Forgot to remove this from #677
> removed .only from Core tests

- src/plugins/Transloadit/index.js
- src/plugins/Transloadit/index.test.js
And also in debug and test messages too!
> transloadit: Capitalise Assembly in user facing messages

- website/src/docs/how-to-plugin.md
- website/src/docs/uppy.md
- website/src/docs/writing-plugins.md
very early, not sure about the direction this is going yet.
> plugin doc draft

- src/core/Utils.js
Fixes https://github.com/transloadit/uppy/issues/705
Tested locally to confirm that it works
@arturi
> Add yaml file type

- examples/digitalocean-spaces/aliasify.js
- examples/digitalocean-spaces/index.html
- examples/digitalocean-spaces/main.js
- examples/digitalocean-spaces/package-lock.json
- examples/digitalocean-spaces/package.json
- examples/digitalocean-spaces/readme.md
- examples/digitalocean-spaces/server.js
- package-lock.json
- package.json
- src/plugins/AwsS3/index.js
- website/src/docs/aws-s3.md
With a custom signing endpoint. Would be good to add an AWS_ENDPOINT env variable to uppy-server too so it can be used with S3 alternatives!
> Add example using AwsS3 with DigitalOcean Spaces

- website/src/docs/uppy.md
Thanks for such a slick looking and useful tool :D
> Trivial typo fix

- src/plugins/Dashboard/FileItem.js
> fix showLinkToFileUploadResult option

- CHANGELOG.md
- src/plugins/StatusBar/StatusBar.js
- src/scss/_statusbar.scss
Before: (note the "failed.Please")
After:
> statusbar: add some spacing between text elements.

- src/plugins/Dashboard/Dashboard.js
- src/plugins/Dashboard/FileItem.js
- src/views/ProviderView/index.js
- website/src/examples/transloadit/index.ejs
- website/themes/uppy/layout/example.ejs
- website/themes/uppy/layout/index.ejs
- website/themes/uppy/layout/page.ejs
- website/themes/uppy/layout/partials/blog.ejs
- website/themes/uppy/layout/partials/community_dropdown.ejs
- website/themes/uppy/layout/post.ejs
- website/themes/uppy/layout/stats.ejs
As a precaution against reverse tabnabbing. see:
- https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c
- https://mathiasbynens.github.io/rel-noopener/
> `rel="noopener noreferrer"` should be added to links containing `target="_blank"`

- src/plugins/Dashboard/Dashboard.js
- src/plugins/Dashboard/FileCard.js
- src/plugins/Dashboard/FileItem.js
- src/plugins/Dashboard/Tabs.js
- src/scss/_dashboard.scss
I think in this case we are suffering from styling issues more than gaining in terms of semantics.
We could also remove lists, those get styled a lot.
> [WIP] Don’t use h1-h6 tags, might solve some styling issues for embedded Uppy

- src/core/Core.js
- src/plugins/Transloadit/Client.js
- src/plugins/Transloadit/index.js
- src/plugins/Transloadit/index.test.js
- src/scss/_dashboard.scss
- src/scss/_informer.scss
- src/server/RequestClient.js
- src/views/ProviderView/index.js
Instead of generic “TypeError: Failed to Fetch”.
> Better provider errors

- src/plugins/Instagram/index.js
fixes #887
@arturi I have added a better image quality for IG icons. Do you mind adding the css fix to make the grid/images all appear with the same sizes/dimensions?
> fix: better thumbnail quality for ig

- packages/@uppy/provider-views/src/index.js
> fix: fix wrong 'no files available' msg flash

- packages/@uppy/aws-s3-multipart/src/index.js
> Check for file existance

- bin/endtoend-build-tests
- test/endtoend/providers/index.html
- test/endtoend/providers/main.js
- test/endtoend/providers/test.js
- test/endtoend/wdio.base.conf.js
- test/endtoend/wdio.local.conf.js
> e2e test for providers

- packages/@uppy/aws-s3-multipart/package.json
- packages/@uppy/aws-s3/package.json
- packages/@uppy/dashboard/package.json
- packages/@uppy/drag-drop/package.json
- packages/@uppy/dropbox/package.json
- packages/@uppy/file-input/package.json
- packages/@uppy/form/package.json
- packages/@uppy/golden-retriever/package.json
- packages/@uppy/google-drive/package.json
- packages/@uppy/informer/package.json
- packages/@uppy/instagram/package.json
- packages/@uppy/progress-bar/package.json
- packages/@uppy/provider-views/package.json
- packages/@uppy/react/package.json
- packages/@uppy/redux-dev-tools/package.json
- packages/@uppy/status-bar/package.json
- packages/@uppy/thumbnail-generator/package.json
- packages/@uppy/transloadit/package.json
- packages/@uppy/tus/package.json
- packages/@uppy/url/package.json
- packages/@uppy/webcam/package.json
- packages/@uppy/xhr-upload/package.json
Should do a patch release today for this!
> Fix peerDependencies of plugin packages.

- website/src/docs/companion.md
Also removed a few "simply"s and "just"s because things that are simple to some may not be simple to others :)
This is just a quick search/replace job so it may have some mistakes. I'd like to get this in quickly anyway and do a site rebuild so that it's not out of date anymore at least.
> Server → Companion in documentation

- packages/uppy/types/index.d.ts
- packages/uppy/types/uppy-tests.ts
Small tweak to align it with the other packages' typings.
> Remove unnecessary 'declare module' from typings.

- packages/@uppy/core/types/index.d.ts
Was actually going to fix #954, but it seems like a fix for that one is already merged :) I guess that issue could be closed now. Anyhow I found some more typing things that could be improved.
Sweet job on the latest release! Better tree shaking / lerna + ts types, what a treat 😍
> Fixed a few issues with uppy/core types

- packages/@uppy/thumbnail-generator/src/index.js
It will be garbage collected soon anyway.
> thumbnail-generator: Remove image clear code, fixes #1025.

- packages/@uppy/transloadit/src/Assembly.js
> transloadit: Use https endpoint for status fetching.

- packages/@uppy/core/src/Plugin.js
See https://github.com/transloadit/uppy/issues/1042
> [core/plugin] Note that the <script> tag should come at the bottom of the page

- package-lock.json
- packages/@uppy/status-bar/src/StatusBar.js
- packages/@uppy/status-bar/src/index.js
- website/src/examples/dragdrop/app.es6
- website/src/examples/i18n/app.html
- website/src/examples/statusbar/app.es6
- use uppy-Root in status-bar when it’s mounted in DOM
- use `https://` for tus.io uploads in examples
> [@uppy/status-bar] Statusbar uppy-Root

- .travis.yml
- test/endtoend/providers/disabled.test.js
- test/endtoend/url-plugin/main.js
- test/endtoend/url-plugin/test.js
- test/endtoend/utils.js
- test/endtoend/wdio.base.conf.js
here's a working version of url-plugin test on travis
> test url-plugin

- bin/release
- bin/sync-version-numbers
Fixes for some issues reported by Artur
> Release fixes

- README.md
- website/src/docs/index.md
> Document bundler-less polyfill use.

- packages/@uppy/companion/package.json
- packages/@uppy/companion/src/server/controllers/callback.js
Fixes “not found” error. Also reverts https://github.com/transloadit/uppy/pull/1157
> companion: pin grant to known stable version

- website/src/privacy.md
Gave Uppy's privacy policy a bit of polish
> Some corrections

- website/src/examples/dashboard/app.es6
- website/src/examples/dragdrop/app.es6
- website/src/examples/statusbar/app.es6
- website/src/examples/transloadit/app.es6
- website/src/examples/xhrupload/app.es6
so we can do quick IE 11 manual test things from uppy.io
> Add polyfills to website examples that do not use prebundled uppy.js

- website/src/docs/tus.md
> Fixed tiny typo in tus.md

- packages/@uppy/aws-s3-multipart/package.json
- packages/@uppy/aws-s3/package.json
- packages/@uppy/companion-client/package.json
- packages/@uppy/core/package.json
- packages/@uppy/dashboard/package.json
- packages/@uppy/drag-drop/package.json
- packages/@uppy/dropbox/package.json
- packages/@uppy/file-input/package.json
- packages/@uppy/form/package.json
- packages/@uppy/golden-retriever/package.json
- packages/@uppy/google-drive/package.json
- packages/@uppy/informer/package.json
- packages/@uppy/instagram/package.json
- packages/@uppy/progress-bar/package.json
- packages/@uppy/provider-views/package.json
- packages/@uppy/redux-dev-tools/package.json
- packages/@uppy/status-bar/package.json
- packages/@uppy/store-default/package.json
- packages/@uppy/store-redux/package.json
- packages/@uppy/thumbnail-generator/package.json
- packages/@uppy/transloadit/package.json
- packages/@uppy/tus/package.json
- packages/@uppy/url/package.json
- packages/@uppy/utils/package.json
- packages/@uppy/webcam/package.json
- packages/@uppy/xhr-upload/package.json
https://github.com/stereobooster/package.json#jsnextmain
> Remove jsnext:main from all @uppy/* since it’s been deprecated

- packages/@uppy/status-bar/src/StatusBar.js
- packages/@uppy/status-bar/src/style.scss
> Update pause-resume-cancel icons

- website/src/docs/react-dashboard-modal.md
- website/src/docs/react-dashboard.md
- website/src/docs/react-dragdrop.md
- website/src/docs/react-progressbar.md
- website/src/docs/react-statusbar.md
> docs: big bold React render() warning

- .gitignore
- packages/@uppy/core/src/_common.scss
- packages/@uppy/core/src/index.js
- packages/@uppy/dashboard/src/style.scss
- packages/@uppy/provider-views/src/Breadcrumbs.js
- packages/@uppy/provider-views/src/Browser.js
- packages/@uppy/provider-views/src/Filter.js
- packages/@uppy/provider-views/src/style.scss
- fix icon animation jiggling
- inherit font, allow overriding outline
- fix breadcrumbs, bug with x button being stuck
- fix an issue with long Dashboard note margin on mobile
- 🚀
> Dashboard ui fixes

- packages/@uppy/webcam/src/index.js
> Don’t show Smile! if countdown is false

- packages/@uppy/companion-client/src/Provider.js
> Companion Client: Use shared storage for logout as well

- packages/@uppy/react/src/Dashboard.d.ts
> Add trigger field

- examples/bundled/index.js
- packages/@uppy/core/src/index.js
- packages/@uppy/core/src/index.test.js
> core: make allowedFileTypes extensions case insensitive

- packages/@uppy/thumbnail-generator/src/index.js
When an SVG image includes external resources, we're not allowed to read
the resized version from the canvas.
Trying to do so would log a SecurityError. Now, Uppy still logs a
warning when `debug: true`, but is silent when `debug: false`.
> thumbnail-generator: do not export tainted canvas, fixes #1321

- packages/@uppy/aws-s3-multipart/src/index.js
- packages/@uppy/companion/src/server/Uploader.js
> use companion-client for remote aws-s3 uploads

- website/src/_posts/2019-03-0.30.md
Struggled a bit with the Dashboard Improvements, let me know if I got anything wrong!
> Uppy 0.30 polish

- website/src/_posts/2019-03-26-roadto10-day1.md
> A thorough iteration

- website/src/docs/react.md
Hi! :wave: 
This PR just fixes a typo I caught when reading the docs related to the use of Uppy with React.
> Fix typo in the React page

- packages/@uppy/companion/src/server/provider/dropbox/index.js
> HTTP-header-safe JSON for dropbox

- website/themes/uppy/layout/post.ejs
- website/themes/uppy/source/css/_page.scss
Listing of all links doesn't work good here when there are more than ~7 links. So I'm using a compact dropdown instead:
Before:
After:
> Update the days navigator of post series

- packages/@uppy/companion/Dockerfile
- packages/@uppy/companion/Dockerfile.test
> companion: install git so we can fetch tus-js-client fork

- packages/@uppy/dashboard/src/style.scss
Wow, that was hard to look at :-) If my eyes are not deceiving me - this fixes the jiggling.
> Dashboard Plugin - fix icons jiggling on hover in safari

- README.md
Temporary link to Browserstack (we'll just add a badge if we migrate automated tests from Saucelabs), needed for the free Browserstack plan [Kvz approved].
> Readme.md - added browserstack logo and link

- website/src/docs/contributing.md
- website/src/docs/plugin-common-options.md
- website/src/docs/plugins.md
- website/src/docs/stores.md
- website/src/docs/writing-plugins.md
- website/src/stats.ejs
- website/themes/uppy/layout/partials/sidebar.ejs
Did another iteration, let's wait on the netlify link and then you can see if you like that or not
> website: Remove Plugins subsection, create Contributing subsection

- packages/@uppy/companion/src/server/Uploader.js
Multipart uploads do not happen in parallel with downloads (i.e downloads completes first before upload begins), so to avoid the situation where the user on the client side doesn't see any progress for the long period while the download is happening in Companion, the PR makes companion send illusive progress while the file is initially being downloaded
> companion: send illusive upload progress when multipart downloads are on

- packages/@uppy/companion/src/server/Uploader.js
fixes https://app.asana.com/0/1113072057568884/1117621385115195/f
> companion: detect bytes upload mismatch for multipart uploads

- website/src/examples/transloadit/index.ejs
Wanted to make this dynamic, but adding a dynamic variable content to the codeblock is hard. No need to waste time on it.
> Simpler caption for Robodog demo

- website/src/docs/plugins.md
- website/src/docs/thumbnail-generator.md
//cc https://github.com/transloadit/uppy/issues/979 and https://github.com/transloadit/uppy/pull/1096
> Add docs for Thumbnail Generator plugin

- packages/@uppy/locales/src/fr_FR.js
I am not sure where the extra strings will be available. But once they are, we can add them or we can merge now and add them later.
> Added french language pack

- packages/@uppy/xhr-upload/src/index.js
Add filename (if specified) to formData in uploadBundle().
Fixes #1486
> xhr-upload: add filename to FormData with `bundle: true`

- packages/@uppy/locales/src/fr_FR.js
Missing translations for FR pack
> Add missing translations

- packages/@uppy/robodog/src/form.js
It's currently advertised, but doesn't work. :) This PR fixes this.
Tested against the Robodog integration example.
> Robodog: Add support for submitOnSuccess option

- packages/@uppy/transloadit/src/index.js
- website/src/docs/transloadit.md
So you can inspect them better.
> transloadit: add assembly status property to assembly errors

- website/themes/uppy/layout/index.ejs
A few adjustments and corrections to the feature list on the homepage @nqst @arturi
> Some polish for the feature list

- .github/ISSUE_TEMPLATE/integration_help.md
- website/src/support.md
Polished the text on the Support Page @arturi
> Support polish

- packages/@uppy/utils/src/prettyETA.js
- packages/@uppy/utils/src/prettyETA.test.js
As proposed in [Issue 1434](https://github.com/transloadit/uppy/issues/1434).
P.S.: This is my very first PR ever, apologies if I have done it wrong.
> Status Bar: Hide seconds if more than 1 hour

- packages/@uppy/locales/src/zh_CN.js
Added zh_CN translation to locales/src
> Add zh_CN translation

- packages/@uppy/locales/src/fa_IR.js
> Add fa_IR translation

- website/src/docs/aws-s3.md
capitalization error results in broken link
> Fix post-uploads reference

- website/themes/uppy/source/css/_common.scss
- website/themes/uppy/source/css/_index.scss
Just a cleanup — removed some unused styles and commented code.
> Website cleanup

- packages/@uppy/locales/src/zh_TW.js
> Add zh_TW translation

- packages/@uppy/locales/src/es_GL.js
Inclusion of locale translation for Galician language (Spanish region).
> Included locale for Galician language (Spanish region).

- packages/@uppy/utils/src/getDroppedFiles/utils/webkitGetAsEntryApi.js
> getDroppedFiles.js - made .relativePath of nonfoldered files null

- examples/transloadit/main.js
- packages/@uppy/robodog/src/addDashboardPlugin.js
- packages/@uppy/robodog/src/dashboard.js
- packages/@uppy/robodog/src/form.js
- packages/@uppy/robodog/src/pick.js
Pass Dashboard options through to the dashboard plugin.
> robodog: actually support specifying Dashboard options

- website/src/docs/community-projects.md
@kvz, added uppy-aws-amplify to the community projects.
> Added uppy-aws-amplify to community projects

- bin/locale-packs.js
- packages/@uppy/core/src/index.js
- packages/@uppy/dashboard/src/index.js
- packages/@uppy/locales/src/ar_SA.js
- packages/@uppy/locales/src/es_GL.js
- packages/@uppy/locales/src/hu_HU.js
- packages/@uppy/locales/src/ja_JP.js
- packages/@uppy/locales/src/nl_NL.js
- packages/@uppy/locales/src/pt_BR.js
- packages/@uppy/locales/src/sr_RS_Latin.js
- packages/@uppy/locales/src/tr_TR.js
- packages/@uppy/provider-views/src/index.js
1. Added some translations for 'Add more'.
2. Moved all provider-views translations to Core, this eliminates a dependency of provider-views upon Dashboard.
> Adjust i18n

- .travis.yml
- packages/@uppy/companion/infra/kube/companion/companion-kube.yaml
- packages/@uppy/companion/infra/kube/companion/companion-redis.yaml
- packages/@uppy/companion/infra/kube/gcloud-deploy.sh
Apply a few patches and change deployment to a different cloud provider.
> Change cloud in gcloud-deploy

- packages/@uppy/utils/src/getFileType.js
- packages/@uppy/utils/src/mimeTypes.js
- Added `heic` and `heif`, fixes #1604
- Refactored `getFileType` cause it had redundant checks
Some `.heic` files can be found here: http://nokiatech.github.io/heif/examples.html
> core: Added heic file type, refactor getFileType

- packages/@uppy/locales/src/sv_SE.js
Disclaimer: I created these translations with the help of a native Swedish speaker, but I'm not one myself. Therefore any further improvements or adjustments requested are beyond my powers.
> Add translations in Swedish

- website/src/docs/fileinput.md
> docs: Talk about using a custom file input, instead of the file-input plugin

- packages/@uppy/dashboard/src/index.js
- website/src/docs/dashboard.md
> dashboard: add dashboard:file-edit-start and dashboard:file-edit-complete events

- website/src/docs/companion.md
It's been a while, I think we can safely remove this now.
> website: remove uppy server notice

- website/src/docs/redux.md
> uppy.io/docs/redux - mentioned that we can't persist Uppy state

- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/companion/src/server/controllers/get.js
- packages/@uppy/companion/src/server/controllers/url.js
fixes #1774
we somehow missed s3 options in the URL plugin. So I created a method to return these options so that it's all in one place
> companion: fix s3 uploads for URL plugins

- packages/@uppy/companion/infra/kube/gcloud-deploy.sh
Statefulsets image only should be updated.
> Fix statefulset update

- packages/@uppy/provider-views/src/index.js
> [provider-views] list all files in a folder for provider view if nextpagepath is returned

- package-lock.json
- package.json
The build was failing like this: https://travis-ci.org/transloadit/uppy/jobs/578792955#L743.
Adding `pacote` seems to fix it. Please merge if it looks good to you :)
> build: add pacote to fix upload-to-cdn

- packages/@uppy/dashboard/types/index.d.ts
The typings seem to be outdated, so here is a PR to fix that.
> Add missing fields to DashboardOptions

- packages/@uppy/locales/src/da_DK.js
I have **not** made any automated tests (if there are any that tests locales) - I have copied the en_US.js file and translated everything. Then I have tested in this way:
`const Danish = require('@uppy/locales/lib/da_DK')`
`const uppy = Uppy({
restrictions:{
locale: Danish
}
})`
and seen that everything works.
> Added Danish locale

- packages/@uppy/aws-s3-multipart/src/index.js
- packages/@uppy/companion-client/src/index.js
- packages/@uppy/companion-client/src/tokenStorage.js
- packages/@uppy/form/src/index.js
S3 Multipart was doing a weird thing and probably causing more cancellation
bugs.
> fixes flagged by LGTM.com

- package-lock.json
- packages/@uppy/companion/package.json
- packages/@uppy/companion/src/standalone/helper.js
- packages/@uppy/companion/src/standalone/index.js
> companion: upgrade connect-redis

- packages/@uppy/provider-views/src/style/uppy-ProviderBrowser-viewType--grid.scss
- packages/@uppy/provider-views/src/style/uppy-ProviderBrowserItem-fakeCheckbox.scss
Also make sure checkboxes never shrinks.
> Fix sizes for smaller images in grid layout (for Facebook)

- README.md
Hello! I came across your tool and found a couple of minor issues in the Readme file. I made these changes and wanted to push them out - I hope you don't mind, the editor in me wanted to help out.
> Minor wording and formatting changes

- packages/@uppy/companion/src/server/provider/dropbox/index.js
> companion: set a more visible thumbnail size for dropbox

- packages/@uppy/locales/src/is_IS.js
> Added Icelandic 🇮🇸

- package-lock.json
- packages/@uppy/companion/package.json
- packages/@uppy/companion/src/companion.js
- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/tus/src/index.js
> tus,companion: terminate tus upload on-upload cancel

- website/src/support.md
- website/themes/uppy/source/css/_page.scss
@tim-kos
https://deploy-preview-1913--uppy.netlify.com/support
> Website: impove support page — better styling, removed checkboxes

- packages/@uppy/core/src/index.js
- website/src/docs/uppy.md
> Add reset-progress event to docs

- packages/@uppy/companion/src/standalone/index.js
For the `/:providerName/send-token?uppyAuthToken=****` path, which returns an html content, the browser may try to fetch for the favicon, in which cases, the companion URL becomes the value of the `referer` header, and this URL may contain the `uppyAuthToken`. The purpose of this is to mask the `uppyAuthToken` that maybe present in these URLs
> companion: mask token from logged referrer URLs

- website/src/privacy.md
- website/themes/uppy/layout/example.ejs
Discussed (private link) in https://app.intercom.io/a/apps/qiqpfgjg/inbox/inbox/conversation/24554991679
> website: update Privacy Policy to reflect that tus and uppy demo uploads are deleted after 72h, not 24h

- packages/@uppy/tus/types/index.d.ts
From: https://uppy.io/docs/tus/
> Correct Tus.TusOptions typings based on docs

- packages/@uppy/locales/src/ko_KR.js
I've added Korean Locale.
If there is anything wrong, please let me know.
> add Korean Locale

- packages/@uppy/core/src/index.js
- website/src/docs/uppy.md
> core: setState(modifiedFiles) in onBeforeUpload

- packages/@uppy/dropbox/src/index.js
- packages/@uppy/facebook/src/index.js
- packages/@uppy/google-drive/src/index.js
- packages/@uppy/instagram/src/index.js
- packages/@uppy/onedrive/src/index.js
this option is no longer used and is a dead code.
> providers: remove redundant use of options

- packages/@uppy/utils/src/mimeTypes.js
> core: Add .tsv and .tab: text/tab-separated-values

- packages/@uppy/webcam/src/index.js
> Fix#2071 Check the availability isTypeSupported api before calling.

- packages/@uppy/companion/src/standalone/helper.js
- website/src/docs/companion.md
Follow up PR, based on this discussion: https://github.com/transloadit/uppy/pull/2109#issuecomment-594440734
> Allow S3 ACL to be specified in Companion Standalone

- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/companion/src/server/controllers/url.js
- packages/@uppy/companion/src/server/provider/drive/index.js
- packages/@uppy/companion/src/server/provider/dropbox/index.js
- packages/@uppy/companion/src/server/provider/facebook/index.js
- packages/@uppy/companion/src/server/provider/instagram/graph/index.js
- packages/@uppy/companion/src/server/provider/instagram/index.js
- packages/@uppy/companion/src/server/provider/onedrive/index.js
I'm not sure how I missed this in the past, but better late than never :)
> companion: emit error to client if download fails

- packages/@uppy/xhr-upload/src/index.js
- website/src/docs/xhrupload.md
Also linkify some references in the text to other options.
>  docs: document `XHRUpload#validateStatus` option 

- packages/@uppy/robodog/package.json
:see_no_evil:
Should have been done in https://github.com/transloadit/uppy/pull/2165
Before this is merged: could we have forgotten something else?
> Add facebook and onedrive

- packages/@uppy/robodog/src/addDashboardPlugin.js
> Pass hideUploadButton to Dashboard in Robodog too

- website/src/docs/dashboard.md
> Fix minor typo in Dashboard docs

- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/companion/test/__tests__/companion.js
> companion: fix uploader protocol validation

- packages/@uppy/companion/src/server/provider/drive/adapter.js
- packages/@uppy/companion/src/server/provider/drive/index.js
this PR sets target mimetypes and file extensions for gsuite files before sending them to uppy client
fixes #2187
> Set gsuite file extensions

- packages/@uppy/locales/src/fr_FR.js
Hey!
This is a more accurate translation of the Powered by, in french.
> More accurate french translation of powered by

- packages/@uppy/aws-s3/src/MiniXHRUpload.js
- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/xhr-upload/src/index.js
> companion,xhr-upload,aws-s3: send useFormData option in companion

- package-lock.json
- packages/@uppy/thumbnail-generator/package.json
- packages/@uppy/thumbnail-generator/src/index.js
Follow up to #2195, after https://github.com/transloadit/uppy/pull/2195#issuecomment-617323569
> Exifr use .js

- bin/locale-packs.js
- packages/@uppy/aws-s3/src/index.js
- packages/@uppy/locales/src/en_US.js
- packages/@uppy/locales/src/fi_FI.js
- packages/@uppy/screen-capture/src/index.js
https://github.com/transloadit/uppy/pull/2195#issuecomment-618248602
https://github.com/transloadit/uppy/pull/2195#issuecomment-618082184
> Fix build locales

- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/companion/src/server/controllers/get.js
- packages/@uppy/companion/src/server/provider/drive/index.js
- packages/@uppy/companion/src/server/provider/dropbox/index.js
- packages/@uppy/companion/src/server/provider/facebook/index.js
- packages/@uppy/companion/src/server/provider/instagram/graph/index.js
- packages/@uppy/companion/src/server/provider/instagram/index.js
- packages/@uppy/companion/src/server/provider/onedrive/index.js
- packages/@uppy/companion/test/__tests__/companion.js
> companion: catch download failures via response status codes

- packages/@uppy/companion/src/server/provider/dropbox/index.js
- packages/@uppy/companion/src/server/provider/onedrive/index.js
> companion: check if body is present in error response

- packages/@uppy/locales/src/bg_BG.js
Inherited from the up-to-date en_US localization
> Add new localization for Bulgarian language [bg_BG]

- packages/@uppy/companion/src/standalone/helper.js
> companion: check env for truthy value

- packages/@uppy/aws-s3/src/index.js
This was accidentally using the `file` object from _before_ the getUploadParameters() function was called. That function may use setFileState or setFileMeta, and it's async so it's also possible that some _other_ part of the program uses either of those methods to update the file object. We need to re-fetch the file object in the `then()` and `catch()` handlers to make sure we are up to date.
> aws-s3: fix accidental reset of `file.meta`, fixes #2240

- packages/@uppy/companion/src/server/controllers/url.js
- packages/@uppy/companion/src/server/helpers/request.js
this has no critical implications, but it's better to have consistent behaviour
> companion: enable protection when fetching file size

- package-lock.json
- packages/@uppy/companion/package.json
Closes #2331, kind of—the `request` warning remains but that is already on @ifedapoolarewaju's list to address later.
> companion: a few dependency updates

- packages/@uppy/locales/src/zh_CN.js
- Sync new strings from en_US
- Fix incorrect translations
- Remove obsolete variants
> locales: add new strings for Chinese Simplified

- website/themes/uppy/layout/layout.ejs
- website/themes/uppy/source/css/_common.scss
- website/themes/uppy/source/css/_page.scss
- website/themes/uppy/source/css/_settings.scss
- website/themes/uppy/source/js/common.js
Fixing problems w/ the sidebar we encoutered because of the TransloaditBar.
**Before:**
**After:**
**Note:** I could commit some JS crimes. Correct me if there's anything wrong!
> Make sidebar work better w/ TransloaditBar

- website/src/docs/index.md
- website/src/docs/writing-plugins.md
Add comment to getting started around the #2226
> Add preact 10 comment

- package-lock.json
- packages/@uppy/dashboard/package.json
- packages/@uppy/dashboard/src/components/Dashboard.js
It was not good enough :/
Ref #2402
> revert #2379

- packages/@uppy/companion/src/server/controllers/logout.js
- packages/@uppy/companion/src/server/provider/zoom/index.js
the logout functionality seemed not to be working. The token was not being revoked. Also getting the credentials from environment variables may not be reliable as the options may be passed by other means
> companion: fix zoom logout endpoint

- website/src/examples/dashboard/app.es6
- website/src/examples/dashboard/app.html
- website/src/examples/transloadit/app.es6
this PR enables the Zoom plugin on the example page should `#enable-zoom` be added to the url.
> website: enable zoom example conditionally

- website/src/privacy.md
- website/src/support.md
- website/themes/uppy/layout/page.ejs
- website/themes/uppy/layout/partials/plugin_list.ejs
- website/themes/uppy/layout/partials/sidebar.ejs
- website/themes/uppy/source/css/_common.scss
- website/themes/uppy/source/css/_page.scss
- website/themes/uppy/source/css/_stats.scss
Here, a bunch of website-related things is fixed:
- Burger menu is now toggleable on Support & Privacy pages (on mobile)
- Tables are now responsible and scrollable on mobile (e.g. on current `master` you can't scroll support options table horizontally on the [Support page](https://uppy.io/support/))
- Removed unnecessary paddings inside code blocks
- Other tiny fixes
> Bunch of website fixes

- packages/@uppy/tus/src/getFingerprint.js
> tus: fix fallback to default `fingerprint` implementation

- packages/@uppy/transloadit/types/index.d.ts
> transloadit: add auth.expires type, fixes #2454

- packages/@uppy/companion/src/config/grant.js
- packages/@uppy/companion/test/__tests__/provider-manager.js
This was requested during the Zoom App review
> companion: remove ouath scopes for zoom

- website/src/examples/transloadit/app.es6
This PR enables Zoom on the Transloadit example page because Zoom app reviewers need to test with https://api2.transloadit.com/companion.
When Zoom is enabled (via #enable-zoom), Assembly instructions tailored for video watermarks will be used. A different Assembly instruction is required because Zoom does not have image files (which the original instructions are meant for).
> website: enable Zoom on transloadit example

- packages/@uppy/locales/src/zh_CN.js
Ref https://github.com/transloadit/uppy/pull/2335
> locales: fix missleading strings for zh_CN

- packages/@uppy/companion/src/server/provider/index.js
> companion: remove support for legacy instagram API

- website/src/docs/react-dashboard-modal.md
- website/src/docs/react-dashboard.md
Fixed a small spelling error, turning `inluded` to `included`
> Spelling fix

- examples/custom-provider/client/MyCustomProvider.js
- examples/custom-provider/server/index.js
- website/src/_posts/2020-03-custom-providers.md
- website/src/docs/companion.md
- website/src/docs/dropbox.md
- website/src/docs/google-drive.md
hopefully I didn't miss anything
> docs: document Companion 2.0 related changes

- website/src/_posts/2020-08-companion-2.0.md
- website/src/_posts/2020-09-companion-2.0.md
Here's a first iteration of the Companion 2.0 blog post. Please let me know what you think! Will add Artur and Kevin as reviewers when they get back.
> website[blog]: first iteration of companion 2.0 blog post

- packages/@uppy/dropbox/README.md
- packages/@uppy/facebook/README.md
- packages/@uppy/onedrive/README.md
- packages/@uppy/zoom/README.md
Hi! This pr updates the readme description to provide a bit more information about each uppy provider plugin
> Update readme pages for npm

- packages/@uppy/provider-views/src/index.js
This solves a bug of mutating state where not intended.
Seems this issue could be more wide spread than this instance but this is where I'm seeing the error so just fixing here.
I would suggest something like [klona](https://github.com/lukeed/klona) as a better solution.
> provider-views: Fix mutating state where not intended

- examples/dev/Dashboard.js
- website/src/examples/xhrupload/app.es6
- website/src/examples/xhrupload/app.html
> Fix XHR upload demos, fixes #2517

- website/src/docs/dashboard.md
Corrected localhost URL to actual URL
> Corrected localhost URL to actual URL

- packages/@uppy/core/src/index.js
- packages/@uppy/core/src/index.test.js
- packages/@uppy/core/types/index.d.ts
- website/src/docs/robodog-dashboard.md
- website/src/docs/robodog-form.md
- website/src/docs/robodog-picker.md
- website/src/docs/uppy.md
> Restrictions: add maxTotalFileSize

- packages/@uppy/core/src/index.js
- packages/@uppy/core/types/index.d.ts
- website/src/docs/uppy.md
> Add uppy.opts.infoTimeout

- packages/@uppy/robodog/src/addTransloaditPlugin.js
- website/src/docs/robodog-dashboard.md
Added missing configurable options.
> Update addTransloaditPlugin.js to include missing configurable Transloadit plugin options.

- packages/@uppy/image-editor/src/Editor.js
- packages/@uppy/image-editor/src/index.js
- packages/@uppy/image-editor/types/index.d.ts
- website/src/docs/image-editor.md
Allows to manage image editor buttons. Sometimes, people need limited actions and this option can provide this functionality.
> Image editor optional buttons

- packages/@uppy/image-editor/src/Editor.js
- packages/@uppy/image-editor/types/index.d.ts
> Image editor zoom button and  types fix

- packages/@uppy/dashboard/src/index.js
- packages/@uppy/status-bar/src/StatusBar.js
- packages/@uppy/status-bar/src/index.js
- packages/@uppy/status-bar/src/style.scss
- website/src/docs/dashboard.md
- website/src/docs/statusbar.md
> Status Bar and Dashboard: add “done” after upload is complete

- package-lock.json
- package.json
- packages/@uppy/core/src/index.test.js
- test/endtoend/i18n-drag-drop/main.js
- test/resources/DeepFrozenStore.js
Follow up to #320
This adds a `DeepFrozenStore` that uses `deep-freeze` module in `setState()` and uses it in one end-to-end test. This way we know that at least choosing a locale pack, selecting a file and uploading it doesn’t mutate state.
> test: use DeepFrozenStore in one end to end test

- packages/@uppy/core/types/index.d.ts
> core types: addFile returns string, not void

- packages/@uppy/companion/src/server/controllers/thumbnail.js
> companion: return function after sending response

- README.md
- examples/bundled/index.js
- examples/cdn-example/index.html
- examples/custom-provider/client/main.js
- examples/dev/Dashboard.js
- examples/dev/DragDrop.js
- examples/react-example/App.js
- examples/react-native-expo/App.js
- examples/redux/main.js
- examples/uppy-with-companion/client/index.html
- examples/vue/src/App.vue
- packages/@uppy/companion/KUBERNETES.md
- packages/@uppy/companion/test/__tests__/providers.js
- packages/@uppy/companion/test/__tests__/url.js
- packages/@uppy/tus/README.md
- packages/uppy/types/index.test-d.ts
- test/endtoend/providers/main.js
- test/endtoend/tus-drag-drop/main.js
- website/src/docs/companion.md
- website/src/docs/index.md
- website/src/docs/tus.md
- website/src/examples/dashboard/app.es6
- website/src/examples/dashboard/index.ejs
- website/src/examples/dragdrop/app.es6
- website/src/examples/i18n/app.html
- website/src/examples/statusbar/app.es6
- website/src/frontpage-code-sample.ejs
- website/themes/uppy/layout/index.ejs
- website/themes/uppy/layout/partials/frontpage-code-sample.html
The public tusd demo moved to tusdemo.net to hopefully prevent *.tus.io from getting flagged for viruses/etc uploaded by users.
> use tusd.tusdemo.net

- packages/@uppy/dashboard/src/utils/getFileTypeIcon.js
- packages/@uppy/utils/src/mimeTypes.js
> utils: Add archive mime types

- .github/workflows/companion-deploy.yml
- packages/@uppy/companion/Dockerfile
We didn't push to our docker hub previously. This makes sure we do. 
You can check it here, all pushes are only from this PR https://hub.docker.com/r/transloadit/companion/tags?page=1&ordering=last_updated
> Fixes around Github actions and Companion deploys. 

- packages/@uppy/companion-client/src/RequestClient.js
- packages/@uppy/companion-client/types/index.d.ts
- packages/@uppy/dropbox/src/index.js
- packages/@uppy/facebook/src/index.js
- packages/@uppy/google-drive/src/index.js
- packages/@uppy/instagram/src/index.js
- packages/@uppy/onedrive/src/index.js
- packages/@uppy/unsplash/src/index.js
- packages/@uppy/zoom/src/index.js
- website/src/docs/aws-s3-multipart.md
- website/src/docs/dropbox.md
- website/src/docs/facebook.md
- website/src/docs/google-drive.md
- website/src/docs/instagram.md
- website/src/docs/onedrive.md
- website/src/docs/url.md
- website/src/docs/zoom.md
> companion-client: support options cookies send rule

- website/src/docs/aws-s3.md
This is something I struggled with, so I figured others reading these docs would need this info as well.
Feel free to reword (or correct!) at will - I'm not at all wedded to the language here, I just think that this is a piece of info I would have found useful.
> List required permissions to upload S3 files using companion

- .github/CONTRIBUTING.md
I added a rough draft of a guide for creating new integrations. It definitely needs some work, and it will hopefully make the creation of new integrations easier
> docs: Add Integration Guide

- packages/@uppy/aws-s3-multipart/types/index.d.ts
> Adds companionHeaders to aws s3 multipart options object

- .github/workflows/companion-deploy.yml
Tag docker image with git tags along with git SHAs and latest. 
Solves #2750
> Docker tag release

- packages/@uppy/xhr-upload/src/index.js
We use uppy in an app with JWT-based auth. In JWT-based auth, the bearer token goes as a header.
Uppy sets the headers for all files immediately as they are added. This presents a problem since, all files would have the token of the moment the files are added; however, if throughout the process of uploading multiple files — specially when using the `limit` option — the bearer token changed, even if we update the XHRUpload or file header options, the headers were already computed and will now have a stale value.
This PR moves the header setting to the requests queue `run` function so that the headers are computed just before the upload starts and get the opportunity to have _fresh_ options should they have changed while the upload began.
> Set headers just before the upload in case options changed

- packages/@uppy/companion/src/server/provider/drive/adapter.js
- packages/@uppy/companion/src/server/provider/drive/index.js
Adds some additional meta data for image/video files
> Add additional Google Drive Metadata

- packages/@uppy/image-editor/src/index.js
- packages/@uppy/locales/src/en_US.js
> image-editor: fix `flipHorizontal` string

- packages/@uppy/webcam/src/index.js
Fix issue where the `modes: ['audio-only']` option was ignored when getting tracks from the media stream, and so audio-only recording failed to start with an error. 
Now we check to see if the Webcam is set to `'audio-only'` and if so, only load audio tracks. We also set the constraints object's `video` attribute to false if this is the case.
Solves the issue raised in https://github.com/transloadit/uppy/pull/2492#issuecomment-798962677.
> [FIX] - @uppy/webcam 

- packages/@uppy/aws-s3/src/index.js
https://github.com/transloadit/uppy/issues/2820
> AWS-S3 removeUploader triggered on uninstall

- packages/@uppy/dashboard/src/components/FileCard/index.js
- packages/@uppy/dashboard/src/index.test.js
- packages/@uppy/dashboard/types/index.d.ts
- website/src/docs/dashboard.md
The unit test could be a bit improved – currently it's just testing that having a callback doesn't throw, it's not actually testing the feature. But I've tested it locally and it seems to work on my machine.
Fixes: https://github.com/transloadit/uppy/issues/2591
> add dynamic metaFields option

- packages/@uppy/react/src/propTypes.js
The error was starting to annoy me and I noticed that it was not a reported issue.
> Add function as allowed prop type

- packages/@uppy/core/src/index.js
- packages/@uppy/core/src/index.test.js
- website/src/docs/writing-plugins.md
Fixes: https://github.com/transloadit/uppy/issues/2840
> core: enrich error event for use from postproocessor

- .eslintrc.js
- package-lock.json
- package.json
Fix 356 warnings about `import/no-unresolved`. Initial issue in https://github.com/transloadit/eslint-config-transloadit/issues/10, but I felt it's better to fix it here as it's specific to this repository.
> Fix eslint uppy package imports

- packages/@uppy/drag-drop/src/index.js
- packages/@uppy/drag-drop/types/index.d.ts
- packages/@uppy/drag-drop/types/index.test-d.ts
- website/src/docs/dragdrop.md
Closes #2171
- Fix eslint warnings
- Expose drag and drop events
- Update types and type tests
- Update docs
> Expose drag-drop events

- packages/@uppy/companion/src/server/provider/drive/adapter.js
- packages/@uppy/companion/src/server/provider/drive/index.js
reference:
- https://workspaceupdates.googleblog.com/2020/03/shortcuts-for-google-drive.html
- https://developers.google.com/drive/api/v3/reference/files#resource
closes #2698
> Google drive shortcuts

- BACKLOG.md
- package-lock.json
- package.json
- packages/@uppy/xhr-upload/src/index.js
- website/src/docs/xhrupload.md
Fixes: https://github.com/transloadit/uppy/issues/782
> xhr: change default name depending on whether `bundle` is set

- packages/@uppy/dashboard/src/index.js
- website/src/docs/dashboard.md
See https://github.com/transloadit/uppy/pull/2144#issuecomment-600581690
> dashboard: set default trigger to null instead of a specific class selector

- packages/@uppy/react-native/file-picker/selectImage.js
- packages/@uppy/react-native/file-picker/takePicture.js
Removes disabling of eslint rule and improve code readability.
> react-native: refactor `takePictureWithExpo`

- packages/@uppy/core/src/UIPlugin.js
- packages/@uppy/dashboard/src/components/VirtualList.js
Apply feedback from https://github.com/transloadit/uppy/pull/2926
- Remove `sync` option from `VirtualList`.
- Update `UIPlugin` render.
> Remove `sync` option from `VirtualList` & update `UIPlugin` render

- website/src/docs/vue.md
Add props in example in order to see how props are used.
> Minor - Add props example

- packages/@uppy/aws-s3/src/index.js
- packages/@uppy/core/types/index.d.ts
- packages/@uppy/core/types/index.test-d.ts
> Add types for `uppy.once` method

- packages/@uppy/screen-capture/src/index.js
- packages/@uppy/webcam/src/index.js
https://caniuse.com/?search=mediadevices
IE users would need this polyfill:
https://github.com/mozdevs/mediaDevices-getUserMedia-polyfill
> expect built-in support for `MediaDevices`  API

- website/src/_posts/2021-07-1.30.md
Polished the update post a little bit :)
> A bit of polish

- .github/CONTRIBUTING.md
Needs to use a valid public https oauth callback url
> Add instagram development notes

- packages/@uppy/angular/projects/angular/src/lib/components/dashboard-modal/dashboard-modal.component.ts
- packages/@uppy/angular/projects/angular/src/lib/components/dashboard/dashboard.component.ts
- packages/@uppy/angular/projects/angular/src/lib/components/drag-drop/drag-drop.component.ts
- packages/@uppy/angular/projects/angular/src/lib/components/progress-bar/progress-bar.component.ts
- packages/@uppy/angular/projects/angular/src/lib/components/status-bar/status-bar.component.ts
- packages/@uppy/angular/projects/angular/src/lib/utils/wrapper.ts
- packages/@uppy/dashboard/types/index.d.ts
- packages/@uppy/drag-drop/types/index.d.ts
- packages/@uppy/progress-bar/types/index.d.ts
- packages/@uppy/react/src/Dashboard.d.ts
- packages/@uppy/react/src/DashboardModal.d.ts
- packages/@uppy/react/src/DragDrop.d.ts
- packages/@uppy/react/src/ProgressBar.d.ts
- packages/@uppy/react/src/StatusBar.d.ts
- packages/@uppy/status-bar/types/index.d.ts
- test/endtoend/typescript/main.ts
Necessary to fix e2e test suite. Follow up of https://github.com/transloadit/uppy/pull/2949.
> @uppy/angular: fix types

- packages/@uppy/store-redux/src/index.js
- packages/@uppy/store-redux/src/index.test.js
- packages/@uppy/store-redux/types/index.d.ts
- packages/@uppy/store-redux/types/index.test-d.ts
For consistency.
Refs: https://github.com/transloadit/uppy/pull/2949
> @uppy/store-redux: force `new` keyword

- packages/@uppy/image-editor/src/inputrange.scss
Refs: https://sass-lang.com/documentation/breaking-changes/slash-div
> @uppy/image-editor: fix SASS deprecation warning

- .github/CONTRIBUTING.md
- website/src/_template/contributing.md
Remove non-ASCII quotes and fix color syntaxing. Also updating `website/src/_template/contributing.md` so the website version stays up-to-date.
> meta: update `CONTRIBUTING.md`

- packages/@uppy/dashboard/src/components/EditorPanel.js
- packages/@uppy/dashboard/src/components/FileCard/index.js
- packages/@uppy/dashboard/src/components/PickerPanelContent.js
- packages/@uppy/dashboard/src/index.js
- packages/@uppy/dashboard/src/style.scss
- packages/@uppy/image-editor/src/Editor.js
- packages/@uppy/image-editor/src/index.js
- packages/@uppy/screen-capture/src/index.js
- `Done` is called `Cancel` everywhere
- `Cancel` actually cancelles in file meta editor
- Save button added to the top in Image Editor
> Dashboard: rename Done to Cancel, add Save to Image Editor

- packages/@uppy/transloadit/package.json
- packages/@uppy/transloadit/src/Assembly.js
- packages/@uppy/transloadit/src/AssemblyOptions.js
- packages/@uppy/transloadit/src/AssemblyWatcher.js
- packages/@uppy/transloadit/src/Client.js
- packages/@uppy/transloadit/src/index.js
- packages/@uppy/transloadit/src/index.test.js
Refactor to resolve all ESLint warning on this package.
> @uppy/transloadit: refactor to use private properties

- packages/@uppy/core/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/3026
> @uppy/core: detach event listeners on close

- packages/@uppy/aws-s3/package.json
- packages/@uppy/aws-s3/src/MiniXHRUpload.js
- packages/@uppy/core/package.json
- packages/@uppy/core/src/index.js
- packages/@uppy/core/src/index.test.js
- packages/@uppy/dashboard/package.json
- packages/@uppy/dashboard/src/index.js
- packages/@uppy/store-redux/package.json
- packages/@uppy/store-redux/src/index.js
- packages/@uppy/xhr-upload/package.json
- packages/@uppy/xhr-upload/src/index.js
Refs: https://github.com/transloadit/uppy/pull/3040#issuecomment-886468554
> deps: replace `cuid` with `nanoid`

- packages/@uppy/core/types/index.d.ts
> @uppy/core: Add types for `options_logger`

- packages/@uppy/vue/package.json
- packages/@uppy/vue/src/file-input.js
- packages/@uppy/vue/types/file-input.d.ts
- packages/@uppy/vue/types/index.d.ts
- packages/@uppy/vue/types/index.test-d.ts
Added FileInput Vue component. Added the following files:
* `packages/@uppy/vue/src/file-input.js`
* `packages/@uppy/vue/types/file-input.d.ts` 
and added the dependency to `package.json`
Also updated `index.test-d.ts` and `index.d.ts`
> @uppy/vue: add Vue FileInput component (#3120)

- packages/@uppy/core/types/index.d.ts
- packages/@uppy/core/types/index.test-d.ts
> Improve accuracy/compatibility of success/error callback types

- packages/@uppy/aws-s3/src/MiniXHRUpload.js
I noticed that [this commit changed its position](https://github.com/transloadit/uppy/commit/405157ea49a892973170eabffad82904835e6039#diff-fa367bfcefda1d5a80deb4ca70a03be09d792a47e1e4070db71347ae54f56f45R127-L256), which actually caused the `InvalidStateError`.
> @uppy/aws-s3: fix invalid state error of XHR

- packages/@uppy/locales/src/de_DE.js
Add missing entry 'editFileWithFilename' to locale de_DE - solves #3157
> Add missing `editFileWithFilename` to `de_DE` locale

- website/src/_posts/2019-04-liftoff-23.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005169
No. 5i, removed broken link, couldn't find a replacement link.
> remove broken link

- .github/CONTRIBUTING.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005169
No. 6i, replaced broken link with the correct link.
> replace webdriver.io guide link

- website/src/_data/authors.yml
- website/src/_posts/2021-08-2.0.md
- website/src/docs/migration-guides.md
> Add migration guides to website

- website/src/_posts/2016-09-0.10.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005169 
No. 2i, couldn't find a link that corresponds to the broken one so removed it.
> remove-broken-link

- .github/workflows/cdn.yml
- .github/workflows/ci.yml
- .github/workflows/end-to-end.yml
due to hitting this error: nodejs/node#40030
https://github.com/transloadit/uppy/pull/3159/checks?check_run_id=3544858518
> degrade to node 14 in github actions

- packages/@uppy/dashboard/src/index.js
> Fix `autoOpenFileEditor` for `@uppy/dashboard`

- .github/workflows/cdn.yml
- .github/workflows/ci.yml
- .github/workflows/companion.yml
- .github/workflows/end-to-end.yml
- .github/workflows/website.yml
- packages/@uppy/dashboard/src/components/FileList.js
And upgrade `actions/setup-node` version.
> ci: test on Node.js v16.x

- packages/@uppy/xhr-upload/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/3195
> @uppy/xhr-upload: fix `this.uppy is undefined` error

- packages/@uppy/react/src/Dashboard.js
- packages/@uppy/react/src/Dashboard.test.js
- packages/@uppy/react/src/DashboardModal.js
- packages/@uppy/react/src/DashboardModal.test.js
- packages/@uppy/react/src/DragDrop.js
- packages/@uppy/react/src/DragDrop.test.js
- packages/@uppy/react/src/ProgressBar.js
- packages/@uppy/react/src/ProgressBar.test.js
- packages/@uppy/react/src/StatusBar.js
- packages/@uppy/react/src/StatusBar.test.js
- packages/@uppy/react/src/nonHtmlPropsHaveChanged.js
Fixes: https://github.com/transloadit/uppy/issues/3203
> @uppy/react: propagate prop mutation

- packages/@uppy/core/types/index.d.ts
> Fix typo in `@uppy/core` types

- packages/@uppy/dashboard/src/components/FileItem/Buttons/index.js
> Fix i18n error in `CopyLinkButton`

- website/src/docs/companion.md
> docs: fix typo in companion.md

- packages/@uppy/locales/src/es_ES.js
@Murderlon Translation done!, if you need me to do more translations I can help 😊
> added translate for missingRequiredMetafield es_ES

- website/src/docs/drag-drop.md
Hey! 😄
This is only a tiny PR, but I think I spotted a slight typo when I was just reading through the docs?
> Fixed typo

- packages/@uppy/angular/package.json
Fixes #3354
Thanks to @jcompagner for the research.
> Fix module field in @uppy/angular package.json

- website/src/examples/transloadit/app.es6
Web Crypto API is now [supported by all modern browsers](https://caniuse.com/?search=subtlecrypto), it's no longer necessary to bundle a polyfill of the `node:crypto` module.
> website: remove dependency on `crypto` in @uppy/transloadit example

- website/src/docs/core.md
> Document `file.name` in uppy docs

- website/src/docs/audio.md
> docs: fix typo in audio.md

- packages/@uppy/drag-drop/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/3385
> @uppy/drag-drop: fix `undefined is not a function` TypeError

- packages/@uppy/screen-capture/types/index.d.ts
> Add missing option to the types

- packages/@uppy/image-editor/src/inputrange.scss
> @uppy/image-editor: Namespace input range css

- packages/@uppy/transloadit/src/index.js
Refs: https://github.com/transloadit/uppy/pull/3394
> @uppy/transloadit: better defaults for rate limiting

- packages/@uppy/transloadit/src/index.js
> @uppy/transloadit: simplify `#onTusError`

- packages/@uppy/core/src/locale.js
- packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.js
- packages/@uppy/locales/src/en_US.js
- packages/@uppy/provider-views/src/Filter.js
- packages/@uppy/provider-views/src/SearchProviderView/Header.js
- packages/@uppy/provider-views/src/SearchProviderView/InputView.js
- packages/@uppy/provider-views/src/SearchProviderView/SearchProviderView.js
- packages/@uppy/provider-views/src/style.scss
- website/src/docs/core.md
- Extra dot in FileItem, between the image author and the file size
- Display search term at the top when showing search results
@nqst do you have a better idea on the search term placement?
> Unsplash: UI improvements

- packages/@uppy/locales/src/fr_FR.js
Fix wording in case of max file is 1.
Add "save" translation
> Update french locale trad

- packages/@uppy/companion/ARCHITECTURE.md
- packages/@uppy/companion/src/standalone/helper.js
> fix callback urls

- website/src/docs/thumbnail-generator.md
- `thumbnailtype` -> `thumbnailType`
> fix(docs): typo in property `thumbnailType`

- packages/@uppy/companion/src/standalone/helper.js
> add support for COMPANION_UNSPLASH_SECRET

- packages/@uppy/companion/src/companion.js
- website/src/docs/companion.md
> fix periodicPingUrls oops

- .github/workflows/release-candidate.yml
Refs: https://github.com/transloadit/uppy/pull/3478#issuecomment-1043058350
> meta: ensure README is correctly formatted when doing releases

- packages/@uppy/provider-views/src/style.scss
Fixes a layout bug introduced in https://github.com/transloadit/uppy/pull/3438
> provider-view: fix breadcrumbs

- website/src/docs/companion.md
> add corsOrigins to docs

- website/src/docs/companion.md
- website/themes/uppy/layout/partials/docs_menu.ejs
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/5079389/conversations/26852700007188
> fix broken link

- packages/@uppy/companion/src/companion.js
- packages/@uppy/companion/src/config/companion.js
- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/companion/src/server/middlewares.js
In the spirit of @Murderlon 's recent refactoring, I decided to also refactor companion.js and Uploader to fix linting and pull out some logic into separate modules. Maybe easier to look at the individual commits
> Companion refactor

- packages/@uppy/aws-s3/src/MiniXHRUpload.js
fixes #3572
I've tested locally and it fixes the problem at hand
> fix wrong events being sent to companion

- website/src/_posts/2022-03-2.4-2.7.md
Refs: https://github.com/transloadit/uppy/pull/3588
> website: fix linter error on blog post

- packages/@uppy/tus/src/index.js
> fix hasOwn

- package.json
- private/locale-pack/helpers.mjs
- private/locale-pack/index.mjs
- private/locale-pack/test.mjs
- website/src/_template/contributing.md
- website/src/docs/audio.md
- yarn.lock
This should decrease marginally (depending on your local FS speed) the time it takes to run `yarn build:locale-pack`.
> locale-pack: refactor to use more parallel processing

- packages/@uppy/audio/types/index.d.ts
> Fix type in @uppy/audio

- packages/@uppy/informer/src/TransitionGroup.js
Left over from https://github.com/transloadit/uppy/pull/3732
> @uppy/informer: remove remaining `require` call

- .eslintrc.js
- packages/@uppy/companion-client/package.json
- packages/@uppy/companion-client/src/AuthError.js
- packages/@uppy/companion-client/src/Provider.js
- packages/@uppy/companion-client/src/RequestClient.js
- packages/@uppy/companion-client/src/RequestClient.test.js
- packages/@uppy/companion-client/src/SearchProvider.js
- packages/@uppy/companion-client/src/Socket.js
- packages/@uppy/companion-client/src/Socket.test.js
- packages/@uppy/companion-client/src/index.js
- packages/@uppy/companion-client/src/tokenStorage.js
- yarn.lock
Revival of #3693. Let's wait for AWS plugins refactor before merging this.
> Revert "Revert "@uppy/companion-client: refactor to ESM""

- packages/uppy/index.js
- packages/uppy/index.mjs
- packages/uppy/package.json
- yarn.lock
Fixes: https://github.com/transloadit/uppy/issues/3684
> uppy: add Zoom plugin to the bundle and fix ESM exports

- packages/@uppy/tus/types/index.d.ts
Fixes https://github.com/transloadit/uppy/pull/3720#discussion_r885152986
Closes #3801
> @uppy/tus: make `onShouldRetry` type optional

- website/src/docs/aws-s3-multipart.md
> docs: Fix typo in aws-s3-multipart.md

- .github/workflows/companion-deploy.yml
- Dockerfile
> Build an ARM64 container

- packages/@uppy/companion/README.md
Refs: c1407070fbb30eb4fb04cb6cb9f64be28f87fab7
> doc: fix Google Drive example

- packages/@uppy/transloadit/src/AssemblyOptions.js
I wasn't able to reproduce the error, but based on the stack trace I'm guessing that might fix the issue.
> @uppy/transloadit: fix TypeError when file is cancelled asynchronously

- examples/custom-provider/package.json
- examples/vue/package.json
- examples/vue3/package.json
- private/dev/package.json
- yarn.lock
Refs: https://vitejs.dev/blog/announcing-vite3.html
> meta: upgrade to Vite v3

- e2e/cypress/integration/dashboard-tus.spec.ts
https://docs.cypress.io/guides/guides/test-retries#Custom-Configurations
> Add retries for flaky e2e test

- packages/@uppy/compressor/src/index.js
> @uppy/compressor: fix upload causing meta name to reset

- website/src/docs/image-editor.md
> doc: Fix typo in image-editor.md

- website/src/docs/image-editor.md
> doc: fix linter failure in `image-editor.md`

- packages/@uppy/companion/package.json
- packages/@uppy/tus/package.json
- yarn.lock
https://github.com/tus/tus-js-client/releases/tag/v3.0.0
> Upgrade tus-js-client to 3.0.0

- packages/@uppy/companion/src/server/emitter/redis-emitter.js
- packages/@uppy/companion/src/server/redis.js
https://github.com/redis/node-redis/issues/2032
> fix crash if redis disconnects

- packages/@uppy/locales/src/ja_JP.js
Add compressor string translation to Japanese locale
> Add compressor string translation to Japanese locale

- packages/@uppy/utils/src/getFileType.test.js
- packages/@uppy/utils/src/mimeTypes.js
> Fix webp mimetype

- website/src/docs/companion.md
> fix contributing link

- packages/@uppy/utils/package.json
> Fix @uppy/utils microtip.scss export

- packages/@uppy/react/src/useUppy.js
> @uppy/react: useUppy: fix unmount on NextJS dev mode

- packages/@uppy/core/types/index.d.ts
Fixes an error introduced in #4055.
> @uppy/core: fix types

- website/src/docs/index.md
> Update "Dashboard typo"

- .github/workflows/linters.yml
Previously the linter would not run on e.g. a blog post update.
> meta: run linters on almost every PRs

- website/src/robots.txt
- website/themes/uppy/layout/partials/plugin_list.ejs
Refs: https://github.com/transloadit/uppy/pull/3363
> website: remove references to the deleted `disc.html` page

- packages/@uppy/xhr-upload/src/index.js
The issue is described and discussed here: https://github.com/transloadit/uppy/issues/3640
It was fixed for AWS mini XHR and TUS uploaders with this PR: https://github.com/transloadit/uppy/pull/3797/files#
I've just applied the same updates to the XHR Plugin
> @uppy/xhr-upload: queue requests for socket token for remote files

- packages/@uppy/companion/src/server/controllers/url.js
- packages/@uppy/companion/test/__tests__/companion.js
> fix error message

- website/src/docs/remote-sources.md
see https://github.com/transloadit/uppy/blob/main/packages/%40uppy/remote-sources/src/index.js#L26
> fix default sources

- packages/@uppy/angular/projects/uppy/angular/src/lib/utils/wrapper.ts
Fixes: https://github.com/transloadit/uppy/issues/4138
> @uppy/angular: remove unnecessary `console.log` call

- packages/@uppy/companion/src/server/s3-client.js
not sure if it's the cleanest solution, but it fixes #4135
> @uppy/companion: add workaround for S3 accelerated endpoints

- packages/@uppy/aws-s3/src/MiniXHRUpload.js
- packages/@uppy/xhr-upload/src/index.js
> fix `Cannot mark a queued request as done` in `MiniXHRUpload`

- packages/@uppy/golden-retriever/src/index.js
Closes #4080
Co-authored-by: Antoine du Hamel <duhamelantoine1995@gmail.com>
> Fix retry upload with Golden Retriever

- packages/@uppy/aws-s3/src/MiniXHRUpload.js
- packages/@uppy/xhr-upload/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/3640
> @uppy/xhr-upload: fix `Timed out waiting for socket`

- packages/@uppy/core/types/index.d.ts
> @uppy/core: make cancel() and close() arguments optional in types

- packages/@uppy/aws-s3/src/MiniXHRUpload.js
- packages/@uppy/tus/src/index.js
- packages/@uppy/xhr-upload/src/index.js
Fixes #4166, introduced in #4148
> replace `this.getState().files` with `this.uppy.getState().files`

- website/src/docs/facebook.md
see https://community.transloadit.com/t/advice-for-facebook-app/16276/2
> Add note about facebook approval

- packages/@uppy/aws-s3-multipart/src/index.js
- packages/@uppy/tus/src/index.js
> @uppy/aws-s3-multipart,@uppy/tus: fix `Timed out waiting for socket`

- packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
- packages/@uppy/aws-s3-multipart/src/index.js
review / suggested changes for #4179
> bikeshedding PR for #4179 - remove dead code and simplify

- packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
- packages/@uppy/aws-s3-multipart/src/index.js
- packages/@uppy/companion-client/src/RequestClient.js
It still far from done, but I think it's a good enough PoC already, if you want to test it out.
> @uppy/aws-s3-multipart: refactor rate limiting approach

- packages/@uppy/angular/projects/uppy/angular/tsconfig.lib.json
- packages/@uppy/utils/types/index.d.ts
This reverts commit a249e09163b8ff38ee595f47f7f882ecaea4a0b3.
> @uppy/utils: fix types

- packages/@uppy/core/src/Uppy.test.js
> core: fix typo in Uppy.test.js

- packages/@uppy/companion/KUBERNETES.md
> Fix typo in KUBERNETES.md

- packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.scss
- packages/@uppy/dashboard/src/components/FileItem/MetaErrorMessage.jsx
Fixes #4273
Also fix styling issue
> @uppy/core: fix metafields validation when used as function

- packages/@uppy/dashboard/src/components/AddFiles.jsx
- fix broken grouping and tagline logic (didn't take into account all acquirers like showNativePhotoCameraButton)
- don't show lonely My Device
https://community.transloadit.com/t/hide-my-device/16456
> fix dashboard acquirers list

- packages/@uppy/core/src/Uppy.js
- packages/@uppy/core/src/Uppy.test.js
Fixes this issue with Status Bar and by allowing new upload after progress is reset:
https://user-images.githubusercontent.com/1199054/221958460-38646db9-5b1a-4982-aad3-5160dd1816e0.mov
> @uppy/core: fix uppy.resetProgress()

- packages/@uppy/companion/src/server/emitter/redis-emitter.js
> @uppy/companion: fix typo in redis-emitter.js

- .github/workflows/companion-deploy.yml
- .github/workflows/release.yml
instead of only on companion release
> Move heroku deploy to every commit

- website/themes/uppy/layout/layout.ejs
Let's make sure folks visiting the old website know they are on an old un-maintained version.
Refs: https://github.com/transloadit/uppy/pull/4369
> website: add a deprecation notice and a link to the new website

- packages/@uppy/core/src/Uppy.js
Fixes: https://github.com/transloadit/uppy/issues/4349
> @uppy/core: fix bug with `setOptions`

- packages/@uppy/companion/src/server/jobs.js
> @uppy/companion: add `service: 'companion'` to periodic ping

- README.md
Feel free to correct if this is not the desired image or the alt text needs changes.
> docs: fix logo in readme

- packages/@uppy/xhr-upload/README.md
> @uppy/xhr-upload: fix type in README.md

- packages/@uppy/companion/src/server/helpers/jwt.js
- packages/@uppy/companion/src/standalone/index.js
- packages/@uppy/companion/test/__tests__/preauth.js
> Revert "Refactor/dedupe cookie/session logic"

- BUNDLE-README.md
- CHANGELOG.md
- README.md
- examples/aws-nodejs/public/drag.html
- examples/aws-nodejs/public/index.html
- examples/cdn-example/index.html
- examples/uppy-with-companion/client/index.html
- packages/@uppy/transloadit/CHANGELOG.md
- packages/@uppy/transloadit/package.json
- packages/uppy/package.json
| Package           | Version | Package           | Version |
| ----------------- | ------- | ----------------- | ------- |
| @uppy/transloadit |   3.1.5 | uppy              |   3.9.1 |
- @uppy/transloadit: clean up event listener to prevent cancelled assemblies (Merlijn Vos / #4447)
> Release: uppy@3.9.1

- packages/@uppy/companion/src/standalone/helper.js
> fix undefined protocol and example page

- packages/@uppy/dashboard/src/components/FileCard/index.jsx
> @uppy/dashboard: include the old state when setting new

- examples/custom-provider/server/CustomProvider.cjs
- packages/@uppy/companion/src/server/provider/credentials.js
> Custom provider fixes

- examples/aws-nodejs/index.js
- examples/aws-nodejs/package.json
- yarn.lock
Extracted from https://github.com/transloadit/uppy/pull/4463. Our example was still using the SDK v2, upgrading it to v3 so it's more relevant.
> examples/aws-nodejs: upgrade to AWS-SDK v3

- packages/@uppy/aws-s3-multipart/src/index.js
Refs: https://github.com/transloadit/uppy/pull/4205#discussion_r1240036220
> @uppy/aws-s3-multipart: fix resume single-chunk multipart uploads

- packages/@uppy/aws-s3/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/4543
> @uppy/aws-s3: fix remote uploads

- packages/@uppy/aws-s3-multipart/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/4564
> @uppy/aws-s3-multipart: fix support for non-multipart PUT upload

- packages/@uppy/react/src/DashboardModal.js
> @uppy/react: allow `id` from props

- packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
- packages/@uppy/aws-s3-multipart/src/index.js
> @uppy/aws-s3-multipart: fix crash on pause/resume

- packages/@uppy/status-bar/src/StatusBar.jsx
Fixes: https://github.com/transloadit/uppy/issues/4582
> @uppy/status-bar: fix ETA when status bar is installed during upload

- packages/@uppy/companion/src/server/controllers/s3.js
> @uppy/companion: allow dynamic S3 bucket

- Dockerfile
- Dockerfile.test
Node.js v18.17.1 fixed some important vulnerabilities.
> meta: upgrade Node.js docker version

- packages/@uppy/companion/src/companion.js
- packages/@uppy/companion/src/server/controllers/refresh-token.js
- packages/@uppy/companion/src/server/provider/drive/index.js
- packages/@uppy/companion/src/server/provider/index.js
- packages/@uppy/companion/src/server/provider/onedrive/index.js
also [handle google drive refresh token revoked](https://github.com/transloadit/uppy/commit/c91ed4b4d255143a914b197776a3f806739fcbc1)
> Onedrive refresh tokens

- packages/@uppy/compressor/package.json
- packages/@uppy/compressor/src/index.js
- packages/@uppy/compressor/src/index.test.js
- yarn.lock
> @uppy/compressor: update file.meta.name after compression, becase format/extension might have changed

- packages/@uppy/companion/src/server/provider/onedrive/adapter.js
- packages/@uppy/companion/src/server/provider/onedrive/index.js
> @uppy/companion: fix onedrive pagination

- packages/@uppy/companion/src/server/provider/onedrive/adapter.js
> fix edge case for pagination on root

- .env.example
- private/dev/Dashboard.js
> fix VITE_COMPANION_ALLOWED_HOSTS

- packages/@uppy/aws-s3-multipart/src/index.js
- packages/@uppy/aws-s3-multipart/src/index.test.js
- packages/@uppy/companion-client/src/RequestClient.js
> aws-s3-multipart - call `#setCompanionHeaders` in `setOptions`

- .github/CONTRIBUTING.md
> add companion hotfix doc

- packages/@uppy/companion-client/src/Provider.js
that would be triggered when uploading multiple files in parallell if a 401 occurs, it would cause multiple refresh-token requests to be fired in parallel also only call refresh-token if we have a token
and reset the token if refresh-token fails with 401
> fix a refresh token race condition

- .github/workflows/linters.yml
- package.json
fixes https://github.com/transloadit/uppy/pull/4704#issuecomment-1735929961
> meta: update linter config to cover more files

- packages/@uppy/companion-client/types/index.d.ts
Added the type for Companion OAuth keys in response to https://github.com/transloadit/uppy/issues/4664#issuecomment-1708924715
> Added Companion OAuth Key type

- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/companion/src/server/controllers/s3.js
- packages/@uppy/companion/src/server/helpers/utils.js
> Bucket fn also remote files

- packages/@uppy/dashboard/src/Dashboard.jsx
> @uppy/dashboard: Remove uppy-Dashboard-isFixed when uppy.close() is invoked

- packages/uppy/index.mjs
To allow creating custom plugins via CDN imports
Closes #4615
> uppy CDN: Export UIPlugin and BasePlugin

- bin/upload-to-cdn.js
upload-to-cdn was failing because we upgraded to AWS-SDK v2 to v3 in https://github.com/transloadit/uppy/pull/4776
> Migrate to AWS-SDK V3 syntax

- package.json
https://git-scm.com/docs/git-clean#Documentation/git-clean.txt--X
This should avoid devs mistakenly removing all their uncommitted changes when they only want to clean the build artefacts.
> Fix build clean

- packages/@uppy/utils/src/FileProgress.ts
Necessary for https://github.com/transloadit/uppy/pull/4839
> @uppy/utils: improve `preprocess` and `postprocess` types

- packages/@uppy/provider-views/src/Item/components/ItemIcon.jsx
Closes #4650
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#referrerpolicy
> @uppy/provider-views: add referrerpolicy to images

- packages/@uppy/form/src/index.js
Closes #4663 
https://caniuse.com/mdn-api_htmlformelement_requestsubmit
> @uppy/form: use requestSubmit

- .github/workflows/output-watcher.yml
- bin/build-lib.js
see https://github.com/transloadit/uppy/pull/4868#issuecomment-1897717779
> remove comments in output code

- .github/workflows/output-watcher.yml
- bin/build-lib.js
> meta: improve output watcher diff

- packages/@uppy/companion-client/src/Provider.ts
> fix ts errors

- packages/@uppy/audio/.npmignore
- packages/@uppy/companion-client/.npmignore
- packages/@uppy/compressor/.npmignore
- packages/@uppy/core/.npmignore
- packages/@uppy/drop-target/.npmignore
- packages/@uppy/image-editor/.npmignore
- packages/@uppy/locales/.npmignore
- packages/@uppy/status-bar/.npmignore
- packages/@uppy/store-default/.npmignore
- packages/@uppy/tus/.npmignore
- packages/@uppy/utils/.npmignore
- packages/@uppy/xhr-upload/.npmignore
- private/js2ts/index.mjs
Refs: https://community.transloadit.com/t/esbuild-loader-complains-about-tsconfig-shared-not-found/16988
> meta: exclude `tsconfig` files from npm bundles

- packages/@uppy/compressor/package.json
- packages/@uppy/core/package.json
- packages/@uppy/dashboard/package.json
- packages/@uppy/status-bar/package.json
- yarn.lock
Fixes: https://github.com/transloadit/uppy/issues/4931
Fixes: https://github.com/transloadit/uppy/issues/4932
> bump `@transloadit/prettier-bytes`

- packages/@uppy/onedrive/src/OneDrive.jsx
I believe it was never implemented
> fix custom oauth2 credentials for onedrive

- packages/@uppy/box/src/Box.jsx
> fetchPreAuthToken in box too

- packages/@uppy/companion/src/config/companion.js
https://github.com/transloadit/uppy/pull/5003#issuecomment-2007045486
> improve error msg

- packages/@uppy/core/src/BasePlugin.ts
- packages/@uppy/core/src/Restricter.ts
- packages/@uppy/core/src/Uppy.ts
Those reports errors when compiling with TS 5.4
> @uppy/core: fix some type errors

- packages/@uppy/status-bar/src/StatusBar.tsx
> @uppy/status-bar: remove default target

- packages/@uppy/progress-bar/src/ProgressBar.tsx
> @uppy/progress-bar: remove default target

- packages/@uppy/companion/package.json
- yarn.lock
see https://community.transloadit.com/t/issue-with-companion-redis-options/17058
> upgrade redis

- bin/build-bundle.mjs
> @uppy/locales: do not build dist folder

- examples/custom-provider/client/MyCustomProvider.jsx
Ref: https://github.com/transloadit/uppy/pull/4977#issuecomment-2056292274
> meta: fix custom provider example

- packages/@uppy/dashboard/src/Dashboard.tsx
> @uppy/dashboard: fix type of trigger option

- packages/@uppy/svelte/package.json
Svelte 5 is in release candidate since today.
> Add svelte 5 as peer dep

- packages/@uppy/compressor/package.json
- packages/@uppy/core/package.json
- packages/@uppy/dashboard/package.json
- packages/@uppy/status-bar/package.json
- yarn.lock
`0.3.3` breaks builds so let's make sure we get the fix in from `0.3.4`
> Upgrade @transloadit/prettier-bytes

- packages/@uppy/svelte/src/components/Dashboard.svelte
- packages/@uppy/svelte/src/components/DashboardModal.svelte
- packages/@uppy/svelte/src/components/DragDrop.svelte
- packages/@uppy/svelte/src/components/ProgressBar.svelte
- packages/@uppy/svelte/src/components/StatusBar.svelte
I stumble upon this bug while working on https://github.com/transloadit/uppy/pull/5181, worth doing a quick fix IMO.
> @uppy/svelte: do not attempt removing plugin before it's created

- private/release/formatChangeLog.js
We are regularly using `e2e`, `examples`, or `docs` as subsystems. We are no longer using `website`.
> meta: improve changelog generator

- docs/uppy-core.mdx
> docs: document clearUploadedFiles

- .eslintrc.js
- packages/@uppy/audio/src/RecordingScreen.tsx
- packages/@uppy/status-bar/src/StatusBarUI.tsx
Refs: https://github.com/transloadit/uppy/pull/5209
> meta: use default argument value instead of `defaultProps`

- packages/@uppy/provider-views/src/style/uppy-ProviderBrowser-viewType--list.scss
Fixes #5233
Not sure why it wasn't picked up by before but now we make sure the correct font is used.
> @uppy/provider-views: fix wrong font for files

- docs/uploader/transloadit.mdx
> docs: clarify assemblyOptions for @uppy/transloadit

- packages/@uppy/companion/src/standalone/helper.js
- packages/@uppy/companion/src/standalone/index.js
> improve companion logging

- packages/@uppy/locales/src/fa_IR.ts
> @uppy/locales: fix fa_IR export

- README.md
> Fix Transloadit logo in README in darkmode

- README.md
> Fix broken workflow status badges in README

- packages/@uppy/provider-views/src/ProviderView/ProviderView.tsx
In continuation of https://github.com/transloadit/uppy/pull/5288.
https://github.com/transloadit/uppy/assets/7578559/0bb108b6-05ea-4a7c-8556-51e10e1a29e7
> `.openFolder()` - return progress indication

- packages/@uppy/core/src/Uppy.ts
Transloadit testing area depends on this in a lot of states so let's keep it.
> @uppy/core: bring back resetProgress

- private/upload-to-cdn/index.js
The file was moved, and we forgot to update the path
> meta: fix require path in `upload-to-cdn`

- packages/@uppy/remote-sources/src/index.ts
> @uppy/remote-sources: fix options type

- docs/uploader/aws-s3-multipart.mdx
> docs: fix getTemporarySecurityCredentials in aws-s3

- packages/@uppy/tus/src/index.ts
> @uppy/tus: Fix onShouldRetry type signature

- .yarn/patches/p-queue-npm-8.0.1-fe1ddcd827.patch
- package.json
- yarn.lock
Almost reverts https://github.com/transloadit/uppy/pull/5391, but keep the new version
> meta: add back patch for `p-queue`

- .github/workflows/bundlers.yml
- bin/build-bundle.mjs
- packages/@uppy/aws-s3/src/index.ts
- packages/@uppy/box/src/index.ts
- packages/@uppy/compressor/src/index.ts
- packages/@uppy/dropbox/src/index.ts
- packages/@uppy/facebook/src/index.ts
- packages/@uppy/google-drive/src/index.ts
- packages/@uppy/google-photos/src/index.ts
- packages/@uppy/image-editor/src/ImageEditor.tsx
- packages/@uppy/image-editor/src/index.ts
- packages/@uppy/informer/src/index.ts
- packages/@uppy/instagram/src/index.ts
- packages/@uppy/onedrive/src/index.ts
- packages/@uppy/screen-capture/src/index.ts
- packages/@uppy/tus/src/index.ts
- packages/@uppy/unsplash/src/index.ts
- packages/@uppy/url/src/index.ts
- packages/@uppy/xhr-upload/src/index.ts
- packages/@uppy/zoom/src/index.ts
- packages/uppy/.npmignore
- packages/uppy/bundle.mjs
- packages/uppy/package.json
- packages/uppy/src/bundle.ts
- packages/uppy/src/index.ts
- packages/uppy/tsconfig.build.json
- packages/uppy/tsconfig.json
- private/js2ts/index.mjs
- tsconfig.json
> uppy: export plugin options

- private/dev/Dashboard.js
- private/dev/tsconfig.json
Two things kept annoying me. My TS language server constantly being confused because there is no `tsconfig.json` in `private/dev/` and the fact that our main dev file is not formatted so everytime you change anything you get a huge diff. Fixing that now.
**Questions**
1. Shall I simplify the `tsconfig.json` to only have `{}` inside and leave it at that? That also fixes it for me but probably not accurate.
2. Shall I do the same for all packages inside `private/`? Same problems there.
> Add tsconfig to packages in private/

- docs/locales.mdx
> docs: fix broken links in locale docs

- packages/@uppy/transloadit/src/index.ts
- packages/@uppy/tus/src/index.ts
Ref: https://github.com/transloadit/uppy/issues/3641#issuecomment-2336670764
> @uppy/tus: correctly type tus on UppyFile

- packages/@uppy/tus/src/index.ts
> @uppy/tus: fix retry check for status code 400

- packages/@uppy/image-editor/package.json
- yarn.lock
> @uppy/image-editor: upgrade cropperjs

- e2e/cypress/integration/dashboard-transloadit.spec.ts
> try to fix flaky test

- packages/@uppy/provider-views/src/GooglePicker/googlePicker.ts
see https://github.com/transloadit/uppy/issues/5532#issuecomment-2512349529
> Google picker scope

- packages/@uppy/google-drive-picker/src/GoogleDrivePicker.tsx
- packages/@uppy/google-photos-picker/src/GooglePhotosPicker.tsx
> Fix TS generics on new Google Picker plugins

- packages/@uppy/core/src/Uppy.ts
Fixes #5508 
Accidentally removed in some refactor for no reason it seems.
> @uppy/core: bring back validateRestrictions

- packages/@uppy/google-drive-picker/src/GoogleDrivePicker.tsx
- packages/@uppy/google-photos-picker/src/GooglePhotosPicker.tsx
> Fix Google Picker plugins locale

- packages/@uppy/onedrive/src/OneDrive.tsx
> @uppy/onedrive: fix AsyncStore import

- packages/@uppy/core/src/index.ts
- packages/@uppy/provider-views/src/SearchProviderView/SearchProviderView.tsx
Fixes #5584 
Follow up PR will clean up some more imports (stylistic, not fixes)
> @uppy/provider-views: fix incorrect import

- packages/@uppy/unsplash/src/Unsplash.tsx
> @uppy/unsplash: make utmSource optional

- packages/@uppy/aws-s3/src/index.test.ts
- packages/@uppy/aws-s3/src/index.ts
> @uppy/aws-s3: allow uploads to fail/succeed independently

- packages/@uppy/tus/src/index.ts
> @uppy/tus: fix resumeFromPreviousUpload race condition

- packages/@uppy/provider-views/src/GooglePicker/googlePicker.ts
would previously just download thumbnails
> fix google photos picker videos

- packages/@uppy/locales/src/cs_CZ.ts
> @uppy/locales - update cs_CZ.ts

- packages/@uppy/status-bar/src/StatusBarUI.tsx
> @uppy/status-bar: fix aria-hidden warning

- packages/uppy/src/bundle.ts
> Fix BasePlugin export for CDN bundle

- packages/@uppy/react/src/useUppyState.ts
> @uppy/react: pass getServerSnapshot to useSyncExternalStoreWithSelector

- .github/workflows/release.yml
- bin/build-bundle.mjs
- private/upload-to-cdn/index.js
seems to have been broken for a while
https://github.com/transloadit/uppy/actions/runs/13830580019/job/38693751942
> Fix locales building

- packages/@uppy/audio/src/Audio.tsx
- packages/@uppy/audio/src/locale.ts
- packages/@uppy/box/src/Box.tsx
- packages/@uppy/core/src/BasePlugin.ts
- packages/@uppy/core/src/Uppy.ts
- packages/@uppy/core/src/types.test.ts
- packages/@uppy/dashboard/src/Dashboard.tsx
- packages/@uppy/drag-drop/src/DragDrop.tsx
- packages/@uppy/dropbox/src/Dropbox.tsx
- packages/@uppy/facebook/src/Facebook.tsx
- packages/@uppy/file-input/src/FileInput.tsx
- packages/@uppy/google-drive-picker/src/GoogleDrivePicker.tsx
- packages/@uppy/google-drive/src/GoogleDrive.tsx
- packages/@uppy/google-photos-picker/src/GooglePhotosPicker.tsx
- packages/@uppy/image-editor/src/ImageEditor.tsx
- packages/@uppy/instagram/src/Instagram.tsx
- packages/@uppy/onedrive/src/OneDrive.tsx
- packages/@uppy/react/src/FileInput.ts
- packages/@uppy/remote-sources/src/index.ts
- packages/@uppy/screen-capture/src/ScreenCapture.tsx
- packages/@uppy/status-bar/src/locale.ts
- packages/@uppy/unsplash/src/Unsplash.tsx
- packages/@uppy/url/src/Url.tsx
- packages/@uppy/webcam/src/Webcam.tsx
- packages/@uppy/webcam/src/locale.ts
- packages/@uppy/webdav/src/Webdav.tsx
- packages/@uppy/zoom/src/Zoom.tsx
> @uppy/core: fix locale type for plugins

- packages/@uppy/utils/src/mimeTypes.ts
> @uppy/utils: add msg mimetype

- packages/@uppy/companion/src/server/provider/dropbox/index.js
- packages/@uppy/companion/test/__tests__/providers.js
this adds support for team spaces folders
note: Do **not** enable any Team scopes (permissions) at https://www.dropbox.com/developers/apps that will break the app (making it a team admin app instead)
> implement dropbox business teams

- packages/@uppy/angular/package.json
- packages/@uppy/angular/projects/uppy/angular/package.json
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard-modal/dashboard-modal.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard/dashboard.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/drag-drop/drag-drop.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar-demo.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/status-bar/status-bar.component.ts
- yarn.lock
Since using Uppy 18 with Angular 19 seems to work fine, I just updated the dependencies and the ranges, with the addition of the new inject() function for dependency injection.
> Support Angular 19

- packages/@uppy/angular/package.json
- packages/@uppy/angular/projects/uppy/angular/package.json
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard-modal/dashboard-modal.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard-modal/dashboard-modal.module.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard-modal/dashboard-modal.stories.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard/dashboard.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard/dashboard.module.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard/dashboard.stories.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/drag-drop/drag-drop.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/drag-drop/drag-drop.module.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/drag-drop/drag-drop.stories.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar-demo.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar.module.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar.stories.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/status-bar/status-bar.component.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/status-bar/status-bar.module.ts
- packages/@uppy/angular/projects/uppy/angular/src/lib/components/status-bar/status-bar.stories.ts
- packages/@uppy/angular/projects/uppy/angular/src/public-api.ts
- yarn.lock
Since using Uppy 18 with Angular 19 seems to work fine, I just updated the dependencies and the ranges, with the addition of the new inject() function for dependency injection.
> Support Angular 19 (#5709)

- packages/@uppy/audio/src/Audio.tsx
- packages/@uppy/box/src/Box.tsx
- packages/@uppy/core/src/types.test.ts
- packages/@uppy/dashboard/src/Dashboard.tsx
- packages/@uppy/drag-drop/src/DragDrop.tsx
- packages/@uppy/dropbox/src/Dropbox.tsx
- packages/@uppy/facebook/src/Facebook.tsx
- packages/@uppy/file-input/src/FileInput.tsx
- packages/@uppy/google-drive-picker/src/GoogleDrivePicker.tsx
- packages/@uppy/google-drive/src/GoogleDrive.tsx
- packages/@uppy/google-photos-picker/src/GooglePhotosPicker.tsx
- packages/@uppy/image-editor/src/ImageEditor.tsx
- packages/@uppy/instagram/src/Instagram.tsx
- packages/@uppy/onedrive/src/OneDrive.tsx
- packages/@uppy/remote-sources/src/index.ts
- packages/@uppy/screen-capture/src/ScreenCapture.tsx
- packages/@uppy/unsplash/src/Unsplash.tsx
- packages/@uppy/url/src/Url.tsx
- packages/@uppy/utils/src/Translator.ts
- packages/@uppy/webcam/src/Webcam.tsx
- packages/@uppy/webdav/src/Webdav.tsx
- packages/@uppy/zoom/src/Zoom.tsx
Ref: https://github.com/transloadit/uppy/issues/5697#issuecomment-2815621054
> ts: make locale strings optional

- packages/@uppy/core/src/Uppy.ts
This fixes #5781 
please go through the issue comments for more context
**After :**
https://github.com/user-attachments/assets/ce7f384c-0888-47ab-a57b-2fa8d6f17f2e
> @uppy/core: resolve stale state issue in checkAndUpdateFileState

- packages/@uppy/companion/src/server/Uploader.js
- packages/@uppy/companion/src/server/provider/index.js
> @uppy/companion: add provider name to metadata

- package.json
changed build`watch` script for e2e
> fix e2e script

- packages/@uppy/aws-s3-multipart/package.json
- packages/@uppy/aws-s3/package.json
- packages/@uppy/box/package.json
- packages/@uppy/dashboard/package.json
- packages/@uppy/dropbox/package.json
- packages/@uppy/facebook/package.json
- packages/@uppy/google-drive-picker/package.json
- packages/@uppy/google-drive/package.json
- packages/@uppy/google-photos-picker/package.json
- packages/@uppy/instagram/package.json
- packages/@uppy/onedrive/package.json
- packages/@uppy/react-native/package.json
- packages/@uppy/react/package.json
- packages/@uppy/remote-sources/package.json
- packages/@uppy/svelte/package.json
- packages/@uppy/transloadit/package.json
- packages/@uppy/tus/package.json
- packages/@uppy/unsplash/package.json
- packages/@uppy/url/package.json
- packages/@uppy/vue/package.json
- packages/@uppy/webdav/package.json
- packages/@uppy/xhr-upload/package.json
- packages/@uppy/zoom/package.json
- yarn.lock
Closes #5774
There are still some warnings left but they are better done in their own PRs as they require bigger changes.
> Resolve @uppy/core yarn install warnings

- .changeset/calm-rabbits-live.md
- packages/@uppy/locales/package.json
> @uppy/locales: move dev deps actually to devDependencies

- package.json
- turbo.json
[always run yarn build before watch](https://github.com/transloadit/uppy/commit/2507302e29d9594f7082f38803adc9bea58d53ec) 
or else everything doesn't get built
closes https://github.com/transloadit/uppy/issues/5858
> Fix turbo scripts

- .changeset/puny-llamas-tap.md
- packages/@uppy/provider-views/src/ProviderView/ProviderView.tsx
- packages/@uppy/provider-views/src/SearchProviderView/SearchProviderView.tsx
- packages/@uppy/redux-dev-tools/src/index.js
- packages/@uppy/store-redux/src/index.js
> Fix remaining package.json imports

- .github/workflows/release.yml
Closes #5868 
- Run `corepack yarn workspace @uppy/angular prepublishOnly`
- Upload to CDN
- Update versions in readme's to latest CDN version
- Bring back Companion docker deploy
> Add missing release steps

- .changeset/curvy-ravens-drum.md
- packages/@uppy/svelte/src/lib/components/Dashboard.svelte
- packages/@uppy/svelte/src/lib/components/DashboardModal.svelte
- packages/@uppy/svelte/src/lib/components/DragDrop.svelte
- packages/@uppy/svelte/src/lib/components/ProgressBar.svelte
- packages/@uppy/svelte/src/lib/components/StatusBar.svelte
> @uppy/svelte: fix prop passing and types

- .changeset/big-cloths-look.md
- packages/@uppy/dashboard/src/Dashboard.tsx
- packages/@uppy/status-bar/src/StatusBarOptions.ts
Ref: https://github.com/transloadit/uppy/pull/5728#issuecomment-3031052997
Closes #5811
> Fix locale types between dashboard and status-bar

- .changeset/curly-trees-camp.md
- packages/@uppy/transloadit/src/index.ts
> @uppy/transloadit: add `user_meta` type

- biome.json
(cherry picked from commit 250806ea2d95d519e9f96224024695bd4e4f56fe) (cherry picked from commit 25080705c2fe3178c8ae01f402573f0fb1cbea37)
closes #5888
> add react rules

- biome.json
> Fix biome broken lint 2

- .changeset/odd-goats-bow.md
- packages/@uppy/react/package.json
- packages/@uppy/vue/package.json
> @uppy/vue,@uppy/react: remove status-bar from export map

- examples/react/.stackblitzrc
- examples/sveltekit/.stackblitzrc
- examples/vue/.stackblitzrc
> add typescript as a dev dep in stackblitz env

- .changeset/thick-ears-tease.md
- packages/@uppy/transloadit/package.json
> @uppy/transloadit: move `transloadit` into `dependencies`
