transloadit/uppy

website/src/docs/uppy.md
If the uploadStarted is set to false, and the autoProceed is on, it asks to retry the file and displays them as failures.
Example: https://github.com/transloadit/uppy/issues/1112#issuecomment-785160268
=> Fix: uploadStarted should say true

packages/@uppy/aws-s3-multipart/src/index.js
=> fix: Aws-s3-multipart sends outdated file info to upload-success event

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/server/emitter/index.js, packages/@uppy/companion/src/server/emitter/redis-emitter.js, website/src/docs/companion.md
Adds new setting `redisPubSubScope` which configures the `scope` parameter at https://www.npmjs.com/package/node-redis-pubsub. Allows one to share a redis instance/cluster with other services more easily.
=> Feature: add redis pubsub scope setting

website/src/docs/svelte.md
There was a hanging sentence, that made this documentation unclear. Fixed the sentence, added an example.
=> Documentation: Corrected hanging sentence in Svelte documentation, added an example

.github/workflows/companion-deploy.yml, Procfile, bin/companion-heroku, package-lock.json, packages/@uppy/companion/Procfile, packages/@uppy/companion/package.json
Currently we push the entire repo to heroku and it installs the whole dependency tree, leading to 400MB+ image sizes. Companion is actually self contained so we can only push that folder to Heroku and reduce our image sizes by 90%, and increase deploy performance by a similar margin.
=> companion: smaller heroku deployment

website/src/docs/drop-target.md
On the Drop Target page the npm installation instructions say to install `drag-drop` instead of `drop-target`. This fixes.
=> Fix npm package name for drop-target

examples/svelte-example/package.json, package-lock.json, package.json, packages/@uppy/companion/package.json
This PR updates TypeScript from version `3.7.3` to `~4.1`, in order to accommodate the upcoming Angular integration (#2381). This update does come with breaking changes, which can be read [here](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes).
Well Angular straight up requires a TypeScript version `>= 4.0 < 4.2`, so basically either `4.1` or `4.0`. Since the former is newer, it seems like the better choice.
Unfortunately, due to the way npm 7 handles dependencies, we can't isolate this change to just one folder. The short explanation is that dependencies that only one package has are installed into root, and a different TypeScript version is installed into that package directory, so the other dependencies can't find it. There are of course solutions, but most are hacky, and …
=> Upgrade TypeScript

packages/@uppy/core/src/index.js, website/src/docs/uppy.md
Should we call it something more distinct, `logoutAll` or `signout`? `logout` could be confused with `log`, but maybe not. It is consistent with `this.provider.logout` that it calls internally.
=> Add uppy.logout() that logs user out of all cloud providers

packages/@uppy/webcam/src/index.js
[FIX] - improve MIME type detection to solve issue in iOS Safari where the first Blob in the Array might not have a MIME type specified and so would crash the Webcam component when we try to determine the MIME type.
=> [FIX] Webcam - improve MIME type detection to solve issue in iOS Safari 

packages/@uppy/core/src/index.js
[`AggregateError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError#browser_compatibility) is now available in most browser engines, and is standard.
=> core: use AggregateError when available

packages/@uppy/core/src/index.js
AKAICT, `addFiles` doesn't cut any corner (anymore?), I think it should be used as soon as there is more than one file to add. This PR is removing the comment suggesting to use that method only with lots of files.
Fixes: https://github.com/transloadit/uppy/issues/2787
=> core: remove outdated comment

.eslintrc.js, packages/@uppy/dashboard/src/components/FileItem/FileProgress/index.js
In recent Big Linting Update™️ https://github.com/transloadit/uppy/pull/2796 autofix changed `stroke-width="2"` to `strokeWidth="2"` due to this rule https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md. Preact doesn’t play nice with camelCased html properties.
What do you think @goto-bus-stop @kvz, should we remove the rule?
https://preactjs.com/guide/v10/differences-to-react/#svg-inside-jsx:
> SVG is pretty interesting when it comes to the names of its properties and attributes. Some properties (and their attributes) on SVG objects are camelCased (e.g. clipPathUnits on a clipPath element), some attributes are kebab-case (e.g. clip-path on many SVG elements), and other attributes (usually ones inherited from the DOM, e.g. oninput) are all …
=> Dashboard: fix individual progress by renaming camelCased svg properties

packages/@uppy/companion/src/server/Uploader.js
Allows the companion user to specify a max chunk size for tus uploads, to prevent issues like running out of memory in primitive tusd implementations.
Fixes #2663
=> add chunkSize companion option

packages/@uppy/dashboard/src/utils/trapFocus.js
This seems to just be a typo, and I'm not sure why it's working at all, but it breaks when building with snowpack.
=> Remove double-slash from require path

packages/@uppy/dashboard/src/components/AddFiles.js, packages/@uppy/dashboard/src/style.scss
I noticed that Chrome showed an incorrect font on the Dashboard buttons:
Here, I've made a simple fix to resolve this — so everything looks as expected:
=> Fix incorrect font in Chrome on the Dashboard

packages/@uppy/companion-client/src/RequestClient.js
Changes the HTTP request error handling logic to only replace the
message inside an Error object, instead of creating a new Error. This
should keep stack traces intact and prevents us from obscuring any
potential additional properties on the original Error.
Hopefully this improves debugability. someone in Transloadit support
is running into issues _somewhere_ between the S3 plugin and Companion,
but the error message is missing. I think `${err}` in this code _should_
show the error, but it's even better if we can keep the stack trace and
stuff.
=> companion-client: rethrow original error objects

packages/@uppy/url/src/index.js
Only `@uppy/url` plugin is missing `companionCookiesRule` option.
[The documentation](https://github.com/transloadit/uppy/blob/f4e99fa7bf8ac085d4215215aa1d2b3342ef9fef/website/src/docs/url.md#companioncookiesrule-same-origin)
=> url: Add missing companionCookiesRule option

packages/@uppy/companion/src/server/helpers/request.js
When a URL import attempt responds with a redirect, we tried to naively
parse the URL with `new URL()`. This is a problem when the URL is
invalid, because that constructor will throw an error.
Redirect URLs are also allowed to be relative URLs, which was not
supported by us.
With this change, invalid URLs will cause a redirect to be blocked,
and relative redirects will work.
=> companion: support relative redirect URLs in responses

packages/@uppy/url/src/index.js
In the case of an invalid URL, this is no proper way to handle an error. `uppy.state.info` only show the error without any info that due to which URL error was thrown. 
So returning the error or file so it can be handled as need. throwing the error will not be backward compatible
=> return fileId or error in plugin.addFile

packages/@uppy/utils/src/Translator.js
Fixes types and small code edits:
`<regex>[Symbol.split](<string>)` is equivalent to `String.prototype.split.call(<string>, <regex>)` and potentially more readable (the downside it's not compatible with IE, which may be why we currently use the latter). I'm not sure where we stand in term of IE compatibilty.
Refs: https://github.com/transloadit/uppy/pull/2899
=> Translator: refactor interpolate

packages/@uppy/core/src/index.js, packages/@uppy/store-redux/src/index.js
~Using `forceUpdate` is closer to the intent than an empty `setState` call is IMHO.~
~Calling `setState` in the constructor is not useful, we can simply assign a `state` property to the object.~
nevermind it's not the preact `setState` but the uppy one. Instead, I'm adding comments to emphasise it's not the preact `setState` method.
=> Add comments around empty setState calls

packages/@uppy/core/src/index.js, packages/@uppy/transloadit/src/index.js
Targeting conservatively in case this is a breaking change. Node.js v15+ defaults to crashing if there are unhandled promises rejections at runtime (https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
It's indeed quite tricky to spot and to find where the rejected promise comes from, after investigation it looks like it this error that is being thrown from the `errorHandler`: https://github.com/transloadit/uppy/blob/57eae08e9d1c0fdc12bd487ad8d777e389d43ec4/packages/@uppy/core/src/index.js#L290-L293
=> transloadit: fix unhandled promise rejections

packages/@uppy/core/src/index.js, packages/@uppy/core/types/index.d.ts, packages/@uppy/dashboard/src/index.js, packages/@uppy/status-bar/src/index.js
Resolve TODO comment by making a shared `getObjectOfFilesPerState` function in core and reusing it in dashboard and statusbar.
=> Create `getObjectOfFilesPerState` for plugins

packages/@uppy/core/src/index.js
It used to be just the short file object, now it’s the full one that is the same you get from other callbacks and events in Uppy.
Supersedes https://github.com/transloadit/uppy/pull/1594/files#
=> core: onBeforeFileAdded: pass full file object with extension, detected type, meta, size, etc

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3/src/MiniXHRUpload.js, packages/@uppy/aws-s3/src/index.js, packages/@uppy/tus/src/index.js, packages/@uppy/utils/src/RateLimitedQueue.js, packages/@uppy/utils/src/RateLimitedQueue.test.js, packages/@uppy/utils/types/index.d.ts, packages/@uppy/xhr-upload/src/index.js
IE users will need a polyfill for `Symbol` (e.g., https://github.com/rousan/symbol-es6).
=> xhr: use symbol for internal options

website/src/_posts/2016-08-0.8.0.md, website/src/_posts/2016-09-0.10.md, website/src/_posts/2017-02-0.14.md, website/src/_posts/2017-05-0.17.md, website/src/_posts/2017-09-0.19.md, website/src/_posts/2017-10-0.20.md, website/src/_posts/2017-12-0.22.md, website/src/_posts/2018-02-0.23.md, website/src/_posts/2018-10-0.28.md, website/src/_posts/2019-04-liftoff-23.md, website/src/_posts/2019-10-1.5.md, website/src/_posts/2019-11-1.6.md, website/src/_posts/2020-03-custom-providers.md, website/src/_posts/2020-04-1.10.md, website/src/_posts/2020-04-1.13.md, website/src/_posts/2020-07-1.18-image-editor.md, website/src/_posts/2020-10-1.22.md, website/src/_posts/2020-12-1.24.md, website/src/_posts/2021-02-1.26.md, website/src/_posts/2021-04-1.27.md, website/src/_posts/2021-07-1.30.md
This commit is the result of running ESLint `--fix` on our current blog posts, so only auto-fixable lint errors are being updated.
=> tools: fix linter errors in JS code snippets inside blog posts

.eslintignore, website/src/_posts/2021-XX-XX.md
Enable linter on future blog posts (enabling the linter on existing blog posts would require some major refactors, auto-fixable errors are being suggested in #2991).
=> tools: lint JS code snippets inside blog posts

package.json, packages/@uppy/angular/package.json
A rogue `.gitignore` file was preventing the `dist` folder from shipping with the Angular integration. It's been... *taken care of*.
I added a `files` section to the `package.json` file for `@uppy/angular`, so it should, you know, actually be usable. Thanks to some Uppy folks for helping me track down the source of the issue.
Note: I also made Angular build for production instead of dev mode, when you run the NPM build script.
Closes #2987
=> angular: Fix broken packaging

.github/CONTRIBUTING.md, packages/@uppy/robodog/types/index.d.ts, packages/@uppy/robodog/types/index.test-d.ts, packages/@uppy/transloadit/types/index.d.ts
Have been interested in using Robodog for a while but the lack of types was a no-go for me. I also added the transloadit assembly type (ported from transloadit node.js) as well as inner result/file types.
There's still some inaccuracy here due to `addDashboardPlugin.js` and its exclusion of different dashboard settings based on `inline`, however I think this is close enough for the time being.
Fixes #2447
=> Add Robodog Types

packages/@uppy/core/src/index.js
When the `'error'` event is emitted, the error is stored on the file
object if the second argument is a file.
I don't know if that is intentional behaviour or if it's a coincidental
effect of the implementation. We don't use it anywhere.
When an upload step fails, `Uppy#_runUpload()` may emit an 'error'
message with the upload ID in the second argument. So then `file` is the
upload ID in this event handler. A string is not null, but it also
doesn't have an `.id` property, so the `setFileState()` call would fail.
Now it checks to make sure that the second argument actually could be a
file.
The upload ID argument is actually also not used. So I removed it in the
second commit. It isn't documented anywhere and it is only available in
some situations if the plugin doesn't do its own error …
=> core: tighten duck type check for file objects

examples/angular-example/package.json, examples/dev/package.json, package.json, packages/@uppy/angular/package.json, packages/@uppy/companion/package.json, packages/uppy/types/index.d.ts, test/endtoend/typescript/main.ts
Angular depends on `rxjs` v6, I think it makes sense to use this instead. Also moving `browser-sync` to the `examples/dev` package and fixing other e2e test failures.
=> test: fix end2end test suite

bin/after-version-bump.js, bin/upload-to-cdn.js, website/inject.js, website/package.json, website/scripts/highlight.js
Remove use of `promisify` when a native promise API is available.
=> tools: remove use of `promisify` where possible

examples/transloadit-textarea/main.js, packages/@uppy/companion/src/companion.js, packages/@uppy/provider-views/src/SharedHandler.js, website/src/examples/markdown-snippets/app.es6
Targeting `2.0` because I believe `for..of` loops are not supported there, could be easily backported to 1.0 though.
=> core: remove use of `Array.prototype.reduce` where possible

lerna.json
We always create them but never commit them so might as well not create them in the first place.
=> Lerna bootstrap without `package-lock.json` files

packages/@uppy/provider-views/src/Breadcrumbs.js, packages/@uppy/provider-views/src/style.scss
Closes #2552
- It's now slightly more obvious the breadcrumps are links
- The active folder looks more active and can't be clicked again
- Fix eslint warnings
**Before**
**After**
=> Tweak breadcrump styling

packages/@uppy/core/src/index.js, packages/@uppy/core/src/index.test.js
This mostly reverts commit f2d30420f32da01cd4c2e466201751bf6c779156.
I'm using `Symbol.for('uppy test: createUpload')` to allow testing of `#createUpload`, I'm not sure if there's a better way of doing this. In any case, it'd be nice if we can remove this from the production build, but I haven't looked into it.
`calculateProgress` used to be called `_calculateProgress` in 1.0, I'm not sure if we wanted to have it exposed or not. It has a decent code coverage, so I left it exposed.
=> @uppy/core: use private fields

packages/@uppy/drag-drop/src/index.js, packages/@uppy/webcam/src/index.js
Using `babel-plugin-inline-package-json` (when building with `IS_RELEASE_BUILD=true npm run build`).
=> meta: fix `package.json` imports to be inlined by Babel

packages/@uppy/core/src/index.js
Also removes the binding of the method to `this` in the constructor: IMO, it should be the responsibility of the users to do that, and I don't see in which use case you would pass the `uppy.emit` as a callback.
=> @uppy/core: move event emitter to private properties

packages/@uppy/core/src/BasePlugin.js, packages/@uppy/core/src/UIPlugin.js, packages/@uppy/core/src/index.js, packages/@uppy/dashboard/src/components/Dashboard.js
Core classes methods are not suited to be used as eventHandlers, I don't think it makes sense to have them bound.
=> @uppy/core: avoid binding methods to instance in constructor

packages/@uppy/core/src/index.js, packages/@uppy/core/types/index.d.ts
~Doesn't break user code that still uses `.state` instead of `.getState`, and limits the possibility of users discovering the deprecated property.~
Mark the property as deprecated in the TypeScript definitions to nudge users to move away from it so it can be removed in a future semver-major release (`2.0.0`? `3.0.0`?).
=> @uppy/core: mark `state` as deprecated

packages/@uppy/informer/package.json, packages/@uppy/informer/src/TransitionGroup.js, packages/@uppy/informer/src/index.js
This module was breaking `create-react-app`. Instead, it vendors in the original package relevant code.
@arturi wdyt?
=> @uppy/informer: remove dependency to `preact-transition-group`

packages/@uppy/companion/src/server/helpers/jwt.js
When companion server is running on a different domain than the frontend, Chrome (and probably other browsers) will error with `A cookie associated with a cross-site resource at http://xx.com/ was set without the `SameSite` attribute It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with SameSite=None and Secure` when a thumbnail is loaded.
See also
- https://community.transloadit.com/t/dropbox-and-box-thumbnails-returning-401-unauthorized/15781
- https://community.transloadit.com/t/dropbox-image-thumbnail-issue-in-chrome/15418
This PR fixes that issue. I have verified the error and that this PR fixes the error.
=> Send sameSite and secure for https cookies

.eslintrc.js, package.json, packages/@uppy/core/src/index.js, packages/@uppy/dashboard/src/index.test.js
`AbortControler` is available globally as of Node.js v15.0.0, v14.x needs a CLI flag and it's not available at all on v12.x.
=> build: fix building on Node.js v14.x LTS

packages/@uppy/core/src/index.js
Just one with all the errors before upload.
=> Don’t show double error info message for required metafields

.eslintrc.js, packages/@uppy/transloadit/package.json, packages/@uppy/transloadit/src/Assembly.js, test/endtoend/create-react-app/src/App.js, website/package.json
The "unsafe" version of `engine.io-client` is still used for the website, but is no longer a dependency of any of the `@uppy` packages. I've marked the website deps as `devDependencies` so this version is marked `dev: true` in the `package-lock.json`.
Fixes: https://github.com/transloadit/uppy/issues/2875
=> @uppy/transloadit: upgrade `socket.io-client` version

website/themes/uppy/source/css/_common.scss
I don't recall where I get the info from, but I remember that setting the bg-color to the root element improves the experience on mobile when the user scrolls over the top or the bottom of the document.
=> website: set background color on root element

packages/@uppy/webcam/src/index.js
Closes #3068 
Before webcam previews we only needed `opts.mirror` to know whether we needed to mirror because the image/video would be instantly added, and re-opening would reset the state. But when that feature was introduced, we needed to toggle the mirror option without re-opening, otherwise you would see the video preview and its video controls flipped. But this caused the video start function to always enable mirroring. This PR fixes that by using `opts.mirror` as the initial setting and adding `shouldMirror` to toggle mirroring.
=> Fix webcam mirror option

packages/@uppy/companion/src/server/provider/drive/index.js, packages/@uppy/provider-views/src/Browser.js, packages/@uppy/provider-views/src/ProviderView/ProviderView.js
Closes #3067 
- Sort Google Drive files and folders alphabetically.
- Remove unused client-side sorting logic.
**Questions**
- What was the client-side sorting logic used for? It isn't used anywhere.
=> Sort Google Drive list by name

website/themes/uppy/layout/index.ejs
...because #3004 was merged before https://github.com/transloadit/api2/pull/2706 has been merged (Box is broken now on uppy.io due to no support in companion)
=> Temporarily disable Box

packages/@uppy/dashboard/src/components/AddFiles.js
This mostly reverts commit 72965029f24a5edaa5cca7a2ae6e5020c9e73e2b.
Refs: https://github.com/transloadit/uppy/pull/2397
=> Revert "dashboard: mostly restore backwards compatibility for the `browse` strings

packages/@uppy/companion/src/server/logger.js, packages/@uppy/companion/test/__tests__/logger.js
When logging an object it would print `[object Object]` if `color` was set.
e.g.: google drive callback: `callback.oauth.resp [object Object]`
Now we will instead use util.inspect before calling color so it can log the object structure.
Also fix some linting warnings by reordering code. See second commit for easier to read changes
=> Companion improve logging

packages/@uppy/core/src/BasePlugin.js, packages/@uppy/core/src/UIPlugin.js, packages/@uppy/core/types/index.d.ts, packages/@uppy/dashboard/src/index.js, packages/@uppy/webcam/src/index.js, website/src/docs/writing-plugins.md
Fixes #3092 
- Create and call `onUnmount` in `UIPlugin` for plugins that require clean up
- Update webcam `stop` to clean up when already recording
- Update "Writing plugins" docs
- Move `onMount` and `onUnmount` from `BasePlugin` into `UIPlugin`
- Update types
=> Create `onUnmount` in `UIPlugin` for plugins that require clean up

packages/@uppy/core/types/index.d.ts, packages/@uppy/core/types/index.test-d.ts, packages/@uppy/dashboard/types/index.d.ts, packages/@uppy/dashboard/types/index.test-d.ts, packages/@uppy/drag-drop/types/index.d.ts, packages/@uppy/image-editor/types/index.d.ts, packages/@uppy/image-editor/types/index.test-d.ts, packages/@uppy/thumbnail-generator/types/index.d.ts, packages/@uppy/thumbnail-generator/types/index.test-d.ts, packages/@uppy/transloadit/types/index.d.ts, packages/@uppy/transloadit/types/index.test-d.ts, packages/@uppy/utils/types/index.d.ts
Closes #2922 
Utilizing declaration/interface merging, all events can be typed across all packages. ~~I'm opening this as a draft to collect feedback before I spend time finishing this off.~~
Positives: 
- Event names are autocompleted within VSCode with no hacks required
- Merging is additive for any `@uppy` package the user installs.
- Easy to add & maintain
Negatives:
- Unavoidable breaking change for people passing in a metadata structure as part of the generic, as Typescript does not support partial generic inference. I'm unsure if this is an issue, as it was only previously implemented for two events.
=> Typescript Typed events

package.json, packages/@uppy/robodog/package.json, packages/uppy/bundle.js, packages/uppy/package.json
The legacy bundle was missing `regenerator-runtime` dependency and was not defining `Uppy` global.
=> build: fix legacy bundle

packages/@uppy/aws-s3/src/MiniXHRUpload.js, packages/@uppy/utils/src/NetworkError.js
Also fixes other linter warnings in this file, and migrating `NetworkError` to use the [Error Cause stage 3 proposal](https://github.com/tc39/proposal-error-cause).
=> @uppy/aws-s3: refactor to use private fields

packages/@uppy/dashboard/src/components/FileCard/index.js, packages/@uppy/dashboard/types/index.d.ts, website/src/docs/dashboard.md
Browsers without support for the HTML `form` attribute would misbehave, making it impossible to validate the form at all, and potentially validate an unrelated upper form if users are embeding Uppy inside a a `<form>`.
FWIW this attribute is supported on all the browsers we officially support, but it's quite cheap to add a check and fallback to the old behavior if we don't detect any support.
It would be worth to backport this to Uppy 1.x, as we still support IE 11 there. There might also be another bug related to Preact 8 on that branch, as it seems the `form` attribute is not added at all to the DOM elements, so we should do some extra check before releasing a patch version.
Fixes: https://github.com/transloadit/uppy/issues/3111
=> @uppy/dashboard: fix metafield form validation

packages/@uppy/companion/package.json, packages/@uppy/companion/src/server/controllers/send-token.js, packages/@uppy/companion/src/server/helpers/utils.js, packages/@uppy/companion/test/__tests__/callback.js
=> safely escape <script> injected code

packages/@uppy/core/src/index.js, website/src/docs/dashboard.md
https://html.spec.whatwg.org/multipage/input.html#attr-input-required
> Constraint validation: If the element is required, and its value IDL attribute applies and is in the mode value, and the element is mutable, and **the element's value is the empty string**, then the element is suffering from being missing.
This is important to align the pre-upload check with the form validation done by the browser (if the browser does have support for the `form` attribute). We should backport this to Uppy v1.x.
=> @uppy/core: reject empty string as valid value for required meta fields

examples/dev/Dashboard.js, packages/@uppy/core/src/index.js, packages/@uppy/core/src/index.test.js, packages/@uppy/core/types/index.d.ts, packages/@uppy/dashboard/src/index.js, packages/@uppy/locales/src/bg_BG.js, packages/@uppy/locales/src/de_DE.js, packages/@uppy/locales/src/en_US.js, packages/@uppy/locales/src/fa_IR.js, packages/@uppy/locales/src/fr_FR.js, packages/@uppy/locales/src/nb_NO.js, packages/@uppy/locales/src/pl_PL.js, packages/@uppy/locales/src/ro_RO.js, packages/@uppy/locales/src/sk_SK.js, packages/@uppy/locales/src/th_TH.js, packages/@uppy/locales/src/zh_CN.js, packages/@uppy/locales/src/zh_TW.js, packages/@uppy/locales/template.js, packages/@uppy/robodog/src/pick.js, website/src/docs/uppy.md
- Renaming `allowMultipleUploads` to `allowMultipleUploadBatches`, keeping the old option as alias for now
- Change the “Can’t add new files: already uploading” string, because it also applies after the upload is complete
- Don’t allow drag-drop after initial upload, if `allowMultipleUploadBatches: false`
Related: https://github.com/transloadit/uppy/issues/2806, https://github.com/transloadit/uppy/issues/1575
=> Core: rename allowMultipleUploads to allowMultipleUploadBatches

packages/@uppy/react/src/CommonTypes.d.ts, packages/@uppy/react/src/Dashboard.d.ts, packages/@uppy/react/src/DashboardModal.js, packages/@uppy/react/types/index.test-d.tsx
Fixes #2972
- `OmitTarget` was incorrectly also added to `DashboardModal`, which can in fact have a `target`.
=> Fix React `DashboardModal`'s `target` type

packages/@uppy/aws-s3/src/index.js, packages/@uppy/thumbnail-generator/src/index.js, packages/@uppy/xhr-upload/src/index.js
I got an error report to know the `this.i18n` is undefined ([@uppy/aws-s3/src/MiniXHRUpload.js#L139](https://github.com/transloadit/uppy/blob/main/packages/%40uppy/aws-s3/src/MiniXHRUpload.js#L139)), use `setOptions` from [BasePlugin](https://github.com/transloadit/uppy/blob/a3aac6ba4cd1322c59b030c2779ea64038e23b4c/packages/%40uppy/core/src/BasePlugin.js#L37-L48) will fix this issue.
=> Fix `i18n` in aws-s3, thumbnail-generator, and xhr-upload

packages/@uppy/xhr-upload/types/index.d.ts
Should resolve issue #3144.
Running `npm run lint` I get lots of warnings from files I did not touch;
running `npm run test`I get warnings about 'locale has missing string', even after I run `npm run build:lib`.
Maybe this is a result of my working environment (it is a windows system).
=> Add methods to type definition for XHRUploadOptions

website/src/_posts/2016-08-0.9.0.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005169 
No. 3i, removed the link as I couldn't find a replacement. The only link I could find that seemed to be about the same thing as the original link is: https://github.com/transloadit/uppy/blob/main/website/src/docs/google-drive.md, but this is already available on the website for users to see.
=> remove google drive link

website/src/_posts/2019-04-liftoff-08.md
https://app.intercom.com/a/apps/qiqpfgjg/inbox/inbox/all/conversations/26852700005169
No. 4i, found two possible links to replace the broken link and I replaced it with this link: https://github.com/tus/tus-js-client/blob/master/lib/node/fingerprint.js, but this is the other potential link I found: https://github.com/tus/tus-js-client/blob/master/lib/browser/fingerprint.js Would you like me to put the second link in or is the one I already used fine?
=> replace fingerprint.js link

packages/@uppy/core/src/index.js, packages/@uppy/google-drive/src/index.js, packages/@uppy/locales/src/en_US.js, packages/@uppy/provider-views/src/ProviderView/AuthView.js, packages/@uppy/provider-views/src/style.scss, website/src/_posts/2016-09-0.10.md
Closes #3153 
**Before**
**After**
=> Update Google Drive for brand compliance

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
**Use case**: Encrypting AWS Multipart Parts in AWS Multipart Uploader 
**What happens**:
Each underlying blob of each chunk in the prepareUploadParts (new v2 version) is replaced with an encrypted version of itself:
```
this.uploaders[file.id].chunks[partNum] =  new Blob([new Uint8Array(ciphertext)]);
```
This works perfectly. 
**Except in the following case**:
If one is uploading thousands of files with a total of many GB, we see a ```net::ERR_OUT_OF_MEMORY``` in Chromium based Browsers during the ```xhr.send``` in ```uploadPartBytes``` method in ```packages/@uppy/aws-s3-multipart/src/MultipartUploader.js```
I guess, under some circumstances, the garbage collector is a bit behind which may create this case, where the ```xhr.send``` cannot allocate sufficient memory. By explicitly …
=> Fix `net::ERR_OUT_OF_MEMORY` in `@uppy/aws-s3-multipart`

packages/@uppy/utils/src/AbortController.js
=> fix: AbortController is not defined on Node.js (Server Side Render)

packages/@uppy/core/src/index.js, packages/@uppy/transloadit/src/index.js, packages/@uppy/transloadit/src/index.test.js, test/endtoend/transloadit2/index.html, test/endtoend/transloadit2/main.js, test/endtoend/transloadit2/test.js, test/endtoend/wdio.base.conf.js
Fixes: https://github.com/transloadit/uppy/issues/3189
=> @uppy/transloadit: fix unhandledPromiseRejection failures

packages/@uppy/locales/src/nb_NO.js
"Done" is missing for the Norwegian locale.
For "proof" that this is a correct translation, please see: [Google Translate](https://translate.google.com/?sl=en&tl=no&text=Done&op=translate).
Thanks!
=> Add 'done' to nb_NO.js

packages/@uppy/provider-views/src/SearchProviderView/SearchProviderView.js
Copied the same code changes as in the`ProviderView.js`.
This change fixes the "attempted to use private field on non-instance" error message and also fixes the `isDisabled` issue.
=> Fix "attempted to use private field on non-instance"

.eslintrc.js, BACKLOG.md, packages/@uppy/dashboard/src/style.scss, packages/@uppy/status-bar/src/Components.js, packages/@uppy/status-bar/src/StatusBar.js, packages/@uppy/status-bar/src/calculateProcessingProgress.js, packages/@uppy/status-bar/src/index.js, packages/@uppy/status-bar/src/style.scss
Fixes #766
- **Allow hoisted functions in `.eslintrc`**
I'm strongly in favor of using `use-before-define`, but ignoring it for functions. Hoisting is a feature which can be used to write more intention revealing code.
- **Refactor status bar plugin and resolve all eslint warnings**
I took small steps with commits in between to greatly simplify the code and make it more obvious what is happening. See `StatusBar` [before](https://github.com/transloadit/uppy/blob/4b7a2cc67e9c5af691f8e2fe3f5b2d0523939feb/packages/@uppy/status-bar/src/StatusBar.js) and [after](https://github.com/transloadit/uppy/blob/4ef070f580bee4e71cb3a39b11f1732b3354b5a0/packages/@uppy/status-bar/src/StatusBar.js).
- **Show all details on mobile when `showProgressDetails` is `true`**
See this …
=> Show all details on mobile when `showProgressDetails` is `true`

BACKLOG.md, packages/@uppy/image-editor/src/Editor.js
A silly hack that we can get rid of when moving to ESM.
Fixes: https://github.com/transloadit/uppy/issues/3199
=> @uppy/image-editor: add workaround for when `Cropper` is loaded as ESM

packages/@uppy/tus/src/index.js, website/src/docs/tus.md
To close #3217 I added the possibility that opts `headers` argument support that could be a function
=> Adding support to define the headers as a function in the Tus protocol plugin

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/test/__tests__/uploader.js, website/src/docs/companion.md
- warn on startup if uploadUrls is not specified as not specifying it is a security risk
- improve docs to make it more clear why uploadUrls should be specified (say that uploadUrls is required even though it is not, due to backward compatibility)
- no longer require_tld (it gives a false security and causes problems when wanting to use localhost) - fixes #2831
=> Make uploadUrls recommended

examples/custom-provider/server/index.js, examples/uppy-with-companion/server/index.js, packages/@uppy/companion/src/server/middlewares.js, packages/@uppy/companion/src/standalone/index.js, packages/@uppy/companion/test/__tests__/cors.js, website/src/docs/aws-s3-multipart.md, website/src/docs/aws-s3.md
Add the following headers to `access-control-allow-headers` by default:
- Authorization
- Origin
- Content-Type
- Accept
I believe they are always needed for basic operation of companion, and if the developers forget to add them I believe they will get cryptic errors. See #3021
Let me know if anyone knows any reason why these headers cannot be default added.
Also:
- Remove custom middlewares `setHeader` in examples and standalone
- Update outdated readme for S3: AWS now requires JSON instead of XML format
- refactor cors middleware to avoid duplicates
If this PR can not be merged, we need to update all example code to include the custom `setHeader` middleware.
=> Default allow headers

packages/@uppy/companion/src/server/provider/error.js
Makes it easier to debug when we can see it in the log files
e.g.:
```
companion: 2021-09-20T20:03:53.226Z [error] provider.onedrive.list.error ProviderApiError: Access Denied
companion: 2021-09-20T19:57:49.897Z [error] provider.onedrive.list.error ProviderApiError: Item does not exist
```
We don't know what is the error code here...
=> Include status code in HTTP error message

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.test.js, website/src/docs/aws-s3-multipart.md
Fixes #3190
**Questions**
The current retry implementation only retries under these conditions:
https://github.com/transloadit/uppy/blob/a298e59f17d6a1aba7786fe8c60df73242104940/packages/%40uppy/aws-s3-multipart/src/MultipartUploader.js#L216-L223
This means the implementer _must_ return something like this when their custom `prepareUploadParts` fails: 
```js
Promise.reject({ source: { status: 500 } })
```
Do we want to have the same logic for retrying `prepareUploadParts`? Something else? Either way it would need to be documented.
=> Retry `prepareUploadParts` on fail for `@uppy/aws-s3-multipart`

packages/@uppy/drop-target/src/index.js, packages/@uppy/drop-target/types/index.d.ts, packages/@uppy/drop-target/types/index.test-d.ts, website/src/docs/drop-target.md
Supersedes #2973
Alternative approach to make the solution more generic and aligned with previous solutions.
- Expose events
- Update types
- Update docs
---
The problem @tobiasps posed could now be solved like so (in combination with [`uppy.setFileMeta`](https://uppy.io/docs/uppy/#uppy-setFileMeta-fileID-data))
```js
.use(DropTarget, {
// ...
onDrop: (event) => {
const { files } = uppyInstance.getState()
// do something with `event` and `files`
}),
})
```
=> Expose `@uppy/drop-target` events

packages/@uppy/transloadit/src/AssemblyOptions.js, test/endtoend/transloadit2/main.js
Co-authored-by: Merlijn Vos <Murderlon@users.noreply.github.com>
Fixes: https://github.com/transloadit/uppy/issues/3189
=> @uppy/transloadit: pass fields to transloadit

packages/@uppy/store-redux/README.md, website/src/docs/redux.md, website/src/docs/stores.md
Fixes #3173 
- Improve code snippets in docs to avoid confusion.
=> Improve docs on redux store integration

packages/@uppy/core/types/index.d.ts
I found the second parameter of `uppy.removeFile()` missing in the type definitions.
=> chore: Add `FileRemoveReason` type

packages/@uppy/screen-capture/README.md, website/src/docs/screen-capture.md
Closes #3279
Locale will be automatically added by #3276 once it's merged and ran.
=> Create docs for `@uppy/screen-capture`

packages/@uppy/provider-views/src/Browser.js
I think it broke here: https://github.com/transloadit/uppy/pull/3196/files#diff-07601b1fb93ec00e2790e18a70cdc9025a2e722d971a092148f29f312322ab63L56
=> Fix provider-views restrictions checkboxes

packages/@uppy/companion/Dockerfile, packages/@uppy/companion/Dockerfile.test, packages/@uppy/companion/docker-compose-dev.yml, packages/@uppy/companion/docker-compose-test.yml, packages/@uppy/companion/docker-compose.yml
2nd attempt, to (hopefully) fix https://github.com/transloadit/uppy/pull/3289#issuecomment-957574896.
=> @uppy/companion: fix Dockerfiles

packages/@uppy/utils/types/index.d.ts
=> fix: @uppy/utils - `getFileType()` always returns a string

packages/@uppy/core/src/Uppy.js, packages/@uppy/core/src/__snapshots__/Uppy.test.js.snap, packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.js, packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.scss, packages/@uppy/dashboard/src/components/FileItem/FilePreviewAndLink/index.js, packages/@uppy/dashboard/src/components/FileItem/MetaErrorMessage.js, packages/@uppy/dashboard/src/components/FileItem/index.js, packages/@uppy/dashboard/src/index.js, packages/@uppy/locales/src/en_US.js
Better UI for https://github.com/transloadit/uppy/pull/2896
Added `uppy.#checkRequiredMetaFieldsOnFile` to check if the error has been fixed after a single file was edited and update the UI.
Mockups from @nqst:
=> Required meta fields UI

packages/@uppy/webcam/types/index.d.ts
=> Add `showRecordingLength` to `@uppy/webcam` types

packages/@uppy/core/src/Uppy.js
This goes with: https://github.com/transloadit/uppy/issues/3296
Transpiling Uppy 2 to ES5 results in errors due to the lack of polyfill support for the spread operator in ES5. Converting Sets to arrays prior to spreading fixes this and allows for Uppy 2 to be used in ES5 browsers.
=> Convert sets to arrays prior to using spread operator to enable transpilation to ES5

examples/aws-companion/server.js, examples/uppy-with-companion/server/index.js, packages/@uppy/companion/README.md, website/src/_posts/2020-03-custom-providers.md, website/src/docs/companion.md
It was never an option. See #3306
=> Remove references of incorrect `options` argument for `companion.socket`

packages/@uppy/image-editor/src/Editor.js, packages/@uppy/image-editor/src/index.js
`croppedCanvasOptions` were not being passed to `getCroppedCanvas` when getting the image blob.
I noticed that the options are being passed when called from here though:
https://github.com/transloadit/uppy/blob/main/packages/%40uppy/image-editor/src/Editor.js#L41
But when debugging the issue I couldn't see when that `save` function gets called in the preact component, is it dead code? If someone can confirm this I am happy to delete that function in this PR too.
=> Pass croppedCanvasOptions to getCroppedCanvas

website/src/docs/dashboard.md
`disableLocalFiles` is an option that is detailed below, but is easily missed as is not included in the 'content's section at the top of the documentation. This section is useful for quickly scanning for an option you're looking for.
=> Add disableLocalFiles to options summary

bin/build-bundle.js, packages/@uppy/core/src/Uppy.js
Reverts transloadit/uppy#3297
Fixes https://github.com/transloadit/uppy/issues/3328
=> Revert "Convert sets to arrays prior to using spread operator to enable transpilation to ES5"

bin/update-yarn.sh, packages/@uppy/companion/package.json
When running from the Dockerfile, Corepack cannot pick up the information from the parent package.json and tries to run with an older version of Yarn.
This PR adds the Yarn version info to the Companion `package.json`, which should hopefully fix the issue.
=> @uppy/companion: fix deploy Yarn version

babel.config.js, package.json, yarn.lock
Optional chaining is still not supported on all environments – even though it's supported by browsers Uppy actually supports. Adding the plugin explicitly, it can be removed in a future semver-major.
=> build: force use of `@babel/plugin-proposal-optional-chaining`

website/src/docs/aws-s3.md, website/src/docs/core.md, website/src/docs/screen-capture.md, website/src/docs/status-bar.md, website/src/docs/webcam.md
This also updates files that were out of sync with the build process.
=> @uppy/webcam: fix broken links in `webcam.md`

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
this.lockedCandidatesForBatch code in #uploadParts definitely is the cause of the bug with unresumable uploads after pause (#3341).
Not sure if this.lockedCandidatesForBatch is at all necessary, so proposing to drop it.
=> Drop lockedCandidatesForBatch and mark chunks as 'busy' on preparing as a fix for #3341

packages/@uppy/dashboard/src/components/FileCard/index.js
Closes #2754
If you edit a file, change a meta field such as caption, then click edit file and click save or cancel — your meta field change is discarded. This saves your changes when opening the image editor.
=> Save meta fields when opening the image editor

bin/update-yarn.sh, packages/@uppy/companion/Dockerfile, packages/@uppy/companion/package.json
The Dockerfile tries to build Companion standalone using some
trickery that is very much tied to npm logic, Yarn is not the fittest
tool here.
=> @uppy/companion: don't pin Yarn version in `package.json`

.eslintrc.js, bin/update-contributors.mjs
Needed for https://github.com/transloadit/uppy/pull/3363.
=> meta: enable linter on mjs scripts

.yarn/patches/babel-plugin-transform-commonjs-npm-1.1.6-0007fa2809, babel.config.js, examples/dev/Dashboard.js, examples/dev/DragDrop.js, examples/dev/index.html, examples/dev/index.js, examples/dev/package.json, examples/dev/vite.config.js, package.json, yarn.lock
It's a bit hacky, but it works :)
We should be getting even more performance when we switch to ESM and
stop using JSX in `.js` files.
Next step would be to migrate the website to Vite (EDIT: probably not, the website is using Hexo there's no reason to move away from it), and the bundle to ESBuild.
=> meta: use Vite for examples/dev

.eslintrc.js, packages/uppy/index.mjs, private/locale-pack/helpers.mjs, private/locale-pack/index.mjs, private/locale-pack/test.mjs
Turns out `.mjs` files were not covered by the linter. This PR aims to fix that.
=> meta: update linter config to parse ESM files

packages/@uppy/companion/package.json, yarn.lock
=> Upgrade ws in companion

packages/@uppy/angular/.npmignore, packages/@uppy/companion/.npmignore, packages/@uppy/svelte/.npmignore, packages/@uppy/vue/.npmignore, packages/uppy/.npmignore
This issue was probably introduced when we switched to Yarn, I suppose Lerna was not following the same rules as npm and Yarn.
See: https://www.npmjs.com/package/npm-packlist
Fixes: https://github.com/transloadit/uppy/issues/3360
Fixes: https://github.com/transloadit/uppy/issues/3378
=> add `.npmignore` files to ignore .gitignore when packing

website/src/_posts/2021-12-2.1-2.3.md
The `lint-markdown` job is failing on `main`, this PR fixes it. It also fix `NPM` -> `npm`.
=> website: update december 2021 blog post

packages/@uppy/companion/package.json, packages/@uppy/companion/src/server/helpers/request.js, yarn.lock
https://huntr.dev/bounties/c1c03ef6-3f18-4976-a9ad-08c251279122/
tested with:
- `http://[::FFFF:127.0.0.1]:8080/`
- `http://[::ffff:7f00:1]:8080/`
=> improve private ip check

packages/@uppy/transloadit/src/Assembly.js
Fixes: https://github.com/transloadit/uppy/issues/3156
=> @uppy/transloadit: ignore rate limiting errors when polling

babel.config.js
Fixes #3421 
It's interesting that this needs to be explicitly included, just like nullish coalescing, in order for it to work.
=> Force include babel numeric separator

package.json, yarn.lock
In https://github.com/transloadit/uppy/pull/3363, the `"resolutions"` field in `package.json` was mistakenly altered, which broke `yarn dev`.
=> dev: fix Vite custom plugin

packages/@uppy/dashboard/src/index.js
After https://github.com/transloadit/uppy/pull/3017 automatic focus (superfocus) got broken, because it checks if Informer message is currently present on screen, and screenreader might be reading it, and we don’t want to break it off.
=> Fix superfocus

packages/@uppy/companion/src/server/helpers/request.js, packages/@uppy/companion/src/standalone/helper.js, website/src/docs/companion.md
At present, the URL loading component of the Companion makes two GET requests to the target URL. The first is only used to gather meta information (the files Content-Length and Content-Type), and then is aborted. The second downloads the file. Of course, depending on how much of the body has already been sent, and how well the delivering server understands aborts, this may result in a significant amount of unnecessary body data also being sent in that first meta request.
HTTP has a way to gather meta information about a file, the HEAD HTTP method. It is specified that a response from HEAD should include the Content-Length that will be returned from a GET request, making this a suitable option assuming the server in question implements HEAD correctly.
This change optimistically attempts a …
=> Default to HEAD requests when the Companion looks to get meta information about a URL

.yarn/patches/exifr-npm-7.1.3-e3f1c7a57d, package.json, packages/@uppy/thumbnail-generator/package.json, packages/@uppy/thumbnail-generator/src/index.js, yarn.lock
We are patching the `mini.umd.js` because Vite (or ESBuild?) doesn't seem to support UMD files. We also used this opportunity to remove a bunch of stuff we are not using from Exifr. When switching to ESM, we could get rid of the patch file and directly import the necessary parts from Exifr.
To re-generate the file, clone Exifr repo, change line 230 of `rollup.config.js` to select `"cjs"` instead of `"umd"` and update `src/bundles/mini.mjs` to match the version in the patch.
=> @uppy/thumbnail-generator: exifr: remove legacy IE support

packages/@uppy/companion/src/server/helpers/utils.js
This can happen for example when `encrypted` has less than 32 bytes
of hex content.
Without this patch, a `TypeError` is thrown, which is unexpected and set off
monitoring.
=> Fix TypeError when invalid initialization vector

packages/@uppy/companion/src/server/controllers/thumbnail.js, packages/@uppy/companion/src/server/provider/box/index.js, packages/@uppy/companion/src/server/provider/dropbox/index.js
those are the only two providers who use companion-proxied thumbnails
dropbox had been broken after #3159
box did never work before because it just showed a placeholder (see box api)
also upgraded dropbox thumbnail api to v2
and rewrite to async/await
=> fix broken thumbnails for box and dropbox

packages/@uppy/companion-client/src/Provider.js, packages/@uppy/companion/package.json, packages/@uppy/companion/src/server/provider/credentials.js, packages/@uppy/provider-views/src/ProviderView/ProviderView.js, packages/@uppy/robodog/src/addProviders.js, private/dev/Dashboard.js, website/src/docs/robodog-dashboard.md, website/src/docs/robodog-picker.md, website/src/docs/transloadit.md, yarn.lock
This PR will contain the final bits we need to start using Companion's dynamic oauth feature on transloadit.com. May add a few more things here as I work on the transloadit.com side…
So far this:
- fails loudly if requested third-party credentials do not exist, instead of silently falling back to the preconfigured one. There was no way for developers to see what went wrong before
- adds options to Robodog so you don't have to remember how `companionKeysParams` works and don't have to duplicate your transloadit API key. Now you can do:
```js
robodog.dashboard({
params: {
auth: { key: 'your transloadit api key' }
},
providers: ['instagram'],
instagram: {
credentialsName: 'your instagram credentials name on transloadit.com'
}
})
```
To do:
- when requested third-party credentials can't be …
=> Finishing touches on Companion dynamic Oauth

.eslintrc.js, bin/build-lib.js, package.json, private/dev/vite.config.js, yarn.lock
This PR adds support for ESM in `.js` and `.jsx` files.
And don't try to `mkdir` the lib folder if we already know it exists.
=> meta: add support for ESM sources in build script

website/src/docs/aws-s3-multipart.md
Missing comma and wrong attribute name on cors example config
=> Missing comma and wrong attribute name on cors example config

.env.example, .github/CONTRIBUTING.md, .gitignore, bin/companion.sh, package.json, private/dev/Dashboard.js, private/dev/DragDrop.js, website/src/_template/contributing.md, yarn.lock
Fixes: https://github.com/transloadit/uppy/issues/3473
Refs: https://github.com/transloadit/uppy/pull/3478#discussion_r809073905
=> meta: use a single `.env` file for config

.eslintignore, bin/build-bundle.mjs, packages/@uppy/robodog/bundle-legacy.js, packages/@uppy/robodog/bundle.js, packages/uppy/bundle-legacy.js, packages/uppy/bundle.js
Make `Uppy` available on the global scope when loaded from the CDN bundle.
=> meta: fix CDN bundle

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.test.js, packages/@uppy/aws-s3-multipart/types/index.d.ts, packages/@uppy/aws-s3-multipart/types/index.test-d.ts, website/src/docs/aws-s3-multipart.md
This updates the part data passed to prepareUploadParts to also include an object of chunk data. Every part number passed should have a key in the object, with the value being it's associated chunk.
I added some tests for validation, but it mostly just tests that the chunks are indexed correctly in the object. It would be nice to actually validate that it's passing the proper chunk data as well, but I couldn't figure out how to do something like that with the mocked Blob objects.
This is intended to fix https://github.com/transloadit/uppy/issues/3391
=> Add chunks back to prepareUploadParts, indexed by partNumber

.github/workflows/ci.yml, .github/workflows/companion.yml, .github/workflows/end-to-end.yml, .github/workflows/manual-cdn.yml, .github/workflows/release-candidate.yml, .github/workflows/release.yml, .github/workflows/website.yml
I can see that the "install dependencies" (yarn) step on our github actions is taking the majority of the time.
I believe that our caching logic is not valid, and that this may be the reason why.
I believe it should be like this: https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
However the [setup-node](https://github.com/actions/setup-node) action also uses the cache action and hopefully will handle this correctly when specifying "yarn".
=> meta: Fix yarn caching in github actions

packages/@uppy/companion/src/server/Uploader.js
Giving a clear separation between client-provided info and server
provided ones.
=> @uppy/companion: reorder reqToOptions

packages/@uppy/companion/package.json, yarn.lock
=> upgrade node-redis-pubsub

packages/@uppy/companion/src/server/provider/drive/index.js
Fixes https://github.com/transloadit/uppy/issues/3387
`orderBy: 'folder,name'` sorts the files returned from https://www.googleapis.com/drive/v3/files with folders first and then sorts by name. This should prevent the insertion of folders to the top of the results when scrolling/paginating like see in #3387
=> Order Google Drive results by folder to show all folders first

bin/build-lib.js
Rewrite all `export … from …` to `module.exports = require(…)` when transpiling ESM to CJS, and `export default …` to `module.exports = …`  when transpiling ESM to CJS.
We were relying on `@babel/plugin-transform-modules-commonjs` plugin, which adds a `default` property to `module.exports` instead re-assign it. E.g, for `export {default} from './Audio.jsx', it would transpile to
```js
Object.defineProperty(exports, "__esModule", {
value: true
});
Object.defineProperty(exports, "default", {
enumerable: true,
get: function () {
return _Audio.default;
}
});
var _Audio = require("./Audio.jsx");
```
when we want
```js
module.exports = require('./Audio.js')
```
This should fix the deploy GHA (https://github.com/transloadit/uppy/runs/5491775612?check_suite_focus=true).
=> meta: fix support of export declaration in source files

bin/build-lib.js, e2e/clients/dashboard-compressor/index.html, e2e/clients/index.html, yarn.lock
- Upgrade Parcel and Cypress to latest versions (not actually related to the CI failure, but nice to have imo)
- Fix output of ESM packages: the failure comes from the fact the transpile step was treating default import as `require('…').default`. It should have been caught by the e2e GHA then, but that's another issue that https://github.com/transloadit/uppy/pull/3561 is trying to address.
=> meta: fix e2e

packages/@uppy/companion/src/server/provider/drive/index.js
Fixes #3539 
By default Google only returns 10 shared drives in `fetchSharedDrives`. I have more than that so some of mine were missing from the file picker.
On `main`, 10 shared drives are loaded before my folders and files.
Two changes in this PR
The first and smallest one was to increase the `pageSize` for listing shared drives to the maximum of 100. This is probably good enough for most use-cases (and would be for mine).
The second was to check the response to `fetchSharedDrives` and see if a `nextPageToken` was returned and to continue fetching shared drives until no page token is returned. This is different from how the file pagination works, but I couldn't figure out how to keep track of two cursors (one for the shared drives and one for the files) for subsequent pagination …
=> @uppy/companion - Fetch all Google Drive shared drives

packages/@uppy/companion/src/server/logger.js, packages/@uppy/companion/src/server/middlewares.js, packages/@uppy/companion/src/standalone/index.js, packages/@uppy/companion/test/__tests__/logger.js
but don't do it for common error types that we ourselves produce
I implemented this as a middle ground. not logging stack traces for ProviderApiError and ProviderAuthError because those are part of the normal flow and not really bugs from us.
fixes #3495
=> always log errors with stack trace

packages/@uppy/robodog/bundle.js
It's still unclear to how it was working before that – I couldn't find where the global variable used to be assigned and when that was removed. Anyway, the fix is quite straight-forward, we should release a new version with the fix soon.
Fixes: https://github.com/transloadit/uppy/issues/3582
=> @uppy/robodog: fix CDN bundle

packages/@uppy/companion/src/config/companion.js, packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/src/server/controllers/s3.js, packages/@uppy/companion/src/standalone/helper.js
not all people use buckets with ACL
until next major you can use COMPANION_AWS_DISABLE_ACL=true
to disable setting of ACL in s3 (because the default is currently `public-read`)
I thinkwe should set default to no acl in the next major.
fixes #3570
=> Allow not setting ACL when uploading to S3

packages/@uppy/webcam/types/index.d.ts
I found these options in docs and in code, but not in types
=> preferredVideoMimeType and preferredVideoMimeType in WebcamOptions interface

packages/@uppy/companion/package.json, yarn.lock
Previously it would throw `command not found: jest` error
when running `yarn workspace @uppy/companion test`.
=> @uppy/companion: fix `yarn test` command

e2e/cypress/integration/dashboard-tus.spec.ts, packages/@uppy/tus/src/index.js, packages/@uppy/utils/src/RateLimitedQueue.js, yarn.lock
Fixes: https://github.com/transloadit/uppy/issues/3594
//cc @Acconut
=> @uppy/tus: fix double requests sent when rate limiting

e2e/cypress/integration/dashboard-transloadit.spec.ts, e2e/tsconfig.json, packages/@uppy/status-bar/src/Components.js, packages/@uppy/transloadit/src/Assembly.js, packages/@uppy/transloadit/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/3156
=> @uppy/transloadit: close assembly if upload is cancelled

packages/@uppy/core/src/Restricter.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

.github/workflows/ci.yml, .github/workflows/companion-deploy.yml, .github/workflows/companion.yml, .github/workflows/e2e.yml, .github/workflows/manual-cdn.yml, .github/workflows/release-candidate.yml, .github/workflows/release.yml, .github/workflows/website.yml
and use the more general `lts/*` version descrption for Node.js installs
=> meta: upgrade GHA actions

e2e/clients/dashboard-compressor/app.js, e2e/cypress/integration/dashboard-compressor.spec.ts, packages/@uppy/compressor/src/index.js
When using the mimeType option of compressorJS to set a specific output format, although compressorJS converts the image successfully, the file keeps it's original filename with the original extension, plus the original type.
This solution seemed simple enough, I tested it in my local machine and now all images get a `originalfilename.webp` name and a `image/webp` extension when initializing the plugin with the `mimeType: 'image/webp'` option
=> Merge new name and type into compressed file

packages/@uppy/core/src/Uppy.js
This would deserve a test, but it would be nice to land it sooner rather than later.
=> @uppy/core: fix TypeError in event handler when file was removed

packages/@uppy/aws-s3-multipart/types/index.d.ts
This tiny PR adds companionCookiesRule parameter in AWS S3 Multipart plugin which was missing. 
Related issue: https://github.com/transloadit/uppy/issues/3619
=> Add `companionCookiesRule` type to @uppy/aws-s3-multipart

packages/@uppy/utils/src/getFileType.test.js, packages/@uppy/utils/src/mimeTypes.js
Fixes #3439
Begs the question again whether we should just use a library for mime types because I'm sure this is not the last time this is happening. Unfortunately adding one would be around 20KB, I'm not sure how much our file is but probably way less. It's a tradeoff.
=> Fix `getFileType` for dicom images

packages/@uppy/transloadit/src/Client.js
Returning a non-2xx code is not a `NetworkError`, it's a rejection from the server and we should handle it as such.
=> @uppy/transloadit: improve fetch error handling

packages/@uppy/compressor/src/index.js
In my last PR I updated the file itself's filename and extension. However, there was also a meta field, which is used for example by the AWS XHR plugin, which kept the old filename and mime-type.
This PR now updates that meta field also, and makes the code a bit cleaner
=> Set meta on file compression

packages/@uppy/core/src/Uppy.js
Should have been done as part of #3629
=> @uppy/core: fix `TypeError` when file was removed

packages/@uppy/vue/package.json
The readme states that `@uppy/vue` uses the MIT license, but this information is missing in the `package.json`.
=> Add license field to package.json in @uppy/vue

packages/@uppy/dashboard/src/components/EditorPanel.js, packages/@uppy/locales/src/es_ES.js
Add missing `save` translation to Spanish locale.
=> Add `save` translation to Spanish locale

.eslintrc.js, packages/@uppy/companion-client/package.json, packages/@uppy/companion-client/src/AuthError.js, packages/@uppy/companion-client/src/Provider.js, packages/@uppy/companion-client/src/RequestClient.js, packages/@uppy/companion-client/src/RequestClient.test.js, packages/@uppy/companion-client/src/SearchProvider.js, packages/@uppy/companion-client/src/Socket.js, packages/@uppy/companion-client/src/Socket.test.js, packages/@uppy/companion-client/src/index.js, packages/@uppy/companion-client/src/tokenStorage.js, yarn.lock
Reverts transloadit/uppy#3693
This breaks the dev env because `@uppy/tus` has not been converted to ESM.
=> Revert "@uppy/companion-client: refactor to ESM"

packages/@uppy/tus/src/getFingerprint.js, packages/@uppy/tus/src/index.js
Doesn't have any effect on the CJS-transpilled version (the one that we ship via npm), only for the dev env.
=> @uppy/tus: fix broken import

packages/@uppy/tus/src/index.js
Fixes: https://github.com/transloadit/uppy/issues/3710
=> @uppy/tus: wait for user promise on beforeRequest

bin/update-contributors.mjs, private/locale-pack/test.mjs, private/release/updateChangelogs.js
Let's not use Node.js-specific globals in our ESM code.
=> meta: prepare internal script files for lint rule hardening

packages/@uppy/audio/package.json, packages/@uppy/audio/src/formatSeconds.test.js, packages/@uppy/audio/src/supportsMediaRecorder.test.js, packages/@uppy/aws-s3-multipart/src/index.test.js, packages/@uppy/aws-s3/package.json, packages/@uppy/aws-s3/src/index.test.js, packages/@uppy/aws-s3/src/isXml.test.js, packages/@uppy/companion-client/src/Socket.test.js, packages/@uppy/dashboard/src/index.test.js, packages/@uppy/store-default/package.json, packages/@uppy/store-default/src/index.test.js, packages/@uppy/thumbnail-generator/src/index.test.js, packages/@uppy/transloadit/src/Assembly.js, packages/@uppy/transloadit/src/AssemblyOptions.test.js, packages/@uppy/webcam/package.json, packages/@uppy/webcam/src/Webcam.test.js, packages/@uppy/webcam/src/formatSeconds.test.js, packages/@uppy/webcam/src/supportsMediaRecorder.test.js, packages/@uppy/xhr-upload/src/index.test.js, yarn.lock
Jest globals are not available if we drop Babel, and dropping Babel for our tests is a requirement for mocking ES modules.
=> meta: prepare test files for lint rule hardening

bin/build-lib.js
To test some private class fields, the source code may contain `Symbol`-defined methods. Those are intended for testing purposes only, there's no need to include them in the dist files.
=> meta: removes test functions from the dist files

packages/@uppy/dashboard/src/Dashboard.jsx
Chrome doesn't seem to provide a valid "relativePath" property for files that get passed from a HTMLInputElement.webkitdirectory.
I'm actually not sure if the "file.relativePath" test is necessary at all here?
fixes #3765
=> @uppy/dashboard: use webkitRelativePath when querying a file's relative path

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/src/server/redis.js, packages/@uppy/companion/src/standalone/index.js
https://github.com/transloadit/uppy/commit/bb178edb2e8afff80bf1ecff586c987c596f3364
to prevent buildup in redis
fixes #3748
also refactor/reuse code
=> expire redis keys after 1 day

.github/workflows/ci.yml, package.json
Removing v14.x in the `package.json` as we don't want to maintain that version for developing Uppy, but keep it in the CI to catch potential fixable errors.
=> meta: do not test on EOL versions of Node.js

__mocks__/nanoid/non-secure.js, bin/build-lib.js, packages/@uppy/core/src/Uppy.test.js
This commit removes all the hacks that needed to happen in order to ship working CJS code. Onwards, we plan to distribute Uppy packages as ESM.
=> meta: disable ESM to CJS transform in dist files

packages/@uppy/transloadit/src/index.js
Clients are expected to use `error.assembly` to inspect details about
failed Assemblies, but then we do need to always give that property
back.
I think we should have a test for this but not sure how to approach it,
since it depends on responses from the Transloadit API. I guess we'd
require a new e2e test for it?
=> transloadit: propagate error details when creating Assembly fails

packages/@uppy/url/src/Url.jsx
Need to strip query string from URL when turning into a filename.
=> improve Uppy Url's url->filename

packages/@uppy/url/src/Url.jsx, packages/@uppy/url/types/index.d.ts
Uppy Url is great! Thank you. For my use case, I need to be able to pass thru some meta data with the File, in addition to the URL.  Harmless to make it optional, but very useful to have it.  Without it, I had to copy/paste the code in addFile to add it externally, since there's no intermediate opportunity to add data before uppy.addFile gets called.
=> enable passing optional meta data to Uppy URL plugin's addFile API

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3-multipart/src/index.test.js, packages/@uppy/aws-s3/src/index.js, packages/@uppy/aws-s3/src/index.test.js, packages/@uppy/companion-client/src/RequestClient.js
Closes #2465
I'd like to be able to update the `companionHeaders` object before uploading files so the JWT token can be refreshed if needed.
Let me know your thoughts or if there's a better approach. Thanks
=> (aws-s3-multipart) Allow companionHeaders to be modified before uploading files

packages/@uppy/core/types/index.d.ts, packages/@uppy/core/types/index.test-d.ts, packages/@uppy/dashboard/types/index.d.ts, packages/@uppy/dashboard/types/index.test-d.ts
Refs: https://github.com/transloadit/uppy/pull/3811
=> @uppy/core,@uppy/dashboard: fix types for some events

packages/@uppy/xhr-upload/src/index.js
This resolves an issue when mocking XHR uploads using [MSW](https://mswjs.io/).
=> @uppy/xhr-upload: replace `ev.target.status` with `xhr.status`

packages/@uppy/react/src/useUppy.js
With new version of React [added additional check to `React.StrictMode`](https://reactjs.org/docs/strict-mode.html#:~:text=To%20help%20surface%20these%20issues,state%20on%20the%20second%20mount.).
Beacuse of this uploader plugin is not set - `No uploader type plugins are used` warning is reported.
=> Reset Uppy instance when React component is unmounted

packages/@uppy/transloadit/src/index.js
This was broken during the ESM transition.
Refs: https://github.com/transloadit/uppy/pull/3725
=> @uppy/transloadit: fix `COMPANION_PATTERN` export

.github/workflows/release.yml, private/release/autoFixConflicts.js, private/release/choose-semverness.js, private/release/commit-and-open-pr.js, private/release/config.js, private/release/getUpToDateRefsFromGitHub.js, private/release/interactive.js
We would first need to release a new version of 2.x to make sure everything's working as expected.
This PR fixes the bugs we add when releasing 3.0.0-beta, and also add a merge step to the release script so `3.x` branch stays up-to-date with `main`.
I'm using `fetch` to get the latest version of the beta branch as that's not an info the GitHub API can give us, which means we need to use Node.js 18.x for running the release on the beta branch (or the `NODE_OPTIONS=--experimental-fetch yarn release` on Node.js 16.x).
=> meta: fix release process for beta branch

packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/test/__tests__/companion.js, packages/@uppy/companion/test/__tests__/uploader.js
- `protocol` sent from Uppy in any `get` request is now **required** (previously it would default to Multipart).
=> do not use a default upload protocol

packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/test/__tests__/uploader.js
=> Companion: make `emitSuccess` and `emitError` private

packages/@uppy/companion/src/server/Uploader.js
see #3511
- `chunkSize` option will now be used as `partSize` in AWS multipart - previously only **valid** values would be respected. Invalid values would be ignored. Now any value will be passed on to the AWS SDK, possibly throwing an error on invalid values.
=> remove chunkSize backwards compatibility

packages/@uppy/companion/src/server/middlewares.js
- No longer supporting Node.js v12 and older
=> Companion: minor code tweaks for node >=14

examples/aws-companion/server.js, examples/digitalocean-spaces/server.js, examples/uppy-with-companion/server/index.js, packages/@uppy/companion/README.md, packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/standalone/index.js, website/src/docs/companion.md
with { app, emitter }
gives more flexibility in the future
- `companion.app()` function now returns an object `{ app, emitter }` where `app` is the object that was returned in previous versions
=> rewrite companion.app() to return an object

packages/@uppy/companion/src/config/companion.js, packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/src/standalone/helper.js, website/src/docs/companion.md
- Default to no ACL for S3 uploads (previous default was `public-read` but AWS now discourages ACLs).
- Remove environment variable `COMPANION_AWS_DISABLE_ACL`, will instead only use `COMPANION_AWS_ACL`
=> Companion 3 default to no s3 acl

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/config/companion.js, packages/@uppy/companion/src/standalone/helper.js, packages/@uppy/companion/src/standalone/index.js, packages/@uppy/companion/test/__tests__/subpath.js
- `/metrics` endpoint will now always lie under `options.server.path`
=> remove deprecated duplicated metrics

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/standalone/helper.js
[add warning about default getKey](https://github.com/transloadit/uppy/commit/94f19a6d3a4d57191656ec5302a0b5ee8f65ae72)
[add env variable to get a safer getKey default](https://github.com/transloadit/uppy/commit/9626a87f85aae0bfade6266f44b35af82f5716b7) 
COMPANION_S3_GETKEY_SAFE_BEHAVIOR
=> Getkey safe behavior

.github/CONTRIBUTING.md, website/src/docs/companion.md
=> de-dupe companion dev docs

packages/@uppy/dashboard/src/components/FileCard/index.jsx, packages/@uppy/image-editor/src/ImageEditor.jsx, packages/@uppy/image-editor/types/index.d.ts, packages/@uppy/image-editor/types/index.test-d.ts, website/src/docs/image-editor.md
This PR adds a `cancel` event to the `@uppy/image-editor` package. This should close #3846.
Do let me know if I missed anything or if any further changes are required.
Thank you!
=> @uppy/image-editor: Add image editor cancel event

packages/@uppy/aws-s3/package.json, packages/@uppy/core/package.json, packages/@uppy/dashboard/package.json, packages/@uppy/store-redux/package.json, packages/@uppy/xhr-upload/package.json, yarn.lock
`nanoid` recently released a new ESM-only version.
Refs: https://github.com/ai/nanoid/blob/main/CHANGELOG.md
=> upgrade `nanoid` to v4

package.json, packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.test.js, packages/@uppy/aws-s3-multipart/types/index.d.ts, packages/@uppy/aws-s3-multipart/types/index.test-d.ts, website/inject.js, website/src/docs/aws-s3-multipart.md
Closes #3881
Unfortunately, my [proposal](https://github.com/transloadit/uppy/issues/3881#issuecomment-1183023392) didn't work because 1) the default Companion implementation needs to match the custom provided one and 2) it was naive of me to think you always want to do it on the client. If you want to get your presigned URLs from your own server, you can't send back `new Request` as JSON. It's then superfluous to come up with your own response, to then manually turn those into `Request`'s on the client (might as well use the response directly).
New approach:
- Make `headers` part indexed too, like `presignedUrls`. It's not pretty but it works.
- Add a test for it. 
- Update docs.
- Update types.
Optional todos:
- Should [`listParts`](https://uppy.io/docs/aws-s3-multipart/#listParts-file-u …
=> aws-s3-multipart: make `headers` part indexed too in `prepareUploadParts`

e2e/clients/dashboard-ui/app.js, e2e/cypress/integration/dashboard-ui.spec.ts, packages/@uppy/dashboard/src/components/FileCard/index.jsx, packages/@uppy/image-editor/src/ImageEditor.jsx, packages/@uppy/remote-sources/src/index.js
Fixes #3911 
Fixes #3910
Fixes `uninstall` of `@uppy/remote-sources`
=> Fix `uppy.close()` crashes when remote-sources or image-editor is installed

e2e/cypress/integration/dashboard-transloadit.spec.ts, packages/@uppy/core/src/Uppy.js, packages/@uppy/core/src/Uppy.test.js, packages/@uppy/transloadit/src/Client.js, packages/@uppy/transloadit/src/index.js
When starting an upload and removing it right away, it creates a race
condition when the assembly is created with no files and is never
closed. This commit ensures that the assembly is closed right away if
there are no scheduled uploads.
=> @uppy/transloadit: cancel assemblies when all its files have been cancelled

packages/@uppy/tus/package.json, yarn.lock
`@jest/globals` should be in the `devDependencies` list, not in the
`peerDependencies`.
Refs: https://community.transloadit.com/t/why-is-jest-globals-a-peer-dependency-of-every-uppy-package/16182/1
=> @uppy/tus: fix dependencies

packages/@uppy/drop-target/src/index.js
I don't think we need it exposed (unless we want users to be able to overwrite it, but then we should have tests for that, and it would make more sense as a static or as a prototype method). Let's remove it for now, we can always re-introduce it later if someone complains.
=> @uppy/drop-target: remove `isFileTransfer` from the public API

packages/@uppy/screen-capture/src/RecorderScreen.jsx, packages/@uppy/screen-capture/src/ScreenCapture.jsx, packages/@uppy/screen-capture/src/StopWatch.jsx, packages/@uppy/screen-capture/types/index.d.ts
- rename `RecorderScreen` class file to match with the class name.
- renamte `Stopwatch` to `StopWatch` (PascalCase convention).
- Remove custom TS definition in favor of the built-in one.
=> @uppy/screen-capture: fix TODOs

bin/build-bundle.mjs
We rely on `.name` for the `@uppy/remote-sources` plugin.
=> meta: `keepNames` in bundle

e2e/cypress/integration/dashboard-transloadit.spec.ts, packages/@uppy/transloadit/src/index.js
That should also avoid sending more than one `DELETE` request to Transloadit API.
=> @uppy/transloadit: send `assembly-cancelled` only once

packages/@uppy/remote-sources/src/index.js
Minifiers may be tempted to overwrite the `.name` property of the plugin classes to save some bytes.
=> @uppy/remote-sources: do not rely on `.name` property

packages/@uppy/core/src/Uppy.js, packages/@uppy/core/types/index.test-d.ts, packages/@uppy/store-default/README.md, packages/@uppy/store-default/src/index.js, packages/@uppy/store-default/src/index.test.js, packages/@uppy/store-default/types/index.d.ts, packages/@uppy/store-default/types/index.test-d.ts, website/src/docs/stores.md
Breaking: `new` keyword is now mandatory.
=> @uppy/store-default: export the class, don't expose `.callbacks`

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.test.js
Closes #3909
- Rename `#prepareUploadParts` to `#prepareUploadPartsRetryable`
- Call `this.#onError` instead of `return` to correctly handle error
- Add a test for it
=> Correctly handle errors for `prepareUploadParts`

packages/@uppy/companion/src/config/companion.js
Instead of silently ignoring the legacy option, it now shows `Error: The Provider option "providerOptions.s3" is no longer supported. Please use the option "s3" instead.`.
=> @uppy/companion: show deprecation message when using legacy s3 options

packages/@uppy/compressor/src/index.js
=> Fix Compressor being broken when no name is in the compressed blob

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.test.js
The docs say "Cancellation cannot fail in Uppy, so the result of this
function is ignored". So let's ignore it indeed.
Refs: https://community.transloadit.com/t/1-how-to-handle-promise-rejections-2-how-to-cancel-an-upload-that-hasnt-begun/16187
=> @uppy/aws-s3-multipart: ignore exception inside `abortMultipartUpload`

examples/digitalocean-spaces/server.js, packages/@uppy/companion/src/config/companion.js, packages/@uppy/companion/src/server/helpers/utils.js, packages/@uppy/companion/src/standalone/helper.js, website/src/docs/companion.md
and update docs
reference: #3592
=> fix default getKey for non-standalone too

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.test.js
The `#uploadParts` function calls itself after any part is uploaded. It also
determines which new chunks to upload based on their `state.busy` value. This
introduced a race condition, as `state.busy` was being set to false in the XHR
event handlers. So if one part were to complete while another part had finished
the XHR request, but not yet completed, then an upload for that second part
would be started again, despite the fact that the previous upload was still in
progress. Multiple uploads for the same part at the same time cause numerous
issues, and should never happen.
This is especially noticeable when an XHR request fails. `#uploadPart` is
wrapped in `#retryable`, so the part will be retried, however, for the entire
`retryDelay`, the chunk's `state.busy` value would be false, meaning …
=> @uppy/aws-s3-multipart: Fix race condition in `#uploadParts`

README.md
because cropping images is not editing metadata.
although I cannot find out how to crop images using the demo at https://uppy.io/
=> Fix statement about cropping images

packages/@uppy/companion/src/config/companion.js, website/src/docs/companion.md
Omitting this has been printing warnings for a long time now.
See #3180
=> enforce usage of uploadUrls

packages/@uppy/aws-s3-multipart/src/index.js
A bit embarrassing, but I forgot to change the default implementation of `prepareUploadParts`, which calls Companion, which meant everything crashed.
We really should get #3665 working.
=> Fix @uppy/aws-s3-multipart when using Companion

packages/@uppy/provider-views/src/ProviderView/ProviderView.jsx, packages/@uppy/provider-views/src/View.js
Fixes #3973
When going into a folder, adding a folder, logging out, or cancelling the filter input remains in state but is not rendered in the input field. This causes a weird and unobvious state.
=> Reset filter input correctly in provider views

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3/src/index.js, packages/@uppy/drop-target/src/index.js, packages/@uppy/form/src/index.js, packages/@uppy/golden-retriever/src/index.js, packages/@uppy/transloadit/src/index.js, packages/@uppy/tus/src/index.js, packages/@uppy/utils/package.json, packages/@uppy/utils/types/index.d.ts, packages/@uppy/xhr-upload/src/index.js
Alternative to https://github.com/transloadit/uppy/pull/3980.
=> @uppy/utils: use exports map

packages/@uppy/transloadit/src/index.js, packages/@uppy/transloadit/types/index.d.ts, packages/@uppy/transloadit/types/index.test-d.ts, packages/uppy/index.mjs, website/src/docs/transloadit.md, website/src/examples/transloadit/app.es6
Remove export of `ALLOWED_COMPANION_PATTERN`, `COMPANION`, and `COMPANION_PATTERN` in favor of `COMPANION_URL` and `COMPANION_ALLOWED_HOSTS`. This PR also adds back static properties that were present in `2.x` but marked them as deprecated.
=> @uppy/transloadit: deprecate static properties, export new names

packages/@uppy/utils/src/getDroppedFiles/utils/webkitGetAsEntryApi/index.js
It looks like trying to retrieve the dropped items must happen synchronously – otherwise only the first item gets treated and the other ones are garbage collected.
Fixes: https://github.com/transloadit/uppy/issues/3988
=> @uppy/utils: fix drop of multiple files on Chromium browsers

packages/@uppy/tus/src/index.js, packages/@uppy/tus/types/index.d.ts, website/src/docs/tus.md
Closes #3977
I think the use case is valid enough to add `file` as a second argument, even though we deviate from `tus-js-client` on this.
=> `@uppy/tus`: add file argument to `onBeforeRequest`

examples/cdn-example/index.html, examples/uppy-with-companion/client/index.html
`Uppy` call is now exported as `Uppy` instead of `Core`.
Refs: https://github.com/transloadit/uppy/pull/3981
=> example: update to new CDN export names

packages/@uppy/aws-s3/src/MiniXHRUpload.js
Fixes #3919
Unfortunately I can't easily test this as we can't get the AWS S3 E2E tests to work: #3665.
But the issue is clear enough to know where the problem is.
=> aws-s3: fix incorrect comparison for `file-removed`

examples/svelte-example/.gitignore, examples/svelte-example/README.md, examples/svelte-example/package.json, examples/svelte-example/server.mjs, yarn.lock
The example was lacking a server to handle uploads and respond to them.
=> example: fix svelte example

packages/@uppy/react/package.json, website/src/docs/react-dashboard-modal.md, website/src/docs/react-dashboard.md, website/src/docs/react-dragdrop.md, website/src/docs/react-fileinput.md, website/src/docs/react-progressbar.md, website/src/docs/react-statusbar.md, website/src/docs/react.md, yarn.lock
I tried what was the behavior of the major package managers with regard to `ppe`:
- **npm**: it installs peer dependencies only if they are mandatory, and simply ignores them if they are optional.
- **Yarn (Berry)**: will emit the same warning `doesn't provide @uppy/dashboard (pce892), requested by @uppy/react` regardless if the peer dependency is optional.
- **pnpm**: does the right thing (ignores missing optional peer deps, and throw an error if there are required peer deps missing).
Having the packages as peer dependencies lets the users choose which part of Uppy they want to use – no need to install `@uppy/dashbaord` f you're only using `@uppy/file-input`, and most users needed to install those packages anyway to use the CSS files.
=> @uppy/react: move `@uppy/` packages to peer dependencies

packages/@uppy/aws-s3/src/MiniXHRUpload.js, packages/@uppy/aws-s3/src/index.js, packages/@uppy/aws-s3/types/index.d.ts, packages/@uppy/transloadit/src/index.js, packages/@uppy/tus/src/index.js, packages/@uppy/tus/types/index.d.ts, packages/@uppy/xhr-upload/src/index.js, packages/@uppy/xhr-upload/types/index.d.ts, website/src/docs/aws-s3.md, website/src/docs/tus.md, website/src/docs/xhr-upload.md
Change counterintuitive `metaFields` to `allowedMetaFields`
=> @uppy/tus, @uppy/xhr-upload, @uppy/aws-s3: `metaFields` -> `allowedMetaFields`

.github/CONTRIBUTING.md, website/src/_template/contributing.md, website/src/examples/markdown-snippets/app.es6, website/src/examples/markdown-snippets/app.html, website/src/examples/markdown-snippets/index.ejs
Co-authored-by: Artur Paikin <artur@arturpaikin.com>
=> website: replace Robodog example with Uppy plugins

examples/transloadit/README.md, examples/transloadit/index.html, examples/transloadit/main.js, examples/transloadit/package.json, examples/transloadit/server.cjs, yarn.lock
Co-authored-by: Artur Paikin <artur@arturpaikin.com>
=> example: replace Robodog example with Transloadit + RemoteSources + Form

packages/@uppy/vue/package.json, website/src/docs/vue.md, yarn.lock
Similar to https://github.com/transloadit/uppy/pull/4004.
=> @uppy/vue: move `@uppy/` packages to peer dependencies

.eslintrc.js, examples/react-example/.babelrc.js, examples/react-example/.gitignore, examples/react-example/App.jsx, examples/react-example/README.md, examples/react-example/index.html, examples/react-example/main.js, examples/react-example/main.jsx, examples/react-example/package.json, examples/react-example/vite.config.js, yarn.lock
Switch to ESM, upgrade from React 16 to React 18, and add a README with instructions.
=> example: upgrade React example to use React 18

packages/@uppy/utils/package.json, website/src/docs/file-input.md, website/src/docs/image-editor.md, website/src/docs/migration-guides.md, website/src/docs/transloadit.md
- Bring back Transloadit and Image Editor docs
- Fix `yarn start`
- Correct indentation in migration guide
- Update Robodog migration example to use correct imports
=> Post-release website fixes

.github/workflows/companion-deploy.yml, README.md
I didn't agree with the change in https://github.com/transloadit/uppy/pull/3677, where Companion is deployed on _any change_ in the Companion folder. Users of Docker are forcibly on a nightly version, we could push a broken commit and they get a broken build. It also results in lots of tags and pushes to Dockerhub, people feel like they are always behind.
This PR changes the publish to only happen when a new git tag is pushed for Companion, which is what happens automatically by our GitHub Actions CI when a release happens.
=> Only publish Companion to Dockerhub on release

packages/@uppy/companion/package.json
Fixing this license issue from https://socket.dev/npm/package/@uppy/companion
=> Fix Companion license

packages/@uppy/transloadit/src/index.js, packages/@uppy/transloadit/types/index.d.ts
For a better DX, let's indicate what should be used instead of the deprecated API.
=> @uppy/transloadit: improve deprecation notice

packages/@uppy/core/types/index.d.ts, packages/@uppy/dashboard/types/index.d.ts, packages/@uppy/thumbnail-generator/types/index.d.ts
Given that https://github.com/transloadit/uppy/pull/4048 has some weird linter issues, let's land only the `.d.ts` file changes that actually matter for the users.
Fixes: https://github.com/transloadit/uppy/issues/4053
=> update definition type files for TS 4.8 compatibility

examples/angular-example/README.md, examples/angular-example/package.json, yarn.lock
To make it consistent with the other example packages.
=> example: fix Angular example package name

.github/workflows/ci.yml, .github/workflows/companion.yml, .github/workflows/e2e.yml, .github/workflows/manual-cdn.yml, .github/workflows/release-candidate.yml, .github/workflows/release.yml, .github/workflows/website.yml
We can skip the install of Cypress in all CI jobs but the e2e (which should improve things) and we can cache Cypress cache which should also improve things.
I'm also using [`yarn workspaces focus`](https://yarnpkg.com/cli/workspaces/focus) feature to cut down even more on the install time, especially in the Companion CI that don't need any deps expects Companion's.
=> meta: improve CI npm install time

packages/@uppy/dashboard/src/Dashboard.jsx, packages/@uppy/dashboard/src/components/AddFiles.jsx, packages/@uppy/webcam/src/Webcam.jsx, packages/@uppy/webcam/types/index.d.ts, website/src/docs/webcam.md
Should fix https://github.com/transloadit/uppy/issues/4032, but I'm having trouble testing: it works different in Chrome and Firefox on Android for me at the moment.
=> webcam: add nativeCameraFacingMode to Webcam and Dashboard

BUNDLE-README.md, packages/uppy/types/index.test-d.ts, website/src/docs/core.md, website/src/docs/index.md, website/src/docs/locales.md, website/src/docs/plugin-common-options.md, website/src/examples/i18n/app.html, website/src/uppy.ejs
I don't know if we want to rewrite all the examples to ESM, and/or if you want to keep demonstrating the legacy bundle. In any case, we should merge ASAP so we don't keep incorrect examples on the website.
=> meta: remove all remaining occurrences of `Uppy.Core`

.github/workflows/ci.yml, .github/workflows/companion.yml, .github/workflows/e2e.yml, .github/workflows/website.yml
E.g. we don't need to run the e2e suite on PRs that are only changing a GHA workflow file, or the companion CI if Companion wasn't touched.
=> meta: limit the number of unnecessary CI runs

packages/@uppy/core/src/Restricter.js, packages/@uppy/core/src/Uppy.test.js
G'day,
We believe we have identified an issue with the way @uppy/core's `Restrictor` class validates `maxNumberOfFiles` when ghost files are present.
`Restrictor` counts all the files, including files with `isGhost == true`, against the `maxNumberOfFiles` configuration. This prevents a user from uploading a replacement for the ghost file using the 'Re-select' link. A `RestrictionError` is raised instead with the message "You can only select X file".
We have tested this fix in our own implementation's sandbox and would like to raise this with the team for feedback and merge consideration.
- `maxNumberOfFiles` Uppy configuration set to `1`
- Without service worker configured for golden retriever
- Select a larger video file (20mb+)
- Close the uploader without reloading the page
- Open the …
=> @uppy/core: Fix `Restrictor` counts ghost files against `maxNumberOfFiles`

packages/@uppy/companion/package.json, packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/test/__tests__/uploader.js, yarn.lock
..instead of identical byte values
When doing performance testing I discovered:
when uploading large files on fast connections, sometimes a LOT of events will be emitted. (with distinct byte values) - this causes logs to flood and a lot of events to be sent to the client slowing down everything
=> Companion throttle progress by time

.github/workflows/companion-deploy.yml, .github/workflows/release.yml
Alternative to https://github.com/transloadit/uppy/pull/4074.
- Keep deploying to DockerHub on every push to `main`, but mark it as `edge`.
- Make Heroku deploy part of the release process so Heroku demo only uses the stable version.
- Add DockerHub deploy step to the release process marking it with the correct semver tag.
=> meta: fix Companion deploy

packages/@uppy/image-editor/src/style.scss
Fixes: https://github.com/transloadit/uppy/issues/4112
Apply big-screen styles for controls only if Dashboard width is at least medium-size.
=> image-editor: fix controls in small Dashboard

packages/@uppy/golden-retriever/src/index.js
Fixes #4093
During this I shockingly found out about this in the `install` of Golden Retriever:
```js
this.uppy.on('state-update', this.saveFilesStateToLocalStorage)
```
`state-update` is an undocumented event which triggers on **any state change in uppy or in any of the plugin states**. This results in this function being called regularly every second. Every call, whenever there are no files (happens a lot), we do a state update, **which triggers this function again**. This PR fixes the latter problem.
But in my opinion the `state-update` event shouldn't exist and we should only be able to listen to updates that matter for Golden Retriever. However, that discussion/solution shouldn't have to block this fix.
=> Fix endless webcam re-render with Golden Retriever

packages/@uppy/golden-retriever/src/index.js
Closes #4094 
This aligns the condition with the other storage methods such as IndexedDB. I really can't tell why this condition was there in the first place, if you have an idea please voice concern.
=> @uppy/golden-retriever: fix condition to load files from service worker

website/themes/uppy/layout/index.ejs, website/themes/uppy/layout/layout.ejs, website/themes/uppy/source/css/_stats.scss
`div.on-the-githubs` block is populated with `<li>` elements, which [are only allowed within `ul`, `ol` or `menu`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element).
It matters for accessibility (e.g. screen readers).
=> website: fix tag for Activity Feed

packages/@uppy/core/types/index.d.ts
Closes #4126 
Note: I was unable to get my fork working in the project where I discovered the issue, but the change seems simple enough… any tips how I could verify this locally would be appreciated.
=> Fix Uppy.cancelAll and Uppy.close types

packages/@uppy/url/src/UrlUI.jsx
This PR resolves a UX issue where the user uploading would receive an error if they pasted a url that had additional whitespace around it.
Thank you, looking forward to your feedback.
`trim()`s the input value within the `UrlUI` preact component before it calls `addFile`.
Because this deals directly with UX by attempting to prevent user error, it seemed most appropriate to place this value transformation directly within the preact component.
I wasn't sure where to include a test case for this. I struggled to find a pattern for testing a preact component in the lib. Requesting guidance in understanding where or how this case could be best written in following the existing patterns of the Uppy lib. 🙂
https://user-images.githubusercontent.com/565743/195644384-f630c91c-ca7a-4c80-8bb5-77a6bd9da …
=> @uppy/url: Trim whitespace around user input url

.github/workflows/website.yml
Because the GHA bot is merging the release PR, the website workflow doesn't run automatically. By adding a manual dispatch, we can make sure the website is updated after each release.
=> meta: add a manual deploy for website

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3-multipart/types/index.d.ts
We have never used this option.
=> @aws-s3-multipart: remove unused `timeout` option

packages/@uppy/utils/src/AbortController.js, packages/@uppy/utils/types/index.d.ts
Refs: https://github.com/whatwg/webidl/pull/1179
=> @uppy/utils: add `cause` support for `AbortError`s

packages/@uppy/companion-client/src/Provider.js, packages/@uppy/companion-client/src/RequestClient.js
...that caused double OPTIONS to be sent for each inital reqeust
Also simplify, deduplicate and async/awaitify code and fix lint.
This race condition caused the RequestClient to send X redundant OPTIONS requests immediately when starting an upload, where X is the number of files uploaded. This affected all Companion-related uploads: s3, s3-multipart, google drive etc. Note that after the initial requests, it would not send double OPTIONS (such as multipart uploading individual parts, because it would be cached by then).
This cache would be cleared for every upload "session".
After this PR, we only send OPTIONS once, then wait for the response before continuing. We globally cache the allowed headers based on `companionUrl`, so even in subsequent upload sessions, it will not send any more …
=> @uppy/companion-client: prevent preflight race condition

packages/@uppy/image-editor/src/cropper.scss
Add checkered background to cropper viewbox to indicate transparent parts of image.
Before:
After:
=> image-editor: add checkered background

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/utils/src/RateLimitedQueue.js
This is to avoid leaving aborted requests in the queue that would be reported as errors instead of being ignored.
=> @uppy/aws-s3-multipart: empty the queue when pausing

packages/@uppy/dashboard/src/Dashboard.jsx, packages/@uppy/dashboard/src/components/Dashboard.jsx, packages/@uppy/dashboard/src/components/FileItem/Buttons/index.jsx, packages/@uppy/dashboard/src/components/FileItem/Buttons/index.scss, packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.jsx, packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.scss, packages/@uppy/dashboard/src/components/FileItem/FileProgress/index.jsx, packages/@uppy/dashboard/src/components/FileItem/FileProgress/index.scss, packages/@uppy/dashboard/src/components/FileItem/index.jsx, packages/@uppy/dashboard/src/components/FileItem/index.scss, packages/@uppy/dashboard/src/components/FileList.jsx, packages/@uppy/dashboard/src/style.scss
With only one file / image selected, display it large and centered, and re-generate image preview so it's `600px` large.
Fixes #3970.
=> Dashboard: Single file mode

.github/workflows/ci.yml, .github/workflows/companion.yml, .github/workflows/e2e.yml, .github/workflows/linters.yml, .github/workflows/lockile_check.yml, .github/workflows/manual-cdn.yml, .github/workflows/release-candidate.yml, .github/workflows/release.yml, .github/workflows/website.yml
The `set-output` command is deprecated. Let's use the `GITHUB_OUTPUT` environment file.
Refs: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> meta: do not use the set-output command in workflows

packages/@uppy/aws-s3-multipart/src/index.js
The newly introduced check contains a typo. It should check `file.remote.url` not `file.remove.url`.
=> @uppy/aws-s3-multipart: Fix typo in url check

packages/@uppy/companion-client/src/RequestClient.js
Setting `Access-Control-Allow-Headers: *` should be interpreted as when that header is missing, for backward compat.
=> @uppy/companion-client: treat `*` the same as missing header

packages/@uppy/aws-s3-multipart/types/index.d.ts
The typing here is not aligned with the docs. Minor thing
```
...
An example of what the return value should look like:
{
"url": "https://bucket.region.amazonaws.com/path/to/file.jpg?partNumber=1&...",
"headers": { "Content-MD5": "foo" }
}
```
https://uppy.io/docs/aws-s3-multipart/#signPart-file-partData
=> @uppy/aws-s3-multipart: Aligning singPart with doc

packages/@uppy/aws-s3/src/index.js
I was getting this error: 
```
TypeError: Failed to construct 'URL': Invalid URL
at resolveUrl (index.js:46:10)
at Object.defaultGetResponseData [as getResponseData] (index.js:313:19)
at Function.<anonymous> (MiniXHRUpload.js:195:27)
at emitAll (index.js:131:14)
at Object.emit (index.js:33:7)
at UppySocket.emit (Socket.js:120:59)
at WebSocket.value (Socket.js:46:16)
```
it's because from the XML content that Digital ocean space returns, there are no protocal on the link like AWS s3.
You guys also leave a note here about that: https://github.com/transloadit/uppy/blob/bef7b58beff5485c0de208fc3ab4296ae22127e6/packages/%40uppy/aws-s3/src/index.js#L271
```
// Some S3 alternatives do not reply with an absolute URL.
// Eg DigitalOcean Spaces uses /$bucketName/xyz
location: …
```
=> fix: add https:// to digital oceans link

packages/@uppy/audio/README.md
Export should be named `Audio`, reflecting later usage
=> Update @uppy/audio Readme

.env.example, examples/aws-companion/package.json, examples/aws-php/package.json, examples/custom-provider/package.json, examples/digitalocean-spaces/package.json, examples/multiple-instances/package.json, examples/node-xhr/package.json, examples/php-xhr/package.json, examples/python-xhr/package.json, examples/react-example/package.json, examples/transloadit-markdown-bin/package.json, examples/transloadit/package.json, examples/vue/package.json, examples/vue3/package.json, examples/xhr-bundle/package.json, package.json, private/dev/package.json, website/package.json, yarn.lock
Note that Uppy devs will probably have to update their `.env` file to escape `$` chars.
=> meta: upgrade to Vite 4 and ESBuild 0.16

packages/@uppy/utils/types/index.d.ts
Was pulling my hair out while passing `bytesTotal` (as requested by the type definition) and was getting `NaN` back as a result 😅 (see https://github.com/transloadit/uppy/blob/b8e1f9c995a365fd8ee042fe66944a3f425091b7/packages/%40uppy/utils/src/getSpeed.test.js for correct usage)
=> Fix getSpeed type (referenced `bytesTotal` instead of `uploadStarted`)

packages/@uppy/aws-s3-multipart/src/index.js
Currently, the shape of the metadata property makes Companion crash.
=> @uppy/aws-s3-multipart: fix metadata shape

.github/workflows/bundlers.yml, .github/workflows/ci.yml, .github/workflows/companion-deploy.yml, .github/workflows/companion.yml, .github/workflows/e2e.yml, .github/workflows/linters.yml, .github/workflows/lockile_check.yml, .github/workflows/manual-cdn.yml, .github/workflows/release-candidate.yml, .github/workflows/release.yml, .github/workflows/website.yml
Yarn v4 enables global caching by default, using a local cache simplifies the use of @actions/cache.
Also simplifies the publish to npm step.
=> ci: make sure Yarn's global cache is disabled

website/src/docs/companion.md
The comment detailing what option the `COMPANION_PATH` environment variable corresponds to said `server.port`, but I think this is a copy/paste mistake and should be `server.path`.
=> Fix comment about COMPANION_PATH

packages/@uppy/utils/src/getDroppedFiles/utils/webkitGetAsEntryApi/index.js
=> @uppy/utils: better fallbacks for the drag & drop API

packages/@uppy/core/src/Uppy.js, packages/@uppy/locales/src/fr_FR.js, packages/@uppy/xhr-upload/src/index.js, packages/@uppy/xhr-upload/src/locale.js, website/src/docs/core.md, website/src/docs/xhr-upload.md
Instead of cancelling the upload, let's give the user control over what to do when a stalling is detected.
The stall detection was added in https://github.com/transloadit/uppy/pull/378, but using a hard-coded time limit is probably not a good idea.
=> @uppy/xhr-upload: add `'upload-stalled'` event

packages/@uppy/companion/package.json, packages/@uppy/companion/src/companion.js, yarn.lock
Upgrade the `grant` dependency.
This is necessary in order to get a newer version of the transitive dependency `request-compose` which works with bundlers like esbuild.
=> @uppy/companion upgrade grant dependency

packages/@uppy/audio/src/Audio.jsx, packages/@uppy/core/src/Uppy.js, packages/@uppy/dashboard/src/Dashboard.jsx, packages/@uppy/screen-capture/src/ScreenCapture.jsx
On Transloadit, we see a ton of errors such as “Screen recorder access is not supported”, which should actually be warnings.
Also because we were sometimes not logging the original error, but `{ message, details }`, the stack trace was lost.
=> Warn more instead of erroring

packages/@uppy/transloadit/src/AssemblyOptions.js, packages/@uppy/transloadit/src/index.js, packages/@uppy/transloadit/types/index.d.ts, private/dev/Dashboard.js
Refs: https://github.com/transloadit/uppy/pull/4059
Fixes: https://github.com/transloadit/uppy/pull/4295
=> @uppy/transloadit: fix `assemblyOptions` option

packages/@uppy/utils/src/getDroppedFiles/utils/webkitGetAsEntryApi/index.js
=> workaround chrome crash

packages/@uppy/image-editor/types/index.d.ts
Reported by TypeScript >= 4.8, see [TypeScript 4.8 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#unconstrained-generics-no-longer-assignable-to-).
Currently using `skipLibCheck` as a workaround.
Amends issue #4053 and PR #4048.
=> uppy/image-editor: Fix TypeScript error in image-editor types

packages/@uppy/core/types/index.d.ts
=> @uppy/core: fix some types

packages/@uppy/core/src/_variables.scss, packages/@uppy/dashboard/src/style.scss
After modifying the dashboard background, the icon hover styles became barely visible. Fixing it here:
**Before:**
**After:**
Full preview:
https://user-images.githubusercontent.com/375537/223401003-1f3ff9ad-1ebd-454d-be38-de82b00fc142.mp4
=> @uppy/dashboard: Fix low-contrast hover styles

packages/@uppy/companion/src/server/helpers/request.js, packages/@uppy/companion/test/__tests__/http-agent.js
in development when `allowLocalUrls` is true
also improve error so we can distinguish between resolved ip forbidden or hostname ip forbidden
=> @uppy/companion: allow local ips when testing

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/companion-client/src/Socket.js, packages/@uppy/tus/src/index.js
- Don’t auto-open socket when adding to the queue; cleanup on abort
- Socket: don't open if already opened
Co-authored-by: Antoine du Hamel <duhamelantoine1995@gmail.com>
=> RateLimitedQueue: fix ‘cannot mark request as done’

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/server/controllers/s3.js, packages/@uppy/companion/src/server/controllers/url.js, packages/@uppy/companion/src/server/middlewares.js, packages/@uppy/companion/src/standalone/index.js
increase body size for s3 complete endpoint
fixes #1945
also:
[refine body parsers](https://github.com/transloadit/uppy/commit/cc26ecc50242735fa70b43b5c2b54f966227503b) 
to make it possible to adjust them individually, also improves security and speed, because we don't have to parse all body types (and all sizes) for all endpoints
=> @uppy/companion: only body parse when needed & increased body size for s3

packages/@uppy/companion/src/standalone/helper.js
COMPANION_REDIS_PUBSUB_SCOPE -> redisPubSubScope
docs: https://github.com/transloadit/uppy.io/pull/88
=> @uppy/companion: add missing env variable for standalone option

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3/src/MiniXHRUpload.js, packages/@uppy/tus/src/index.js, packages/@uppy/xhr-upload/src/index.js
also: sync duplicated code between all plugins - created #4377 for this
Not sure if this has any side effects. Does golden retriever depend on this? does golden retriever even support retrieving companion uploads?
fixes #4356
=> make sure that we reset serverToken when an upload fails

.github/workflows/bundlers.yml
Previously only direct dependencies of `uppy` were overridden, which did not cover packages such as `@uppy/utils`.
=> meta: use overrides to make sure no uppy package is fetch from npm

packages/@uppy/informer/src/TransitionGroup.js
The idea behind this PR is to fix [this issue](https://github.com/transloadit/uppy/issues/3971)
We found that when user has an unstable connection and the browser disconnects and connects again many times really fast it can lead to a situation where the informer tries to remove a component that no longer is there.
Instructions to reproduce this bug are listed in the linked issue.
=> @uppy/informer: add a check in `TransitionGroup` when component is null

packages/@uppy/companion/src/server/provider/drive/index.js, packages/@uppy/companion/src/server/provider/dropbox/index.js, packages/@uppy/companion/test/__tests__/providers.js
...because adding 10k files still takes about 5 minutes (to paginate all files), see discussion here: #4389
advantages:
- adding huge folder as much faster
- listing files is faster when scrolling (when a lot of files), because less `/list` API calls
disadvantages:
- it takes longer to show the user the first list (when a lot of files) and more data will be used (e.g. mobile)
=> @uppy/companion: increase max limits for remote file list operations

e2e/cypress/integration/dashboard-aws-multipart.spec.ts, e2e/cypress/support/e2e.ts, packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/status-bar/src/Components.jsx
When the user clicks retries, we need to have cleared up all the cache regarding the file to retry, otherwise we are likely to target an already expired ID.
Fixes: https://github.com/transloadit/uppy/issues/4366
=> @uppy/aws-s3-multipart: make retries more robust

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3-multipart/types/index.d.ts, packages/@uppy/aws-s3/src/index.js
When uploading small files (e.g. ≤100MiB), using multipart can decrease the upload performance as it introduces more overhead for uploading just one part.
This can be solved without too much difficulty by hitting the non-multipart endpoint for files with only one chunk.
=> @uppy/aws-s3-multipart: add `shouldUseMultipart ` option

packages/@uppy/aws-s3-multipart/src/index.js
The intent was to match the `@uppy/aws-s3` plugin option, and that's what we are documenting as well, however  the implementation was using a different API signature, which would make migrating to the future aggregated S3 plugin more complicated than necessary.
=> @uppy/aws-s3-multipart: fix `getUploadParameters` option

packages/@uppy/xhr-upload/src/index.js
Currently multiple files send as 
```
field_from_form_for_files[]: [object File],[object File],[object File]
``` 
and it breaks default form behaviour, with this fix it works properly, like
```
field_from_form_for_files[]: (binary)
field_from_form_for_files[]: (binary)
field_from_form_for_files[]: (binary)
```
=> @uppy/xhr-upload: allow to upload multiple files in metaData

packages/@uppy/core/types/index.d.ts
The `state` getter was removed a while back, and we forgot to fix the types.
Refs: https://github.com/transloadit/uppy/commit/c042f0220b7637c8294d673c24b2c73e9a089681
Fixes: https://github.com/transloadit/uppy/issues/4090
=> @uppy/core: remove `state` getter from types

e2e/cypress.config.mjs, e2e/cypress/integration/dashboard-xhr.spec.ts, e2e/mock-server.mjs, package.json, packages/@uppy/companion/package.json, packages/@uppy/companion/src/server/helpers/request.js, packages/@uppy/url/src/Url.jsx, yarn.lock
- We should make sure it works for old Companion as well, so `name: meta.name || getFileNameFromUrl(url)`
- Is `response.request.requestUrl` a good original url source for the fallback?
Before:
After:
=> @uppy/companion: Use filename from content-disposition instead of relying on url, with fallback

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3/src/MiniXHRUpload.js, packages/@uppy/tus/src/index.js, packages/@uppy/utils/package.json, packages/@uppy/utils/src/EventManager.js, packages/@uppy/utils/types/index.d.ts, packages/@uppy/xhr-upload/src/index.js
See original issue: https://github.com/transloadit/uppy/issues/4446
Not actually sure how to test this locally, this was a simple global find & replace.
=> @uppy/utils: rename `EventTracker` -> `EventManager`

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/tus/src/index.js, packages/@uppy/xhr-upload/src/index.js
- Fixed tus `pause`/`resume`/`cancel` being ignored on Companion — don't close sockets after pause/resume events are sent
- Close sockets on error and complete
Fixes #4409
:warning: ** Note:**
`pause`/`resume`/`cancel` works in tus, but only `cancel` works in S3 Multipart for remote uploads. For local uploads you can `pause`/`resume` them. @mifi says pause/resuming remote uploads could be complicated because of streaming.
Related:
- https://github.com/transloadit/uppy/pull/4368
=> Don't close socket while upload is still in progress

.eslintrc.js, package.json, yarn.lock
It is useful for local testing, but should never be committed. This lint rule should help catch that during code reviews.
=> meta: disallow use of `.only` in tests

packages/@uppy/provider-views/src/Item/components/GridLi.jsx, packages/@uppy/provider-views/src/Item/components/ListLi.jsx, packages/@uppy/provider-views/src/ProviderView/ProviderView.jsx, packages/@uppy/provider-views/src/SearchProviderView/SearchProviderView.jsx, packages/@uppy/provider-views/src/View.js
This PR changes a few things:
- Adds `recordShiftKeyPress` callback to the `mousedown` event in list and grid list items. This currently only tracks the `keydown` event, so when checkboxes receive mouse events (e.g. a click) even without the shift key, the shift key state isn't updated.
- Resets `lastCheckbox` when switching folders. We don't want to track the last checkbox clicked between folders because no range of folders can be computed from that, and that causes shift-clicking on a file in a different folder to fail. 
- Combine existing selection with new selected range. The existing range selection resets any previously selected files, and therefore doesn't support selecting multiple non-overlapping ranges. This concatenates the existing selections with the new range, and removes …
=> @uppy/provider-views: Fix range selection not resetting and computing correctly

packages/@uppy/companion/src/server/helpers/request.js
reverts https://github.com/transloadit/uppy/pull/4489#discussion_r1225535334
=> @uppy/companion: remove randomness from file names

packages/@uppy/core/src/Uppy.js
Without this, first `file-complete` event arrives, setting progress to full total amount of `bytesUploaded` and `complete: true`, then late throttled `upload-progress` re-sets that `bytesUploaded` to a new value, making `calculateTotalProgress` confused.
=> @uppy/core: Don't set late (throttled) progress event on a file that is 100% complete

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
We were using `Math.ceil` instead of `Math.floor` which ended up creating always one part too many.
=> @uppy/aws-s3-multipart: fix the chunk size calculation

packages/@uppy/tus/src/index.js
We should retry on HTTP 423 Locked (happens when a paused download is resumed too quickly), like tus-js-client default `onRetry` does.
=> @uppy/tus: retry on 423 HTTP error code

packages/@uppy/companion/src/server/controllers/s3.js
Attempting to list a multipart upload with 0 uploaded parts would return an empty array with AWS SDK v2, and returns `undefined` with AWS SDK v3.
It's broken since #4285, I think.
=> @uppy/companion: fix part listing in s3

e2e/cypress/integration/dashboard-aws-multipart.spec.ts, packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.js
When pausing the upload, we don't want to remove the cached `uploadId`, otherwise Uppy needs to re-upload the file from the beginning, even if it has already uploaded some chunks.
It's broken since #4424 landed I think.
=> @uppy/aws-s3-multipart: fix pause/resume

examples/aws-nodejs/index.js, examples/aws-nodejs/public/index.html
Using url-encoded body instead of JSON allows the browser to skip the CORS preflight request, speeding up the upload.
=> examples/aws-nodejs: showcase an example without preflight requests

examples/aws-nodejs/README.md
I ran Prettier on it, then I updated some paragraphs.
=> examples/aws-nodejs: update README

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3-multipart/types/chunk.d.ts
We could certainly benefit from a full TS overwrite, but adding a few JSDoc comment already goes a long way so that's what this PR is doing.
=> @uppy/aws-s3-multipart: add types to internal fields

e2e/cypress/integration/dashboard-aws-multipart.spec.ts, packages/@uppy/aws-s3-multipart/src/MultipartUploader.js, packages/@uppy/aws-s3-multipart/src/index.js
https://github.com/transloadit/uppy/pull/4526 introduced a regression causing already aborted UploadId to be reused.
=> @uppy/aws-s3-multipart: fix upload retry using an outdated ID

.yarn/patches/start-server-and-test-npm-1.14.0-841aa34fdf.patch, package.json, yarn.lock
I was getting locally `npm command not found` when trying to run `yarn e2e:ci` locally.
=> meta: use `corepack yarn` instead of `npm` to launch E2E

packages/@uppy/companion/test/__tests__/uploader.js
and [remove invalid assertion](https://github.com/transloadit/uppy/commit/26417630b6654e121e5418c4a8cf2d6db8f549cb) 
success event never seems to have included "bytesTotal" in payload
this assertion was mistakenly moved from onProgress to success in https://github.com/transloadit/uppy/commit/1b5c0d7d4b6ac2f387ac5699d587e281f6579afe
=> @uppy/companion: fix infinite recursion in uploader test

packages/@uppy/locales/src/pt_BR.js
Upon testing multiple locales, I realized some options are falling back to English for the editor plugin. I did some digging and found out that the locales are missing in pt-BR. This should do it. 
I am a native Brazilian Portuguese speaker therefore I'm confident the translations are correct but please feel free to have someone review this translations if necessary. Hope this helps!
=> Add missing pt-BR locales for ImageEditor plugin

.github/ISSUE_TEMPLATE/1-bug.yml, .github/ISSUE_TEMPLATE/2-feature.yml
We sort new issues between bug and feature automatically
=> meta: Don't use triage label

packages/@uppy/status-bar/src/StatusBar.jsx
This ensures that the internal state of the status bar will be correct when the upload is started programmatically rather than using the Dashboard UI.
Before this PR, the status bar would be showing `NaNs left` because some of the internal variables were still at value `undefined`.
=> @uppy/status-bar: listen to `upload` event instead of button click

packages/@uppy/aws-s3-multipart/src/createSignedURL.js
Referencing `globalThis` before the functions are called causes `require` errors in server rendered environments as soon as the `createSignedURL.js` file is imported because `globalThis.crypto` is `undefined`.
=> @uppy/aws-s3-multipart: Read from `globalThis` in functions

e2e/cypress.config.mjs
The default value was 5s, causing a lot of flakiness.
=> e2e: increase `requestTimeout` to 16s

packages/@uppy/provider-views/src/ProviderView/ProviderView.jsx
=> @uppy/provider-views: fix infinite folder loading 

.github/CONTRIBUTING.md
https://github.com/transloadit/uppy.io/issues/134#issuecomment-1632102417
=> Add i18n to CONTRIBUTING.md

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3-multipart/src/index.test.js
Resolves [File objects passed to AWS S3 Multipart contains outdated state information](https://github.com/transloadit/uppy/issues/4533). Now the `HTTPCommunicationQueue` in the AWS S3 Multipart plugin has a private `#getFile` function, passed when the communication queue is instantiated, which is called to refresh the file object when calling the following user-defined functions:
- `createMultipartUpload`
- `signPart`
- `listParts`
- `abortMultipartUpload`
- `completeMultipartUpload`
See also [the issue on the community forum](https://community.transloadit.com/t/custom-file-metadata-not-persisted-across-user-defined-functions-in-aws-s3-multipart/16661/3) in which I initially raised this issue.
Please let me know if you have any feedback. In particular, I wasn't sure how to design the unit …
=> Refresh file before calling user-defined functions in AWS S3 Multipart

e2e/cypress/integration/dashboard-aws-multipart.spec.ts
#4587 increased `requestTimeout` to 16s, but there were still that hard coded timeout which was making the test extra flaky.
=> e2e: remove too short timeout

.github/workflows/ci.yml
https://github.com/nodejs/node/issues/48921
=> lock node-js version on ci

packages/@uppy/dashboard/src/Dashboard.jsx, packages/@uppy/provider-views/src/ProviderView/ProviderView.jsx, packages/@uppy/provider-views/src/ProviderView/index.js, packages/@uppy/provider-views/src/index.js
The dashboard provides a default/fallback icon for plugins without icon. The ProviderView does not - so a plugin that can be shown just fine on the overview panel, produces an error when it's actually opened. Let's use the same fallback icon.
=> @uppy/provider-views: fix ProviderView error on empty plugin.icon

packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/src/server/controllers/s3.js, packages/@uppy/companion/src/server/helpers/utils.js
While uploading from Box, Gdrive or any other companion provider, if the file name is something like `Joe Rogan’s Shortest Podcasts.mp4` so `Rogan’s` which is not url safe. the upload got 500 error.
so updated the Metadata to use `rfc2047Encode` function. in file `packages/@uppy/companion/src/server/Uploader.js`
Please advice if needed any more changes
=> @uppy/companion: Fix Uploader.js metadata normalisation

packages/@uppy/companion/src/server/Uploader.js
This PR fixes redis default ttl 
prev was in version v3 but in https://github.com/transloadit/uppy/pull/3589 updated to v4 but we need to update the syntax also to set redis url
https://github.com/transloadit/uppy/issues/3748#ref-commit-3387b84
**code changes** 
`this.storage.set(redisKey, jsonStringify(state), 'EX', keyExpirySec)` has been updated to 
` this.storage.set(redisKey, jsonStringify(state), {
EX: keyExpirySec,
})
`
file `packages/@uppy/companion/src/server/Uploader.js`
=> @uppy/companion: fix Redis key default TTL

packages/@uppy/core/src/Uppy.js, packages/@uppy/core/src/Uppy.test.js
Closes #4470
- Change default signature of `onBeforeFileAdded` to check for duplicate files to not make this a breaking change.
- Swap order of `checkIfFileAlreadyExists` and `onBeforeFileAdded`.
This means:
- If you add the same file again before uploading, it will override it.
- If you add the same file after uploading, you can upload it again. Depending on your uploader and backend this may or may not override the file. Tus for instance always generates unique IDs so it wouldn't override it. But people should be able to handle it the way they want.
Needs docs PR too.
=> @uppy/core: allow duplicate files with onBeforeFileAdded

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3/src/index.js, packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/src/server/controllers/s3.js, packages/@uppy/transloadit/src/Client.js, packages/@uppy/xhr-upload/src/index.js
Refs: https://www.rfc-editor.org/rfc/rfc9110#name-overview
=> use uppercase HTTP method names

e2e/cypress/integration/dashboard-transloadit.spec.ts, packages/@uppy/aws-s3-multipart/types/index.d.ts, packages/@uppy/aws-s3-multipart/types/index.test-d.ts, packages/@uppy/aws-s3/types/index.d.ts, packages/@uppy/aws-s3/types/index.test-d.ts
Attempt at making `@uppy/aws-s3` types more useful for consumers.
=> @uppy/aws-s3,@uppy/aws-s3-multipart: update types

Dockerfile, Dockerfile.test
update to node-18.17.0-alpine as node 16 have 1 high security issue https://nodejs.org/en/blog/vulnerability/february-2023-security-releases#nodejs-permissions-policies-can-be-bypassed-via-processmainmodule-high-cve-2023-23918
=> update to node-18.17.0-alpine, 

packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3-multipart/src/index.test.js
=> @uppy/aws-s3-multipart: pass the `uploadURL` back to the caller

packages/@uppy/aws-s3-multipart/types/index.d.ts, packages/@uppy/aws-s3/types/index.d.ts
Fixes: https://github.com/transloadit/uppy/issues/4629
=> allow empty objects for `fields` types

packages/@uppy/companion/src/server/emitter/redis-emitter.js
This makes the Redis emitter API consistent with the Node emitter API and the documentation.
Fixes #4646
=> Alias "removeListener" as "off" in Redis emitter

packages/@uppy/image-editor/src/Editor.jsx, packages/@uppy/image-editor/src/ImageEditor.jsx, packages/@uppy/image-editor/src/style.scss, packages/@uppy/image-editor/src/utils/getCanvasDataThatFitsPerfectlyIntoContainer.js, packages/@uppy/image-editor/src/utils/getScaleFactorThatRemovesDarkCorners.js
- on 90deg rotations, the image now fits fully into the view, and cropbox wraps it entirely (fixes https://github.com/transloadit/uppy/issues/4380)
- on granular rotations, the image scales like on android
- on granular rotations, we always see `[-45°, 45°]` range (previously we saw values such as `-59°`)
- I removed `requestAnimationFrame` code temporarily while developing. Should we add it back, is there some issue/use case that it helps solve that we can observe in action?
- make "granular rotation" and "90 deg rotation" work around the cropbox center instead of image center (cropper 1 doesn't support this https://github.com/fengyuanchen/cropperjs/issues/580, but we can do it manually)
- disable scale-on-rotation if the cropbox doesn't exactly match the …
=> Improve image rotation

packages/@uppy/companion/src/server/helpers/utils.js, packages/@uppy/companion/src/server/provider/credentials.js
when async function rejects promise unhandled
prevents `Invalid initialization vector` from crashing companion in prod.
=> @uppy/companion: catch "invalid initialization vector" instead of crashing

.github/CONTRIBUTING.md
- Moved **#Development** section above the **#Tests** section
Because people develop first and test second, especially since tests fail by default without the correct env file.
- Removed mentions of **Uppy.io**
Looks like we moved the website to https://github.com/transloadit/uppy.io.
- Clarified **corepack** usage
Previous instructions would always be doing `yarn install` for me (with my old version of yarn) because I already had yarn installed.
```sh
#previous instructions
corepack -v || npm i -g corepack
yarn -v || corepack enable
yarn install || corepack yarn install
```
- Added a section for the command beginner contributors probably most want, `yarn run dev`
=> Improve Contributing.md

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/config/companion.js, packages/@uppy/companion/src/server/controllers/s3.js, packages/@uppy/companion/src/standalone/helper.js
this will give a 404 instead of throwing an error
also allow disabling URL endpoint too
=> remove s3 endpoints if s3 disabled

packages/@uppy/dashboard/src/components/EditorPanel.jsx, packages/@uppy/dashboard/src/components/FileCard/index.jsx
Fixes #4045
This makes both “cancel” buttons firing this event though. Probably only the image editor neends to fire it?
=> Make file-editor:cancel event fire when the Image Editor “cancel” button is pressed

packages/@uppy/tus/src/index.js
This PR fixes the issue where user-defined `onSuccess`, `onError`, and `onProgress` callbacks were being ignored in the Tus plugin. While these options were accepted during initialization, they were not being called in the respective events.
This change ensures that if a user has provided any of these callbacks, they will be called in addition to the internal handlers.
- Utilized user-defined `onSuccess`, `onError`, and `onProgress` callbacks in the Tus plugin.
- Updated the code to check for and invoke user-defined callbacks if provided.
=> Fix: Utilize user-defined onSuccess, onError, and onProgress callbacks in @uppy/tus

packages/@uppy/companion/src/server/provider/facebook/index.js, packages/@uppy/companion/src/server/provider/instagram/graph/index.js
was accidentally introduced here:
https://github.com/transloadit/uppy/commit/35812ca378b9b02290a2ab51261ddaeff8211fda#diff-48004ff4f8ca0268432082f97fc45b2443ceb2e5936284b7985b8aa68494dbbcR94
How to reproduce the error with facebook (before this PR):
- Log into your facebook account in Uppy and list files
- Go to facebook settings and privacy https://www.facebook.com/privacy/checkup/?source=settings_and_privacy
- Remove the Transloadit app
- now reload uppy and click facebook again and abserve the error
I've tested the fix with facebook and it works.
=> fix instagram/facebook auth error regression

packages/@uppy/svelte/package.json
Refs: https://github.com/transloadit/uppy/pull/4652
=> @uppy/svelte: revert breaking change

.dockerignore, .github/workflows/companion.yml, Dockerfile
theory: this PR's build should fail with
```
#23 22.96 node_modules/@szmarczak/http-timer/dist/source/index.d.ts(25,18): error TS2430: Interface 'ClientRequestWithTimings' incorrectly extends interface 'ClientRequest'.
#23 22.96   The types returned by 'setTimeout(...)' are incompatible between these types.
#23 22.96     Type 'ClientRequest' is not assignable to type 'this'.
#23 22.96       'ClientRequest' is assignable to the constraint of type 'this', but 'this' could be instantiated with a different subtype of constraint 'ClientRequest'.
#23 ERROR: process "/bin/sh -c cd /app && corepack yarn workspace @uppy/companion build" did not complete successfully: exit code: 1
#22 [linux/arm64 build 7/9] RUN apk --update add  --virtual native-dep   make gcc g++ python3 libgcc libstdc++ git && …
```
=> run type checks also for companion and add files to docker

packages/@uppy/companion/src/server/Uploader.js
with tus
as recommended in https://github.com/tus/tus-js-client/pull/606
because sometimes HEAD reports an incorrect size
=> @uppy/companion: use deferred length for tus streams

packages/@uppy/companion/tsconfig.json
and fix ts error in tsconfig ("module")
because stuff like generator-runtime isn't needed anymore. example: https://www.unpkg.com/@uppy/companion@4.5.1/lib/server/provider/credentials.js
alternatively close this PR and instead merge #4669
=> upgrade ts target

packages/@uppy/utils/src/dataURItoBlob.test.js, packages/@uppy/utils/src/dataURItoBlob.ts, packages/@uppy/utils/src/dataURItoFile.js
=> convert datauritoblob to ts 🎉

packages/@uppy/image-editor/src/ImageEditor.jsx
Didn't overthink the solution, it's taken from https://github.com/fengyuanchen/cropperjs/issues/551#issuecomment-1642138810, we'll want to go for cropperjs's solution when they implement it.
See https://github.com/transloadit/uppy/issues/4305#issuecomment-1717170265 for details.
___
Note for the reviewers: the obvious solution would be to just return the original image if user didn't do any transformations with the image, however this is a separate issue. A black line will appear even if we rotate the image.
___
Fixes #4305
=> ImageEditor.jsx - remove 1px black lines

e2e/cypress/integration/dashboard-aws-multipart.spec.ts, packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3-multipart/src/index.test.js
This is a tricky one. Using `RateLimitedQueue` is complex and unintuitive. We also duplicate this logic between tus and S3. We can not reuse the existing `#shouldRetry` as it's very tightly coupled and full of side-effects.  It's also odd that there is a global retry iterator, which takes the default or user provided `retryDelays` and turns it into an iterator, as this seems to unnecessarily share the retry interval between all requests.
There is an open issue about all of this: https://github.com/transloadit/uppy/issues/4173.
For now this fix is fine.
=> @uppy/aws-s3-multipart: retry signature request

.eslintrc.js, .prettierignore, .prettierrc.js, e2e/clients/index.html, examples/transloadit/index.html, package.json, yarn.lock
JS files are ignored for now because we want to migrate them to TS anyway.
MD files are also ignored to minimize the diff.
Nothing is enforcing use of Prettier for now (so it doesn't reject PRs), maybe it should?
=> meta: add Prettier

packages/@uppy/core/types/index.d.ts
Order them in ASCII order for readability
=> @uppy/core: type more events

packages/@uppy/core/package.json
This should allow bundler to not include Preact when no UIPlugin is used.
=> @uppy/core: mark the package as side-effect free

packages/@uppy/aws-s3-multipart/src/index.js
Not ideal design, but better than making a breaking change. Some of our methods are expecting the `signal` to be a separate argument instead of being in the options bag. It shouldn't be a problem to pass the same `AbortSignal` twice, hopefully that's something we can fix in a future major.
=> @uppy/aws-s3-multipart: pass `signal` as separate arg for backward compat

examples/aws-nodejs/public/index.html
Refs: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/throwIfAborted#browser_compatibility
=> example: simplify code by using built-in `throwIfAborted`

packages/@uppy/aws-s3-multipart/src/index.js
When chunks have already been uploaded, they are removed from memory. If the user resume an upload whose first chunk has been uploaded, they were getting a `TypeError` back.
=> @uppy/aws-s3-multipart: fix `TypeError`

packages/@uppy/core/package.json
CSS files do contain some side effects, as some Uppy plugins rely on some CSS class being styled by core.
=> @uppy/core: fix `sideEffects` declaration

packages/@uppy/core/types/index.d.ts, packages/@uppy/core/types/index.test-d.ts
fix https://github.com/transloadit/uppy/issues/4758
=> @uppy/core: simplify types with class generic

packages/@uppy/companion/src/server/Uploader.js, packages/@uppy/companion/src/server/helpers/utils.js
to align it with getKey - closes #4763
=> add getBucket metadata argument

packages/@uppy/core/src/_variables.scss, packages/@uppy/dashboard/src/style.scss, packages/@uppy/react-native/file-picker/url.js
Set a new color to meet the WCAG AA criteria:
This closes #4767.
=> Update Uppy's blue color to meet WCAG contrast requirements

bin/build-ts.mjs
The previous version was failing to build dependencies in the right order; it was also way slower by spawning 2 `tsc`  processes per plugin instead of 1 for all plugins.
=> meta: fix build of TypeScript plugins

packages/@uppy/dashboard/types/index.d.ts
singleFileFullScreen->centerSingleFile
fix: #4755
=> fix(@uppy/dashboard): fix wrong option type in index.d.ts

bin/upload-to-cdn.js, package.json, yarn.lock
From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.
This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).
```console
$ npx aws-sdk-js-codemod@0.26.1 -t v2-to-v3 bin/upload-to-cdn.js
```
`@uppy/companion` switched to AWS SDK for JavaScript v3 in https://github.com/transloadit/uppy/pull/4285
=> chore: migrate AWS SDK for JavaScript v2 APIs to v3 in bin folder

packages/@uppy/companion-client/src/Socket.js, packages/@uppy/companion-client/src/Socket.test.js, packages/@uppy/companion-client/src/index.js
This reverts part of commit 17826da517f5a18d67f5e9f6cbe7c35e230818f5.
=> @uppy/companion-client: revert breaking change

packages/@uppy/companion-client/src/Provider.js
fixes `this.uppy.log.warn is not a function`
=> @uppy/companion-client: fix log type error

private/js2ts/index.mjs
- add `@ts-ignore` comment on `package.json` imports.
- better detect imports of local `.js` files.
- do not remove non-JS files from the source.
=> meta: improve js2ts script

packages/@uppy/locales/src/de_DE.ts
Follow up to https://github.com/transloadit/uppy/pull/4797 with new translation structure
Original text:
> Thanks for making uppy! I appreciate the hard work and versatility.
> 
> When integrating this for a mobile PWA, I noticed two translation strings are missing which I've added to this PR. I hope you find this useful, too.
> 
> Thanks,
> Leo
Thanks for the initial review @Acconut!
=> Add missing translations to de_DE

packages/@uppy/companion/src/server/controllers/s3.js, packages/@uppy/companion/src/server/middlewares.js, packages/@uppy/companion/src/server/s3-client.js
for `createPresignedPost`
fixes #4809
=> @uppy/companion: fix accelerated endpoints for presigned POST 

packages/@uppy/companion-client/src/RequestClient.js, packages/@uppy/companion/src/server/Uploader.js
fixes #4815
also improve error logging when canceling
don't close socket when pausing:
because it prevented us from canceling an upload that is paused
note that we here sacrifice the ability to pause uploads and have other uploads take over the paused upload's rate limit queue spot.
this is sacrificed because we will soon remove the ability to pause/resume uploads anyways
=> @uppy/companion: fix double tus uploads

examples/custom-provider/client/MyCustomProvider.jsx, packages/@uppy/aws-s3-multipart/src/index.js, packages/@uppy/aws-s3/src/index.js, packages/@uppy/core/src/Uppy.js, packages/@uppy/provider-views/src/ProviderView/ProviderView.jsx, packages/@uppy/provider-views/src/SearchProviderView/SearchProviderView.jsx, packages/@uppy/provider-views/src/View.js, packages/@uppy/tus/src/index.js, packages/@uppy/url/src/Url.jsx, packages/@uppy/xhr-upload/src/index.js
for some reason, only when testing locally using VITE_COMPANION_URL=https://api2.transloadit.com/companion only we get this error...
i'm thinking for some reason, the remote file gets serialized into state and then de-serialized again causing remote.requestClient to be gone
so I solve it by instead storing the request clients in Uppy
fixes #4791
=> fix uploadRemoteFile undefined

packages/@uppy/core/src/BasePlugin.ts, packages/@uppy/core/src/UIPlugin.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/core/src/index.ts
I noticed some types were incomplete/incorrect while working on https://github.com/transloadit/uppy/pull/4839.
=> @uppy/core: fix types

.eslintrc.js
Those should be linted as `.ts` files, except with JSX support.
=> meta: fix linting of `.tsx` files

packages/@uppy/locales/src/hr_HR.ts
The "Save" button when in ImageEditor mode is not properly translated because of the missing "save" property in locale.
Before: 
AFter:
=> fix "Save" button translation in hr_HR.ts

private/js2ts/index.mjs
We were missing the `paths` property in `compilerOptions`, resulting in TS being unable to resolve local dependencies.
=> meta: fix `js2ts` script

packages/@uppy/companion/package.json, packages/@uppy/tus/package.json, yarn.lock
=> Upgrade tus-js-client

packages/@uppy/compressor/package.json, packages/@uppy/core/package.json, packages/@uppy/core/src/Restricter.ts, packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/dashboard/package.json, packages/@uppy/golden-retriever/package.json, packages/@uppy/status-bar/package.json, yarn.lock
More recent versions are written in TS, so we can rely on upstream types.
Refs: https://github.com/transloadit/monolib/comapare/1d649aa77fbabed471420f73f9433954452743bd...HEAD
Refs: https://github.com/transloadit/monolib/commits/main/packages/prettier-bytes
=> upgrade `@transloadit/prettier-bytes`

packages/@uppy/dashboard/src/components/FileItem/index.scss
Closes #4835
I'm not sure why this CSS was there. `xhr-upload` has a `bundle` option, which sends all the files in one request instead of multiple. For this option it makes sense to hide the individual file remove button, because you can't alter a concatenated upload. Removing this CSS however doesn't change that, when `bundle` is `true` the button is still hidden on files, but now it does show the button when the option is `false`.
=> @uppy/xhr-upload: show remove button

packages/@uppy/core/types/index.d.ts
We export it here:
https://github.com/transloadit/uppy/blob/c48aa82a8a68392f5c5f09d866deebd8806fe8a6/packages/@uppy/core/src/index.ts#L5
But until then, it was missing from the types, see https://community.transloadit.com/t/module-uppy-core-has-no-exported-member-debuglogger/16930/2.
=> @uppy/core: add `debugLogger` as export in manual types

package.json, packages/@uppy/angular/.gitignore, packages/@uppy/companion/.gitignore, packages/@uppy/svelte/.gitignore, packages/@uppy/vue/.gitignore
Turns out that `-e` is completely ignored when using `-X`, so we had to be a bit more clever to make the clean command delete all ignored files but `node_modules/` folder – the trick we're using is to mark all the content of `node_modules/` as trackable, run `git clean -X`, and restore the `.gitignore` file.
=> meta: fix `yarn build:clean`

private/locale-pack/index.mjs
As we are starting to refactor packages to TS, we can no longer load the locale from the source file, we need to import the output JS file.
Refs: https://github.com/transloadit/uppy/actions/runs/7545261719/job/20540469630
=> meta: generate locale pack from output file

.github/workflows/output-watcher.yml, packages/@uppy/core/src/Uppy.ts
The idea is that it should help review TS refactor PRs, as it might be easier to spot breaking changes from the output (ideally TS refactor PRs should produce no changes at all)
=> meta: add `output-watcher` GHA to help check output diff

packages/@uppy/core/src/BasePlugin.ts, packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/status-bar/src/StatusBar.tsx
As suggested by https://github.com/transloadit/uppy/pull/4883#discussion_r1462917831
=> @uppy/core: add utility type to help define plugin option types

.prettierrc.js, package.json
It was getting a bit annoying that my editor constantly formats it differently on files that have already been formatted before through git hooks.
=> meta: put experimental ternaries in .prettierrc.js

packages/@uppy/companion-client/src/Provider.ts, packages/@uppy/core/src/BasePlugin.ts, packages/@uppy/image-editor/src/Editor.tsx, packages/@uppy/image-editor/src/ImageEditor.tsx, packages/@uppy/xhr-upload/src/index.test.ts, packages/@uppy/xhr-upload/src/index.ts
1. Removes `[key: string]: unknown` from `PluginOptions` – that was probably added by mistake
2. Ensures the `AlwaysDefinedKeys` are one of the optional key of the `Opts` type. That should help catch instances where we defined by mistake a default value for a mandatory option, or we mistakenly mark as required an option meant to be optional.
3. Fix the resulting type errors in the codebase and tests.
=> meta: validate `defaultOptions` for stricter option types

packages/@uppy/companion/src/server/controllers/url.js, packages/@uppy/companion/src/server/helpers/request.js, packages/@uppy/companion/test/__tests__/http-agent.js
example: on our server, the url `https://mifi-testing.s3.us-east-1.amazonaws.com/` resolves to:
```js
[
{ address: '52.216.113.54', family: 4 },
{ address: '54.231.199.162', family: 4 },
{ address: '52.216.29.232', family: 4 },
{ address: '54.231.196.10', family: 4 },
{ address: '54.231.168.26', family: 4 },
{ address: '54.231.172.98', family: 4 },
{ address: '54.231.139.34', family: 4 },
{ address: '52.217.226.234', family: 4 },
{ address: '64:ff9b::34d8:1de8', family: 6 },
{ address: '64:ff9b::36e7:c40a', family: 6 },
{ address: '64:ff9b::36e7:a81a', family: 6 },
{ address: '64:ff9b::36e7:ac62', family: 6 },
{ address: '64:ff9b::36e7:8b22', family: 6 },
{ address: '64:ff9b::34d9:e2ea', family: 6 },
{ address: '64:ff9b::34d8:7136', family: 6 },
{ address: '64:ff9b::36e7:c7a2', family: 6 …
```
=> Fix companion dns and allow redirects from http->https again

packages/@uppy/transloadit/src/index.js, packages/@uppy/transloadit/types/index.d.ts, packages/@uppy/transloadit/types/index.test-d.ts
This adds an option `clientName` which, if present, will be appended to the `Transloadit-Client` header. The idea is that this can be used to add information about which client application created an Assembly. For example, it is helpful to know whether an Assembly was created by the Uppy dashboard on page A or page B.
=> @uppy/transloadit: Add option for client name

packages/@uppy/companion-client/src/Provider.ts, packages/@uppy/companion-client/src/RequestClient.ts, packages/@uppy/companion-client/src/SearchProvider.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/core/src/index.ts, packages/@uppy/utils/package.json, packages/@uppy/utils/src/CompanionClientProvider.ts, packages/@uppy/utils/src/CompanionFile.ts
In preparation for https://github.com/transloadit/uppy/pull/4919
=> @uppy/companion-client: type changes for provider-views

.eslintrc.js, .yarn/patches/tus-js-client-npm-3.1.3-dc57874d23.patch, package.json, packages/@uppy/companion-client/src/RequestClient.ts, packages/@uppy/companion-client/src/Socket.ts, packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/image-editor/src/Editor.tsx, packages/@uppy/image-editor/src/ImageEditor.tsx, packages/@uppy/image-editor/src/utils/limitCropboxMovementOnMove.ts, packages/@uppy/image-editor/src/utils/limitCropboxMovementOnResize.ts, packages/@uppy/status-bar/src/Components.tsx, packages/@uppy/status-bar/src/StatusBar.tsx, packages/@uppy/status-bar/src/calculateProcessingProgress.ts, packages/@uppy/tus/src/getFingerprint.ts, packages/@uppy/tus/src/index.ts, packages/@uppy/utils/src/getDroppedFiles/utils/webkitGetAsEntryApi/index.ts, packages/@uppy/xhr-upload/src/index.test.ts, yarn.lock
Type assertions are not inherently bad, we need them in some places. We should still avoid using them when we can, I try to remove all that looked like could be avoided in this PR, the one that stay are those that are due to either TS unable to infer the correct types, or cases where there's nothing better than throwing a `TypeError` on runtime.
The `tus-js-client` patch was also sent upstream: https://github.com/tus/tus-js-client/pull/670
=> meta: disable `@typescript-eslint/no-non-null-assertion` lint rule

packages/@uppy/dashboard/src/Dashboard.jsx, packages/@uppy/dashboard/src/components/EditorPanel.jsx
Fixes #4878, implicitly fixes #4442.
Implements "file list ⟷ metaEditor ⟷ imageEditor" state machine we discussed in Slack.
Tested with all combinations of:
- `.use(ImageEditor, { target: Dashboard })` present/absent
- `autoOpenFileEditor` true/false
- `metaFields` present/absent
=> MetaEditor + ImageEditor - new state machine logic

packages/@uppy/utils/src/EventManager.js, packages/@uppy/utils/src/EventManager.ts
Users may not update all their Uppy packages at once, moving the `EventManager` class to core ended up breaking some users. Moving the class was necessary for the TS transition, but we could live with some duplicated code until we release 4.0.0.
This PR re-introduce the `EventManager.js` file as it was before the TS transition, it’s only there for backward compatibility. Uppy plugins should keep referencing the one in `@uppy/core`.
=> @uppy/utils: remove EventManager circular reference

packages/@uppy/audio/src/Audio.tsx, packages/@uppy/core/src/UIPlugin.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/image-editor/src/ImageEditor.tsx, packages/@uppy/status-bar/src/StatusBarOptions.ts, packages/@uppy/utils/src/findDOMElement.ts
=> Improve findDOMElement and UIPluginOptions types

packages/@uppy/audio/src/Audio.tsx, packages/@uppy/core/src/Restricter.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/utils/src/UppyFile.ts, packages/@uppy/utils/src/generateFileID.ts, packages/@uppy/utils/src/getFileType.ts
Extracted from https://github.com/transloadit/uppy/pull/4919
=> Introduce `ValidateableFile` & move `MinimalRequiredUppyFile` into utils

packages/@uppy/core/src/UIPlugin.ts
Using `instanceof` is problematic as it won't detect plugins from different Uppy distributions. Whether we should support that use-case is certainly debatable – having more than one Uppy distribution is good indication that there's a bug in the build chain – but it seems useful to only produce a warning rather than failing hard.
=> @uppy/core: fix plugin detection

babel.config.js, bin/build-lib.js, packages/@uppy/dashboard/src/components/AddFiles.jsx, packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.jsx
Refs: https://github.com/transloadit/uppy/pull/4919/files#r1500434342
=> meta: add support for `Fragment` short syntax

e2e/cypress/integration/dashboard-transloadit.spec.ts
has been failing 3 times in an hour:
https://github.com/transloadit/uppy/actions/runs/8029895005/job/21936709051 https://github.com/transloadit/uppy/actions/runs/8029682841/job/21936256011 https://github.com/transloadit/uppy/actions/runs/8029645114/job/21936175459
cy:command ✔  get	.uppy-StatusBar-actionBtn--upload
cy:command ✔  click
cy:fetch ➟  (createAssemblies) POST ***/assemblies
Status: 200
cy:xhr ➟  POST https://api2-baarn.transloadit.com/resumable/files/
Status: 201
cy:xhr ➟  POST https://api2-baarn.transloadit.com/resumable/files/
cy:command ✔  window
cy:command ✘  assert	expected **1** to equal **0**
=> fix e2e flake

packages/@uppy/image-editor/src/ImageEditor.tsx
Fixes #4956
Added by mistake in #4880
=> @uppy/image-editor: remove default target

packages/@uppy/xhr-upload/src/index.ts
=> @uppy/xhr-upload: fix getResponseData regression

packages/@uppy/box/src/Box.jsx, packages/@uppy/companion-client/src/Provider.ts, packages/@uppy/companion-client/src/getAllowedHosts.ts, packages/@uppy/companion-client/src/index.ts, packages/@uppy/dropbox/src/Dropbox.jsx, packages/@uppy/facebook/src/Facebook.jsx, packages/@uppy/google-drive/src/GoogleDrive.jsx, packages/@uppy/instagram/src/Instagram.jsx, packages/@uppy/onedrive/src/OneDrive.jsx, packages/@uppy/unsplash/src/Unsplash.jsx, packages/@uppy/zoom/src/Zoom.jsx
In preparation to move companion plugins to TS. 
This was more or less impossible to type as we put the entire plugin class into `initPlugin` and it puts all kinds of properties on it, a weird pattern regardless of types. There is more duplication this way, but all the companion plugins are completely duplicate already, just the class name, `id`, and `title` are different more or less.
=> Replace Provider.initPlugin with composition

packages/@uppy/tus/src/index.ts, packages/@uppy/utils/src/RateLimitedQueue.test.ts, packages/@uppy/utils/src/RateLimitedQueue.ts
Since we are not doing #4173 for #4764, it's better to have it typed if the code is sticking around for a while.
=> @uppy/utils: migrate RateLimitedQueue to TS

packages/@uppy/utils/src/RateLimitedQueue.ts
The fixed types as we discussed on the Uppy call.
=> @uppy/utils: fix `AbortablePromise` type

packages/@uppy/core/src/BasePlugin.ts, packages/@uppy/core/src/UIPlugin.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/core/src/index.ts
This aggregate the changes from https://github.com/transloadit/uppy/pull/4989, https://github.com/transloadit/uppy/pull/4987, and https://github.com/transloadit/uppy/pull/4984.
=> @uppy/core: various type fixes

.yarn/patches/resize-observer-polyfill-npm-1.5.1-603120e8a0.patch, package.json, yarn.lock
The upstream package is defining its own types which are incompatible with TS built-in DOM types.
There's already an open PR to fix the problem upstream (https://github.com/que-etc/resize-observer-polyfill/pull/102), but it looks like it's not going to be merged.
=> meta: fix `resize-observer-polyfill` types

packages/@uppy/aws-s3-multipart/src/createSignedURL.js, packages/@uppy/aws-s3-multipart/src/createSignedURL.test.js
This fixes #5005 .
AWS SDK will escape all characters including "!'()*" such as not escaped by `encodeURI/encodeURIComponent` .
This is aimed according to RFC 3986.
https://datatracker.ietf.org/doc/html/rfc3986
Those are escaped by AWS SDK's implementation, but it is complicated, so I investigated what code escapes that:
S3 presigner using command (for example, UploadPartCommand)
=> Ser(Request serializer) Middleware of UploadPartCommand
=> se_UploadPartCommand
=> resolvedPath
=> extended-uri-component
https://github.com/smithy-lang/smithy-typescript/blob/main/packages/smithy-client/src/extended-encode-uri-component.ts
@aws/signature-v4 (now deprecated, moved to @smithy/signature-v4)
SignatureV4
=> getCanonicalQuery
https://github.com/smithy-lang/smithy-typescript/blob/main/packages/signat …
=> @uppy/aws-s3-multipart: Fix escaping issue with client signed request

packages/@uppy/audio/src/Audio.tsx, packages/@uppy/audio/src/index.ts, packages/@uppy/dashboard/src/Dashboard.tsx, packages/@uppy/dashboard/src/index.ts, packages/@uppy/drop-target/src/index.ts, packages/@uppy/webcam/src/Webcam.tsx, packages/@uppy/webcam/src/index.ts
We forgot to expose the user-facing options on some plugins. This PR fixes that.
=> add missing exports

packages/@uppy/status-bar/src/StatusBar.tsx
It seems to be required by newer versions of TS.
=> @uppy/status-bar: refine type of private variables

packages/@uppy/drag-drop/src/DragDrop.tsx
It seems to be required by newer versions of TS.
=> @uppy/drag-drop: refine type of private variables

packages/@uppy/aws-s3-multipart/src/index.ts
It's not invalid to initialize that plugin with just the default values.
=> @uppy/aws-s3-multipart: mark `opts` as optional

packages/@uppy/angular/projects/uppy/angular/package.json
Fixes: https://github.com/transloadit/uppy/issues/4893#issuecomment-2045923954
=> @uppy/angular: fix Angular version requirement in peerDeps

packages/@uppy/core/src/BasePlugin.ts
c48aa82a8a68392f5c5f09d866deebd8806fe8a6 introduced that condition, but it looks like a bug, we don't want to skip the `setState` call otherwise the plugin UI will not get re-rendered.
Fixes: https://github.com/transloadit/uppy/issues/5071
=> @uppy/core: fix `setOptions` not re-rendereing plugin UI

.github/dependabot.yml
We have a warning about using Node.js 16 on our GHA, it seems like something we could easily use automation to keep up-to-date with that.
=> meta: add `dependabot.yml` to keep GHA up-to-date

packages/@uppy/dashboard/src/utils/getFileTypeIcon.tsx
Adds missing application/x-zip-compress mime type in the array of archive type in `getFileTypeIcon.tsx` file.
=> @uppy/dashboard: add missing x-zip-compress archive type

packages/@uppy/utils/package.json, packages/@uppy/utils/src/fetcher.ts
Taken out of #4745.
Tried to write tests but unsuccessful:
- `XMLHttpRequest` does not work in Node.js so testing without mocking not possible
- Tried [`xhr-mock`](https://www.npmjs.com/package/xhr-mock) but it didn't work at all for me
- Tried [`mock-xmlhttprequest`](https://www.npmjs.com/package/mock-xmlhttprequest) but only `newServer` worked, which wasn't flexible enough, and the more flexible `newMockXhr` didn't work for me.
However once I add this to `xhr-upload`, we can indirectly test it in e2e because all requests will be made with `fetcher` then.
=> @uppy/utils: add fetcher

packages/@uppy/form/src/index.ts
Closes #5057 
`submitOnSuccess` and `triggerUploadOnSubmit` is a valid combination for a use case where you want Uppy to start uploading if the user manually clicks submit inside the form but also submit the form after Uppy has successfully uploaded files (clicking upload instead of submit). Because we use `form.requestSubmit()` the submit only happens if form validations pass.
The problem however is that `submitOnSuccess` triggers the `submit` event listener which we use to `triggerUploadOnSubmit`, which makes Uppy start uploading after it just finished uploading, causing an infinite loop.
**Solution**
Manually setting a `completed` boolean based on `upload` (start) and `upload-success`.
It doesn't feel right but I don't think we can do much better without redesigning uppy internals. …
=> @uppy/form: fix `submitOnSuccess` and `triggerUploadOnSubmit` combination

packages/@uppy/provider-views/src/Browser.tsx
as discussed with @lakesare in #5050
currently the loadedXFiles i18n key is not in use at all
I don't know where/when it got lost in translation
=> bring back "loaded X files..."

packages/@uppy/image-editor/src/Editor.tsx
Trying to upgrade our deps reveals a new lint errors: we should be applying the label to the `<button>` elements, not the `<label>` ones.
=> @uppy/image-editor: fix label definitions

packages/@uppy/utils/src/dataURItoBlob.ts, packages/@uppy/utils/src/dataURItoFile.ts
As its name implies, it returns a `File`.
=> @uppy/utils: improve return type of `dataURItoFile`

packages/@uppy/core/src/Restricter.ts, packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/core/src/Uppy.ts
Fixes: https://github.com/transloadit/uppy/issues/5115
The code isn't pretty and in hindsight I regret making `Restricter` a class rather than just a series of functions outside of core. But it is what it is now.
=> @uppy/core: reference updated i18n in Restricter

packages/@uppy/core/src/Uppy.ts, packages/@uppy/provider-views/src/ProviderView/ProviderView.tsx, packages/@uppy/utils/src/generateFileID.ts
=> @uppy/core: add instance ID to generated IDs

packages/@uppy/companion/src/server/helpers/request.js
Otherwise we get a TypeError when `requestUrl` is a `URL`
=> @uppy/companion: coerce `requestUrl` to a string

packages/@uppy/xhr-upload/src/index.ts
Closes https://github.com/transloadit/uppy/issues/5131
Accidentally introduced a breaking change. I thought sending back a `url` is mandatory and that's why we have things like `getResponseData` and `responseUrlFieldName` so you can get it in a flexible way.  But it seems it wasn't needed and people didn't do it and now their uploads stopped working.
=> @uppy/xhr-upload: do not throw when res is missing url

packages/@uppy/core/src/Uppy.ts
Only one loop instead of many. Ideally we'd have better state management in general, but that's a bigger thing. Tiny improvement for now.
=> @uppy/core: make getObjectOfFilesPerState more efficient

README.md, docs/guides/migration-guides.md, docs/presets/remote-sources.mdx, docs/sources/audio.mdx, docs/sources/companion-plugins/box.mdx, docs/sources/companion-plugins/dropbox.mdx, docs/sources/companion-plugins/facebook.mdx, docs/sources/companion-plugins/google-drive.mdx, docs/sources/companion-plugins/instagram.mdx, docs/sources/companion-plugins/onedrive.mdx, docs/sources/companion-plugins/unsplash.mdx, docs/sources/companion-plugins/url.mdx, docs/sources/companion-plugins/zoom.mdx, docs/sources/screen-capture.mdx, docs/sources/webcam.mdx, docs/user-interfaces/elements/drop-target.mdx, docs/user-interfaces/elements/image-editor.mdx, docs/user-interfaces/elements/status-bar.mdx, packages/@uppy/image-editor/README.md
Ref: https://github.com/transloadit/uppy/pull/4343
=> Remove `target` option from examples and document consistently

docs/framework-integrations/react.mdx, docs/framework-integrations/svelte.mdx, docs/framework-integrations/vue.mdx
Closes #5021
Should we also remove `plugins` prop altogether (see issue)? It's not even documented as an API option 🤔
=> Remove redundant `plugins` prop from examples

packages/@uppy/image-editor/src/Editor.tsx
Due to removal of `"aria-label='<tooltip-text>'"` from control button's label the tooltip has stopped working. PR ref - https://github.com/transloadit/uppy/pull/5111
Based on package being used for tooltips https://www.npmjs.com/package/microtip#usage, there should be following attributes for the tooltip to work:-
1. aria-label 
2. data-microtip-position 
3. role="tooltip"
So, in this PR I have removed the label element and moved all 3 attributes to button element now
=> @uppy/image-editor: fix tooltips

packages/@uppy/companion/src/server/socket.js
to prevent companion from crashing with RangeError: Max payload size exceeded
=> handle ws error

docs/README.md, docs/sources/companion-plugins/box.mdx, docs/sources/companion-plugins/zoom.mdx
fixes #2453
This PR:
- adds documentation for Zoom
- updates wording for Box to match what's written on their site at the moment
- in the Readme.md, adds a more clear direction towards docs in uppy.io (https://github.com/transloadit/uppy.io/pull/243)
=> Improve provider docs: Box & Zoom

bin/companion.sh, docs/companion.md, package.json, yarn.lock
All Node.js versions have the `--watch` built-in nowdays.
=> meta: remove `nodemon` from the deps

packages/@uppy/companion/package.json, packages/@uppy/companion/src/standalone/index.js, yarn.lock
That module is not doing anything special, IMO using it puts more maintenance burden on us than implementing it ourselves.
=> @uppy/companion: remove dependency on `express-request-id`

packages/@uppy/aws-s3/src/index.ts
=> encode uploadid

packages/@uppy/tus/src/index.ts
Conditionally calling the headers argument was missing from getCompanionClientArgs.
=> @uppy/tus: fix no headers passed to companion if argument is a function

docs/uploader/xhr.mdx, packages/@uppy/xhr-upload/src/index.ts
We might want to revert that in `4.x` branch.
Fixes: https://github.com/transloadit/uppy/issues/5165
=> @uppy/xhr-upload: fix regression for lowercase HTTP methods

packages/@uppy/aws-s3-multipart/src/index.test.ts, packages/@uppy/aws-s3-multipart/src/index.ts
=> @uppy/aws-s3: resolve all headers on response

e2e/cypress/integration/dashboard-transloadit.spec.ts, packages/@uppy/transloadit/src/Client.ts, packages/@uppy/transloadit/src/index.ts
- If you haven't started the upload yet, this is unneeded.
- If you did start the upload and you try to `removeFile`(s), Uppy throws an error that `individualCancellation` is not supported
- If you remove files after the upload is complete, the API returns a `404` for `/update_assemblies` (which was a bug in itself, trying to call this after the assembly is done).
Internally it was also brought up that `/update_assemblies` is not something we want to publicly expose.
=> @uppy/transloadit: remove `updateNumberOfFilesInAssembly`

examples/custom-provider/client/MyCustomProvider.jsx, packages/@uppy/box/src/Box.tsx, packages/@uppy/core/src/Uppy.ts, packages/@uppy/dropbox/src/Dropbox.tsx, packages/@uppy/facebook/src/Facebook.tsx, packages/@uppy/google-drive/src/GoogleDrive.tsx, packages/@uppy/instagram/src/Instagram.tsx, packages/@uppy/onedrive/src/OneDrive.tsx, packages/@uppy/provider-views/README.md, packages/@uppy/provider-views/src/ProviderView/ProviderView.tsx, packages/@uppy/provider-views/src/SearchProviderView/SearchProviderView.tsx, packages/@uppy/provider-views/src/View.ts, packages/@uppy/unsplash/src/Unsplash.tsx, packages/@uppy/utils/src/CompanionClientProvider.ts, packages/@uppy/zoom/src/Zoom.tsx
*This is a series of PRs that make the https://github.com/transloadit/uppy/pull/5050 PR smaller*
___
This PR gets rid of `.onFirstRender()` method.
1. The code for `.onFirstRender()` repeats in all provders, the only thing changing is `provider.rootFolderId`
2. In the #5050 PR, we will need `provider.rootFolderId` as a separate entity
3. Having `.onFirstRender()` makes it so that:
- **Dropbox.tsx** depends on code in **ProviderView.tsx** (`.getFolder()`) AND
- **ProviderView.tsx** depends on code in **Dropbox.tsx**  (`.onFirstRender()`)
It's easier to reason about code when the dependency is one-directional.
This _is_ a breaking change, but only for people who implement their own providers.
I checked it locally with all providers:
=> PartialTree - get rid of `.onFirstRender()`

packages/@uppy/core/src/Restricter.ts, packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/core/src/locale.ts
*This is a series of PRs that make the https://github.com/transloadit/uppy/pull/5050 PR smaller*
___
Currently, exceeding the aggregate size of files is reported as `"hi.png exceeds maximum allowed size of 20 MB"`, where `"hi.png"` is the first file that overflows the max allowed size (there might be many files after this first file!).
This PR changes this phrasing to `"You selected 25 MB of files, but maximum allowed size is 20 MB"`.
The former phrasing looks a bit better when we're hovering over greyed-out files, however in #5050 UI we won't have greyed-out files, so we shouldn't worry about that.
The new phrasing makes more sense as an error notification, both in current UI and in #5050 UI.
> [!NOTE] 
> I understand it seems like we should change `"You selected %{size} of files, but …
=> PartialTree - change the `maxTotalFileSize` error

packages/@uppy/core/src/types.test.ts
Ref: #4764
Some tests to make sure types keep working as expected.
=> @uppy/core: add type tests

packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/core/src/Uppy.ts
Found out while working on #5158 that we block `removeFiles` during on upload if `capabilities.individualCancellation` is `false` but we blindly allow it in `clearUploadedFiles`.
=> @uppy/core: check capabilities in clearUploadedFiles

packages/@uppy/webcam/src/CameraScreen.tsx, packages/@uppy/webcam/src/Webcam.tsx
Contrarily to what the TODO says, it's not unused.
=> @uppy/webcam: add missing types for `recordedVideo`

.github/CONTRIBUTING.md, packages/@uppy/companion/package.json
it doesn't work with yarn berry
see discussion in #4682
also document the hotfix release process
=> remove prepublishOnly

docs/guides/migration-guides.md
accidentally introduced here https://github.com/transloadit/uppy/commit/2f21ce99c993b5de50bb2d3a22b49f622b356f41
note the [documentation here](https://github.com/transloadit/uppy/commit/2f21ce99c993b5de50bb2d3a22b49f622b356f41#diff-70afb35b8caaea3e072dc6b386df48ed7a0ebf6649213c6ce7050c535c44cef0) which correctly describes how it should work
=> fix broken commit

packages/@uppy/transloadit/src/Assembly.ts
We have to update the state before we emit otherwise `transloadit:result` doesn't emit the results.
=> @uppy/transloadit: fix transloadit:result event

docs/uploader/aws-s3-multipart.mdx, docs/uploader/tus.mdx, docs/uploader/xhr.mdx
Apparently forgotten after #5011
=> docs: correct allowedMetaFields

packages/@uppy/react/src/Dashboard.ts, packages/@uppy/react/src/DashboardModal.ts, packages/@uppy/react/src/DragDrop.ts, packages/@uppy/react/src/FileInput.ts, packages/@uppy/react/src/ProgressBar.ts, packages/@uppy/react/src/StatusBar.ts
Fixes #5218 
Also removes the confusing `react:` prefix, which serves no purpose and is confusing coming from the vanilla version.
=> @uppy/react: remove `react:` prefix from `id` & allow `id` as a prop

examples/angular-example/src/app/app.component.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/core/src/types.test.ts
`@uppy/tus` and `@uppy/transloadit` return `{}` for the `Body` so it's better to set the default to `Record<string, never>`. `@uppy/xhr-upload` users should define their own `Body` type.
=> @uppy/core: set default for Body generic

packages/@uppy/transloadit/src/index.ts
Ref: #5231 
Current state of Transloadit plugin is a bit hacky, keeping track of the same things in multiple places but some more outdated than others. This has all been fixed and simplified in #5158, but let's backport one more fix into 3.x.
=> @uppy/transloadit: also fix outdated assembly transloadit:result

packages/@uppy/companion/src/server/provider/google/googlephotos/index.js, packages/@uppy/core/src/Restricter.ts, packages/@uppy/core/src/Uppy.ts, packages/@uppy/image-editor/src/ImageEditor.tsx, packages/@uppy/provider-views/src/Breadcrumbs.tsx, packages/@uppy/provider-views/src/Item/components/GridItem.tsx, packages/@uppy/provider-views/src/Item/components/ListItem.tsx, packages/@uppy/provider-views/src/ProviderView/Header.tsx, packages/@uppy/provider-views/src/ProviderView/ProviderView.tsx, packages/@uppy/transloadit/src/Client.ts, packages/@uppy/utils/src/CompanionFile.ts, packages/@uppy/utils/src/UppyFile.ts, packages/@uppy/utils/src/generateFileID.ts
https://github.com/transloadit/uppy/pull/5061#issuecomment-2188717555 also change the type of UppyFile.name, because it can be undefined
=> fix various google photos issues

packages/@uppy/vue/src/dashboard-modal.ts, packages/@uppy/vue/src/dashboard.ts, packages/@uppy/vue/src/drag-drop.ts, packages/@uppy/vue/src/file-input.ts, packages/@uppy/vue/src/progress-bar.ts, packages/@uppy/vue/src/status-bar.ts
We were not passing the right props (the Vue ones instead of the Uppy ones).
=> @uppy/vue: fix passing of `props`

.github/CONTRIBUTING.md
1. Removes
> See above Instagram instructions for setting up a tunnel, but replace instagram with zoom in the URL. Note that you also have to add the OAuth redirect URL to OAuth allow list in the Zoom Oauth app settings or it will not work.
We don't need https for the Zoom integration.
In fact, Zoom is the only provider that actively disallows `https`, at least `https` introduced using `http://redirectmeto.com` (ngrok alternative).
2. Removes 
> Add the following scopes: recording:read, user:read, user_info:read
The scopes are named differently now, and I'm describing the necessary scopes here https://uppy.io/docs/zoom.
3. Removes
> To test recording a meeting, you need to sign up for a Zoom Pro trial (can be cancelled later), for example using their iOS app.
I think that's not possible …
=> CONTRIBUTING.md - remove the Zoom section

packages/@uppy/dashboard/src/Dashboard.tsx
As documented, `null` should not be treated the same as `undefined`.
Fixes: https://github.com/transloadit/uppy/issues/5282
=> @uppy/dashboard: fix handling of `null` for `doneButtonHandler`

docs/guides/migration-guides.md, packages/@uppy/companion/src/server/helpers/utils.js, packages/@uppy/companion/src/server/provider/Provider.js, packages/@uppy/companion/src/server/provider/facebook/index.js, packages/@uppy/companion/src/server/provider/index.js, packages/@uppy/companion/src/server/provider/providerErrors.js, packages/@uppy/companion/test/__tests__/providers.js, packages/@uppy/companion/test/mockserver.js
closes #5245
note that I couldn't get `appsecret_time` working, but it seems to be working without
___
[From Evgenia] In this PR:
- switching from singular requests to [Facebook's batch requests](https://developers.facebook.com/docs/graph-api/batch-requests/#errors)
- implementation of `appsecret_proof` support for Facebook
- decorative: renaming from `StreamHttpJsonError` to `HttpError`
=> implement facebook app secret proof

packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/core/types/index.d.ts
Hello Team,
Even though the clearUploadedFiles in the `uppy/core` method is documented on the doc site, it is not accessible outside.
Upon investigation, I realized it is not present in `index.d.ts`.
This PR adds the method to the `index.d.ts` file along with some unit tests for said method.
=> @uppy/core: add clearUploadedFiles to type definition

packages/@uppy/form/src/index.ts
Closes #5278
Sometime ago I switched our `form.submit()` to `form.requestSubmit()` (https://github.com/transloadit/uppy/pull/4852) so that we first trigger form validation and only submit when there are no errors, while `submit()` always submits.
Unfortunately I didn't realize that unlike `submit()` `requestSubmit()` triggers the `'submit'` event again, which caused a loop. This was fixed in https://github.com/transloadit/uppy/pull/5058. 
Unfortunately I didn't realize again that `requestSubmit()` no longer works after `event.preventDefault()`, which we need for the `triggerUploadOnSubmit` in order to hold off the submit to upload with Uppy. If you also enable `submitOnSuccess`, then once we reach `requestSubmit()` it no longer works because of `preventDefault()`.
AFAIK for these specific …
=> @uppy/form: bring back submit() instead of requestSubmit()

packages/@uppy/companion/src/server/controllers/connect.js
The previous version was creating the opportunity for a TypeError when assumptions on the client request were not met.
=> @uppy/companion: fix TypeError

docs/guides/migration-guides.md, packages/@uppy/companion/package.json
There's a bug with `styleText` util we're using.
=> @uppy/companion: do not list Node.js 20.12 as compatible

packages/@uppy/aws-s3-multipart/src/createSignedURL.test.ts, packages/@uppy/aws-s3-multipart/src/createSignedURL.ts
Using dots in bucket names is discouraged by AWS documentation, but it is still allowed. In order to support such buckets without getting a TLS error, we need to move the bucket name parameter from domain name to URL path.
=> @uppy/aws-s3: fix signing on client for bucket name with dots

docs/guides/migration-guides.md, packages/@uppy/companion-client/src/RequestClient.ts
because it prevented us from canceling an upload that is paused. Note that we here sacrifice the ability to pause uploads and have other uploads take over the paused upload's rate limit queue spot. this is sacrificed because we will soon remove the ability to pause/resume uploads anyways
(cherry picked from commit e4dbe77d2fd8912beebd695d9d7cf80a3ca924d6)
this was cherrypicked from https://github.com/transloadit/uppy/pull/4816#issuecomment-1850147652
=> don't close socket when pausing

packages/@uppy/core/src/index.ts
Common types which should be exported for consumers. Transloadit testing area also needs all of these.
=> @uppy/core: export UppyOptions, UppyFile, Meta, Body

docs/companion.md
Let's recommend against using a regex, for most cases it's not the "right" choice.
=> docs: add note regarding `COMPANION_CLIENT_ORIGINS_REGEX`

docs/sources/companion-plugins/url.mdx
noticed the css import wasn't noted in the docs — and without it, the url plugin looks a bit weird.
=> add css import for url plugin

.eslintrc.js
Namely, it wouldn't catch a missing extension in an import
=> meta: add missing lint rule for `.ts` files

packages/@uppy/xhr-upload/src/index.test.ts, packages/@uppy/xhr-upload/src/index.ts
=> @uppy/xhr-upload: correctly type xhrUpload meta

packages/@uppy/companion/src/server/controllers/send-token.js, packages/@uppy/companion/test/__tests__/callback.js
https://github.com/transloadit/uppy/issues/5334#issuecomment-2228359806
=> Improve error message when `window.opener == null`

packages/@uppy/aws-s3/src/index.ts
Fixes: https://github.com/transloadit/uppy/issues/5352
=> @uppy/aws-s3: only send `PartNumber` and `ETag` in completion request

docs/uploader/xhr.mdx, packages/@uppy/xhr-upload/src/index.test.ts, packages/@uppy/xhr-upload/src/index.ts
Closes #5349
`getResponseData` was deleted for 4.0 as I thought `onAfterResponse` covers the use case as well but you can't modify the response from inside it. I tried altering `onAfterResponse` to allow you to return a body and deprecate the `void` signature with backwards compatibility, but it didn't feel right and `onAfterResponse` is also called after every request, even it it fails. `getResponseData` is only called once after success(full retries).
=> @uppy/xhr-upload: bring back getResponseData

docs/uploader/aws-s3-multipart.mdx, packages/@uppy/aws-s3/src/HTTPCommunicationQueue.ts, packages/@uppy/aws-s3/src/MultipartUploader.ts, packages/@uppy/aws-s3/src/index.test.ts, packages/@uppy/aws-s3/src/index.ts, packages/@uppy/aws-s3/src/utils.ts
Fixes #5347 
As seen in the issue, `new Uppy().use(AwsS3, {})` is causing generic type issues. The problem is the incompatibility between the `Body` generic on `Uppy` and `AwsS3`. It's probably safer to work with the default Body generic in plugins and export a enhanced type for users to implement if they care.
=> @uppy/aws-s3: use default Body generic & export AwsBody

packages/@uppy/status-bar/src/StatusBarUI.tsx
Fixes: https://github.com/transloadit/uppy/issues/5142
=> GoldenRetriever + `hideUploadButton=true`

packages/@uppy/audio/src/PermissionsScreen.tsx, packages/@uppy/webcam/src/PermissionsScreen.tsx, private/dev/index.html
PR accompanying https://github.com/transloadit/uppy.io/pull/266
=> Don't use `<h1>` in Uppy markup

packages/@uppy/dashboard/src/Dashboard.tsx, packages/@uppy/dashboard/src/components/Dashboard.tsx, packages/@uppy/dashboard/src/components/FileItem/Buttons/index.tsx, packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.tsx, packages/@uppy/dashboard/src/components/FileItem/FilePreviewAndLink/index.tsx, packages/@uppy/dashboard/src/components/FileItem/FileProgress/index.tsx, packages/@uppy/dashboard/src/components/FileItem/index.tsx, packages/@uppy/dashboard/src/components/FileList.tsx, packages/@uppy/utils/src/FileProgress.ts
This PR converts selected @uppy/dashboard files to typescript.
This PR also adds back some props that were lost somewhere along the way, bringing back the "shorten/lengthen file names" functionality.
=> Dashboard - convert some files to typescript

packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.tsx, packages/@uppy/dashboard/src/components/FileItem/index.tsx, packages/@uppy/dashboard/src/components/FileList.tsx
Previously it worked because `props.toggleAddFilesPanel(event)` is also truthy 😞 
This was setting `state.showAddFilesPanel` to `event`.
=> `toggleAddFilesPanel()` - make args consistent

packages/@uppy/core/src/Uppy.ts, packages/@uppy/core/src/index.ts, packages/@uppy/store-default/src/index.ts
The current type is too tightly coupled to our implementation of `store-default` while it only matters that you have these methods present. Without this change, we get errors we can't resolve in the Transloadit testing area because we use a custom store there.
Tested that this change works for Transloadit.
=> @uppy/core: fix store option type

packages/@uppy/aws-s3/src/index.ts
Fixes: https://github.com/transloadit/uppy/issues/5358
=> @uppy/aws-s3: improve error when `endpoint` is not provided

packages/@uppy/compressor/src/index.ts
There's a default `quality` of `0.6`, it doesn't make sense to mark it as mandatory.
=> @uppy/compressor: mark `quality` as optional

packages/@uppy/transloadit/src/index.ts
There are no mandatory options, it's kinda silly to force TS users to provide an empty option bag if they're happy with the defaults – or rather want to define the assembly options later.
=> @uppy/transloadit: do not mark `opts` as mandatory

packages/@uppy/dashboard/src/components/AddFiles.tsx, packages/@uppy/drag-drop/src/DragDrop.tsx, packages/@uppy/file-input/src/FileInput.tsx, private/dev/Dashboard.js
This PR passes a string to `accept`, just like its type wants`(property) JSXInternal.HTMLAttributes<HTMLInputElement>.accept?: string | undefined`.
Technically, `accept` was already transforming the array into a string - but that was undocumented behaviour.
=> Transform the `accept` prop into a string everywhere

docs/companion.md, docs/sources/companion-plugins/box.mdx, docs/sources/companion-plugins/dropbox.mdx, docs/sources/companion-plugins/facebook.mdx, docs/sources/companion-plugins/google-drive.mdx, docs/sources/companion-plugins/google-photos.mdx, docs/sources/companion-plugins/instagram.mdx, docs/sources/companion-plugins/onedrive.mdx, docs/sources/companion-plugins/unsplash.mdx, docs/sources/companion-plugins/url.mdx, docs/sources/companion-plugins/zoom.mdx
One of the most requested things in Intercom is how to use hosted Companion. It was "hidden" in `@uppy/transloadit` docs. Now it's in all remote provider docs and in the companion docs itself.
=> docs: make hosted Companion more clear

docs/uppy-core.mdx
it is confusing to people. explain `cancelAll` and `destroy()`.
https://github.com/transloadit/uppy/pull/5159#issuecomment-2254087908
=> improve `cancelAll` and `destroy()` docs

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/server/controllers/preauth.js, packages/@uppy/companion/src/server/controllers/refresh-token.js, packages/@uppy/companion/src/server/middlewares.js, packages/@uppy/companion/src/server/provider/index.js
=> fix code for custom providers

packages/@uppy/transloadit/src/index.ts
there was an assumption that assembly is required and is never undefined even though it is typed as optional and assigned to undefined in onError
=> Fix many lurking undefined errors

e2e/cypress/integration/dashboard-transloadit.spec.ts, packages/@uppy/transloadit/src/index.ts
**Note**: don't merge this before #5399 (or recreate this pr directly onto main)
- fixes https://github.com/transloadit/uppy/issues/5397
- also refactor from promise.then to async/await
- and fix what seems like broken logic with recursive this.#afterUpload call
=> fix issue with allowMultipleUploadBatches

examples/react-native-expo/App.js
https://github.com/transloadit/uppy/pull/5391/files/3212e58ca75afb7fbe83ae26cec56755c2eb84aa#r1703712209
=> examples: remove `useUppy` from React Native example

packages/@uppy/transloadit/src/index.ts
When you use Uppy and allow uploads to start without any files added, which means you want Transloadit to import files, `@uppy/transloadit` currently always sends a DELETE request immediately after starting the assembly.
This is a regression from #5202
=> @uppy/transloadit: fix check if all files have been removed

packages/@uppy/svelte/package.json
Fixes #5406 
https://publint.dev/@uppy/svelte@4.0.0
=> @uppy/svelte: fix exports condition

packages/@uppy/transloadit/src/index.ts
Used often in the Transloadit testing area but the type is missing in Uppy.
=> @uppy/transloadit: add execution_progress to AssemblyResponse type

BUNDLE-README.md, README.md, packages/@uppy/core/src/Uppy.ts, packages/@uppy/core/src/__snapshots__/Uppy.test.ts.snap
=> docs: remove stale reference to plugins page

docs/golden-retriever.mdx
Updated Golden Retriever documentation so that sw.js import works properly. Otherwise service worker throws an error on registration:
```
TypeError: import() is disallowed on ServiceWorkerGlobalScope by the HTML specification.
```
Reported here: https://github.com/transloadit/uppy/issues/5424
=> docs: fix Golden Retriever service worker import

packages/@uppy/react/src/useUppyState.ts
Fixes #5396 
There's a PR for export map in this package, which would fix this, but it's open for more than a year so it's likely not happening.
=> @uppy/react: fix use-sync-external-store import

package.json, packages/@uppy/locales/src/en_US.ts, packages/@uppy/locales/template.ts, private/dev/Dashboard.js, private/dev/package.json, private/locale-pack/index.mjs, yarn.lock
I was wondering why my locale changes don't show up locally. Turns out we use the Uppy CDN bundle in our dev setup with does not have `@uppy/locales`. Then it still didn't work and it turns out the script was broken since the TS migration.
=> Fix locale-pack for en_US

examples/react-example/App.tsx, examples/react-example/main.tsx, packages/@uppy/core/src/UIPlugin.ts, packages/@uppy/dashboard/src/components/PickerPanelContent.tsx
Ref: #3146 
There's a problem with custom UI plugins when working inside React. For instance, when you add `this.type = 'acquirer'` to your plugin, it will automatically render a icon with the title and clicking on it will call your plugin's `render` method. Let's say you have this:
```js
render() {
return <div>Simple TEXT</div>
}
```
This will crash because Preact inside UIPlugin can't render this. Our own plugins are compiled into `h()` calls instead of JSX syntax. This leads to an awkward situation where you either have to write `h()` calls yourself, which is unwieldy, or inside your React app compile this one file with Preact and import that output file in your React file to then `uppy.use()` it.
---
To make it easier for other frameworks to render inside Uppy's Preact UI, we now pass …
=> Pass container to UIPlugin.render for other frameworks

packages/@uppy/svelte/rollup.config.js
Fixes #5442 
We were bundling Svelte internal code, when we also list `svelte` as a peer dependencies. There was also an assumption that Uppy classes would be global, when we should instead import them.
=> @uppy/svelte: fix generated module to not bundle Svelte

docs/uploader/xhr.mdx, packages/@uppy/xhr-upload/src/index.ts
Ref: https://community.transloadit.com/t/how-to-access-the-file-or-file-name-in-xhr-plugin-onbeforerequest/
We also pass the file `onBeforeRequest` for `@uppy/tus`.
=> @uppy/xhr-upload: pass files to onBeforeRequest

docs/uploader/tus.mdx, packages/@uppy/tus/package.json, packages/@uppy/tus/src/index.test.ts, packages/@uppy/tus/src/index.ts, packages/@uppy/utils/src/UppyFile.ts, yarn.lock
=> @uppy/tus: set response from tus-js-client

packages/@uppy/companion/src/server/emitter/redis-emitter.js
it had multiple issues:
- memory leak in removeAllListeners
- eventName === 'error' wasn't consistently handled
I believe the memory leak might have been introduced in #4623
memory leak from prod:
=> Fix redis emitter

packages/@uppy/tus/src/index.ts
Fixes https://github.com/transloadit/uppy/issues/5473.
=> tus: Avoid duplicate `upload-error` event

packages/@uppy/xhr-upload/src/index.ts
=> @uppy/xhr-upload: add response to upload-error callback

packages/@uppy/dashboard/src/Dashboard.tsx, packages/@uppy/dashboard/src/components/AddFiles.tsx, packages/@uppy/drag-drop/src/DragDrop.tsx, packages/@uppy/file-input/src/FileInput.tsx
This PR:
- created a [proper demo](https://github.com/transloadit/uppy/issues/768#issuecomment-2264902758) of the bug `event.target.value = ''` is preventing, added that demo to the comments
- properly type the text input event: we go from `ChangeEvent` to `TargetedEvent<HTMLInputElement, Event>`
- everything else (`target` => `currentTarget`, `null` => `''`) is a consequence of the correct typing
New version is tested in:
Testing consists of:
1) make sure uploading a duplicate file always triggers `onBeforeFileAdded`
2) make sure `currentTarget.files` actually has files
=>  `.handleInputChange()` - use `.currentTarget`; clear the input using `''`

packages/@uppy/dashboard/src/Dashboard.tsx
This PR lays the ground for https://github.com/transloadit/uppy/pull/5377.
This PR:
- adds `trigger` to default options
- groups modal and inline options (decorative change that will ease the diffs later on)
- adds all options that exist to default options - `onDragLeave`, `onDragOver`, `onDrop`, `plugins` (here we're gradually getting rid of `undefined` as a valid value for the option)
___
Only merge after https://github.com/transloadit/uppy/pull/5367.
Before merging, please change base back to the `main` branch.
=> @uppy/dashboard: stylistic changes for plugin options

docs/companion.md, docs/guides/migration-guides.md, packages/@uppy/companion/src/config/companion.js
because it could be a security risk
https://app.intercom.com/a/inbox/qiqpfgjg/inbox/admin/4490996/conversation/26852700017788
=> disallow corsOrigins "*"

packages/@uppy/xhr-upload/src/index.test.ts, packages/@uppy/xhr-upload/src/index.ts
Caught by surprise when looking into #5494 (couldn't reproduce the reported issue)
=> @uppy/xhr-upload: fix stale file references in events

packages/@uppy/companion/src/config/grant.js, packages/@uppy/companion/test/__tests__/provider-manager.js
I've been doing some testing and from what I can see, this is already supported in https://github.com/simov/grant (which companion uses for OAuth2), when enabling the `state` parameter. It seems to be working and it is checking the parameter when redirected back from the provider: https://github.com/simov/grant/blob/61fe48a8dac6aa4ec5764fadff0898b743b85588/lib/flow/oauth2.js#L72So
For future reference:
The whole state parameter is very confusing and it's used for multiple purposes in different contexts. It's mentioned everywhere in [`grant`](https://github.com/simov/grant). There's:
- Dynamic state
- `transport: 'state'`
- `state: true`
(when `state: true`), the `state` parameter that gets passed in the URL is also different from request to request. it can be
- JWT (e.g. …
=> Enable CSRF protection in grant (OAuth2)

packages/@uppy/tus/src/index.ts
`this.resetUploaderReferences(file.id)` causes the xhr object to be reset to empty XMLHttpRequest
This patch fires the `upload-success` event before calling `this.resetUploaderReferences(file.id)`
to test this patch try:
```
uppy.on('upload-success', (file, response) => {
const xhr = response.body.xhr;
console.log('upload-success', xhr.readyState);
// readyState should be `4` which is the DONE state, before this patch it was always `0`
// https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState 
});
```
Related: #5444, #5456
=> @uppy/tus: fix event upload-success response.body.xhr

.eslintrc.js, .github/workflows/linters.yml, package.json
i'm currently getting errors with yarn lint locally, but CI is succeeding. meaning i always have to bypass commit hooks:
> Unable to resolve path to module '@uppy/...'  import/no-unresolved
=> Fix broken lint on CI

docs/framework-integrations/nextjs.mdx
=> Add Next.js docs

.eslintrc.js
that caused a bundle error because i forgot a `.js` in an import, which was only caught by the webpack bundle job.
```
ERROR in ./node_modules/@uppy/provider-views/lib/GooglePicker/GooglePickerView.js 5:0-65
Module not found: Error: Can't resolve '@uppy/core/lib/useUppyState' in '/home/runner/work/uppy/uppy/node_modules/@uppy/provider-views/lib/GooglePicker'
Did you mean 'useUppyState.js'?
```
https://github.com/transloadit/uppy/actions/runs/11855591962/job/33040156550?pr=5443
=> fix missing lint

packages/@uppy/aws-s3/src/index.ts
=> @uppy/aws-s3: console.error instead of throw for missing etag

.github/CONTRIBUTING.md, packages/@uppy/companion-client/src/Provider.ts, packages/@uppy/companion-client/src/getAllowedHosts.test.ts, packages/@uppy/companion-client/src/getAllowedHosts.ts
- escape regex in default companionAllowedHosts
- also fail early if invalid regex supplied
- and add unit tests
=> Fix allowed origins

packages/@uppy/locales/src/fr_FR.ts
Hello, 
This PR adds missing French translations.
=> Add missing French locale entries

packages/@uppy/companion/src/companion.js, packages/@uppy/companion/src/server/controllers/connect.js, packages/@uppy/companion/src/server/controllers/send-token.js, packages/@uppy/companion/src/server/provider/credentials.js, packages/@uppy/companion/src/server/provider/index.js
Closes #5310 
This fixes the Companion side of the issue. Another change is required on the api side.
When the origins don't match the screen ends up with a 404.
=> @uppy/companion: pass fetched origins to window.postMessage()

packages/@uppy/dashboard/src/style.scss, packages/@uppy/webdav/src/Webdav.tsx
=> @uppy/webdav: add plugin icon

packages/@uppy/react/package.json, yarn.lock
=> @uppy/react: allow React 19 as peer dependency

packages/@uppy/tus/src/index.ts
c.f. https://github.com/transloadit/uppy/blob/d6156bb92f0f0ff400a7dbb46bbe375f10421ac1/packages/%40uppy/tus/src/index.ts#L243-L271
Sonarcloud was complaining because we returned a Promise in our onBeforeRequest handler:
https://github.com/owncloud/web/pull/12052#issuecomment-2565281692
=> @uppy/tus: fix onBeforeRequest type

packages/@uppy/utils/src/fetcher.ts, packages/@uppy/xhr-upload/src/index.test.ts, packages/@uppy/xhr-upload/src/index.ts
=> @uppy/xhr-upload: allow custom error message in onAfterResponse

packages/@uppy/status-bar/src/StatusBar.tsx
=> @uppy/status-bar: fix double upload progress

bin/build-css.js
Before
```
├── dist
│   ├── style.css
│   └── style.min.css
```
After
```
├── dist
│   ├── style.css
│   ├── style.d.css.ts
│   ├── style.min.d.css.ts
│   └── style.min.css
```
=> Add types for css files

packages/@uppy/companion/src/server/s3-client.js
fixes https://github.com/transloadit/uppy/pull/5066#issuecomment-2205988098
=> @uppy/companion: fix forcePathStyle boolean conversion

packages/@uppy/aws-s3/src/HTTPCommunicationQueue.ts, packages/@uppy/aws-s3/src/MultipartUploader.ts, packages/@uppy/aws-s3/src/index.test.ts, packages/@uppy/aws-s3/src/index.ts, packages/@uppy/aws-s3/src/utils.ts, packages/@uppy/companion/src/server/controllers/s3.js
Closes #5513 
Closes #5586
Closes #5565 
Closes #5569 
- `uppy.on('upload-success', (file, response) => {})` now correctly has `response.body` populated.
- `uppy.getFile(someId).s3Multipart` is now always populated (previously only for multipart uploads).
- `uppy.getFile(someId).meta` does not contain S3 related data. Use `file.s3Multipart` for that.
=> @uppy/aws-s3: always set S3 meta to UppyFile & include key

examples/custom-provider/server/index.cjs, examples/uppy-with-companion/server/index.js, packages/@uppy/companion/src/server/controllers/get.js, packages/@uppy/companion/src/server/controllers/googlePicker.js, packages/@uppy/companion/src/server/controllers/url.js, packages/@uppy/companion/src/server/helpers/upload.js, packages/@uppy/companion/src/server/helpers/utils.js, packages/@uppy/companion/src/server/provider/error.js, packages/@uppy/companion/src/server/provider/providerErrors.js, packages/@uppy/companion/src/standalone/index.js
when proxying requests
this in order to make it easier to debug when setting up companion/transloadit integration, and lessen support burden on us.
remove outdated `err.status` checks. this was added [7+ years ago](https://github.com/transloadit/uppy/blame/cf18689c1055055fc73a33fb9fe18e1046dfc8e4/packages/%40uppy/companion/src/standalone/index.js#L143) and we now use `got` which doesn't provide err.status
Instead, for any other unhandled proxied HTTP request error responses, be nice and forward the JSON response to the client for easier debugging
=> @uppy/companion: unify http error responses

packages/@uppy/aws-s3/src/HTTPCommunicationQueue.ts
https://github.com/transloadit/uppy/pull/5602#discussion_r1916248098
=> @uppy/aws-s3: remove console.error

packages/@uppy/aws-s3/src/index.test.ts, packages/@uppy/aws-s3/src/index.ts
Fixes https://github.com/transloadit/uppy/issues/5458
Fixed a bug in the `shouldUseMultipart` function where it failed to return the expected result for large file sizes.
For example, a file size of ~70GB incorrectly returned false.
```javascript
const shouldUseMultipart = (size) => (
size >> 10 >> 10 > 100
)
shouldUseMultipart(75161927680) // Output: false
```
This issue was caused by improper use of the bitwise shift operator for size comparison.
Also, added some tests for the `defaultOptions` to ensure reliability and prevent similar issues in the future.
=> @uppy/aws-s3: Fixed default shouldUseMultipart

packages/@uppy/google-drive-picker/src/GoogleDrivePicker.tsx, packages/@uppy/google-drive-picker/src/locale.ts, packages/@uppy/google-photos-picker/src/GooglePhotosPicker.tsx, packages/@uppy/google-photos-picker/src/locale.ts, packages/@uppy/locales/src/en_US.ts, packages/@uppy/provider-views/src/GooglePicker/GooglePickerView.tsx
=> attempt to fix i18n

packages/@uppy/core/src/Uppy.ts, packages/@uppy/google-drive-picker/src/GoogleDrivePicker.tsx, packages/@uppy/google-photos-picker/src/GooglePhotosPicker.tsx, packages/@uppy/provider-views/src/GooglePicker/GooglePickerView.tsx
=> fix google picker i18n

packages/@uppy/utils/src/getSocketHost.test.ts, packages/@uppy/utils/src/getSocketHost.ts
=> @uppy/utils: do not strip www in getSocketHost

examples/custom-provider/server/CustomProvider.cjs, packages/@uppy/companion/src/server/controllers/googlePicker.js, packages/@uppy/companion/src/server/controllers/url.js, packages/@uppy/companion/src/server/helpers/upload.js, packages/@uppy/companion/src/server/provider/Provider.js, packages/@uppy/companion/src/server/provider/box/index.js, packages/@uppy/companion/src/server/provider/dropbox/index.js, packages/@uppy/companion/src/server/provider/facebook/index.js, packages/@uppy/companion/src/server/provider/google/drive/index.js, packages/@uppy/companion/src/server/provider/instagram/graph/index.js, packages/@uppy/companion/src/server/provider/onedrive/index.js, packages/@uppy/companion/src/server/provider/unsplash/index.js, packages/@uppy/companion/src/server/provider/webdav/index.js, packages/@uppy/companion/src/server/provider/zoom/index.js
This PR does 2 things:
[Always get size from stream response headers](https://github.com/transloadit/uppy/commit/3971bbd73fb2896ff1cab9554154569a5d8b7028)  because i don't really think we need a separate HEAD request for it.
**and:**
Remove `size` method from providers that don't have a backup method for getting size (that is better than GET download response header)
assumption: GET response content-length is as good as (or better than) HEAD response content-length,
meaning it is not necessary to call getURLMeta when we already tried the original GET response content-length
this reduces the chance of hitting the race condition where the size of a URL changes between the GET and HEAD requests are sent.
=> @uppy/companion: remove redundant HEAD request for file size 

packages/@uppy/companion/src/server/Uploader.js
=> log when tus uploaded size differs

packages/@uppy/dashboard/src/components/FilePreview.tsx
Closes #5639 
Browsers have subtle differences when which makes it hard to detect a duplicate between a generated file preview and the original file so we simply do not allow drag & drop of the generated file preview.
=> @uppy/dashboard: do not allow drag&drop of file preview

packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/core/src/Uppy.ts
Closes #5669 
Closes #5676 
**Before**
1. Add a file
2. Call `uppy.upload()` but make it fail (set throttling to offline in your browser)
3. Call `uppy.upload()` again but no throttling
4. Events are not fired, endless uploading state.
You must call `retryAll()` instead but it's better DX if you can simply call `upload()` again and let us figure it out.
**After**
`upload()` behaves like `retryAll()` when errors occurred in a backwards compatible way.
**What if an upload fails and you also add a new file?**
Backwards compatible behaviour similar to how it currently works when using the dashboard. In the dashboard you can only click the retry button and once that upload is done you can click upload again to upload the new files.
When a previous upload partially failed, you add a new file, …
=> @uppy/core: make upload() idempotent

packages/@uppy/core/src/Uppy.test.ts, packages/@uppy/core/src/Uppy.ts
This fixes #5694 
**Before** -- 
Add a file
Call uppy.upload() but make it fail (set throttling to offline in your browser)
Call uppy.upload() again but no throttling
Current behavior -- The return value of uppy.upload() has zero 'successful' uploads. Instead we get something like {"successful":[],"failed":[],"uploadID":"b3TigKGvK_EoPjsJz9LU_"}
**After** -- 
onComplete get's called once and correct state returned in upload result.
=> @uppy/core: fix events when retrying with upload()

examples/aws-nodejs/index.js
Fixes #5666
@Murderlon while trying to reproduce and I came across this bug , where uploading a file from the example code provided at `examples/aws-nodejs/public/index.html`
resulted in uploaded files with **undefined_name** in instead of **fileName** in the S3 key as well as no **fileType** present
reference - 
this was because while making the request to /s3/params  to get the signed URL , it parses the fileName and contentType from the request body to append it to the Key 
https://github.com/transloadit/uppy/blob/f877dac7e19d1513695cddc1544bfd590b59a974/examples/aws-nodejs/index.js#L107-L121
but in default case (without the customEndpoint) it's a **GET request** which causes this error as we're trying to parse the fileName and contentType from req body , …
=> @uppy-example/aws-nodejs: fix fileType not present in S3 objects

.github/workflows/e2e.yml
in an attempt to fix the problem where e2e tests are not always being run on main have already enabled for the repo "Require approval for all external contributors: All users that are not a member or owner of this repository and not a member of the transloadit organization will require approval to run workflows."
=> simplify e2e

packages/@uppy/provider-views/src/GooglePicker/googlePicker.ts
When I implemented the plugin initially I assumed that not appending any `w` or `h` parameter to the [URL would give the original resolution](https://developers.google.com/photos/library/guides/access-media-items#base-urls), but that's clearly not the case.
https://community.transloadit.com/t/google-photos-picker-downloads-resized-image/17538
=> Fix google photos picker

packages/@uppy/companion-client/src/Provider.ts
because Box will send "Pendo" event to opener from a different origin before the real event gets sent.
pulled out from #5719 and improved upon. (i've put the cleanup code inside `finally` so that we get a guaranteed clean up in all scenarios)
closes #5719
=> don't reject on incorrect origin

packages/@uppy/components/src/hooks/screencapture.ts, packages/@uppy/screen-capture/src/ScreenCapture.tsx
This PR encorporates changes suggested in #5791 , into screen-capture plugin.
=> useScreenCapture fixes

packages/@uppy/vue/src/headless/context-provider.ts
**To Reproduce:** run `yarn workspace @uppy-example/vue3 run dev`
**Cause :**  The Proxy object isn't an Uppy class instance, so it can't access private fields like #emitter that are only available within the actual class instance.
**Fix** : `markRaw()` prevents Vue from wrapping the Uppy instance in a Proxy
=> @uppy/vue: use markRaw() for uppy class in context provider

package.json
It kept mysteriously deleting `packages/@uppy/companion/node_modules/webdav/dist/node/compat/env.js` turns out it was because of the line `env.*` in `packages/@uppy/companion/.gitignore`
chery picked from 2508068551ef42c6b7492d18702d7bfaa3dbc4e5
closes #5893
=> fix broken `build:clean` on main

.changeset/afraid-cobras-fix.md, packages/@uppy/companion/src/server/socket.js
You can verify it using:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Media API PoC</title>
</head>
<body>
<h1>Media API Cross-Site WebSocket Hijacking PoC</h1>
<script>
let ws = new WebSocket("wss://<url + base path>/api/poc");
ws.onopen = function () {
console.log("WebSocket connection established.");
ws.send("Malformed JSON");
};
</script>
</body>
</html>
```
=> fix the server crashing due a malformed json in websocket message

examples/react/.stackblitzrc, examples/sveltekit/.stackblitzrc, examples/sveltekit/package.json, examples/vue/.stackblitzrc, yarn.lock
StackBlitz examples took **146+ seconds** to start due to heavy dev dependencies
- Eliminate heavy dev deps like `playwright (~200MB)` `@vitest/browser` `vitest`
- Aggressive install flags: `--prefer-offline --reporter=silent --ignore-scripts --no-optional`
- use pnpm 
- Results **React example: 146s → ~25s (83% faster)**
=> Optmize Stackblitz install times

.github/workflows/bundlers.yml, .github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/lockfile_check.yml, .github/workflows/manual-cdn.yml, .github/workflows/release.yml
Reverts transloadit/uppy#5954
because it fails the release
```
/usr/local/bin/yarn cache dir
error Error: Failed to replace env in config: ${NPM_TOKEN}
at /usr/local/lib/node_modules/yarn/lib/cli.js:95453:13
at String.replace (<anonymous>)
at envReplace (/usr/local/lib/node_modules/yarn/lib/cli.js:95448:16)
at Function.normalizeConfig (/usr/local/lib/node_modules/yarn/lib/cli.js:31940:69)
at NpmRegistry.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:31970:34)
at Generator.next (<anonymous>)
at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
info Visit https://yarnpkg.com/en/docs/cli/cache for documentation about this command.
Error: error Error: Failed to replace env in config: ${NPM_TOKEN}
at …
```
=> Revert "build(deps): bump actions/setup-node from 4 to 5"

.changeset/prefer-assembly-ssl-url.md, packages/@uppy/transloadit/src/index.ts
- ensure the final Transloadit status fetch prefers `assembly_ssl_url`
- add a changeset preparing the patch release
- yarn workspace @uppy/transloadit test
=> Use assembly_ssl_url for final status fetch
