src/plugins/Formtag.js
website/_config.yml

Hey Kevin, think this fixed the multipart file uploading.  I switched from using `for i in x` to running `.forEach`.
`document.querySelectorAll` does not return a javascript `Array` object, so they do not have the higher-order function methods like `map, filter, forEach`, so you need to use `[].forEach.call(fields, ...)`
I didn't want to push to master in case I'm missing something. try it out and let me know!

Multipart File Selection Bug

---

src/plugins/Multipart.js

When appending data with the file on Multipart, the key of the parameter was not passed correctly. Thus, description and resize data are not available in the backend.

[fix] Multipart upload

---

src/plugins/Dashboard/StatusBar.js

`Uploading... 1/3 - 20% - (...)` feels like the first of 3 files is uploading (whereas it means that one file is completely uploaded)
This commit changes it to `Uploading... 20% - 1/3 - (...)` to try to make this clearer.

Reorder status bar items order

---

src/core/Utils.js

This is related to #65: the time string is making some "jumps" when it passes from `1m 10s` to `1m 9s`.
This PR adds a leading `0` to all "trailing" units:
`1m 9s` becomes `1m 09s`, but `9s` stays as it is

ETA with leading zeros

---

src/plugins/Informer.js

If the following scenario happens to quickly:
1. Internet Offline (Informer should be shown "forever")
2. Internet Online (Informer should be shown for 3 seconds)
3. Internet Offline (Informer should be shown forever)
The "disappear timeout" of the "2. Internet Online" hides the "3. Internet Offline" (whereas it should be shown forever).
This PR fixes this by storing and clearing the current `timeoutID` on a new event.

Clear Informer timeout before setting a new one

---

Makefile

The `make install` is failing because it is calling `npm run install` instead of `npm install`.
This PR simply fixes this.

Fix `make install` command

---

src/core/Utils.js
src/plugins/Dashboard/ActionBrowseTagline.js
src/plugins/Dashboard/Dashboard.js
src/plugins/Dashboard/FileList.js
src/plugins/Dashboard/Tabs.js
src/plugins/Dashboard/index.js
src/plugins/DragDrop/index.js
src/plugins/Plugin.js

This patch accepts a DOM element in the `target` option for Plugins. It does this by checking for the `.nodeType` property when an object is passed to `this.mount()`. Another way would be to do `object instanceof Node`, but that doesn't work if the target node is in an `<iframe>`.
This needs a few more things:

Accept a DOM element in `target:` option.

---

src/scss/_dashboard.scss

When the page was scrolled down, the modal close button was
invisible (off-screen). This patch sets the close button to `fixed`
positioning so it's always in the same place on the screen
regardless of scroll, just like the modal background.

Fix Dashboard modal close button position.

---

src/plugins/Tus10.js

I needed to set custom headers and although `tus-js-client`, the dependency to make upload can have custom headers, Uppy was not able to.
This PR is one way to solve it for `Tus10` (because plugins does not always use the same way to send http request, hence to custom the headers)
Waiting for your feedback

Merge tus client options with uppy. Hence, enable custom headers support

---

package.json
src/core/Core.js
src/index.js
src/plugins/Dashboard/index.js
src/plugins/Multipart.js
src/plugins/Transloadit/Client.js
src/plugins/Transloadit/Socket.js
src/plugins/Transloadit/index.js
src/plugins/Tus10.js
test/unit/Transloadit.spec.js
test/unit/index.js

This PR contains the very early beginnings of a Transloadit integration.
Currently: When the `core:upload` event is fired, the plugin creates an Assembly with a configurable `templateId`. <strike>Then, it creates a Tus plugin instance (HACK!) and uses it to upload the files to the assembly.
Of course it shouldn't be creating a Tus plugin instance. The Transloadit plugin _could_ extend from Tus, and that should work fairly well. However it's also pretty nice to have them separate and using the Uppy plugin system.</strike> I've implemented it like I described below :point_down: 
One way to make things work as separate plugins that I can think of is adding an `upload` method to Uppy core and allowing plugins to register promise-returning `beforeUpload` and `afterUpload` callbacks that are …

Transloadit plugin, closes #173

---

src/core/Utils.js
src/plugins/Webcam/CameraScreen.js
src/plugins/Webcam/RecordButton.js
src/plugins/Webcam/RecordStartIcon.js
src/plugins/Webcam/RecordStopIcon.js
src/plugins/Webcam/SnapshotButton.js
src/plugins/Webcam/index.js
src/scss/_webcam.scss
src/uppy-base/src/plugins/Webcam.js

In browsers that support it, this patch shows a "Record" button on the webcam screen that will start or stop a video recording. By default, video and audio is recorded—both can be toggled using the new `video` and `audio` boolean options to the `Webcam` plugin.
```js
uppy.use(Webcam, {
audio: false,
video: true
})
```
Polishing to do:
- What to do when `audio: true`, but `video: false`? Or should these options not even be available to the developer, but let the user decide instead through browser permissions?
- Option for preferred format? FF and Chrome both support WebM, I'm not 100% sure on others (would be :100: to test in some more places)
- Actually show the error somewhere that can theoretically occur if `MediaRecorder` is available, but we don't know the format it used.

Implement reading audio+video from Webcam.

---

src/plugins/Dashboard/index.js

When multiple instances are on the page, `document.querySelector` always picks the first dashboard's elements. This patch instead selects the elements belonging to the current dashboard.

Fix dashboard width when multiple instances exist

---

src/core/Core.js
src/plugins/Transloadit/Socket.js
src/plugins/Transloadit/index.js

This PR does two things:
- Add a `core:error` event for when uploads fail, vs. `core:success`
- Make assembly errors from the Transloadit websocket reject the Transloadit plugin postprocessor promise, firing a `core:error` event
This way users can handle errors if they haven't manually called `upload()` (i.e., most of the time).

Pass through errors

---

src/plugins/Transloadit/index.js

Previously the transloadit plugin would just tell the server that it was going to upload however many files are selected, but that may include files that have been uploaded before. The tus plugin would then not upload files that had been uploaded before, so the number of expected files was different than the number of uploaded files, so the assembly would never finish.
This patch only counts files that haven't started uploading yet. This way the transloadit plugin will tell the server to expect the correct number of files.

Transloadit: Fix starting uploads after a previous upload has finished

---

src/scss/_webcam.scss

Takes up the maximum available space while retaining aspect ratio by using css `max-width: 100%; max-height: 100%` on the video element. /cc @nqst 
Before:
After: 
(This example is a bit exaggerated because the image is very high resolution, but who knows, someone might use a 4K webcam someday!)
And on mobile:

Make the webcam video fill the available space as much as possible

---

src/plugins/DragDrop/index.js
src/plugins/Webcam/CameraScreen.js
src/uppy-base/src/plugins/Webcam.js

This patch removes the last few uses of `document.querySelector` that may end up selecting the wrong elements. The only one that actually matters is the one doing autofocus for the `recordButton` in the Webcam plugin. There probably aren't a lot of use cases that require having multiple webcam plugins open at the same time, but now at least the button autofocus will work there lol.
I don't think the `stop` method in the uppy-base Webcam plugin is used at all so I removed all the stuff from there that depended on the result of the `querySelector` call there as well.

Remove the last few potentially buggy uses of `document.querySelector`

---

src/plugins/Tus10.js

This way an upload preprocessor can set the upload endpoint URL for uploads from remote sources as well.

tus: Also use the endpoint from the `file.tus` property in remote uploads

---

src/plugins/Transloadit/Socket.js
src/plugins/Transloadit/index.js

Provides a "low-level" way to access the uploaded file metadata from transloadit. This way you can do:
```js
const filesById = {}
uppy.on('transloadit:upload', (file) => {
filesById[file.id] = file
})
uppy.on('transloadit:result', (step, result) => {
const original = filesById[result.original_id]
const savings = original.size - result.size
const percent = Math.round((savings / original.size) * 1000) / 10
console.log('saved', percent, 'on the size of', original.name)
})
```
I couldn't think of a way yet to associate the uploaded files with the file objects in Uppy's own state, except for comparing some of their properties (name and size, but it wouldn't be 100% reliable), so I've left that as a TODO 🙈

Transloadit: emit an upload event w/ tl data when a file upload is complete

---

src/core/Core.js
src/plugins/Dashboard/index.js
src/plugins/DragDrop/index.js
src/plugins/Dropbox/index.js
src/plugins/FileInput.js
src/plugins/GoogleDrive/index.js
src/plugins/Informer.js
src/plugins/MagicLog.js
src/plugins/MetaData.js
src/plugins/Plugin.js
src/plugins/ProgressBar.js
src/plugins/Webcam/index.js

This patch adds a method `uppy.close()` that "uninstalls" all plugins and removes any handlers Uppy may have attached. This is useful if you've got an SPA and don't want to keep your Uppy instances around forever while switching between client-side views.
The Tus and Multipart plugins already had an `uninstall` method, so they aren't changed here.

Add `Uppy#close` for tearing down an Uppy instance.

---

src/core/Core.js
src/plugins/Tus10.js

This PR adds the option (default `true`) to "auto-retry" uploads when the use is back online.
Only the uploads already started, not completed and not paused are retried.

Tus10 auto-retry the upload when back online

---

src/core/Core.js
src/core/Utils.js

I can't see any downsides here personally, `createObjectURL` has
wide support (IE10+) and is significantly faster. Without this,
on every state update the browser needs to re-parse the base64
encoded preview, which can lag the Uppy UI to a crawl.
This also seems to fix our issues with the additional requests in the network tab in devtools, I think it only does that for data URLs and not for "network" urls (`http:`, `file:`, `blob:`, etc)

Enable @arturi's Object URL preview thumbnail code

---

src/plugins/Transloadit/index.js

Results that aren't related to an uploaded file will just get a `localId == null`.

Transloadit: fix receiving results not associated with an uploaded file, closes #200

---

src/core/Utils.js
src/plugins/Multipart.js
src/plugins/Tus10.js

This is a fix for [#160](https://github.com/transloadit/uppy/issues/160). It enables Multipart uploads for remote files (e.g Google drive files, etc). @goto-bus-stop do you mind reviewing this?

feature: add support for remote multipart uploads #160

---

src/plugins/Transloadit/index.js

Transloadit: Use the `tus_upload_url` to link results with their input files.

---

src/core/Utils.js
src/plugins/Dashboard/index.js

The "total" ETA shown in the dashboard was inaccurate when multiple
files were being uploaded, because the ETA for multiple simultaneous
uploads were added together to produce the total ETA.
This patch changes the ETA logic to use the total upload speed and
the total amount of bytes remaining to compute the ETA.

Fix ETA when multiple files are being uploaded, closes #188.

---

package.json
src/plugins/Plugin.js

Some more work that was already mostly done by Artur, but
I'd really like to have this in so I'm opening a PR for it :)
I tweaked it a little so it eagerly creates the `nanoraf` instance
when the DOM tree is first mounted. That's a bit simpler than
checking if we need to create an instance in the `update()`
handler, I think.
This speeds up the UI a ton by not reconciling every time if state
is updated frequently. For example, when adding 20 files at once,
previously the UI would reconcile after adding each file, which took
a few ms each time. Especially on a not-supercomputer that could
easily hang the UI for a second or more.
This way the UI reconciliation is sort of detached from the state
updates, and only reconciles up to 60 times per second. In the bulk file
adding case, it only …

Use nanoraf

---

src/core/Core.js
src/core/Utils.js

Now that thumbnail generation is synchronous using URL.createObjectURL,
we can set the thumbnail URL on the file object immediately. This saves
a state update, since `addThumbnail` previously would also trigger a
state update. That used to make sense, because thumbnails were generated
async using a FileReader, but it's not necessary anymore.
It's currently also good for perf because this means morphdom isn't run twice
for each file, but it won't matter much if we start using nanoraf.

Prevent duplicate state update when setting thumbnail

---

src/plugins/FileInput.js
test/unit/index.js
test/unit/plugins/FileInput.spec.js

Allow a configurable input name in the FileInput plugin with a default of `files[]`. This functionality matches the Multipart plugin.
Add basic unit tests for `inputName` FileInput constructor option.

Allow configurable FileInput input name

---

src/plugins/Dashboard/FileCard.js
src/plugins/Dashboard/FileItem.js
src/plugins/Dashboard/getFileTypeIcon.js
src/scss/_dashboard.scss

Originally suggested by @nqst and needed to make sure source icon (the one that’s showing where the file is coming from, Dropbox or Google Drive) is visible. As well as possibly just make the UI nicer.
Design:
Current reality (notice excess borders have also been removed):

[WIP] Improve the look of FileItem component and file type icons

---

src/core/Core.js
src/core/Utils.js
src/plugins/Dashboard/Dashboard.js
src/plugins/Dashboard/StatusBar.js
src/plugins/Dashboard/index.js
src/plugins/Multipart.js
src/plugins/Transloadit/index.js
src/plugins/Tus10.js
src/scss/_dashboard.scss

This PR now does a few different things in order to make the progress bar show stuff from pre and postprocessors fairly accurately:
---
While working on the Transloadit plugin I changed the way uploads are
started. Now, uploads go through a kind of "pipeline", where plugins get a
chance to pre- and postprocess uploaded files. However, this pipeline
didn't take into account that multiple upload "jobs" may be started at
different times--it assumed that you'd only call `upload()` once. Each
plugin (pre, upload, and post) found the relevant files for the job on
its own, which could get out of sync. The Transloadit plugin didn't
support uploading to different assemblies simultaneously at all.
This patch fixes that by moving the files-to-upload finding into the
`upload()` method, and passing …

Add progress API & display for pre- and postprocessors

---

src/core/Core.js
src/plugins/Dashboard/Dashboard.js
src/plugins/Dashboard/StatusBar.js
src/plugins/Transloadit/index.js
src/scss/_dashboard.scss

When an upload fails in a way that causes `upload()` to reject, the error is stored in the state and displayed in the StatusBar w/ a red background. When a new upload is started, the error state is cleared.

Show fatal upload errors in the dashboard StatusBar

---

src/plugins/Multipart.js

This adds a `headers` option that takes an Object. Key/value pairs
are added as HTTP headers on each upload request.

multipart: Add `headers` option, fixes #159.

---

src/plugins/StatusBar/StatusBar.js

This patch fixes the width of the progress bar when a preprocessing or postprocessing plugin emits determinate progress updates (i.e. with a `value`).

statusbar: Fixes for determinate processing progress updates.

---

src/core/Core.js

This fixes an issue with the upload ETA sometimes being `NaN`. These
properties would be undefined when some files did not yet emit progress
events, blowing up the ETA calculation.

core: set bytesUploaded/bytesTotal as soon as the file is added

---

examples/bundled-example/index.html
examples/bundled-example/main.js
package-lock.json
package.json
src/core/Core.js
src/core/Utils.js
src/plugins/Dashboard/index.js
src/plugins/DragDrop/index.js
src/plugins/FileInput.js
src/plugins/MetaData.js
src/plugins/Plugin.js

This PR adds support for extracting metadata from `<form>` elements.
This was asked #153 and came up elsewhere too, I believe. You can use
it like this:
```html
<form class="MyForm" action="/">
<input type="file" />
<input type="hidden" name="bla" value="12333">
<input type="text" name="yo" value="1">
<button type="submit">Upload</button>
</form>
```
```js
uppy.use(DragDrop, {
target: '.MyForm',
locale: {
strings: {chooseFile: 'Выберите файл'}
},
setMetaFromTargetForm: true
})
```
Then UI acquire type plugins, like Dashboard, FileInput and DragDrop,
before mounting themselves or doing anything else, extract FormData
from the `target` `<form>` element (it must be a form currently), and
merge the object with the global `state.meta`. This is done via
`setMeta` method on core. Then, when a …

Extract metadata from form, closes #153

---

src/plugins/Transloadit/index.js

The `transloadit:assembly` event is emitted when an assembly is created.
It receives the assembly data in the first parameter, and the file IDs
of the files that it belongs to in the second parameter.
```js
uppy.on('transloadit:assembly', (assembly, fileIDs) => {
const files = fileIDs.map((id) => uppy.getState().files[id])
console.log({ assembly, files })
})
```
This also adds a new parameter to the `transloadit:upload` and
`transloadit:result` events, containing the assembly data.
```js
uppy.on('transloadit:upload', (file, assembly) => {
console.log('an upload was completed with template id', assembly.template_id)
})
```
```js
uppy.on('transloadit:result', (stepName, result, assembly) => {
console.log(`${stepName}:`, result, 'from', assembly)
})
```

transloadit: Emit event when assembly is created; add assembly data to existing events.

---

src/core/Core.js

Previously this code would treat any error at all as an `onBeforeUpload`
error, and show the informer. We also lost the stack trace for errors
because `err` is stringified in the handler. This is correct for
`onBeforeUpload` rejections, since they are string reasons, but not for
other errors.
Now only actual `onBeforeUpload` errors are handled that way, and fatal
upload errors end up in the StatusBar like before and in the console,
with a stack trace.

core: Only catch errors from `onBeforeUpload`

---

src/plugins/Transloadit/index.js
test/unit/Transloadit.spec.js

This patch adds a `getAssemblyOptions` function option to the
Transloadit plugin. This option can return an object or a Promise for an
object to configure the Transloadit assembly. The returned object can
contain `params`, a `signature`, and `fields`.
`getAssemblyOptions` is called on each file, so each file can return a
different set of options. Files that returned the same options are
bundled together and run through a single assembly. Files that return
different options will be run through different assemblies.
This means that it is now possible to make assembly parameters depend on
user input from eg. the MetaData plugin, and have different parameters
for different files. It's now also possible to generate very short-lived
signatures on the server when an upload starts, by calling …

Dynamic Transloadit assembly options

---

src/plugins/Tus10.js

This stores the Tus upload URL on the file state object as soon as possible, so we can use it to resume a previous upload from localStorage/idb/serviceworker.

tus: Save upload URL early on

---

src/plugins/Transloadit/Client.js

Previously this was sending a `fields` field with a JSON string, but
that's not how it works. Instead we should send separate form
fields for each field.
(Thanks @Acconut!)

transloadit: Fix sending fields to an assembly

---

src/plugins/Transloadit/index.js

transloadit: Fix crash when `waitFor` options are false

---

src/uppy-base/src/plugins/Provider.js

Some other merge didn't include these changes from #265.
`this.opts.host` is the original hostname given by the user in plugin options.
`this.hostname` is the "sticky" hostname, if uppy-server replies with an `i-am` header that is used instead.

providers: consistently use sticky hostname

---

src/core/Core.js
src/core/Utils.js
src/plugins/RestoreFiles/index.js

(I thought this was already merged for some reason 🙈)
> Low prio!
PR #199 changed thumbnails to be `blob:` Object URLs instead of base64
data URLs, which significantly speeds up rerenders. However, there are
some unintended side effects: GIFs play in previews and really large
images (say, 5+ MB) load in slowly from top to bottom.
This PR uses `blob:` Object URLs to read the image and to display the
previews, but uses a `<canvas>` in between to resize the image, like how
it worked before #199. This has the rerender benefits of Object
URLs, while also making GIFs preview as static images.
Todo:

core: Resize thumbnails using <canvas>

---

src/plugins/Transloadit/index.js

`bus` was removed in the recent refactor PR.
Thanks @Acconut

transloadit: fix some `emit()` calls

---

src/core/Core.js
src/plugins/Transloadit/index.js
test/unit/Transloadit.spec.js

This adds back the ability to run assemblies without uploading any
files, which is useful in case the assembly uses an import robot.
To do this, this patch adds a new state key to the Transloadit plugin's
state, named `uploadsAssemblies` (open to bikeshedding lol)
This key associates assembly IDs with the upload ID that triggered them.
This allows figuring out which assemblies need to finish before
resolving the upload promise.
The upload ID is now passed to preprocessors and postprocessors so
they can use it to store metadata that is related to an upload instead
of to a single file.
When `alwaysRunAssembly` is set to true, and zero files are available
for upload, an assembly is created anyway for the options returned by
`getAssemblyOptions(null)`.
It turns out that `afterUpload` actually …

transloadit: Add `alwaysRunAssembly` option 

---

src/plugins/Transloadit/index.js
test/unit/Transloadit.spec.js

Follow-up to #290.
In #290 the `afterUpload` handler would attempt to go through the `uploadsAssemblies` list for the upload, but that didn't exist if `alwaysRunAssembly` was not set and no files were uploaded. This patch initialises the `uploadsAssemblies` list to an empty array as early as necessary.
It also fixes an issue with `getAssemblyOptions` not being able to return a Promise when `alwaysRunAssembly` was set to true.
From manual tests I think this covers all our cases.
There's just one problem now: When no files are being uploaded, we have no place to store progress. That means the statusbar doesn't update when an assembly that imports its input from somewhere is run. Maybe we should attach progress status to the upload itself now, instead of to each file…

transloadit: Fix crash when no files are being uploaded

---

src/core/Core.js
src/generic-provider-views/index.js
src/plugins/Informer.js
src/scss/_informer.scss

Initial take on “explanations” or “details”. We’ve discussed that sometimes we want to provide more details for the user to understand and report errors better. Console might be better suited for this, but most people won’t be able to use it and `debug: false` will likely be set in production.
I’m not sure whether this should be shown on hover, since those Informer messages are likely to only be shown for 3–5 seconds. I was thinking maybe we show a small popover/tooltip on click, and make that persist even after Informer hides itself, until the user closes the popover/tooltip. Same UI could be used to explain errors for specific files, when you click on the similar question mark button on individual file.

Informer: add details `?` button that shows more info on hover or click

---

src/core/Core.js

Previously this would throw "Plugin is not a constructor" when trying to
instantiate the plugin. Now it checks that the Plugin is actually a
function (and hopefully a constructor…) and throws a more helpful error
if it is not.

core: Throw clearer error when `.use`ing undefined

---

src/plugins/Dashboard/FileCard.js

Fixes #286
Using a `data-` attribute instead of the `name` attribute. Inputs with
`name` attributes submit the form they belong to when `enter` is
pressed, but inputs without do not:
https://stackoverflow.com/questions/3008035/stop-an-input-field-in-a-form-from-being-submitted
A cool followup would be to listen for enter keypresses and close the metadata editor when they happen.

dashboard: Prevent submitting outer form while editing metadata

---

src/core/Core.js
src/plugins/AwsS3/index.js
src/plugins/XHRUpload.js

This implements a `getResponseError` option as described in #303. If available, the error message is appended to the generic "Failed to upload" message:
This PR also implements the `getResponseError` function for the S3 plugin. The screenshot above is using the S3 plugin with a presigned URL that expired in the past.

xhrupload: Support error messages from the endpoint

---

src/plugins/Transloadit/Client.js
src/plugins/Transloadit/index.js
website/src/docs/transloadit.md

Just opening this up to show current progress.
When `importFromUploadURLs` option is true, the Transloadit plugin will not try to upload files directly to assemblies using the Tus plugin, but will instead wait for another user-registered upload plugin to complete, and import the URL reported by the uploader plugin into the assembly.

transloadit: support uploading to a different service, then importing into assembly

---

src/core/Core.js

updateAll was performing it's own series of loops to update all the plugins. This PR makes use of the existing iterate method.

updateAll method uses iteratePlugins method

---

src/core/Core.js
src/plugins/Plugin.js

Even when a plugin didn't have a 'type' property it would still get set to type='none' by the parent plugin class. This PR checks that type==='none' and throws an error if it does.
The pluginName check actually uses plugin.id, so I've updated it the errors and variable names to be pluginId instead to avoid confusion (the plugins actually expose id and name).

Checks for plugin type and plugin id rather than name

---

src/core/Core.js
src/plugins/Tus10.js

As discussed briefly in slack. This fixes an issue where
```js
uppy.resetProgress()
uppy.upload()
```
would attempt to "reupload" tus files to the same endpoint, thus actually resuming those uploads instead of creating new ones.
Going to merge this quickly today to publish a beta release to npm, if you have review comments @arturi or would prefer something else we can revert after and address that then :)

Clear stored tus `uploadUrl` when `resetProgress` is called

---

src/core/Core.js
src/plugins/AwsS3/index.js
src/plugins/Transloadit/index.js

Fixes #315
This patch makes function options that can return Promises a bit
easier to use. Previously, most of these required that the user returned
a Promise, even if they were only doing sync work. Also, if an error was
thrown inside the provided function, it would actually throw the error
instead of rejecting a Promise, thus not allowing Uppy to show an error
notification or anything.
Instead, these options now use this pattern:
```js
Promise.resolve()
.then(() => this.opts.onSomething(argument))
```
Inside a `.then()` handler, both a Promise and a plain value can be
returned, and the resulting Promise will be resolved with the correct
value. Also, any sync errors `throw`n inside a `.then()` handler cause
the returned Promise to be rejected.

Handle sync returns and throws in possibly-async function options

---

src/plugins/Transloadit/index.js
src/plugins/Webcam/index.js

`this.state` was a bit confusing, wasn't clear where the state was coming from. now these functions first assign `state = this.core.state.transloadit` explicitly and use that.
From comments here https://github.com/transloadit/uppy/pull/291#discussion_r135058115

transloadit: remove `this.state` getter

---

package-lock.json
package.json
src/core/Core.js
src/plugins/Tus10.js
src/plugins/XHRUpload.js

XHRUpload and Tus were relying on `core:upload-complete` to determine
when their uploads had all finished, but `core:upload-complete` could
fire before all XHR `onload` handlers were called. Then, because
XHRUpload and Tus would resolve their `handleUpload` promises at that
point, the `core:success` event could fire *before* all
`core:upload-success` events had fired, and before the plugins properly
handled responses. In particular, some files may not have `.uploadURL`
properties when `core:success` is fired:
https://community.transloadit.com/t/unable-to-get-to-work-the-awss3-plugin/14477/16
I think, that the XHR `onprogress` event would fire first at 100%, and
then the `onload` handler fired at some point later (after the response
was parsed or whatever the browser does to it). This …

core: Remove `core:upload-complete` event.

---

package-lock.json
package.json

`tus-js-client` v1.4.4 and up will resume an upload when you reuse the
`tus.Upload` instance, where previously it wouldn't.

deps: Update tus-js-client

---

src/core/Core.js
src/core/Utils.js
src/plugins/Dashboard/Dashboard.js
src/plugins/Dashboard/index.js
src/plugins/StatusBar/index.js
website/src/docs/dashboard.md

Fixes #327 
This refactor simplifies the Dashboard modal API, so you can:
```js
uppy.getPlugin('Dashboard').show()/hide()/isOpen()
```
Not sure if `show()` is better than `showModal()` and if its worth changing, `showModal` is more explicit, while `show` might conflict with other things, like “show filecard” or “show provider panel”. But it is simpler to use and remember. Focusing so much on this minor thing, cause it might dictate how we name things everywhere.
Bonus: in an attempt to fix #326, this PR adds support for multiple `trigger`'s.

Dashboard: show()/hide()/isOpen()

---

website/src/docs/uppy.md

Fix minor typo on sample snippet for uppy.updateMeta(data, fileID).

website/docs/uppy: Fix typo on sample snippet for "uppy.updateMeta(data, fileID)"

---

CHANGELOG.md
examples/multiple-instances/.gitignore
examples/multiple-instances/aliasify.js
examples/multiple-instances/index.html
examples/multiple-instances/main.js
examples/multiple-instances/package-lock.json
examples/multiple-instances/package.json
examples/multiple-instances/readme.md
src/core/Core.js
src/core/Core.test.js
src/plugins/RestoreFiles/IndexedDBStore.js
src/plugins/RestoreFiles/ServiceWorker.js
src/plugins/RestoreFiles/ServiceWorkerStore.js
src/plugins/RestoreFiles/index.js
website/src/docs/uppy.md

Adds an `id` option to Uppy, which allows us to prevent conflicts when storing things in `localStorage` and other persistent storage.
This includes changes to GoldenRetriever to:
- use `uppyState:ID` as the localStorage name
- use the ID as the object store name in IndexedDB (database name is always `uppy-blobs`, with a separate object store for each instance ID)
- tag files in serviceWorker with the instance ID
TODO:

Uppy instance ID

---

README.md
package.json
website/src/docs/index.md
website/src/examples/i18n/app.html

This points https://unpkg.com/uppy to the minified bundle instead of to
the commonjs source files.
Use the short endpoint in the readme and website examples.

Add `unpkg` to package.json

---

src/core/Core.js

Seems that the newState was set after emiting "core:state-update" which caused the newState being not set properly
This addresses the issue mentioned in https://github.com/transloadit/uppy/issues/340

set the newState before emiting "core:state-update" .

---

website/src/docs/plugins.md
website/src/docs/statusbar.md

Not a whole lot to this plugin atm :)
I think we should add an option to always show the statusbar, that would be useful for standalone usage. Right now the statusbar is hidden by default, and animates in when an upload starts.
Todo:

docs: Document StatusBar plugin

---

src/plugins/Plugin.js
src/plugins/Plugin.test.js

The `replaceTargetContent` option wasn't being set correctly, this has been updated.
The `mount` method uses a `render` method (which is not set in the Plugin) so I've had to manually add this to the instance for the tests.
The `mount` method also calls an `addTarget` method that isn't part of the base Plugin class. As a future iteration it would be good to include these missing parts to clarify what's happening or to considering extracting out the functionality and add it in by some other means. What do you think?

Add Plugin class unit tests

---

src/plugins/RestoreFiles/index.js

Another part of #324. This does two things:
- Omit completed uploads from saved file state—previously, when an upload was finished and the user refreshed the page, all the finished files would still be there because we saved the entire list of files. The first commit changes it to only store files that are part of an in-progress upload, or that have yet to be uploaded.
- Remove files from cache when upload finished—this uses the `deleteBlobs` function when `core:success` fires.
The first is necessary for the second, because otherwise we'd be deleting blobs but keep the data about those files in localStorage still.
The final part of #324 would be to add a timestamp to cached blobs, and to delete old blobs on boot. That code would *not* have to check the uppy instance ID, but could instead …

restore: Remove files from cache when their upload finished

---

src/plugins/Plugin.js
src/plugins/Plugin.test.js

Add `render` and `addTarget` methods that throw by default. These methods should have a sub-class implementation when a plugin wants to mounts on a DOM element or on another plugin's target.

Add default methods to Plugin base class

---

CHANGELOG.md
src/core/Core.js
src/core/Core.test.js
src/plugins/Dashboard/index.js
src/plugins/Plugin.js
src/plugins/Plugin.test.js
src/plugins/Transloadit/index.js
src/plugins/Webcam/index.js

This change uses the `this.id` property on plugins to store plugin-specific state.
This changes the layout of the state object a bit: plugin state now lives in a `.plugins[this.id]` state key instead of a top-level state key. `state.webcam` → `state.plugins.Webcam` and `state.transloadit` → `state.plugin.Transloadit`, in practice.
I think some of the state the Dashboard sets is dashboard-specific (about the modal mostly I guess) so maybe we could use `get/setPluginState` there as well.

Move `setPluginState` to Plugin class, add `getPluginState` to match

---

src/core/Core.js
src/core/Utils.js

Also adds:
- `warning` support to log
- timestamps (not saying we 100% need those)

Check for `uploader` type plugins, issue warnings; better log

---

src/core/Core.js
src/plugins/Dashboard/Dashboard.js
src/plugins/Dashboard/index.js
src/plugins/ReduxDevTools.js

- Sends state updates to DevTools; Subscribes to DevTools and sets Uppy state to state provided by DevTools for time traveling; supports replaying all actions, step by step, persisting state, jumping to specific state
- Works without modifying everything else, which is cool. Though I’m not saying adopting Redux would be too hard (see #338), and it might provide better structure, but we are just not sure yet;
- We could add support for custom action type names, and then we’ll get actions like `UPPY_ADD_FILE` and such (see this comment https://news.ycombinator.com/item?id=15342850);
- Implemented as a separate plugin
(Try by installing and activating: https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)
And the second commit is useful regardless: …

Add support for Redux DevTools via a plugin

---

CHANGELOG.md
src/plugins/AwsS3/index.js
src/plugins/XHRUpload.js

Closes #243
If `getUploadParameters` returns an object with a `headers` property,
those headers are added to the HTTP request used for the upload.
This way headers like `Content-Disposition` can be added without
requiring support for that on the signing server side.
```js
uppy.use(AwsS3, {
getUploadParameters (file) {
return fetch(`/sign?name=${file.name}&type=${file.type.mime}`)
.then((response) => response.json())
.then((data) => Object.assign(data, {
headers: {
'Content-Disposition': file.meta.contentDisposition
}
}))
}
})
// later
uppy.addFile({
name: 'xyz.jpg',
mime: 'image/jpeg',
data: someArrayBuffer,
meta: {
contentDisposition: 'inline'
}
})
```
To do this the XHRUpload plugin needed to merge header objects
from different configuration locations together, in …

s3: Add ability to configure request headers

---

src/core/Core.js
src/plugins/DragDrop/index.js
src/scss/_dragdrop.scss
test/acceptance/dragdrop.spec.js
test/acceptance/i18n.spec.js
website/src/examples/i18n/app.html

From Alex’s mockup:
The DragDrop plugin looks like this now:
- added `width`, `height` (both `100%` by default to fill the entire container space) and `note` options
- added arrow icon; white background
- refactored CSS and class names
- removed `selectedFiles` count for now

DragDrop: redesign, add note, width/height options, arrow icon

---

src/plugins/Redux.js
src/plugins/Redux.test.js

As requested, recreated the redux plugin (now using Jest tests rather than Tape). Been using this in development at Photobox and haven't come across any issues so far. It's worth noting that for this plugin to work 100% of the time Uppy state should be updated using core.setState rather than using core.state, otherwise the core:state-update event doesn't get fired.
Usage for documentation: 
```javascript
import { Core, Tus10 } from 'uppy';
import Redux from 'uppy/plugins/Redux';
//define a redux action
const uppyUpdatedAction = (prev, curr, patch) => {
type: 'UPPY_UPDATED',
prev,
curr,
patch
};
const uppy = new Core({ wait: false });
uppy
.use(Redux, { dispatch: store.dispatch, action: uppyUpdatedAction }) //where store is your redux store
.use(Tus10, { endpoint: …
```

Adds redux plugin

---

CHANGELOG.md
src/core/Utils.js

- Generate a PNG thumbnail
- Don't reuse canvases during resize
before
after

core: Fix thumbnails with transparent backgrounds, fixes #379

---

src/plugins/RestoreFiles/IndexedDBStore.js
src/plugins/RestoreFiles/ServiceWorkerStore.js

This prevents errors when checking for IndexedDB or service worker
support. While the Golden Retriever can't be used on the server, at
least now it won't crash. That's nice for server rendering, you can still
`require()` your entire client application server side this way.

restore: Fix server-side require()

---

website/src/docs/uppy.md

Website docs for `uppy.getFile` had a typo on `file.preview`.

Fix preview typo

---

src/plugins/Transloadit/index.js

I'm reusing the `upload-error` event for this, maybe we should add a
`postprocess-error` event too. Anyway, this sets the `.error` state on
files if the assembly they were uploaded to fails for some reason.
This was pulled out of #366 to maybe land it faster.

transloadit: Emit file upload error if assembly fails.

---

src/plugins/Dashboard/FileItem.js
src/scss/_dashboard.scss

Previously, file cards in the Dashboard would not show errors that
occurred during processing, such as a failed Transloadit assembly.
This patch also shows the error overlay on files that errored at some
other point than the upload itself.

Show errors that occurred during processing.

---

CHANGELOG.md
src/core/Core.js

This fixes an issue when retrying Tus uploads with the Transloadit
plugin. `uploadComplete` would be true, so the Dashboard would show the
file as complete while it was uploading again.

core: Clear upload progress when upload starts.

---

src/core/Core.js
src/plugins/Dashboard/index.js
src/plugins/Transloadit/index.js
src/plugins/Tus10.js
src/plugins/XHRUpload.js

Instead of restarting only the file upload itself in the Tus or
XHRUpload plugin, start an entirely new upload for retries. This fixes
retrying uploads with processing plugins, like Transloadit. Previously,
only the Tus upload would be retried--with this patch, a new assembly
will be created and the retry will go to that assembly.

Restart the entire upload on retry, fixes #387.

---

website/src/docs/uppy.md

The example for `uppy.updateMeta()` has the arguments in the wrong order.

Fix uppy.updateMeta() example

---

examples/aws-presigned-url/main.js
examples/bundled-example/main.js
src/core/Core.js
src/core/Core.test.js
src/core/Utils.js
src/core/Utils.test.js
src/plugins/AwsS3/index.js
src/plugins/Dashboard/Dashboard.js
src/plugins/Dashboard/FileCard.js
src/plugins/Dashboard/FileItem.js
src/plugins/Dashboard/getFileTypeIcon.js
website/src/docs/aws-s3.md

Fixes #394
Fixes #389
*Note: file pasting is [experimental](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData), only support images, and file name string is always empty, because it doesn’t pass a reference to a file, but copies its data/blob instead, it seems.*
* add checks for empty `fullFileName` and `fileExtension`
* dashboard: if blob is empty on paste, log errors and return, skip `addFile`
* add default `duration` for `info` messages

Fix pasting files, default `image` file name, add type to meta, file type refactor

---

CHANGELOG.md
src/plugins/XHRUpload.js
website/src/docs/xhrupload.md

If no progress events have been emitted for `opts.timeout` milliseconds, abort the upload.
Currently this defaults to 30 seconds.
Set `opts.timeout` to 0 to disable this feature, and never auto-abort the upload.

 xhrupload: stop trying to upload if it stalled 

---

src/scss/_dragdrop.scss

On small screens, the content of the `.uppy-DragDrop-inner` was sticking to the side edges, and when there are two lines of the note, its lines were too close to each other:
Now it's fixed: the note's `line-height` increased, and side paddings added:

Fix of the .uppy-DragDrop-inner spacing on small screens

---

package.json
src/core/Core.js
src/core/Core.test.js

Fixes the issue specified in https://github.com/transloadit/uppy/issues/402
Rather than storing error objects in the state this PR makes it so that it only stores the error message. Full errors get outputted to the console anyway, which is a more useful environment for debugging and logging (and easier for other systems to tap into etc).

Updates state with error messages rather than error objects

---

website/src/docs/index.md

Fixes a few typos on the Getting Started page in the docs.

Website: Fix a few typos on Getting Started page

---

src/core/Core.js
src/react/Dashboard.js
src/react/DashboardModal.js
src/react/DragDrop.js
src/react/ProgressBar.js
src/react/StatusBar.js
src/react/Wrapper.js

The React components were expecting an `instanceOf` the uppy core factory function, not of the uppy core class itself. This patch exposes the uppy core class constructor on the `./core` module for the react components to use.
Tested this by opening up the `examples/react-example` and verifying that there were no proptype warnings in the console. Previously it would log the warning described in #411.

react: Fix `uppy` PropType, closes #411

---

src/generic-provider-views/index.js

getFileType returns undefined for non-whitelisted files and currently fails while uploading files from e.g. dropbox when trying to upload non-whitelisted file. Stack trace from https://uppy.io/examples/dashboard/ while trying to upload a zip file:
```
index.js:169 Uncaught (in promise) TypeError: Cannot read property '1' of undefined
at index.js:169
at <anonymous>
```
Note that checkRestrictions will still fail for such files, but at least it's possible to override this method to look on filenames instead.

Do not check isPreviewSupported for unknown filetypes

---

examples/bundled-example/main.js
src/core/Core.js
src/core/Core.test.js
src/core/Utils.js
src/core/Utils.test.js
src/plugins/AwsS3/index.js
src/plugins/GoldenRetriever/index.js
src/plugins/Transloadit/index.js
src/plugins/Tus.js
src/plugins/XHRUpload.js
website/src/docs/index.md
website/src/docs/react.md
website/src/docs/uppy.md
website/src/examples/dashboard/app.es6
website/src/examples/dashboard/index.ejs

This patch changes `.upload()` to resolve to an object with `{ successful, failed }` properties.
It deprecates the `core:success` event in favour of `core:complete`. `core:complete` receives the same object as its only parameter.

Return { successful, failed } object from .upload().

---

src/index.js
src/plugins/Dashboard/index.js
src/plugins/DragDrop/index.js
src/plugins/Dropbox/index.js
src/plugins/Dummy.js
src/plugins/FileInput.js
src/plugins/GoogleDrive/index.js
src/plugins/Informer.js
src/plugins/Instagram/index.js
src/plugins/ProgressBar.js
src/plugins/StatusBar/index.js
src/plugins/Webcam/index.js

This PR allows passing a custom `id` for any UI plugin (though this has to be manually implemented in any new plugin). This allows using, for example, two `StatusBar`s, one inside the `Dashboard`, and one somewhere on the page, visible even when `Dashboard` is closed. Briefly discussed in https://github.com/transloadit/uppy/pull/328#issuecomment-328242214.
Can be used like this:
```js
.use(Informer, { id: 'MyCustomInformer' })
.use(Dashboard, {
inline: true,
disableStatusBar: false,
disableInformer: true,
getMetaFromForm: true,
closeModalOnClickOutside: false,
plugins: ['MyCustomInformer']
})
```
or
```js
// one StatusBar comes included in the Dashboard, another will be mounted on the page
.use(Dashboard {...})
.use(StatusBar, { id: 'PageStatusBar', target: 'body' }
```

Support custom plugin IDs to allow using multiple copies of a plugin and more

---

src/plugins/Dashboard/index.js
src/plugins/Webcam/index.js

Providers can signal whether they support the current environment using
an optional `isSupported()` method. Providers that always work (eg.
Google Drive) do not need to specify this method.
The check for the Webcam currently only checks if the `getUserMedia`
method exists at all. We could maybe do some more checks, like, if the
mode is `video-only` or `video-audio` but MediaRecorder is not
supported.
e; Oh! Maybe this is helpful: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getSupportedConstraints
e2; nnope that's something different
There might be a better way to do this than an optional method but I
couldn't think of one. I don't think this is terrible but we already have quite
a large API surface for plugins (install, mount, uninstall, render, addTarget;
for providers, …

webcam,dashboard: Add `isSupported()` API for providers

---

src/plugins/XHRUpload.js

Before this all field data values were the same so remote uploads didn't work with S3.

Fix fields in XHR remote uploader

---

src/plugins/Dashboard/index.js
src/plugins/DragDrop/index.js
src/plugins/Plugin.js
src/plugins/Plugin.test.js

- Set `this.target = this.el` when`target` in a DOM element.
- Set `this.target = targetPlugin.addTarget(plugin)` (`addTarget` returns `this.target`, which will be set to the target plugin’s `this.el`) when `target` is a plugin.

Set `this.target` in `Plugin` class

---

src/plugins/GoldenRetriever/IndexedDBStore.js

We should be actually creating the connection right there.
This happened when using multiple instances, the first instance would
auto-cleanup and take the first path, while the second instance would
take this second path.
Fixes part 2 of #429

GoldenRetriever: Fix IndexedDB store initialisation when not cleaning up

---

.eslintignore
CHANGELOG.md
src/core/Utils.js
src/core/Utils.test.js
src/plugins/XHRUpload.js
website/src/docs/xhrupload.md

By default, all files are uploaded simultaneously. You can pass `limit: N` to upload up to `N` files simultaneously.
```js
uppy.use(XHRUpload, {
limit: 10
})
```
Passing `limit: 0` or `limit: Infinity` means unlimited simultaneous uploads.
The limit counts across `upload()` calls, so if there is a `limit: 10` and `upload()` is called with 5 files and then with another 7, it won't start uploading 12 files at the same time.
This uses a helper function inspired by [p-limit](https://www.npmjs.com/package/p-limit). p-limit is ES2015+ so we can't depend on it directly.

Add XHRUpload option to limit simultaneous uploads

---

src/generic-provider-views/index.js

I noticed a bug in the new folder selection feature. Deselecting a folder did not remove all the files of the folder because [this](https://github.com/transloadit/uppy/blob/6fcab8e9cbd56a6c34c40cb70502bdcb94c883eb/src/generic-provider-views/index.js#L75) constantly mutates [this array](https://github.com/transloadit/uppy/blob/6fcab8e9cbd56a6c34c40cb70502bdcb94c883eb/src/generic-provider-views/index.js#L381) during its own iteration, so the indexing gets messed up, and it misses out some items during iteration.

fix: folder deselection did not remove all files

---

src/plugins/Tus.js

This addresses #433. If the restored upload was paused, the Tus plugin does not immediately continue uploading.
I was thinking of waiting to call `uppy.restore()` for paused files until the user unpaused, but I think that would not be the best way to go about this, so I took this route for the Tus plugin. The Tus plugin already handles pausing internally so I think this makes sense.
IMO, when restoring, we should start in a 'confirmation' state, so that we only really restore all the uploads (and start them, if they were not paused previously) once the user confirms that this is a good idea. It might not be a good idea, for example, if the crash happened on WiFi while uploading a 1GB video, but now the user is commuting and on cellular data. They could also cancel it and then we'd remove …

tus: Restore correctly from paused state

---

examples/bundled-example/main.js
package-lock.json
package.json
src/core/Core.js
src/core/Core.test.js
src/plugins/GoldenRetriever/index.js
src/plugins/StatusBar/StatusBar.js
src/plugins/Transloadit/index.js

<strike>Pretty early, mostly just opening this up so I can leave todos here.</strike>
This PR will implement restoring an upload to Transloadit after a browser crash, using GoldenRetriever. It should request new assembly statuses, set up the status WebSocket connections again, and account for any events that were missed.
Currently this happens after Golden Retriever restores an upload. I think we can use this same functionality when the internet connection died and comes `core:back-online` too. We do have information about assemblies, files, and results in state in that case, but we may have missed some events.
If we persist the entire assemblies state to localStorage for Golden Retriever, we could follow the exact same steps both for restoring from localStorage after a page refresh, and …

transloadit: implement assembly status restore

---

website/src/docs/react.md

Hi,
Preactjs link ` https://preact.js.org/` is not reachable. I change it by https://preactjs.com/

https://preact.js.org/ is not reachable

---

CHANGELOG.md
website/src/docs/dashboard.md

Fixes #475 
Just remove old references to `width` and `height` options for Dashboard, which are in fact `maxWidth` and `maxHeight`

Fix references to incorrect width/height attributes

---

src/plugins/AwsS3/index.js

I need this option to keep large amount of uploads working: https://github.com/transloadit/uppy/issues/468

Allow passing on XHRUpload options, such as "limit" to AwsS3 Plugin

---

src/plugins/Dashboard/index.js
src/plugins/ProgressBar.js
src/plugins/StatusBar/StatusBar.js
src/plugins/StatusBar/index.js
src/scss/_common.scss
src/scss/_progressbar.scss
src/scss/_statusbar.scss
website/src/docs/dashboard.md
website/src/docs/progressbar.md
website/src/docs/statusbar.md

Hello
This pull request is connected to issue #464.
The first commit adds an option to hide progress bar after upload is finished.
Please don't hurt me if I did something not the way I was supposed to, I'm new here :smiley:

Add option to hide progress bar after upload finish #464

---

CHANGELOG.md
examples/cdn-example/index.html
src/core/Core.js
src/plugins/Provider/view/index.js
src/plugins/Tus.js
src/plugins/XHRUpload.js
website/src/docs/tus.md

Fixes #445
- Omits files that are `uploadStarted` when selecting which files to upload, even if they are remote. Not sure why did we have a condition to always include remote files?
- Correctly resolve/reject upload promise from remote success/error events for Tus and XHRUpload. Before this PR remote uploads were marked as complete, but `complete` event never fired, because promises were not resolved.
This probably needs a good review and discussion, likely missing something. But in my tests this fixed unnecessary re-uploading from #445 and not emitting `complete` for remote files. Tus/XHR implementations in this area should be more consistent, I think, sharing same methods/conventions.

Fix remote uploads

---

package-lock.json
package.json
website/package-lock.json
website/package.json

This should remove the warnings about insecure dependencies we were
getting. node-notifier@4 depends on an old version of `marked` that has
an XSS vulnerability. We weren't really affected because we don't push
user input through node-notifier, but the warnings show up anyway :P 
I removed it from the root package because it looks like we were only
using it in the website build code.

deps: Update node-notifier

---

website/src/docs/server.md
website/src/docs/uppy.md

Fixed several typos in docs/server and docs/uppy as well as made parentheses and paragraph formatting more consistent.
I also found that some of the links in the docs can be improved by adding the name/ title of the link rather than just `See`.
Could be better:
Good:
Do let me know if you'd like me to add the changes for the related links as well :smile:

Fixed several typos in docs/server and docs/uppy 

---

.travis.yml
package.json

This is also already being done using the `prepublish` hook called by `npm install`. saves some work during CI runs.

ci: Remove duplicate build step

---

src/scss/_statusbar.scss

(Should we use `display: none;` here instead? I am not sure how that
would interact with the animation though.)
Fixes https://transloadit.slack.com/files/U4D4GMZ5H/F8S75H11N/image.png

statusbar: Fix status text still showing when statusbar is hidden

---

src/plugins/AwsS3/index.js

Even only accessing `responseXML` if the response is not XML can throw an error or log a warning, so we should check the Content-Type first.

s3: More robust XML check, fixes #518

---

src/core/Core.js

This way our ETA calculations etc. will be correct even if it takes a
very long time for the first progress event comes in. This helps
especially with XHRUpload's `limit` option, where queued uploads will
not be firing progress events at all until other uploads have finished.
Ref #513's first item

core: Initialise `progress.bytesTotal` as soon as upload starts

---

src/plugins/Transloadit/Socket.js
src/plugins/Transloadit/index.js
website/src/docs/transloadit.md

Similar to the `onExecuting(assembly)` callback in the [transloadit/jquery-sdk](https://github.com/transloadit/jquery-sdk).

transloadit: Add `assembly-executing` event

---

src/plugins/AwsS3/index.js

Fixes a crash when using presigned PUT uploads. The result of `getResponseHeader()` can be `null` so we can't always lowercase it. Ref https://github.com/transloadit/uppy/issues/518#issuecomment-358770704

s3: fix isXml() check when no content-type is available

---

src/plugins/AwsS3/index.js

Ref https://github.com/transloadit/uppy/issues/513
Apply the same limit to upload parameter requests as is applied to
XHRUpload requests.

s3: Respect `limit` option for upload parameter requests too

---

website/src/docs/contributing.md

This guideline added in case anyone tries to clone the same repository without forking.

Added instruction to fork the repo first

---

src/plugins/XHRUpload.js

uppy-server calls this `metadata`. Part of allowing uppy-server to
upload to S3, see https://github.com/transloadit/uppy-server/issues/57

xhrupload: Fix custom form fields in remote uploads

---

src/plugins/Dashboard/Dashboard.js
src/plugins/Dashboard/index.js
src/scss/_dashboard.scss
website/package.json

As described in #562, Dashboard modal fiddled with `document.body.style.top` which resulted in some layouts being broken. There seems to be a better solution, which I borrowed (with credit, as many other things) from their https://github.com/ghosh/micromodal/. 
This should fix the issue, plus there’s now an option to disable this and leave page scroll as is.

Dashboard: fix modal scroll

---

CHANGELOG.md
examples/xhr-bundle/.gitignore
examples/xhr-bundle/aliasify.js
examples/xhr-bundle/index.html
examples/xhr-bundle/main.js
examples/xhr-bundle/package-lock.json
examples/xhr-bundle/package.json
examples/xhr-bundle/readme.md
examples/xhr-bundle/serve.js
src/plugins/XHRUpload.js
website/src/docs/xhrupload.md

Adds a `bundle` option that will upload all files in a single request, instead of separate requests for each file.
It's added as a separate method `uploadBundle()` because the `upload()` method turned out to be really hard to adapt. Mostly because `upload()` uses options from the file objects, so it can have different endpoints for different files for example, which is not something `uploadBundle()` has to worry about. The `upload()` and `uploadBundle()` methods are now really similar but this was easier to do than to add `if` checks  to every other line in `upload()`. We'll have to remember to make changes in all three upload methods now though when necessary (`upload`, `uploadRemote`, `uploadBundle`).
Todo:

Add the XHRUpload `bundle` option.

---

src/plugins/Webcam/CameraScreen.js
src/plugins/Webcam/index.js
src/scss/_webcam.scss
website/src/docs/webcam.md

- Should we add a UI button to flip/mirror the image? Camera might be looking the other way, it could be a front facing camera.
- Decide on what to do with dimensions, if we scale the image to fill the Dashboard UI window, we’ll have to crop some parts, depending on the size if the screen. What about mobile?

[wip] Add `mirror: true` opt that flips webcam picture to act like mirror

---

website/src/examples/dashboard/app.es6
website/src/examples/transloadit/app.es6
website/src/examples/transloadit/app.html
website/src/examples/transloadit/index.ejs

- Adds Transloadit example that crops an image and adds a copyright caption to it
- Requires Transloadit API key for now, link and explanation of how to get one included
- The key is stored in localStorage after input, on page reload the key will be pre-populated for you

Add Transloadit example to website

---

src/core/Core.js

Add wrapper function for emitter.on that returns uppy instance for easy chaining.
Kevin noticed this:
> It seems `.on` does not return the Uppy object.
This didn’t work:
This did:
Now both do.

Add wrapper function for emitter.on

---

src/core/Core.js
src/core/Core.test.js
src/plugins/Dashboard/index.js
src/plugins/DragDrop/index.js
src/plugins/Dummy.js
src/plugins/FileInput.js
src/plugins/Provider/view/index.js
src/plugins/Transloadit/index.test.js
src/plugins/Webcam/index.js

- restriction errors now reuse the Informer error code in `addFile()`, so all errors in addFile go through the same path
- UI plugins swallow rejection errors so they don't end up in the console with no way to fix
- **check min number of files _after_ `onBeforeUpload`** - this is so it works the same way as `onBeforeFileAdded`, which is also called before restriction checks

`addFile()` rejections revamp

---

src/plugins/Transloadit/index.js

Set `fields: true` to send along `fields` from global metadata when creating an assembly. This works nicely with the Form plugin, which adds form field values to the global metadata.
Mimicks the jQuery SDK's `fields: true` option.
I'll add docs for this in https://github.com/transloadit/uppy/pull/546, to prevent merge conflicts

transloadit: Easily pass form fields

---

src/plugins/Transloadit/index.js

And also finish the preprocessing step.
We already do this in the postprocessing step if an error occurs later during assembly execution, so I didnt change anything there.
Turned out to be simpler than I thought :)

transloadit: Emit 'upload-error' when preprocess fails, fixes #615

---

website/src/docs/dashboard.md
website/src/docs/plugins.md

I think we discussed once that `plugins` might be a better approach in general than `target: Plugin`; maybe we should update our examples etc to use the `plugins` option too? For now I'm just adding it to the dashboard options list.

Document Plugin `id` and Dashboard `plugins` options, closes #619

---

src/core/Core.js
src/core/Core.test.js
src/plugins/Tus.js
src/plugins/XHRUpload.js
website/src/docs/uppy.md
website/src/docs/xhrupload.md

Basically, this: #521 
This adds a `response` key to files when the upload completed (regardless of whether it succeeded). `file.response` contains a `status` and a `data` property. `data` is the result of `getResponseData`. One change here is that `getResponseData` is also called if there was an error, not sure if that's a good idea.
Also changing events to emit file objects instead of IDs here because it touches many of the same places.

Revamp XHR response handling

---

src/plugins/Transloadit/Client.js
src/plugins/Transloadit/index.js
website/src/docs/transloadit.md

Addressing @tim-kos's feedback on the Transloadit plugin documentation, opening PR to make it easy to keep a checklist:

Improve Transloadit plugin docs

---

src/core/Core.js
src/plugins/Transloadit/index.js

When a file is removed in Uppy, progress events like `preprocess-complete`, `upload-progress`, `postprocess-progress` and the like are still emitted sometimes. This causes errors reported in #596 and by Alex in Slack:
This PR fixes these issues by checking if the file exists in state before trying to set progress to it. Checks are added in Core and in Transloadit plugin in `onFileUploadComplete`. 
Questions:
- Should we instead prevent progress events from being emitted in the first place in uploader  and encoder plugins?
- Do we need to remove files from Transloadit plugin’s internal file state? I’ve added a method, but it seemed to me it doesn’t solve the issue.
- When you upload 4 files with Transloadit plugin and remove 1 during upload, `finish` event never fires, because Transloadit …

Fix progress events causing errors for removed files

---

src/plugins/XHRUpload.js

There's an error introduced by https://github.com/transloadit/uppy/pull/612 here https://github.com/transloadit/uppy/pull/612/files#diff-ca5a310a56869b8b55189737dc65736cR238
It should be called with the response text and the xhr object.
This fixes #645

Fix XHRUpload.js error handling

---

CHANGELOG.md
src/plugins/GoldenRetriever/index.js

When the ServiceWorker or IndexedDB store reject Promises, log a
warning. Suppresses unhandled rejection errors in the console
that users cannot catch themselves.

restore: Catch rejections

---

src/core/Core.js
src/core/Core.test.js
src/core/Utils.js
src/plugins/AwsS3/index.js
src/plugins/GoldenRetriever/index.js
src/plugins/Provider/view/index.js
src/plugins/Transloadit/index.js
src/plugins/Tus.js
src/plugins/XHRUpload.js
website/src/docs/uppy.md
website/src/docs/xhrupload.md

Follow up after https://github.com/transloadit/uppy/commit/a3845214d7bb53262b0ccfd015c1472a7a282b9b
Converted a lot of events from: `('upload-success', (fileID, uploadResp, uploadURL)` to `('upload-success', (file, uploadResp, uploadURL)`. Less sure its a good idea now:
- We are likely passing stale file objects, so we still have to fetch actual file with `uppy.getFile(file.id)`?
- fileID is better suited for “action” events that we use internally, I think, like `'upload-pause'` and `upload-cancel`. And in some other places, I had to actually retrieve the file object to include in the even quite a few times: https://github.com/transloadit/uppy/pull/647/files#diff-989af75a364b65c408abe1fc3e7ac0f4R62.
I think `file` instead of `fileID` is easier for the end user, because they don’t have to …

Emit full file object instead of fileID in events like uppy.on('event', file, data)

---

src/core/Core.js
src/core/Core.test.js

When specifying custom locale strings, the default strings were no
longer used. That's because we were creating the Translator instance
twice; first with custom locale strings merged into `defaultLocale`,
but then again later with just `this.opts.locale` (no defaults).
This came up in #654, where incomplete custom locale strings were
used, causing some strings to return `undefined`.
This patch removes the latter instantiation so we only keep the one with
the defaults.

Fix merging locale strings in Core.

---

src/plugins/AwsS3/index.js

Similar to the Transloadit plugin, check that parameters are formatted correctly.
This patch explicitly logs the error so it shows up in the console and not just the Informer…feels like we need a way to distinguish between "user errors" like files that fail to meet restrictions and real errors like this or like a failed upload. The former shouldn't be logged to the console but the latter two should.

 s3: Check upload parameters shape, fixes #653

---

src/core/Core.js
src/core/Core.test.js

When doing `cancelAll` (or `reset`), all files are removed but the currentUploads key is not cleared. When you select a file that you had previously also selected, the fileID is the same because file IDs are deterministic. So the file ID was still part of one of the currentUploads, causing it to not be uploaded again (since #552).
This patch also removes all uploads in `cancelAll`.

Clear uploads on `cancelAll`, fixes #660

---

src/core/Core.js
src/core/Core.test.js

Supplied restrictions are now merged with default restrictions. (as described in #675)
I also added a small unit test that covers this change, but I was unsure where to put this.
I can (re)move it if needed.

Added merge of restrictions 

---

src/plugins/Url/index.js

Added check for empty URL with an error message.
Should we try to check the url for typos like `htps://`? I googled a bunch of url-regexes, but reading into this, it seems like introducing them might miss some actually valid urls, like `http://✪df.ws/123`, see https://mathiasbynens.be/demo/url-regex. @ifedapoolarewaju what do you think?

Check url in URL plugin

---

src/plugins/Form.js

Fixes https://github.com/transloadit/uppy/issues/684
Rollup uses get-form-data's ES modules build, and rollup-plugin-commonjs automatically resolves `.default`.
So, if we are being built using rollup, this `require()` won't have a `.default` property.

Fix `get-form-data` being undefined when built with Rollup

---

examples/aws-uppy-server/main.js
examples/aws-uppy-server/package-lock.json
examples/aws-uppy-server/package.json
examples/aws-uppy-server/server.js
src/plugins/AwsS3/index.js

Added Google Drive to the AWS uppy-server example, which is what I used to test this.
Remote uploads via uppy-server do not have a `getResponseHeader`
function or a `responseXML` property. Instead, use the `headers` object,
and parse the XML manually.
Fixes transloadit/uppy-server#71

 s3: Support fake XHR from remote uploads 

---

src/plugins/GoldenRetriever/index.js
src/plugins/ThumbnailGenerator/index.js
src/plugins/ThumbnailGenerator/index.test.js

The `generatePreview()` method that GoldenRetriever used to create new
thumbnails after restoring files no longer exists. This patch makes the
ThumbnailGenerator go through all files after a restore, and tries to
generate a thumbnail for all blob URLs (http:// URLs from remote sources
don't need to be regenerated).

Regenerate thumbnails after restore.

---

CHANGELOG.md
examples/react-example/App.js
src/react/DashboardModal.js

This was always mounting the dashboard DOM element into the current
React container element, but that's not always the right thing to do,
for example if the container element is a small element with `overflow:
hidden` or some `position: relative` style.
This patch allows you to do `target={document.body}` and the like, so
you can mount the dashboard element anywhere.

 react: Allow overriding <DashboardModal /> `target` prop, fixes #739

---

src/core/Core.js
src/core/Core.test.js
src/plugins/Form.js
src/plugins/StatusBar/index.js
website/src/docs/uppy.md

Follow up on #294 
> What we decided to try to implement during the call: return true or modified file from onBeforeFileAdded to add the file, return false to not add the file. Show error message yourself by calling uppy.info('File is too large', 'error') and uppy.log('File is too large').
- Not catching errors from `onBefore*` anymore, since non are expected. Instead we advice to show error messages manually.
- Using returned `files` from `onBeforeUpload` for the actual upload (is this how we wanted to do this? thinking if this might backfire — editing all the files at once like this?)
- Should we make the whole `upload` synchronous too? Seems like there’s no point to keep it async now. **upd:** well, I remembered during my sleep that upload process itself is async, ha-ha.

Return false — abort adding file or upload

---

CHANGELOG.md
src/plugins/DragDrop/index.js

Putting an `<input>` inside a `<label>` links them automatically. Since the input is hidden it doesn't affect styling.

dragdrop: Link <label> and <input>, fixes #749

---

src/plugins/Tus.js
src/plugins/XHRUpload.js

Move the error objects from Uppy Server to a `.cause` property on the
Error instances we emit in `upload-error`. The Error instances now
correctly use the message from the error object reported by Uppy Server.

Retain uppy-server error messages, fixes #707

---

src/plugins/XHRUpload.js
website/src/docs/xhrupload.md

Hope this is ok, naming is tricky, but we were naming params differently across docs, code and blog posts.
//cc @ifedapoolarewaju @goto-bus-stop

Consistent shape for the getResponseData (responseText, response)

---

CHANGELOG.md
src/core/Core.js
src/core/Core.test.js
website/src/docs/uppy.md

`uppy.getFiles()` returns an array of all file objects. This way people
don't have to reach into the internal state object to do something with
the files.

core: Add getFiles() method.

---

src/plugins/AwsS3/index.js
website/src/docs/aws-s3.md

The AwsS3 plugin appears to already support the `headers` field in upload parameters, indicating the request headers that should be sent along with the upload request, so we add it to the documentation.

Document "headers" upload parameter in AwsS3 plugin

---

src/react/Dashboard.js
src/react/DashboardModal.js
src/react/DragDrop.js
src/react/ProgressBar.js
src/react/StatusBar.js
src/react/Wrapper.js
src/react/propTypes.js

Updates to include new options. Also validates things like the metaFields shape.

Update React component PropTypes

---

.travis.yml

Node 8 is the current LTS version.

ci: Bump to Node 8.

---

CHANGELOG.md
src/plugins/Dashboard/Dashboard.js
src/plugins/StatusBar/StatusBar.js

Fixes #774
This way there is no confusion about the encoding. According to an old
React doc page that $SEARCH_ENGINE dug up: https://shripadk.github.io/react/docs/jsx-gotchas.html

Change Unicode characters to HTML entities and \u escapes

---

website/src/docs/uppy.md

Mostly refer to "Uppy's internal state" instead of `uppy.state`. `uppy.state` doesn't really exist anymore, it's now a getter that returns `uppy.store.getState()`.

Update some `uppy.state` docs to align with the Stores feature.

---

src/plugins/Dashboard/ActionBrowseTagline.js
src/plugins/Dashboard/Tabs.js
src/plugins/DragDrop/index.js
src/plugins/FileInput.js
website/src/docs/dragdrop.md
website/src/docs/fileinput.md

Need to update either this or https://github.com/transloadit/uppy/pull/776 with the new option depending on which is merged first.

dragdrop: Add `inputName` option like FileInput has, closes #729.

---

website/src/docs/aws-s3.md

Ugh they use a different CORS format :weary: 
Moved the DO and GCS docs to a new section "S3 Alternatives", instead of shoving both under "Examples".
GCS needs some configuration to enter compatibility mode with S3, and setting CORS options on a bucket is more complicated because they don't have a UI for it. Instead you need to use the gsutil tool. I added steps for doing it without gsutil too for people like me who don't want to install things.

Document Google Cloud Storage setup for the AwsS3 plugin

---

src/core/UppySocket.js

They are generating a bit too much noise in production builds.

Remove log statements from uppy socket

---

src/core/Plugin.js
src/plugins/Dashboard/index.js
src/views/ProviderView/AuthView.js

This saves a lot of time diffing, mostly—every `setState()` call is
currently telling preact to update the vdom, which is cheap but not THAT
cheap :P
I used a Promise resolution for the debounce here, instead of nanoraf,
because it is 1) very small and 2) the same behaviour that Preact has
for `setState()` calls inside components.
This time, it comes with a sync `this.rerender()` method for plugins
that need to handle focus. I think this is best viewed as a hack, and we
should try to use the `componentDidMount()` lifecycle method instead for
this sort of thing.
Adding 150ish files took 10s before this, but 500ms after. I think 500ms
is still a lot, but to optimise that we may have to cut down on setState
calls, or also debounce `plugin.update()` calls—the latter could be
unexpected for …

Debounce render calls again, fixes #669

---

website/src/docs/uppy.md

This part currently renders as "*`<input>`)’s accept attribute*" on the website, this PR should fix it.

Fix dangling parenthesis

---

src/plugins/Tus.js

closes #753
I'm assuming it's OK to just drop the original type field.

Tus plugin: rename metadata field: type→filetype

---

src/plugins/Url/index.js

The way its currently done is I add event listeners in the Url plugin itself, and if the dropped thing is a url (works for text urls, urls from links and images), then the Url plugin takes it as a url.
- Maybe improve `.drag` css class addition/removal, add timeout

Url: Add support for drag-dropping urls, links or images from webpages

---

CHANGELOG.md
src/plugins/AwsS3/Multipart.js
src/plugins/AwsS3/MultipartUploader.js
src/server/RequestClient.js
website/src/docs/aws-s3-multipart.md
website/src/docs/aws-s3.md
website/src/docs/transloadit.md

This patch adds a new resumable upload plugin, using S3's Multipart uploads. S3 Multipart is different from the "multipart" in XHR FormData uploads; it allows you to upload a file in multiple requests (each 5MB+).
This is a separate plugin because the upload process is completely different from the standard AwsS3 upload plugin.
The implementation mirrors the tus upload plugin. There is a MultipartUploader class, very similar to the Upload class in tus-js-client. The MultipartUploader class is used by the AwsS3Multipart plugin to control the upload. (I tried to do everything in the plugin class initially, but it was getting really unwieldy with multiple files each having multiple chunks and each chunk having its individual upload progress etc.) The MultipartUploader class handles the …

S3 Multipart upload

---

src/core/Core.js
src/core/Core.test.js
src/plugins/XHRUpload.js

- Add `timer.done()` and `error: null` to `cancel-all` events
- Ignore progress events in timeout tracker after upload was aborted
- Remove throttling, it was causing issues with `bundle: true` (“with `bundle:false` that doesnt show up so much because the order of events will be different each time, but with `bundle: true` it always  emits those 4 in the same order so it calculates the first one on the leading edge and the last one on the trailing edge, but drops the middle ones”)

Add timer.done() to `cancel-all` events

---

src/core/Core.js
src/core/Core.test.js
src/core/Plugin.js
src/plugins/Dashboard/index.js
src/plugins/GoldenRetriever/index.js
src/plugins/ReduxDevTools.js
src/plugins/ThumbnailGenerator/index.js
src/plugins/ThumbnailGenerator/index.test.js
src/plugins/Transloadit/index.js
src/plugins/Tus.js
src/plugins/XHRUpload.js
src/server/RequestClient.js

A comment was added to `uppy.state` about it being for "backwards compat" in https://github.com/transloadit/uppy/pull/426. This patch uses `.getState()` instead of `.state` everywhere in our own code.
The reason to prefer `getState()` over `setState()`, IMO, is that they mirror eachother nicely. Unlike `this.state` in React components, `uppy.state` is not a simple object value, but a getter that calls `getState()`. `getState()` could return a different object every time and I think this makes that clearer.
We could start warning for `uppy.state` access, too, but I didn't do that yet here. It's not really a problem for it to exist because it's so simple.

Use uppy.getState() instead of uppy.state.

---

src/core/Core.js
src/plugins/Dashboard/index.js
src/plugins/DragDrop/index.js
src/plugins/Dummy.js
src/plugins/FileInput.js
src/plugins/Url/index.js
src/plugins/Webcam/index.js
src/views/ProviderView/index.js

Follow up to https://github.com/transloadit/uppy/pull/294
Otherwise when restrictions were not met, Uppy would throw an error (now just logs). But when you call `uppy.addFile()` yourself, it will throw as expected.

Add try/catch to `addfile()` calls from UI plugins

---

src/plugins/Instagram/index.js
src/plugins/Tus.js
src/plugins/Url/index.js
src/plugins/XHRUpload.js
src/server/Provider.js
src/server/RequestClient.js
src/views/ProviderView/index.js

this PR allows uppy store provider auth tokens in localstorage instead of cookies. This solves the issue of having to deal with the strict cors requirements of cookies
To test this branch locally, it should be used along with this uppy-server branch https://github.com/transloadit/uppy-server/tree/cookieless-auth
they both have to be merged together

refactor: use local storage to store provider token

---

src/server/RequestClient.js
src/server/RequestClient.test.js

As seen in #879, having a trailing slash in a `host` option breaks
providers:
```js
// does not work: does requests like https://server.uppy.io//drive/list
uppy.use(GoogleDrive, { host: 'https://server.uppy.io/' })
```
This patch strips the trailing slash if it exists so we can always
safely append `/drive/list` and get a well formed URL back.
Closes #879

Tolerate trailing slashes in `host` options.

---

src/plugins/AwsS3/index.js

This strips the query string from the URL used for a successful PUT
upload to determine the `uploadURL`. For PUT uploads, the path that you
use for the upload is the same as the path you use to access the object.
But the query string contains a signature for a PUT request, so it can't
be used for a GET request. Simply removing it is not always enough (the
bucket may restrict GET requests) but it's better than having a PUT
signature in there.
Ref https://github.com/transloadit/uppy/issues/815

s3: Fix uploadURL for presigned PUT uploads

---

src/plugins/ThumbnailGenerator/index.js

Use the polyfill for Math.log2() since IE doesn't support this method
This fixes #891 
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log2#Polyfill

Updated ThumbnailGenerator to work with IE

---

src/core/Core.js
src/core/Core.test.js
src/core/Plugin.js
src/plugins/Dashboard/index.js

- Remove plugins when `uppy.close()` is called, not just uninstall
- Remove plugins immutably
- Emit event, remove plugins from Dashboard when they are removed from Uppy
- Check if plugin exists in Uppy before re-rendering, since debounced re-render can happen after a plugin is removed, that’s been causing issues in #890 
Fixes #890

Fix/refactor close() and removePlugin

---

package-lock.json
package.json
src/plugins/AwsS3/index.js
src/plugins/XHRUpload.test.js

Previously, this would set the uploadURL to the bucket root, which was wrong. Now, it doesn't set it, which is not wrong, just not ideal.
Additionally, when `debug: true`, this logs:
The S3 plugin now depends on `this` inside `getResponseData()` referring to the XHRUpload options object, so I added a test for that as well. We could easily not depend on it, but I think it's expected behaviour anyway (to me at least) … if someone disagrees that it's expected we can ditch that. I added `nock` for this test, we could at least copy the strategy used for this test for other XHRUpload tests.
Closes #668

s3: Don't set uploadURL when success_action_status was missing

---

packages/@uppy/dropbox/src/index.js
packages/@uppy/google-drive/src/index.js
packages/@uppy/instagram/src/index.js
packages/@uppy/server-utils/src/RequestClient.js
packages/@uppy/server-utils/types/index.d.ts
packages/@uppy/url/src/index.js

Since developers are allowed to make uppy-server as custom as they want, it's useful if the client can set custom headers depending on the requirement of their uppy-server.

feature: add support for custom headers sent to uppy-server

---

packages/@uppy/dropbox/src/index.js
packages/@uppy/dropbox/types/index.d.ts
packages/@uppy/google-drive/src/index.js
packages/@uppy/google-drive/types/index.d.ts
packages/@uppy/instagram/src/index.js
packages/@uppy/instagram/types/index.d.ts
packages/@uppy/provider-views/src/index.js
packages/@uppy/server-utils/src/Provider.js
packages/@uppy/server-utils/types/index.d.ts
website/src/docs/dropbox.md
website/src/docs/google-drive.md
website/src/docs/instagram.md

This PR makes the `serverPattern` option more robust by allowing `string|Array|RegExp` values.
It also adds documentation for the option

refactor: allow Array, RegExp, and String for serverPattern

---

website/scripts/highlight.js
website/themes/uppy/source/css/_common.scss

The Prism language for this was not enabled.
Also added the "PHP" tag thing to the top right of PHP snippets.

doc: Fix highlighting of PHP snippets

---

.babelrc
package-lock.json
package.json
packages/@uppy/core/src/Plugin.js

Object rest spread was standardised this year so it's safe to use. It
has shipped in major browsers and Node. Because Uppy uses immutable
state we can make a lot of gains in terseness and readability by using
the new object syntaxes, I think.
I updated one place where we were using Object.assign; I think we can
merge it like this first and then update the other places when we are
changing stuff there anyway or when one of us needs a break from brain
intensive tasks.

Add object rest spread transform

---

package-lock.json
package.json
website/build-examples.js

Now you can make changes to the Uppy source code and the examples on the
website will update without having to run `build:lib` first.
Uses a custom Browserify plugin that turns resolved
`@uppy/xyz/lib/index.js` paths into `@uppy/xyz/src/index.js`. We can
move that plugin to a different file and use it in other places later.
It's a bit of a hack but this is easier than maintaining an aliasify
config for every package, I think.
(Also took this opportunity to ES6ify the examples build script using
`const` / arrows / Set.)

Use src/ files in website examples.

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js

Currently, when aborting a S3 multipart upload in progress, the requests for uploading chunks will continue until completion. Uppy logs a lot of `Not setting progress for a file that has been removed` message and then throws this exception:
```javascript
Uncaught TypeError: Cannot read property 's3Multipart' of undefined
at Object.onPartComplete (index.js?6833:216)
at MultipartUploader._onPartComplete (MultipartUploader.js?8614:190)
at XMLHttpRequest.xhr.addEventListener.ev (MultipartUploader.js?8614:236)
at XMLHttpRequest.wrapped (raven.js?2481:377)
```
With this change, all chunk requests will be cleanly aborted before making the request to abort the upload with Amazon.

Abort all chunk requests when aborting the S3 multipart upload

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js

Currently when a request to prepare upload URL for chunks fails, an uncought promise error is reported in the console (`Uncaught (in promise)` and e.g. `TypeError: Failed to fetch`), and the upload is stuck without reporting any errors.
With this change, the request error is thrown in the uppy's upload method promise.

Catch and handle errors in prepareUploadPart of S3 multipart upload

---

packages/@uppy/core/src/Plugin.js
packages/@uppy/core/src/Plugin.test.js
packages/@uppy/dashboard/package.json
packages/@uppy/dashboard/src/index.test.js

I broke this in the object rest spread PR. I noticed the Dashboard was
throwing errors when trying to access `pluginState.target.filter()`.
Added a bunch of tests + fixed that method!

Fix `setPluginState`

---

examples/aws-presigned-url/main.js
examples/bundled-example/main.js
examples/custom-provider/client/main.js
examples/digitalocean-spaces/main.js
examples/redux/main.js
examples/xhr-bundle/main.js
packages/@uppy/core/README.md
packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
packages/@uppy/core/types/index.d.ts
packages/@uppy/transloadit/src/index.test.js
packages/@uppy/xhr-upload/src/index.test.js
website/src/api-usage-example.js
website/src/docs/index.md
website/src/docs/redux.md
website/src/docs/uppy.md
website/themes/uppy/layout/index.ejs

Uppy used to be initialized with `autoProceed: true` by default, meaning that once a file has been selected, an upload would automatically begin right away. In most examples and demos however, we used to set `autoProceed: false`, because you want the user to be able to edit files, or select more than one, and control when the upload starts.
This PR sets `autoProceed: false` by default, so we can remove the boilerplate in many places.

[WIP] core: `autoProceed: false` by default

---

.travis.yml

Cache the npm cache folder instead of node_modules. If my intuition is right this should be a little faster but it is definitely more correct ever since npm v5 :)
We MAY be able to switch to `npm ci` too which would be even faster, and force us to keep lockfiles up to date. Can check that once this PR is green

ci: cache ~/.npm and use latest npm

---

bin/upload-to-cdn.sh

Check if `$TRAVIS_COMMIT` variable starts with `Release` instead of checking for `TRAVIS_TAG`, which we don’t use since Lerna.

Upload to CDN when commit starts with “Release”

---

packages/@uppy/core/src/index.js

Checking for both `typeof window !== 'undefined' && window.addEventListener` solves the problem 🎉
https://github.com/facebook/jest/issues/6643#issuecomment-410818740
https://stackoverflow.com/questions/49911424/what-does-the-variable-window-represent-in-react-native/49911697#49911697

Fix @uppy/core window !== undefined check for React Native

---

website/scripts/highlight.js

This is server side so we don't need to worry about bundle size anyway.
It'll be best if every language is available to use, so we can't forget
about adding one.
In particular this fixes bash highlighting which is nice for the
Companion env variable list.

website: Load all prism languages

---

packages/@uppy/companion-client/src/RequestClient.js

Firstly, thanks for an amazing project.
I am using Uppy with the `aws-s3-multipart` plugin and my own implementation of the S3 related server endpoints on my existing website (I don't need the other integrations like Dropbox etc). However my website uses cookies for authentication and on many browsers the requests to the server fail because the authentication cookies are not sent with the fetch requests. (eg on Chrome as recent as 67, Safari 11.1)
See https://github.com/github/fetch for more information.
> The current default value for credentials is "same-origin", however some browsers implement an older version of the specification where the default was "omit".
I know I could use the events in the plugin (eg `createMultipartUpload`, `prepareUploadPart` etc) to make these requests to my …

Send cookies with fetch requests

---

.travis.yml

And `web:deploy` already runs install. Speeds up builds :sparkles:

ci: No need to web:install if we're not deploying

---

packages/@uppy/transloadit/src/Assembly.js

Avoids logging an error about missing Uint8Array to the console on old browsers, when the Transloadit plugin is not used. If it is used, the error log will appear, but I don't think it actually matters, because the WebSocket doesn't use socket.io's binary stuff.

transloadit: Lazy load socket.io-client, fixes #1009.

---

packages/@uppy/status-bar/src/StatusBar.js
packages/@uppy/status-bar/src/index.js

Previously this would list the number of in-progress uploads, but once
an upload is finished it is no longer in progress.
Now it lists the number of uploads that were started, i.e. are in
progress or completed.

status-bar: Show number of started uploads, fixes #983

---

packages/@uppy/utils/src/getFileType.js
packages/@uppy/utils/src/getFileType.test.js

If we can't determine the file type, use the generic
'application/octet-stream' type. This way `file.type` will always be
defined and uploaders don't have to worry about it being `null` or
whatever.

utils: Add fallback to getFileType

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
packages/@uppy/aws-s3-multipart/src/index.js

Previously, cancelling an upload would not reset all upload-related
objects used by the S3 Multipart plugin. With this patch, cancellation
behaves similarly to files being removed (they are conceptually similar).

aws-s3-multipart: Proper cleanup on cancellation, fixes #992

---

bin/release

Auto update on every release so we don't have to remember to do it
manually. Update it _before_ doing the release so that the Uppy readme on npm is always up to date.

build: Update readme contributors list before publish

---

packages/@uppy/transloadit/src/Assembly.js

There is not much benefit to this (except saving a few HTTP requests)
but if we do this we'll see if anyone's firewalls are blocking WS or
something. Then one day in the future we can switch to plain WebSockets
instead of socket.io to shed 20KB once the Transloadit backend supports
it. Or we can write a minimal socket.io-compatible alternative that only
uses websockets.
<strike>pls don't merge yet, wanna try it on netlify first</strike> works as intended!

transloadit: Only use socket.io's WebSocket transport.

---

bin/endtoend-build-ci

The integration tests are currently failing pending #1013, and those failures are causing website deploys to fail as well. The website deploy does `npm install`, but the integration test uses a local proxy registry and didn't get a chance to revert back to the global registry if the test failed. With this patch, the registry reset code is moved to an `EXIT` trap, so it's always run when the bash script ends, even if the test fails.

Fix registry once integration test is over

---

packages/@uppy/transloadit/src/index.js

Shows up in the informer and in the console when trying to upload a file
from a remote source. Kinda sucks that you have to actually do it, but
this is the easiest place to implement it…else we have to look at other
plugins' private options and hope that users are adding the plugins in
an order that makes that possible.

transloadit: throw and warn when using the old Uppy Server URL

---

packages/@uppy/companion/src/server/provider/index.js

Even when `server.path` is not null, oauth (`grant`) config is to always redirect to root url

Fix bug: oauth always redirects to root path

---

packages/@uppy/companion/src/server/provider/drive.js
packages/@uppy/google-drive/src/DriveProviderViews.js
packages/@uppy/google-drive/src/index.js

This PR builds on top of #977 to add support for Team Drives.  Although it appears to be fully functional (based on my limited testing), this is mostly a proof of concept and the starting point for a discussion on how Team Drive support should look.  I'm not wedded to the idea of bolting support into the existing Google Drive plugin; it might, for instance, be cleaner to create a separate Team Drive plugin which is restricted to only Team Drives (i.e. no access to the user's regular Google Drive).
Team Drives are currently displayed / handled very similarly to folders: they appear at the top of the root list, and when drilled into, they appear in the breadcrumb trail.
"Dev Nonsense" is a Team Drive; the icon is a small, cropped version of the Team Drive's "background image" and …

Google Drive: Support Team Drives

---

bin/release

- Check that the registry is configured correctly.
- Check that we are signed in.
- Check that 2FA is not enabled for publishing.
The first two checks may fail if the local verdaccio registry was recently used.
The last check may be removed in the future once lerna supports OTP.

Add more checks to release script

---

test/endtoend/providers/test.js
test/endtoend/utils.js
test/endtoend/wdio.local.conf.js
test/endtoend/wdio.remote.conf.js

currently when the test runs on travis, we are getting multiple occurrences of port conflicts. So it seems that we are starting companion multiple times as we run parallel browser sessions

tests: start companion once

---

packages/@uppy/dashboard/src/components/AddFiles.js
packages/@uppy/dashboard/src/style.scss

Improve the “info bar” with note and “powered by uppy” positioning on mobile

---

packages/@uppy/dashboard/src/components/FileItem.js
packages/@uppy/dashboard/src/index.js

> Usually the tooltip over the preview thumbnails shows the text "pause upload", but when the upload failed and there is a retry overlay (over the preview), the tooltip is not changed and still says "pause upload" (instead of "retry upload")
Fixes #1033

[Dashboard] Fix incorrect title (tooltip) message on file preview by refactoring

---

packages/@uppy/dashboard/src/components/Dashboard.js
packages/@uppy/dashboard/src/index.js
website/src/docs/dashboard.md

Requested in #717 (and closes #717 if merged):
> I'd like to use the Dashboard component, but not show the list of added files, because I display them elsewhere on the page. it would be handy to have an option to disable the file list.
This adds `showSelectedFiles: true` option, when `false` the `FileList` and `PanelTopBar` (that displays number of selected files, cancel button and a plus button) are never shown, you add files and keep seeing the “drop files here” prompt.
Docs explanation:
> Show the list (grid) of selected files with preview and file name. In case you are showing selected files in your own app’s UI and want the Uppy Dashboard to just be a picker, the list can be hidden with this option.
> 
> See also `disableStatusBar` option, which can hide the progress and upload …

[Dashboard] add showSelectedFiles option

---

packages/@uppy/dashboard/src/components/PanelTopBar.js

When you can only select 2 files and 2 are already selected, it makes no sense to show a plus button in the Dashboard. This PR fixes that.
> Hi, I have to handle each image separately in the application by assigning each image several properties, such as date, credit, photographer and so on. It doesn't make sense to support multiple files for that particular interface. I can set the max number of files to 1, however the Dashboard interface could be confusing to users since they present the add (+) button when a file has already been picked while I'd prefer to tell Dashboard to not display that button by either enabling some single-selection mode or by having it behaving differently by not showing that button when the number of files has already reached its limit.
Fixes …

[@uppy/dashboard] Only show the plus button if selected file count !== maxNumberOfFiles

---

website/src/docs/index.md
website/themes/uppy/source/css/_page.scss

Tim:
> It would be nice to have that html file redy on uppy.io as a copy paste example to sav
> I then read further down the manual and get instructions for the script tag, browserify, etc.
I still lack the html example. It would be nice to have some basic html with a link with id "select-files".
Went with inline Dashboard, cause it’ll appear on the page right away, so feels simpler? Open for suggestions though.

[docs] Add a copy-paste-able and easily understandable Uppy CDN example that works right away

---

packages/@uppy/dashboard/src/index.js

Follow up on https://github.com/transloadit/uppy/pull/1073, can’t wait — this needs an urgent fix and a patch release.
Fixes #1070.
@goto-bus-stop:
> I think we need to do: require('resize-observer-polyfill').default || require('resize-observer-polyfill'), to support both the transpiled version of its ES module format and its CommonJS format. A bit like we did here (although for a different related reason): https://github.com/transloadit/uppy/blob/4684a3e1f3bb43ed59c4ffcda73093cdbe1ddf0d/packages/%40uppy/form/src/index.js#L3-L5

Fixing ResizeObserver is not a constructor, issue #1070

---

packages/@uppy/core/src/Plugin.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/url/src/index.js
packages/@uppy/webcam/src/index.js

Fixes https://github.com/transloadit/uppy/issues/1057 (hopefully ;-)
- Add `onMount` to Plugin which can be used when access to`this.el` is needed
- Add `this.parent` to Plugin, which can be used to access parent plugin like `this.parent.hideAllPanels()` — no need to fish the plugin by id
- Automatically hide panels in Dashboard when a file is added (up until now Providers manually called `hideAllPanels`, which is not ideal — Providers shouldn’t be concerned about Dashboard)

[@uppy/core] Add onMount and this.parent to Plugin

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js

We have an `uppy.cancelAll` in `@uppy/core`. It used to just set `files` object in `uppy.state` to an empty object `{}`. This PR changes this to instead call `uppy.removeFile` on each file in state, because:
> When I click Cancel in the top bar of the dashboard, the state of the dashboard resets and all the already-uploaded files go away, but corresponding file-removed events are not triggered for each uploaded file, which I need so I can properly clean up app state.
> Yeah, the Cancel button uses a different event, cancel-all. We work around this in Uppy's own source code by listening for both file-removed and cancel-all. It's come up before that making the cancel-all action emit file-removed for each file would be easier and less surprising but we never acted on it yet, so thanks for …

Call `removeFile` on each file when doing `cancelAll`

---

packages/@uppy/utils/src/getFileTypeExtension.js
packages/@uppy/utils/src/getFileTypeExtension.test.js

Chrome's MediaRecorder mime types include metadata about the codecs used in container formats like webm and mkv. This patch discards it when determining the file extension to use.

Support mime types with additional data, fixes #1074

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
packages/@uppy/dashboard/src/components/PanelTopBar.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/status-bar/src/StatusBar.js
packages/@uppy/status-bar/src/index.js
website/src/docs/uppy.md

Adds an `allowMultipleUploads` option to @uppy/core. If set to false, `uppy.upload()` can only be called once. Afterward, no new files can be added and no new uploads can be started.
This is intended to serve the `<form>`-like use case.
TODO:

Single-use Uppy instance

---

packages/@uppy/core/src/index.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/xhr-upload/src/index.js
website/src/docs/uppy.md

Fixes #797
- Document methods: cancelAll, document more methods: removePlugin, getPlugin, retryAll, retryUpload, pauseResume, resumeAll, pauseAll
- Document events: upload-retry, cancel-all
- remove `upload-cancel` event — `file-removed` should be enough
⚠️Needs careful review, since this might break something, plus warnings in changelog. This is a good opportunity to re-think some events and their names, so that we cement them before 1.0.

[WIP] [@uppy/core] Document events, deprecate unused

---

packages/@uppy/aws-s3/package.json
packages/@uppy/aws-s3/src/index.js
website/src/docs/aws-s3.md

RequestClient contains the Uppy Companion specific stuff, so we don't have to think about that when working on the S3 plugin.
This fixes an issue where AwsS3 did not use `credentials: 'same-origin'` by default for Companion requests, where the other plugins do.
This also adds support for the RequestClient's `serverHeaders` option.
Finally, when we change the `server*` option names again, we only have to do it in RequestClient and it'll apply here too :)

aws-s3: Use RequestClient, fixes #1088

---

packages/@uppy/transloadit/src/index.js
website/src/docs/transloadit.md
website/src/examples/transloadit/app.es6

Simplify configuration of remote providers by having a `serverPattern` counterpart to `Transloadit.COMPANION`.
Initially, I wanted to auto configure this inside the Transloadit plugin, but the `serverPattern` option is passed through some constructors down to the `Provider` class, which is really internal to provider plugins. Instead of reaching through several private layers, this seems the nicer option…

transloadit: Add COMPANION_PATTERN constant.

---

packages/@uppy/transloadit/src/AssemblyOptions.js
packages/@uppy/transloadit/src/index.js

- Update API key URL in the `auth.key` error message. The old URL still worked but not having to redirect is nice
- Error early if neither `params` nor `getAssemblyOptions` are given.

transloadit: Error tweaks

---

packages/@uppy/core/src/index.js
packages/@uppy/thumbnail-generator/src/index.js
packages/@uppy/thumbnail-generator/src/index.test.js

This is a little clearer than doing it in core.
It now also deals with files being removed while a thumbnail generation job is still in the queue.

Move preview revocation to thumbnail-generator

---

packages/@uppy/thumbnail-generator/src/index.js
packages/@uppy/thumbnail-generator/src/index.test.js

This will allow to define a thumbnail height besides the width, as explained in #979.
Thumbnails will be created as follows to maintain backwards compatibility:
`ThumbnailGenerator(uppy, { })` will produce a `200px` width thumbnail with calculated height to match ratio. 
`ThumbnailGenerator(uppy, { thumbnailWidth: 300 })` will produce a `300px` width thumbnail with calculated height to match ratio. 
`ThumbnailGenerator(uppy, { thumbnailHeight: 300 })` will produce a `300px` height thumbnail with calculated width to match ratio. 
`ThumbnailGenerator(uppy, { thumbnailWidth: 300, thumbnailHeight: 300 })` will produce a `300px` width thumbnail with calculated height to match ratio (and ignore the given height).

Allow to constrain thumbnail height - Fixes #979

---

packages/@uppy/companion/package.json

It was listed both under `dependencies` and `devDependencies`.
This was added for the automated companion.uppy.io deploys so we should check that those still work after merging this.

companion: Remove duplicate typescript dependency

---

website/src/docs/dashboard.md

Just saw that addMoreFiles is not mentioned in the locale docs for Dashboard.
I am not sure about the `"When inline false"` part, just copied it from the other items.
Also, see #1109

Add missing addMoreFiles string to locale

---

packages/@uppy/dashboard/src/index.js
packages/@uppy/status-bar/src/StatusBar.js
website/src/docs/dashboard.md

This tries to prevent itself from being used in a way that would be confusing or unexpected.
- When `allowMultipleUploads` is `true`, logs a warning to the console saying that that is probably not a good experience
- When `inline` is `true`, throws an error because that just does not make sense
- When some uploads failed, the auto-close behaviour is prevented, so the user can try to fix it or cancel.
The option is named after the `hideAfterFinish` options in Status Bar and Progress Bar.
Needs some more testing in funny situations with uploads failing, succeeding, processing etc

Dashboard: Auto close after finish using `closeAfterFinish: true` 

---

packages/@uppy/aws-s3/src/index.js
packages/@uppy/core/src/index.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/drag-drop/src/index.js
packages/@uppy/file-input/src/index.js
packages/@uppy/status-bar/src/index.js
packages/@uppy/transloadit/src/index.js
packages/@uppy/utils/src/Translator.js
packages/@uppy/utils/src/Translator.test.js
packages/@uppy/webcam/src/index.js
packages/@uppy/xhr-upload/src/index.js

In the beginning we used to have unified locale packs that everything in Uppy used — English, Russian, Polish. Then we switched to per-plugin locales, and the ability to load one locale pack was lost for a while. This PR aims to bring this functionality back.
Goal: you have a language pack that you load `const uppy = Uppy({ locale: german})`, plugins have their own `defaultLocale`, which are used when locale pack is not used, or string is not included in that locale pack (it will include most common strings used by standard Uppy plugins maintained in this repo). Then when adding a plugin, you can also override one particular string to your liking, while keeping others from the pack:
```js
.use(Dashboard, {
trigger: '#pick-files',
locale: {
strings: {
dropPasteImport: 'Something else here, …
```

Bring back locale packs

---

bin/make-new-versions-table

Uses the git tags rather than the commit message. That should be more stable for the future too.
@arturi

Fix new versions table script.

---

examples/aws-presigned-url/serve.js
packages/@uppy/aws-s3/src/index.js
packages/@uppy/xhr-upload/src/index.js
website/src/docs/xhrupload.md

This allows configuring the XMLHttpRequest `.responseType` value. Use cases for this are going to be quite rare I think, but it allows the S3 plugin to tell Firefox not to log XML errors when getting empty responses, so it finally fixes #518 :)
Because AwsS3 now sets `responseType: 'text'`, we can no longer use the `responseXML` property. We already did text based parsing for successful responses and now do the same for error responses.

xhr-upload: Add `responseType` option

---

bin/endtoend-build-ci

Needed some fiddling but the solution is quite simple. After building integration tests, we revert to the commit we were on _before_ building integration tests. That removes the changes lerna makes during the publish to the local registry.
Current output (v0.28.1-alpha.0): https://github.com/transloadit/uppy/blob/91c891db00965628686c00be61171a197e93c4b1/examples/dashboard/index.html#L325-L331
New output (v0.28.0): https://github.com/transloadit/uppy/blob/test-deploy-numberfix/examples/dashboard/index.html#L325-L331

Fix version numbers used for website build

---

packages/@uppy/react/src/propTypes.js

Your prop type for width is restricted to numbers, although 100% works(I am using it), and is useful, also your Drag and Drop component allows strings, so allowing both is more consistent.

react: Allow Dashboard props width and height to accept a string for 100%

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js

This fixes an error when files are removed during an upload, eg. by a plugin that does some filtering.
`uppy.removeFile()` already removes the fileID from the
`currentUploads[*].fileIDs` list, so all we need to do is to pass the
updated array instead of the original!
The code around the `.addResultData()` call had to be moved around a bit,
because we now need to use the `currentUpload.fileIDs` list to set the
`.successful` and `.failed` properties.

Don't pass removed file IDs to next upload step, fixes #1003

---

packages/@uppy/companion/src/server/controllers/callback.js

E.g. dropbox wasn't working because state was stored under the dynamic property.

Fix handling of grant state

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
packages/@uppy/status-bar/src/StatusBar.js
packages/@uppy/status-bar/src/index.js

When possible, file sizes are used when calculating the `.totalProgress` value.
If there are files without sizes, the average size of all other files is assumed for the unsized files.
If there are no files with sizes, the percentage is just based on the percentages of the unsized files.
I think we could try in the future to remove the unsized files code or to assume 0% for them, because while testing this it seemed like files could only be unsized while they had not started uploading—eg. instagram don't have file sizes at the start, but once they've been downloaded on Companion, Companion starts emitting events with `bytesUploaded` and `bytesTotal` values. I'm not sure if there's any other case where we may have unsized files though so we could save that for a later time.

Use file sizes for progress calculations, closes #1132

---

packages/@uppy/companion/src/server/helpers/utils.js

This breaks existing keys, so users will have to reauthenticate.
The `secret` key for AES256 must be 32 bytes long, createCipher didn't care (I think it derived a 32 byte key from whatever you gave it?) but createCipheriv does. To ensure that the key is 32 bytes, this hashes the user-provided `secret` using SHA256.
The iv can just be random, but it has to be available for createDecipheriv to work. This patch sticks it in front of the encrypted text, since it's always 16 bytes we can take the first 16 bytes (32 hex chars) in our `decrypt()` function and use it as the iv to decrypt the remaining chars.

Use createCipheriv instead of deprecated createCipher, fixes #1145.

---

packages/@uppy/dropbox/src/index.js
packages/@uppy/google-drive/src/index.js
packages/@uppy/instagram/src/index.js
packages/@uppy/provider-views/src/index.js

This was a bit weird and now it's not. Passing the Provider instance to `ProviderViews` as an option instead of having it look it up on the Plugin object.

Store Provider instances on `this.provider` instead of `this[this.id]`.

---

packages/@uppy/dashboard/src/index.js

This message looked just like other debug messages for Uppy so I didn't notice it for a while! I think we can safely assume that it's an error if somenoe tries to set a nonexistent element as the modal trigger. If they don't want a trigger they shouldn't pass the option.

dashboard: Log error if `trigger` is not found.

---

packages/@uppy/xhr-upload/src/index.js

The same restriction applies to `responseType` as to `withCredentials`.
Both must be set _after_ the open() call in Internet Explorer.

xhr-upload: Fix `responseType` in IE 11, fixes #1228

---

website/src/docs/aws-s3.md

In my case, following the Uppy S3 documentation related to CORS by the letter still resulted in 403 responses with `AccessDenied` from my bucket's HTTP endpoint when my browser tried to upload a file.
It seems like S3 introduced an additional layer of security which generally overrides any public access settings in other places to protect inexperienced S3 users from accidentially making content in their S3 buckets public - at least this is my interpretation.
Therefore I extended the docs to inform Uppy users about the additional measures they potentially need to take.

Update aws-s3.md wrt S3 public access settings

---

packages/@uppy/xhr-upload/src/index.js

(i.e. has left browser concurrency queue (fixes transloadit#1190).

Postpone timeout countdown until upload has started

---

bin/build-lib.js
bin/release
package.json

This makes it faster in most cases, so we have to wait less.
The FRESH=1 environment variable forces recompiling all source files,
and is used in the release script to be doubly sure that everything
we publish is up to date.
```bash
FRESH=1 npm run build:lib
```

Only rebuild changed files with `npm run build:lib`

---

packages/@uppy/react/src/DashboardModal.d.ts

This prop was not marked as optional so that the Typescript compiler complains if it is not present. Fixed.

Typescript: Make DashboardModal.target prop optional

---

packages/@uppy/react/src/Dashboard.js
packages/@uppy/react/src/DashboardModal.js
packages/@uppy/react/src/DragDrop.js
packages/@uppy/react/src/ProgressBar.js
packages/@uppy/react/src/StatusBar.js
packages/@uppy/react/src/Wrapper.js

When changing the Uppy instance, the components will uninstall the UI plugin from the old instance, and install it to the new instance.
One other thing that I wanted to do is warn when you create the Uppy instance in the render() method. that becomes harder when this use case is supported. If we didn't support changing instances, we could simply throw an error if the `uppy` prop ever changes. If we support changing instances, I'm not sure how we'd detect Uppy instances being created in render().

 react: Allow changing instance in `uppy` prop 

---

packages/@uppy/dashboard/package.json
packages/@uppy/dashboard/src/index.js

- Allow multiple dashboard states in the history
- Check if a popstate() event could actually do anything to this modal,
previously we could do `closeModal()` on a modal that was already
closed
- fix modal entering broken state when `closeModal()` is called on a modal
that was already closed (now is a noop)
Fixes #1239

dashboard: Fix issues with multiple modals

---

packages/@uppy/aws-s3/src/index.js

Editing the `name` meta property in the Dashboard UI is reflected in the object name on S3.
Programmatically you can do:
```js
uppy.setFileMeta(fileID, {
name: 'object/key/path.txt'
})
```

s3: Use user provided filename / type for uploaded object, fixes #1238

---

packages/@uppy/aws-s3-multipart/src/index.js
packages/@uppy/core/src/index.js
packages/@uppy/tus/src/index.js
packages/@uppy/xhr-upload/src/index.js
website/src/docs/uppy.md

Change all `upload-success` events to emit:
```js
const body = opts.getResponseData(xhr.responseText, xhr)
const uploadURL = body[opts.responseUrlFieldName]
const uploadResp = {
status: ev.target.status,
body,
uploadURL
}
this.uppy.emit('upload-success', file, uploadResp)
```
Core then sets response and uploadURL on the file object:
```js
{
...
response: uploadResp,
uploadURL: uploadResp.uploadURL
}
```
`uploadURL` will not be passed as a separate parameter anymore, but instead inside the `uploadResp` object.
Hopefully this solves https://github.com/transloadit/uppy/pull/871 and https://github.com/transloadit/uppy/pull/1065.
todo:

Set response in Core rather than in upload plugins

---

packages/@uppy/core/src/index.js

Don’t emit a complete event if an upload has been canceled

---

bin/build-css.js
bin/build-js.js
bin/upload-to-cdn.sh

- In `@uppy/robodog/dist` call css and js files `robodog.js` and `robodog.css`, instead of `transloadit.js` and `style.css`
- Copy `@uppy/robodog/dist` to `uppy/dist/robodog` before uploading to CDN
So Robodog will be available from CDN as:
https://transloadit.edgly.net/releases/uppy/v0.30.0/dist/robodog/robodog.min.css
https://transloadit.edgly.net/releases/uppy/v0.30.0/dist/robodog/robodog.min.js

Add Robodog to CDN

---

packages/@uppy/companion-client/src/Provider.js
packages/@uppy/companion/src/server/controllers/callback.js
packages/@uppy/companion/src/server/controllers/index.js
packages/@uppy/companion/src/server/controllers/send-token.js
packages/@uppy/companion/src/uppy.js
packages/@uppy/companion/test/__tests__/companion.js
packages/@uppy/companion/test/mockserver.js
packages/@uppy/dropbox/src/index.js
packages/@uppy/google-drive/src/index.js
packages/@uppy/instagram/src/index.js
packages/@uppy/provider-views/src/index.js

Providers can be instantiated with a `storage` module that behaves similarly to `localStorage` [here](https://github.com/transloadit/uppy/blob/7a4219ee989e15373c8d92cd941c061539a9deb7/examples/bundled-example/main.js#L32-L34)
The auth URL can also be called similarly as done [here](https://github.com/transloadit/uppy/blob/7a4219ee98/packages/%40uppy/provider-views/src/index.js#L452-L453), but with an additional `redirect` option specified. Like so:
```js
const authState = btoa(JSON.stringify({ origin: location.origin, redirect: location.href }))
const link = `${this.Provider.authUrl()}?state=${authState}`
```
If this is done on react-native (on the same window, not a new one), Companion will redirect to the redirect value set after the OAuth dance is done with a `uppyAuthToken` query …

Make providers support react native

---

packages/@uppy/aws-s3/src/index.js

There is a case where a fileId no longer exists in uppy, namely if the
file is removed from uppy before `getUploadParameters` returns.
fixes #1317

[AWS-S3] Avoid throwing error when file has been removed

---

packages/@uppy/companion/infra/kube/companion/companion-kube.yaml

This will enable pods to use all resource available by the node without setting hard limits on requirements. Makes part of moving to smaller nodes.

Remove resources requirements for companion

---

packages/@uppy/xhr-upload/src/index.js

This allows for the 'complete' event to be properly triggered after uploads have succeeded, failed, or been cancelled.
fixes #1315

[XHRUpload] Reject cancelled uploads

---

README.md
packages/@uppy/aws-s3-multipart/README.md
packages/@uppy/aws-s3/README.md
packages/@uppy/core/README.md
packages/@uppy/dashboard/README.md
packages/@uppy/drag-drop/README.md
packages/@uppy/dropbox/README.md
packages/@uppy/file-input/README.md
packages/@uppy/form/README.md
packages/@uppy/golden-retriever/README.md
packages/@uppy/google-drive/README.md
packages/@uppy/informer/README.md
packages/@uppy/instagram/README.md
packages/@uppy/progress-bar/README.md
packages/@uppy/react/README.md
packages/@uppy/redux-dev-tools/README.md
packages/@uppy/status-bar/README.md
packages/@uppy/store-default/README.md
packages/@uppy/store-redux/README.md
packages/@uppy/thumbnail-generator/README.md
packages/@uppy/transloadit/README.md
packages/@uppy/tus/README.md
packages/@uppy/url/README.md
packages/@uppy/webcam/README.md
packages/@uppy/xhr-upload/README.md

webpack.github.io is for webpack v1, which has been unmaintained for a while…

docs: update webpack homepage URLs

---

packages/@uppy/robodog/README.md

Fix the module name in a few places, remove the old proposal text, link to the correct docs.

robodog: update readme

---

packages/@uppy/provider-views/src/style.scss

maybe @arturi already has a WIP branch for addressing some of these but i noticed this simple fix too :)
in examples/dev, we have a `li { margin: 60px }` declaration that lols the provider view lists. this patch sets the provider view list entries to have 0 margin.
before:
after:

provider-views: eliminate conflicting file list margin

---

packages/@uppy/companion/src/server/Uploader.js
packages/@uppy/companion/src/server/controllers/get.js
packages/@uppy/companion/src/server/controllers/url.js

noticed in #1350, if the validation fails we still try to use the Uploader instance, but it will be in an invalid state (none of the members are populated).
instead, after instantiating an Uploader we need to check if it's valid and respond with the error immediately if it's not.

companion: do not use Uploader instance if options validation failed

---

examples/transloadit-textarea/index.html
examples/transloadit-textarea/main.js
examples/transloadit-textarea/template.json

Uses transloadit's temporary storage. The template JSON is available in `template.json`.
I added some explanation about the example to the html as well.
@arturi

examples: use template + demo key for transloadit-textarea example

---

packages/@uppy/core/src/index.js
website/src/docs/uppy.md

In some languages, it probably doesn't make much sense to put the list
of allowed file types at the end.
The list of mime types/extensions may not be desired at all, so now you
can omit `%{types}` to not show it.

core: un-hardcode concat in `youCanOnlyUploadFileTypes` locale

---

packages/@uppy/companion/src/standalone/helper.js

While trying to setup the companion server, I noticed the callback URIs suggested on the main page are incorrect

Updated the callback URIs to reflect their correct location

---

packages/@uppy/companion-client/src/Provider.js
packages/@uppy/companion-client/src/RequestClient.js
packages/@uppy/companion-client/src/tokenStorage.js

this PR Promisifies token storage, in order to support all kinds of storages (including React Native's Async Storage)

companion-client: add asyn wrapper around token storage

---

packages/@uppy/companion-client/src/AuthError.js
packages/@uppy/companion-client/src/Provider.js
packages/@uppy/companion-client/src/RequestClient.js
packages/@uppy/companion/src/server/controllers/get.js
packages/@uppy/companion/src/server/controllers/list.js
packages/@uppy/companion/src/server/controllers/thumbnail.js
packages/@uppy/companion/src/server/logger.js
packages/@uppy/companion/src/server/provider/drive/index.js
packages/@uppy/companion/src/server/provider/dropbox/index.js
packages/@uppy/companion/src/server/provider/error.js
packages/@uppy/companion/src/server/provider/instagram/index.js
packages/@uppy/core/src/index.js
packages/@uppy/dropbox/src/index.js
packages/@uppy/google-drive/src/index.js
packages/@uppy/instagram/src/index.js
packages/@uppy/provider-views/src/AuthView.js
packages/@uppy/provider-views/src/index.js

return 401 for invalid access token so that the `/authorized` endpoint can be deprecated

companion: return 401 for invalid access token

---

packages/@uppy/companion/infra/kube/companion/companion-kube.yaml

This PR changes the type of data we store on kubernetes from configmap to a secret which is more suitable. I already applied the change on our secrets repo and kept the configmap which can be deleted after this is merged.

Change type on companion from configmap to secret

---

packages/@uppy/companion/src/server/provider/drive/adapter.js
packages/@uppy/provider-views/src/style.scss

Show thumbnails instead of a generic icon in Google Drive

---

website/src/docs/companion.md

The `companion` command would not work if not install globally

Requires -g param

---

packages/@uppy/dashboard/src/components/Dashboard.js
packages/@uppy/dashboard/src/style.scss

___Why not just use `justify-content: space-between`?
Because making the last row items flock to the left side tends to be a trouble, solutions would be either not very browser-compatible, or would include some Js.

Dashboard Plugin: made list items even out

---

packages/@uppy/aws-s3-multipart/types/aws-s3-multipart-tests.ts
packages/@uppy/aws-s3/types/aws-s3-tests.ts
packages/@uppy/dashboard/types/dashboard-tests.ts
packages/@uppy/transloadit/types/transloadit-tests.ts
packages/uppy/types/index.d.ts
test/endtoend/typescript/main.ts
tsconfig.json

Synthetic default imports allow you to `import X from 'x'` if `'x'` is a
CommonJS module. Our `uppy` package relied on that (probably forgot to
update it in a previous patch). If users had set
`allowSyntheticDefaultImports: false`, they would not be able to use the
`uppy` package.
We should at some point go through the typings again and set everything to
the tightest options, because that'll work with the widest array of users,
but for now let's just unbreak this particular case.
Fixes #1395

typescript: fix uppy package use with allowSyntheticImports: false

---

packages/@uppy/core/src/index.js

Since it’s probably unnecessary now and not supported in React Native.
//cc @kvz

Remove console.dir

---

packages/@uppy/xhr-upload/src/index.js
packages/@uppy/xhr-upload/src/index.test.js

I found that the code to determine the upload status is coupled and fixed.
Allowing user to customize the status of upload (still kept its default behavior) makes it more flexible (I actually need this feature badly)
And I also add the unit test, all seems well

allow customized option to set upload status

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
website/src/docs/uppy.md

supports #1251, since I met a similar situation when I need to show my own system notice instead of Uppy's Informer.

feat: fire event when restriction-failed

---

packages/@uppy/core/src/index.js

pass the message parameter separately so the browser can display fancy interactive trees for them.
Also removes the uppyLog variable which i don't think is used by anyone

core: fix logging objects

---

examples/transloadit-textarea/main.js
packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
packages/@uppy/dashboard/src/components/FileItem.js
packages/@uppy/dashboard/src/components/FileItemProgress.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/dashboard/src/style.scss
packages/@uppy/transloadit/src/AssemblyOptions.test.js
packages/@uppy/transloadit/src/AssemblyWatcher.js
packages/@uppy/transloadit/src/Client.js
packages/@uppy/transloadit/src/index.js
packages/@uppy/xhr-upload/src/index.js

When all files are cancelled, we cancel the Assemblies too.
The patch is actually quite small, needed some time to figure out the ordering and such tho.
If files are uploaded with XHRUpload `bundle:true` or Transloadit, they cannot be individually removed. With Transloadit+Tus, you can still individually pause/resume files.
Try it using: https://deploy-preview-1431--uppy.netlify.com/examples/markdown-snippets/

transloadit: Assembly cancellation

---

packages/@uppy/tus/src/index.js

This fixes an issue that occurs when using tus and the limit option to limit the number of parallel uploads.
When you cancel the current uploads, you can't start new uploads after adding new files.
This is because the queue in limitPromises is not emptied on cancel,
due to the upload promise not being resolved or rejected on cancel.
This fixes the issue.

tus: fix cannot start more uploads after cancel

---

packages/@uppy/companion-client/src/Provider.js

Issue a warning if an outdated `serverUrl` or `serverPattern` option is used

---

examples/transloadit/index.html
examples/transloadit/main.js
examples/transloadit/readme.md
packages/@uppy/dashboard/src/index.js
packages/@uppy/robodog/src/dashboard.js
packages/@uppy/robodog/src/index.js
packages/@uppy/robodog/src/pick.js
website/src/docs/robodog-dashboard.md
website/src/docs/robodog-form.md
website/src/docs/robodog.md

- Update "kitchen sink" robodog example with descriptions for each API
- Update "kitchen sink" robodog example to a demo account key with a simple demo template (previously used my old key :scream: )
- Adds default-inline `robodog.dashboard()` API, returning an Uppy instance like the `robodog.form()` API.

robodog: add Dashboard API

---

packages/@uppy/core/src/_variables.scss
packages/@uppy/dashboard/src/style.scss

1. Fixed a problem when the outer border color was too bright:
2. Harmonized the dashed borders: that we have by default and that we have when dragging some file(s).

Fix border colors

---

packages/@uppy/provider-views/src/index.js

I wondered if there’s a simple solution, and this seems to work! So maybe it’s less complex than we anticipated, or am I missing something @ifedapoolarewaju? Auth error informer is not shown, while other errors are.
https://github.com/transloadit/uppy/issues/1425

Don’t show informer for an auth error

---

package-lock.json
packages/@uppy/core/package.json
packages/@uppy/dashboard/package.json
packages/@uppy/drag-drop/package.json
packages/@uppy/dropbox/package.json
packages/@uppy/file-input/package.json
packages/@uppy/google-drive/package.json
packages/@uppy/informer/package.json
packages/@uppy/instagram/package.json
packages/@uppy/progress-bar/package.json
packages/@uppy/provider-views/package.json
packages/@uppy/status-bar/package.json
packages/@uppy/url/package.json
packages/@uppy/webcam/package.json

Webpack likes to pick the ES module versions of modules over CJS
versions. So, if we do `require('preact')`, we can get the ES module
version of it. preact in version 8.3.0 switched its file extension
from `.esm.js` to `.mjs`, which in webpack's default configuration meant
the module implementation became much stricter. The result is that we
get a different value in `require('preact')`.
This older version of preact doesn't use `.mjs` yet so we can safely
`require('preact')` it in webpack. It still picks the ESM version, but
now it uses the looser implementation which is interchangeable for our
purposes.

pin preact to 8.2.9

---

.github/CONTRIBUTING.md

URL: https://uppy.io/docs/contributing.html
The generated `id` for the `Local previews` `h3` element is `Local-previews`.
The anchor linking to that element was looking for `Local-Previews` (capital P), and thus wasn't scrolling to the element.

Fix wrong destination anchor link

---

website/src/_posts/2017-10-0.21.md

At the time of this release, the tokens were not being encrypted. This information was falsely added because I thought JWT encrypts its tokens before it was eventually brought to my attention by @goto-bus-stop that this was not the case. It is in subsequent versions that an actual encryption was implemented.

correct info on blog post about older Uppy server version

---

website/src/docs/aws-s3-multipart.md

Blame it on me, but because the documentation only talked about the additional `ExposeHeader` tag for the `ETag` header, I honestly believed that the `<AllowedMethod>PUT</AllowedMethod>` was a mistake and that the allowed method must be `POST`, as with the "normal" S3 upload. I'm thus proposing to change the documentation to make it crystal clear.

Update AWS S3 Multipart documentation wrt CORS settings

---

website/src/docs/index.md

The Browser Support link in the Installation doesn't work in browsers as it's `#browser-support` instead of `#Browser-Support`

Fix Browser Support link in Installation section

---

packages/@uppy/xhr-upload/src/index.js

Pretty simple one, check is made for "uploadURL" and log is called with "file.uploadURL", which returns undefined. I've fixed it.

Corrects path logging

---

packages/@uppy/utils/src/mimeTypes.js

This fixes a firefox bug, where on folder drop pdf/txt file previews were not getting shown .

mimeTypes.js - added pdf file type

---

CHANGELOG.md
packages/@uppy/companion/src/server/Uploader.js
packages/@uppy/companion/test/__tests__/companion.js
packages/@uppy/xhr-upload/src/index.js

submitting this as a PR in case there is an uploader on Uppy client which relies on the default protocol to be set on companion's end. cc @arturi @goto-bus-stop

companion: remove default upload protocol

---

website/src/docs/thumbnail-generator.md

The first argument is not the file ID, but the whole file object.

Thumbnail Generator – Update arguments in "thumbnail:generated" callback docs

---

website/src/docs/xhrupload.md

The second argument of the callback is now a `response` object with `status` and `body` properties. The `file` object doesn't contain a `response` property anymore.

xhr-upload: Update the `upload-success` event docs

---

packages/@uppy/aws-s3/src/index.js

Per documentation at https://uppy.io/docs/aws-s3/, `fields` can be empty. 
"For presigned PUT uploads, this should be left empty."
Adding a safety check before attempting to extract keys.

Do not extract keys from empty `fields`.

---

packages/@uppy/companion/infra/kube/gcloud-deploy.sh

This updates the script that pushes to docker hub to use Github Tags if they're available for easier version identification and release management.

Fix tags for docker build

---

packages/@uppy/dashboard/src/style.scss

@uppy/dashboard - made added-files previews look more proportional

---

packages/@uppy/informer/src/index.js
website/src/docs/informer.md

Informer has adopted black and white lifestyle quite a while ago, this removes information about color options and related code.

informer: Remove color-related code and docs

---

packages/@uppy/companion/src/server/Uploader.js

companion: set upload  filename from metadata during uploads

---

website/src/docs/stores.md

Docs > Custom Stores > Implementing Stores
link to store-default at the bottom of the page was outdated/broken.
Update to new store-default location in packages/@uppy/src/store-default.

Docs > Custom Stores > Fix store source link

---

packages/@uppy/golden-retriever/src/index.js

Without this PR, `.use(GoldenRetriever)` without options was throwing an error.
How we never discovered this until now is a mystery to me.

golden-retriever: Use this.opts instead of opts

---

packages/@uppy/dashboard/src/index.js

It's a manually cherry-picked PR #1583, because that one was based on the accessibility branch (that diverged with this PR anyway).
Chrome: works
Firefox: works
Safari: works
Edge: works
IE11: doesn't work, I believe IE11 doesn't yet support file pastes (https://caniuse.com/#search=paste).
Closes #1577

@uppy/dashboard - made paste work while we're focused on buttons

---

packages/@uppy/companion/package-lock.json
packages/@uppy/companion/package.json
packages/@uppy/companion/src/server/provider/dropbox/adapter.js

companion: return mimetypes for dropbox files

---

packages/@uppy/utils/src/getDroppedFiles/index.js

Fixes #1622, checked in real IE11 on Windows.

@uppy/utils - made getDroppedFiles.js work for IE11

---

packages/@uppy/provider-views/src/index.js

provider-views: make trailing slash optional when validating auth origin

---

packages/@uppy/companion/src/server/Uploader.js

S3 stores the remote-url of the newly stored file in the `Location`-property of the response. Use it as remote-url-param.
Fixes https://github.com/transloadit/uppy/issues/1607

Fix(1607): Add remote-url to emit-success

---

bin/upload-to-cdn.js
package.json

The mime-types library is already in use by companion, hence no lockfile
update
Tested with my personal bucket

Fix mime types on CDN

---

packages/@uppy/tus/src/index.js
website/src/docs/tus.md

A quick copy-paste hackjob from XHRUpload.
Tested manually on the `examples/transloadit/` `robodog.dashboard()` example, since the Transloadit plugin was already using this unsupported option. Without this patch, uploading a file sends along fields like `relativePath`, and after this patch, it only sends the `assembly_url`, `fieldname` and `filename` fields as intended.

tus: implement `metaFields`

---

packages/@uppy/core/types/index.d.ts

As described in #1653 this makes partial assignment of restrictions passed as options possible.
Closes #1653

Enable partial assignment of restrictions passed as options

---

.github/CONTRIBUTING.md
website/src/_template/contributing.md

Maybe questionable removals, tell me if we should readd those:
1. I removed the part about `npm run web:start` - because why not fire up companion too, I think that's what most people would want. It doesn't require more installs.
2. And I removed the recommendation to exclude `./website/public/` from the editor, I think people are accustomed to removing things from their editors? We don't advise to be removing `output` folders for example.

contributing.md - improved #Local previews section

---

packages/@uppy/core/src/Plugin.js
packages/@uppy/core/src/index.js

After https://github.com/transloadit/uppy/pull/1600, we have `.VERSIONS` property on all plugins. 
With this PR, Uppy produces the following log:
```sh
[Uppy] [17:00:07] Using Core v1.1.0
[Uppy] [17:00:07] Using Dashboard v1.1.0
[Uppy] [17:00:07] Installing Dashboard to a DOM element
[Uppy] [17:00:07] Using Dashboard:StatusBar v1.1.0
[Uppy] [17:00:07] Installing Dashboard:StatusBar to Dashboard
[Uppy] [17:00:07] Using Dashboard:Informer v1.1.0
[Uppy] [17:00:07] Installing Dashboard:Informer to Dashboard
[Uppy] [17:00:07] Using Dashboard:ThumbnailGenerator v1.1.0
[Uppy] [17:00:07] Using GoogleDrive v1.1.0
[Uppy] [17:00:07] Installing GoogleDrive to Dashboard
[Uppy] [17:00:07] Using Instagram v1.1.0
[Uppy] [17:00:07] Installing Instagram to Dashboard
[Uppy] [17:00:07] Using Dropbox v1.1.0 …
```

core: Log versions of Uppy plugins for debugging

---

website/themes/uppy/layout/example.ejs

Website log before this PR:
After this PR:
Reason being, in https://github.com/transloadit/uppy/pull/1451 we started logging things with 2 arguments:
```js
console.log(prefix, message)
```
So with this PR, I’m concatenating [arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) and logging the resulting string.

website: Add support for arguments in website’s console.log hack

---

packages/@uppy/companion/src/standalone/index.js

request logs containing uppyAuthToken will look something like this:
```
::1 - - [13/Jun/2019:13:14:01 +0000] "GET /instagram/send-token?uppyAuthToken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

companion: don't log uppyAuthToken

---

packages/@uppy/dashboard/src/index.js
website/src/docs/dashboard.md

This PR:
- Adds `dashboard:modal-open` and `dashboard:modal-closed` events
- Calls `hideAllPanels()` in the Dashboard when modal is closed — solves the issue where Webcam would continue to be active after the modal is closed (reported in  https://github.com/transloadit/uppy/issues/1568)
- Minor refactor: sorted Dashboard methods logically, grouped event handlers together. This makes the PR harder to review, unfortunately, didn’t think about that, I’m sorry. The only real changes are with the aforementioned events.
Closes https://github.com/transloadit/uppy/issues/1568

dashboard: add modal open and close events

---

packages/@uppy/companion/src/config/grant.js
packages/@uppy/companion/src/server/controllers/callback.js
packages/@uppy/companion/test/mockserver.js

this change prevents us from exposing the provider access_tokens in URLs which could be access in logs or browser history

companion: change oauth access token transport method

---

packages/@uppy/file-input/src/index.js
packages/@uppy/robodog/src/form.js
website/src/docs/robodog-form.md

I think this is the only place that had a hardcoded string.
It now uses the `chooseFiles` localization so it'll already work with existing locale packs.
from `./examples/transloadit` in this repository:

robodog: use chooseFiles string like @uppy/file-input

---

packages/@uppy/companion/src/server/provider/drive/adapter.js
packages/@uppy/companion/src/server/provider/drive/index.js
packages/@uppy/companion/src/server/provider/dropbox/adapter.js
packages/@uppy/companion/src/server/provider/dropbox/index.js
packages/@uppy/companion/src/server/provider/instagram/adapter.js
packages/@uppy/companion/src/server/provider/instagram/index.js

See #1611 - this is only the backend changes, the frontend will need an update for the issue to be completely resolved
Was the idea for all the `adapter.js` files to have the same interface? Drive/dropbox required different parameters, I updated the instagram `getNextPagePath` to match.
Team drive support appeared to be broken, so I made a few changes to get it working. Also, the current team drive API being used is deprecated and I think its usage can be simplified some, I didn't want too make to many changes re that in this PR though

companion: return nextPagePath for drive/dropbox

---

packages/@uppy/xhr-upload/src/index.js

> To recap from the call: We'll merge https://github.com/transloadit/uppy/pull/1587 first, then change the xhr-upload client uploads to send metadata name and type instead, by putting `file.meta.name` in `formData.append` and by slicing the file data Blob + using the `contentType` option.
When uploading a file with `@uppy/xhr-upload`, a server receives the type that is set on the blob, `file.data.type`. This type is reported by the OS and might be incorrect or null, so in Uppy we try to detect the file type by extension sometimes. This PR re-creates the blob, setting `file.meta.type` as type, and uses `file.meta.name` for name, the one that can be updated by the user sometimes.
This should be consistent with how we send `name` and `type` with tus uploads and xhr-uploads on Companion.

xhr-upload: Set type and name from file.meta, re-create blob

---

packages/@uppy/aws-s3/src/index.js
website/src/docs/aws-s3.md

Since the AwsS3 plugin is capable of being used for more than just S3 uploads.  I found it beneficial to handle responses from my cloud provider differently than how it was being handled.  This change will allow anyone to overwrite the getResponseData() method returned by XHRUploader, but still use the default.  All tests were passing.

Allow overriding of getResponseData()

---

packages/@uppy/companion/src/server/provider/dropbox/index.js

companion: remove deprecated dropbox field

---

packages/@uppy/provider-views/src/index.js

Fixes #1423: before this PR, selected file/folder checkbox would appear unchecked after entering a folder:
This was because we were comparing `files` with a `file` object in `currentSelection` array, and `files` would change when moving between folders, so the reference to the file object would change, and `obj === obj` comparison failed, because that actually checks if the reference is the same.
@ifedapoolarewaju what do you think, can we rely on `id` being there for all providers?

provider-views: Persist selected checkboxes when moving between folders

---

packages/@uppy/core/src/index.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/drag-drop/src/index.js
packages/@uppy/file-input/src/index.js
packages/@uppy/provider-views/src/index.js
packages/@uppy/robodog/src/AttachFileInputs.js
packages/@uppy/robodog/src/upload.js
packages/@uppy/url/src/index.js
packages/@uppy/webcam/src/index.js

Fixes #1117
Adds a log to every `catch` in UI plugins, which call `addFile`.

Log error in uppy.addFile try/catch

---

packages/@uppy/aws-s3-multipart/src/index.js
packages/@uppy/companion/src/server/controllers/s3.js

Added metadata field to POST body params in createMultipartUpload method.
Fixes #1291 #1292.

Add metadata support for S3 MultiPart

---

packages/@uppy/status-bar/src/index.js

Before this PR, if you are uploading 2 files, one `100`mb, another `150`mb, the total would show `250` until the first one is uploaded, then total would become `150`, since it calculated only non-complete files.
With this PR we are calculating totals and progress of all `uploadStarted` files.
Fixes #1684

status-bar: Show `total file size / total uploaded of all started` vs `total / total upload of those not complete`

---

packages/@uppy/form/src/index.js
website/src/docs/form.md

This PR does 2 things:
1. Excludes the upload result metadata that `Form` appended to a `<form>` element, when gathering metadata from that form. Addresses https://github.com/transloadit/uppy/issues/1637, where because of this issue we were sending a huge amount of metadata to `tusd` — the whole `complete` object, instead of metadata intended by the user/dev.
2. Appends subsequent results to an array, instead of overwriting previous result. This fixes https://github.com/transloadit/uppy/issues/1147, but it is also probably a breaking change, since before this new results were just overwriting the previous, and the `value` sent to the server was an object, now it’s an array.

form: exclude own metadata, append result instead of overwriting

---

packages/@uppy/dashboard/src/components/PickerPanelTopBar.js
packages/@uppy/dashboard/src/components/icons.js
packages/@uppy/dashboard/src/style.scss

1. Moved the Plus icon to './icons.js'.
2. Removed unneeded `<div>` in PickerPanelTopBar.js
3. Slightly changed the spacing in PickerPanelTopBar.js. What do you think, should we add this spacing as a rule (warning-level for now) to Eslint? If you prefer the way we do it in the rest of the codebase, - let's add the Eslint rule for that then.

Fix header bar css in ie11

---

packages/@uppy/transloadit/src/Assembly.js

It now does updates to the Assembly status locally for the events that can happen frequently.

transloadit: reduce excessive polling

---

packages/@uppy/companion/src/server/Uploader.js
packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js

The 1203% issue was caused by some mixed up `/ 100` and `* 100`s.
The test is incomplete :hankey:

Progress fixes for unsized files

---

packages/@uppy/core/src/_utils.scss
packages/@uppy/dashboard/src/components/AddFiles.js
packages/@uppy/dashboard/src/components/FileItem/FileProgress/index.scss
packages/@uppy/dashboard/src/style.scss
packages/@uppy/provider-views/src/Breadcrumbs.js
packages/@uppy/provider-views/src/style.scss
packages/@uppy/status-bar/src/StatusBar.js
packages/@uppy/status-bar/src/style.scss

1. Added :focus() styles for focusable elements (hopefully I caught all of them).
2. Removed an excessive `<span>`.
3. I made it so that on mobiles some status is not displayed at all (1st - before, 2nd - after):
Before it was always getting cut off, and we were not getting any useful information anyway.
I did this to avoid having `overflow-x: hidden` that was hiding outline of the `'Upload'` button.

Added focus styles for all elements

---

packages/@uppy/webcam/src/index.js
website/src/docs/webcam.md

This PR introduces a new option for the `@uppy/webcam` plugin called `preferredMimeType` which defaults as `null`.
If a value is passed, the browser's `MediaRecorder` implementation checks if the `preferredMimeType` is supported, and if it thinks it is, will attempt to record using the `preferredMimeType` rather than the browser default.
If the `preferredMimeType` is unsupported, the browser will fall back to using its default recording mime type.
This allows, for example, a user to pass `preferredMimeType: "video/webm"` during the `@uppy/webcam` plugin construction which will instruct the browser to record to a `.webm` container.
Specific codecs may also be passed here. For example, `video/webm;codecs=vp8` may still parse as valid by the browser.
This does not currently change the mime …

Allow definition of MediaRecorder mimeType

---

website/src/docs/plugin-common-options.md

There are two pages with /docs/plugins as their permalink (The other one is https://github.com/transloadit/uppy/blob/master/website/src/docs/plugins.md)

Fix docs navigation

---

package-lock.json
packages/@uppy/companion-client/src/RequestClient.js
packages/@uppy/companion/package.json
packages/@uppy/companion/src/server/Uploader.js
packages/@uppy/companion/src/server/controllers/callback.js
packages/@uppy/companion/src/server/controllers/get.js
packages/@uppy/companion/src/server/controllers/url.js
packages/@uppy/companion/src/server/logger.js
packages/@uppy/companion/src/server/middlewares.js
packages/@uppy/companion/src/server/provider/index.js
packages/@uppy/companion/src/standalone/index.js
packages/@uppy/companion/src/uppy.js

starting out by displaying the original error. PRs to improve the situation in general may come after.
UPDATE: went ahead to add request IDs so that logs can be traced for a single request. The request ID is returned in the response header so it can be accessed from the client when an error is returned.
so the Oauth error will now look like this:
```
Companion was unable to complete the OAuth process :(
Error: User session is missing or the Provider was misconfigured
Request ID: acedfbca-782edacf-acedfbca-acedfbca
```
Also when you receive an error on provider view, it should now look something like this:

companion: display truer error during oauth failure

---

packages/@uppy/robodog/src/addDashboardPlugin.js
packages/@uppy/robodog/src/form.js

Previously, dashboard modal options like `closeAfterFinish` were not
available to robodog.form even if the `modal: true` option was set. this
was because the `addDashboardPlugin` function checks that `opts.inline
=== false`, and we were keeping it null/undefined.
Fixes #1638

robodog: fix `form({ modal: true })` not enabling modal options

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/status-bar/src/index.js

This PR:
- Sets file.type to the one detected by Uppy, before calling `onBeforeFileAdded` callback. This way you’ll get a meaningful type in the callback, instead of an empty string or an incorrect one.
- Emits `restriction-failed` for `minNumberOfFiles`, too (so in `uppy.upload()`). Not sure about the signature in this case, it is `(file, err)` for when a file restriction fails, and I made it `(null, err)` for when it’s `minNumberOfFiles`.
- Only logs non-restriction errors when “Upload” is pressed in StatusBar. For that, `return Promise.reject()` had to be changed to `throw` — `Promise.reject` wasn’t caught in `.catch()`. Without this it throws an error in console.
- Checks and throws early if `restrictions.allowedFileTypes` is not an array.
This PR supersedes …

core: Restrictions improvements

---

packages/@uppy/dashboard/src/components/PickerPanelTopBar.js

I added the `// always on the left` comments to implicitly explain why we need two empty `<div>`.
(Second `<div>` is not needed, but I added it too, I think it reads better considering imaginary `justify-content: space-between;`)

@uppy/dashboard - made Add More always stick to the right

---

packages/@uppy/robodog/src/form.js
website/src/docs/robodog-form.md

If you're not intending to couple the upload to form submission, which might commonly happen when using the modal UI with `robodog.form`, you don't want to trigger uploads when the form is submitted.

robodog: allow customizing `triggerUploadOnSubmit`

---

packages/@uppy/core/src/__snapshots__/index.test.js.snap
packages/@uppy/core/src/index.test.js
packages/@uppy/utils/src/generateFileID.js
packages/@uppy/utils/src/generateFileID.test.js

Fixes #1707
This shouldn't be bc-breaking!
Now, non-latin characters are encoded as their charcode in base 32, so
files that only differ by name in a non-latin language will generate
different IDs.

core: adjust ID generation to keep non-latin characters

---

.travis.yml

Right now our branch builds look like this:
We can run up to something like 5 jobs in parallel on travis. If we have 6 jobs, the ENDTOEND=true job will only start when one of the other jobs has finished. Then we have to wait for 3mins for the other job + 13 mins for the endtoend job. By starting ENDTOEND=true first, the other jobs can run in parallel next to it, and likely still be finished before the ENDTOEND job, saving 3 minutes before we can see the final results.

ci: tweak job run order

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
website/src/docs/uppy.md

It is very strange that methods of the core module (for example: `removeFile`) expect the file id as an argument but we don't return it when we add a file. I think if the file id is returned when adding a file it will be much easier for clients to use the API.

Improve addFile API

---

packages/@uppy/companion-client/src/Provider.js
packages/@uppy/companion/src/server/provider/drive/index.js

fixes [this issue](https://app.asana.com/0/707684331679643/1130022427298509/f) so that whenever an error is returned from companion:
1. the auth screen will be displayed if the user was never authenticated
2. if the user is authenticated, the last screen on display before the error will be displayed

Companion errors

---

packages/@uppy/companion/src/companion.js

to avoid issues like [this](https://github.com/transloadit/uppy/pull/1612#issuecomment-515117137) in the future, I am setting internally, the allowed http methods needed by companion. This way, non-standalone servers won't have to always keep track of what headers to set as regards to changes in companion.

companion: set allowed http methods internally

---

website/scripts/highlight.js

This should do it hopefully...
- The regex for detecting code blocks to highlight had a `.*` that was eating into the _contents_ of the block instead of stopping at the closing " for the class attribute.
- Inline code blocks are now escaped (not sure when that stopped happening...)
Sample: https://deploy-preview-1757--uppy.netlify.com/docs/

website: fix highlighting again

---

packages/@uppy/core/src/index.js

Makes it a bit easier to follow. It also logs a warning now when you do
`.retryUpload(SomeNonsenseFileID)` instead of silently adding an invalid
object to the state, which is a less terrible failure.

core: use setFileState inside retryUpload

---

website/src/docs/tus.md

We mentioned that we support all tus-js-client options, but the `on*` event options are not supported because we use them internally. This copies / adapts documentation from the tus-js-client readme, which also means you have to search less for available options because they're now all there on the page
Closes #1327

docs: explicitly document supported tus-js-client options

---

.eslintignore
packages/@uppy/core/src/index.js
packages/@uppy/dashboard/src/index.js
website/themes/uppy/layout/example.ejs

1. I fixed duplicate logs: https://uppy.io/examples/dashboard.
2. `[Uppy] [20:33:17] [Dashboard] resize event didn't fire on time: defaulted to mobile layout` was being logged when the modal was closed, got rid of it.
3. Eslint was highlighting ES5 in /website/examples html files, added those files to the `.eslintignore`.

Fix log duplication and excessive ResizeObserver log

---

website/src/examples/xhrupload/app.css
website/src/examples/xhrupload/app.es6
website/src/examples/xhrupload/app.html
website/src/examples/xhrupload/app.scss

1. Added a list of uploaded files.
2. Moved progress bar from the top of the screen, to under the 'Choose Files' button.

/examples/xhrupload - more obvious UI, added a list of uploaded files

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js

Made sure we can upload new files if we cancel last file (allowMultipleUploads: false)

---

packages/@uppy/core/src/index.js
packages/@uppy/xhr-upload/src/index.js
website/src/docs/xhrupload.md

- Throw an error when trying to upload a remote file with `bundle: true` in `xhr-upload` — we can’t bundle remote files.
- Allow for `uppy.log` type `error` when `catching` errors in `uppy.upload()`.
Fixes #866

xhr-upload: Throw an error when trying to upload a remote file with `bundle: true`

---

package-lock.json
website/package.json

Updated **hexo-filter-github-emojis** from v2.0.0 to v2.1.0.
Things to look for:
1. `<% include_code %>` rendering issue we used to have in v2.0.3  - https://uppy.io/examples/xhrupload/ (✅fixed)
2. Issue where emoticons in excerpts were not getting rendered in /blog (we have this issue now on the website with v2.0.0) - https://uppy.io/blog/  (✅fixed)

website - add new version of hexo-filter-github-emojis

---

CHANGELOG.md
packages/@uppy/transloadit/src/index.js
packages/@uppy/tus/src/index.js
packages/@uppy/xhr-upload/src/index.js
website/src/docs/transloadit.md

- Add `limit` option to `@uppy/transloadit`, it will be passed down to `@uppy/tus`
- Warn in `@uppy/xhr-upload` and `@uppy/tus` when trying to upload > 10 files with `limit: 0` (default)
- Update docs

transloadit: add limit option, warn about using limit when it’s set to 0

---

package-lock.json
package.json

- Add size-limit, `npm run test:size`, that shows uppy bundle size and execution time (with headless chromium)
- `npm run test:size -- --why` will show a webpack graph, like we have with disc, but more detailed:
We can also set a limit like `130kb` for the `uppy` package. Not sure if we should be adding this to individual modules? Seems like a hassle.

build: Add size-limit that shows uppy bundle size and execution time

---

packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.js
packages/@uppy/dashboard/src/components/FileItem/FileInfo/index.scss

- Add `data` attribute with source (so maybe debugging is easier, or some customization, won’t hurt?).
- Hide the icon in CSS, reasons: fixes https://github.com/transloadit/uppy/issues/1412.
Rationale: some users might be unhappy with the icon missing in the minor update, if so, they’ll be able to override it with CSS.

Add data attribute with source, hide the source icon with css

---

website/src/docs/robodog-form.md

I believe this link was meant to link to the Transloadit plugin, where the available options are listed.

Link to Transloadit plugin from Robodog Form page

---

packages/@uppy/form/src/index.js

Fixes #1787
When an existing `input` is used for `@uppy/form` result, and it’s `value` is empty (or the value is otherwise invalid JSON, and finally when it’s not an array), the`@uppy/form` tries to `JSON.parse`, the error occurs — empty string is not valid JSON.
- Try/catch JSON.parse
- Check if the result is an array, if not, set it to an empty array

form: try/catch parsing, set updatedResult to an empty array when not an array

---

packages/@uppy/companion/package.json

I got a security advisory that a package downstream of request v2.85.0 and thus, @uppy/companion v1.4.0 had a vulnerability. updating request removes the offending package.

companion: update request to v2.88.0

---

website/inject.js

This makes the sizes a little more accurate to the actual effect on the bundle, because preact is already unconditionally included in @uppy/core. They still over-estimate the effect (which is probably more "honest" than underestimating it).

website: exclude preact from plugin bundle size calculations

---

packages/@uppy/dashboard/src/index.js
packages/@uppy/locales/src/en_US.js
packages/@uppy/thumbnail-generator/src/index.js
website/src/docs/dashboard.md
website/src/docs/thumbnail-generator.md

This PR adds `waitForThumbnailsBeforeUpload: false` option, when enabled Thumbnail Generator will enter a `preprocess` stage until all thumbnails are generated and all EXIF data is added.
Reason: fixes https://github.com/transloadit/uppy/issues/1775, which asks for “Disable upload button in dashboard until exif data is resolved”.
The option can be passed in from the Dashboard.
Concerns:
1. Is EXIF data available on the `file.data` object by sheer magic (side effect)? It seems that we are not explicitly setting this EXIF data anywhere, and `exif-js` just mutates `file.data`. Should we set it explicitly? Should we add EXIF to `file.meta`?
2. Do we need this functionality at all? @lakesare expressed an opinion that we don’t actually need to worry about this, since EXIF data can be obtained …

thumbnail-generator: add waitForThumbnailsBeforeUpload option, false by default

---

packages/@uppy/companion/src/server/provider/drive/adapter.js
packages/@uppy/companion/src/server/provider/drive/index.js
packages/@uppy/google-drive/src/DriveProviderViews.js

Google Drive API has [deprecated](https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api) the use of `Team Drives`, and replaced it with just `Drives`. This PR drops the deprecated implementation and adds the newly support implementation.

companion,google-drive: drop deprecated usage for Google Drive's "shared drive"

---

package-lock.json
packages/@uppy/aws-s3-multipart/package.json
packages/@uppy/aws-s3/package.json
packages/@uppy/aws-s3/src/index.js

So it works in browser-ish, but non-DOM, environments. Will use the
global `URL` API if available, and fall back to url-parse, which has a
compatible-enough API.
Fixes https://github.com/transloadit/uppy/issues/1720

aws-s3: replace resolve-url by url-parse

---

packages/@uppy/companion-client/src/RequestClient.js
packages/@uppy/companion-client/types/index.d.ts
packages/@uppy/dropbox/src/index.js
packages/@uppy/facebook/src/index.js
packages/@uppy/google-drive/src/index.js
packages/@uppy/instagram/src/index.js
packages/@uppy/onedrive/src/index.js
packages/@uppy/robodog/src/addProviders.js
packages/@uppy/url/src/index.js
website/src/docs/aws-s3.md
website/src/docs/dropbox.md
website/src/docs/facebook.md
website/src/docs/google-drive.md
website/src/docs/instagram.md
website/src/docs/onedrive.md
website/src/docs/robodog-picker.md

For consistency with `companionUrl` etc.
`serverHeaders` still works but is no longer documented. We can remove it in V2.

companion-client: rename serverHeaders to companionHeaders

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
packages/@uppy/aws-s3-multipart/src/index.js
packages/@uppy/utils/src/RateLimitedQueue.js

Fixes an issue where the plugin was queueing too many things, causing deadlock. The entire `MultipartUpload` object was added as a queue entry, but then that object would queue more things, and wait for those things to complete; but the `MultipartUpload` objects were clogging up the queue, so those things would never start. Since the MultipartUpload object manages its requests internally, and it participates in the rate limiting queue, its requests don't need to be queued again.
Fixes an issue where cancelling many queued uploads would cause them to quickly start and then immediately be cancelled, because cancelling the ongoing uploads would synchronously push the queued uploads to the front of the upload queue, synchronously start them, and then synchronously cancel them. Now, queue …

aws-s3-multipart: fix queueing behaviours

---

packages/@uppy/core/src/index.js

We were already doing `if (file.error)` in places, now that is
guaranteed to work even if the error message was empty or the error
object is custom and doesn't have a `.message` property.
fixes https://github.com/transloadit/uppy/issues/882, I think.

core: provide default error message

---

packages/@uppy/dashboard/src/components/FileItem/index.js

The `...props` object that we were spreading into `<FileProgress />`
contained another, different `error` prop, which was empty for
individual file upload failures. By putting the `...props` spread in
front, the file-specific error takes precedence over the global error.
Fixes #1881

dashboard: fix retry icons on individual files

---

packages/@uppy/facebook/src/index.js
packages/@uppy/provider-views/src/Breadcrumbs.js
packages/@uppy/provider-views/src/index.js

This PR adjusts the facebook provider such that, when listing **folders**, it displays it in **list view**, and when listing just **images**, it displays in **grid view**

facebook, provider-views: support list + grid view for facebook

---

packages/@uppy/companion/src/companion.js
packages/@uppy/companion/src/standalone/helper.js
website/src/docs/companion.md

Expose S3 client's useAccelerateEndpoint option that enables usage of Transfer Acceleration endpoint - https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

Add S3 useAccelerateEndpoint to Companion

---

packages/@uppy/utils/src/RateLimitedQueue.js
packages/@uppy/utils/src/RateLimitedQueue.test.js

Fixes a problem where a synchronous S3 `getUploadParameters()` would crash, because `@uppy/utils` assumed the return value was a Promise.
Fixes https://github.com/transloadit/uppy/issues/1906

utils: accept sync functions in `wrapPromiseFunction()`

---

packages/@uppy/core/src/index.js

I'm seeing some upload-success events after the file removal, this is causing an exception.

fix: skip upload-success event for a file that has been removed

---

packages/@uppy/core/types/core-tests.ts
packages/@uppy/core/types/index.d.ts
packages/@uppy/utils/types/index.d.ts

This PR adds the proper typing for `UppyFile.response` as indicated in #1856.

add UppyFile.response typing

---

packages/@uppy/provider-views/src/Breadcrumbs.js

Currently, the provider views breadcrumbs is failed to render due to using `Fragment`

fix: provider views breadcrumbs is failed to render

---

examples/custom-provider/server/index.js
examples/uppy-with-companion/server/index.js
packages/@uppy/companion/src/standalone/index.js

This PR addresses this [lgtm security issue](https://lgtm.com/projects/g/transloadit/uppy/snapshot/b3545d3244e34b6945d55a7256df8bfcdffaa558/files/packages/@uppy/companion/src/standalone/index.js?sort=name&dir=ASC&mode=heatmap#x2a1b855e0849df53:1). The solution is to only allow credentials when request origins are whitelisted.

companion: conditionally set Access-Control-Allow-Credentials

---

website/src/docs/uppy.md

It appears the response parameter is undefined by a lot of unloaders. Making a note in the docs to reflect this.

Add a note about response parameter

---

packages/@uppy/companion/README.md
packages/@uppy/companion/examples/serverless/index.js
packages/@uppy/companion/examples/serverless/serverless.yml
packages/@uppy/companion/src/companion.js
packages/@uppy/companion/src/server/Uploader.js
packages/@uppy/companion/src/server/controllers/callback.js
packages/@uppy/companion/src/server/controllers/connect.js
packages/@uppy/companion/src/server/controllers/get.js
packages/@uppy/companion/src/server/controllers/list.js
packages/@uppy/companion/src/server/controllers/logout.js
packages/@uppy/companion/src/server/controllers/oauth-redirect.js
packages/@uppy/companion/src/server/controllers/s3.js
packages/@uppy/companion/src/server/controllers/send-token.js
packages/@uppy/companion/src/server/controllers/thumbnail.js
packages/@uppy/companion/src/server/controllers/url.js
packages/@uppy/companion/src/server/helpers/jwt.js
packages/@uppy/companion/src/server/helpers/utils.js
packages/@uppy/companion/src/server/middlewares.js
packages/@uppy/companion/src/server/provider/drive/index.js
packages/@uppy/companion/src/server/provider/dropbox/index.js
packages/@uppy/companion/src/server/provider/index.js
packages/@uppy/companion/src/standalone/helper.js
packages/@uppy/companion/src/standalone/index.js
packages/@uppy/companion/src/standalone/start-server.js
packages/@uppy/companion/test/__tests__/provider-manager.js

renaming all occurrences of uppy / uppyOptions to companion / companionOptions to reduce confusion when reading the codebase (especially for possible contributors).
@kiloreux added you just in case you spot anything of with the `packages/@uppy/companion/examples/serverless/` part

companion: rename uppy occurrences to companion

---

website/src/docs/robodog-dashboard.md
website/src/docs/robodog-form.md
website/src/docs/robodog-picker.md
website/src/docs/robodog-upload.md
website/src/docs/robodog.md
website/src/docs/transloadit.md

- Uses `#upload-form` as a CSS selector for all the form examples, so copy-pasting parts from different examples works
- Uses uppercase `Robodog` variable for all Robodog namespace references, which is what the CDN exports. There was also one pre-Robodog-name reference to `transloadit.form()` which is now fixed.

docs: make Robodog naming more consistent

---

bin/locale-packs.js
packages/@uppy/locales/src/es_GL.js
packages/@uppy/locales/src/gl_ES.js
website/inject.js

the `es-GL` locale means Spanish in Greenland.
`gl-ES` means Galician in Spain.
I just renamed the file here which is a breaking change. I think that's
acceptable for the locales package, as it isn't a dependency of anything
else. `@uppy/locales@2.0` doesn't affect anything. what do y'all think?

locales: Rename es_GL → gl_ES

---

packages/@uppy/companion/infra/kube/companion/companion-redis.yaml

Change Deployment to `apps/v1` since our cluster is now on 1.16.

Change Deployment type to stable api

---

packages/@uppy/aws-s3/src/index.js
packages/@uppy/aws-s3/src/index.test.js

The start of a test suite for the awsS3 plugin. The first few are always the hardest.
Since `getUploadParameters` throws without the configuration option `companionURL` a warning message was included in the constructor.

Test aws s3 plugin

---

packages/@uppy/core/types/core-tests.ts
packages/@uppy/core/types/index.d.ts

Casting event param to Event type rather than string. This offers stricter parameter checking avoiding fat fingering and code completion.

add event type

---

package-lock.json
packages/@uppy/thumbnail-generator/package.json
packages/@uppy/thumbnail-generator/src/exif.js
packages/@uppy/thumbnail-generator/src/index.js

exif-js causes errors in strict mode (see #1928) which results in thumbnails not being generating in certain environments (webpack with ES6 modules I believe).  This removes the dependency and instead hard codes the exif-js source in Uppy.  I initially tried to replace exif-js with another library like exifreader or exif-parser, but they didn't seem to work and the change to one of those libraries could potentially cause other issues due to a complete change in libraries.
Because Uppy only uses a small portion of exif-js I was able to remove all the exif-js code for reading XMP and IPTC metadata as well as the code that created the thumbnail blob (since Uppy was deleting that tag after reading the metadata).  This should theoretically improve the performance of the thumbnail generator, …

Hard code exif-js source in Uppy

---

packages/@uppy/dashboard/src/components/AddFiles.js
packages/@uppy/dashboard/src/components/Dashboard.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/dashboard/src/style.scss

Also refactor `uppy-DashboardTabs-list`, etc.
Full size:
Short screen:
Mobile:
Short screen mobile:

Dashboard: hide note/poweredBy on short screens, improve provider list behavior

---

.travis.yml
packages/@uppy/companion/src/server/provider/drive/adapter.js
packages/@uppy/companion/src/server/provider/facebook/adapter.js
packages/@uppy/companion/src/server/provider/instagram/adapter.js

IIRC, node 6 compatibility is enforced because of [api2](https://github.com/transloadit/transloadit-api2/blob/master/api2/package.json#L11) (gonna double check if this is still the case), so it makes sense to test that we continuously compatible with this version.

companion: test companion on node 6 + fix incompatible code

---

packages/@uppy/companion/src/server/controllers/callback.js
packages/@uppy/locales/src/de_DE.js
packages/@uppy/locales/src/en_US.js
packages/@uppy/locales/src/es_ES.js
packages/@uppy/locales/src/fr_FR.js
packages/@uppy/locales/src/nl_NL.js
packages/@uppy/webcam/README.md
packages/@uppy/webcam/src/CameraScreen.js
packages/@uppy/webcam/src/RecordingLength.js
packages/@uppy/webcam/src/formatSeconds.js
packages/@uppy/webcam/src/formatSeconds.test.js
packages/@uppy/webcam/src/index.js
packages/@uppy/webcam/src/style.scss
website/src/docs/webcam.md

When this is true (by default it is false), it counts the duration of a recording and displays it to the user as below. Add a test for generating the correct duration of the recording. 
I personally found this useful for using Uppy as a dictaphone. I built a small proof of concept at the weekend (using a hacky method of putting the duration counter in a CSS pseudoelement) but wanted to see if I could improve on it by integrating a better version into Uppy core. Hopefully you will find it a useful feature!

[feature] - Add new ‘showRecordingLength’ option for the Webcam plugin

---

packages/@uppy/companion/src/standalone/index.js

This change is added in order to validate our companion.uppy.io domain with OneDrive

companion: oneDrive domain validation

---

packages/@uppy/aws-s3/src/index.js

Detects text/html responses that start with `<?xml ` as XML.

aws-s3: support GCS responses, fixes #896

---

packages/@uppy/utils/src/isPreviewSupported.js
packages/@uppy/utils/src/isPreviewSupported.test.js

Fixes #1931 
Works in (MacOS): Chrome, Firefox. Silently ignored on Safari, which doesn’t support `webp` yet. (In Safari the file currently returns an `application/octet-stream` for `webp`, instead of `image/*`).

thumbnail-generator: Add webp to the list of supported types

---

packages/@uppy/companion/src/server/Uploader.js

We were using the wrong `meta` field for the file name.

companion: use original file name in S3 Multipart uploads

---

packages/@uppy/dashboard/src/index.js
packages/@uppy/drag-drop/src/index.js

Updating `dropEffect` on `ondrop` doesn't matter, since the effect will
already have been executed at that point. It should be updated in
ondragenter/ondragover instead.
fixes #1978

drag-drop/dashboard: move dropEffect assignment to dragover

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
packages/@uppy/aws-s3-multipart/types/index.d.ts
website/src/docs/aws-s3-multipart.md

Fixes #1984
Update `prepareUploadPart` contract to accept an optional `headers` property in the returned value.
If `headers` are present, they will be sent along the S3 presigned URL
Note: I've tested by locally publishing the package, and it works well.
Here is an example of implementation of a custom `prepareUploadPart`:
```typescript
export const prepareUploadPart = async (
file: Uppy.UppyFile,
partData: { uploadId: string; key: string; body: Blob; number: number },
) => {
const response = await fetch(`/api/upload/tickets/${partData.uploadId}/parts/${partData.number}`, {
method: 'GET'
});
const data = await response.json();
return {
url: data.uploadUrl,
// here is the new property:
headers: data.headers,
};
};
```

feat(s3-multipart): add optional headers for signed url

---

packages/@uppy/react/src/DashboardModal.js

ComponentWillReceiveProps has been renamed and is not recommended for use. I have moved the logic of ComponentWillReceiveProps to componentDidUpdate lifecycle.

componentWillReceiveProps logic moved to componentDidUpdate

---

packages/@uppy/xhr-upload/src/index.js

This PR is to fix the bug #2016 .
When a limit parameter is provided to the XHR plugin, and some uploads time out, it is possible that the RateLimitQueue get stuck.
This fix free a slot in the RateLimitQueue when an upload times out.

Free rate limit queue when upload times out (#2016)

---

packages/@uppy/companion/src/server/Uploader.js

Forgot this in the previous PR https://github.com/transloadit/uppy/pull/1866.
Closes https://github.com/transloadit/uppy/issues/2014
Closes https://github.com/transloadit/uppy/issues/1957

companion: also pass metadata to getKey for multipart S3 uploads

---

packages/@uppy/companion/src/server/helpers/utils.js
packages/@uppy/companion/test/__tests__/companion.js
website/src/examples/dashboard/app.html

This PR is an extension of this [commit](https://github.com/transloadit/uppy/commit/1971117ee316e337b7d00b2703dcf6ae8ba8cb69) which makes the encryption output shorter by encoding them as `base64` instead of `hex`. This is needed because encrypted tokens were coming out too long for Onedrive and servers were throwing errors as a result.
fixes #2006

companion,website: make encryption shorter + enable onedrive on website

---

packages/@uppy/aws-s3/src/index.js

See https://github.com/transloadit/uppy/issues/2025

remove encodeURIComponent to avoid encoding characters twice

---

packages/@uppy/dashboard/src/components/AddFilesPanel.js
packages/@uppy/dashboard/src/components/FileCard/index.js
packages/@uppy/dashboard/src/components/PickerPanelContent.js
packages/@uppy/dashboard/src/components/PickerPanelTopBar.js

Changed the aria-level attribute to the correct syntax, aria-level should be equivalent to an integer value. Changes were also made to meet ADA compliance.

Changed aria-level attribute to correct syntax.

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js
packages/@uppy/core/src/loggers.js
packages/@uppy/status-bar/src/StatusBar.js
website/src/docs/uppy.md

Show errors in logs always. `nullLogger` --> `justErrorsLogger`
Reasoning: too often we ended up showing errors in the Informer bubble, but not in the console, which is wrong and annoying. Devs still have an option to silence logs or direct them elsewhere by setting a custom logger.

core: Always log errors

---

packages/@uppy/companion/src/standalone/helper.js

* Google drive callback url now uses 'google' and not 'drive'
* Fixes callback url by removing the conditional for google providerName
The callback for google drive should be `https://upload.redmtnsci.com/connect/google/callback`
I just set this up and the conditional statement should be removed because the callback is `google` not `drive`.
```
- Be sure to add https://upload.redmtnsci.com/connect/drive/callback, https://upload.redmtnsci.com/connect/dropbox/callback, https://upload.redmtnsci.com/connect/instagram/callback, https://upload.redmtnsci.com/connect/facebook/callback, https://upload.redmtnsci.com/connect/microsoft/callback as your Oauth redirect uris on their corresponding developer interfaces.
- The URL https://upload.redmtnsci.com/metrics is available for  statistics to keep …
```

fix: remove conditional to replace `google` with `drive` 

---

packages/@uppy/companion/src/server/Uploader.js
packages/@uppy/xhr-upload/src/index.js

fixes #2019 (we can all go one year backwards once this is merged)

companion,xhr-upload: add option to set http method for remote multipart uploads

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js

This PR aims to fix the bug mentioned in Issue #1988 .
For instance, if we have a restriction `video/webm` and the mime-type of the recorded video is `video/webm; codecs=\"vp8, opus\"`:
The existing code makes the comparison `match('video/webm; codecs=\"vp8, opus\"','video/webm')` which will return false.
We need to be doing `match('video/webm','video/webm; codecs=\"vp8, opus\"')` for it to return true. So I just swappedthe params
Fixes #1988

Fix mime type checking bug

---

website/src/examples/transloadit/app.es6

pointing it to companion.uppy.io because facebook is not available on api2 yet

website: optionally enable facebook with transloadit

---

bin/upload-to-cdn.js
package.json

After merging this PR, with every new CDN release, an extra file is uploaded, such as:
https://transloadit.edgly.net/releases/uppy/v1.8.0/uppy-v1.8.0.zip
We can still decide if/how we want to integrate that in our website, but i can imagine download buttons having an appeal to _a_ user base.

Upload downloadable zip archive of releases to CDN

---

packages/@uppy/companion/src/companion.js
packages/@uppy/companion/src/server/controllers/get.js
packages/@uppy/companion/src/server/controllers/list.js
packages/@uppy/companion/src/server/controllers/logout.js
packages/@uppy/companion/src/server/provider/drive/index.js
packages/@uppy/companion/src/server/provider/dropbox/index.js
packages/@uppy/companion/src/server/provider/error.js
packages/@uppy/companion/src/server/provider/facebook/index.js
packages/@uppy/companion/src/server/provider/instagram/graph/index.js
packages/@uppy/companion/src/server/provider/instagram/index.js
packages/@uppy/companion/src/server/provider/onedrive/index.js

Currently when any error whatsoever is received from provider APIs, companion sends back status code `500` to uppy client. But this response can be misleading because it gives the impression that something internally went wrong with companion. Whereas, some of the errors from the provider APIs could actually be `40x` errors which require the user from uppy client, to make changes accordingly.
The change in this PR fixes this issue by:
- sending back a `424 (FAILED DEPENDENCY)` error whenever a 40x error is returned from providers. And also attempts to parse and send back the message return from the provider
- sending back a `502 (Bad Gateway)` error whenever a 50x error is returned from providers. And also attempts to parse and send back the message return from the provider.
this approach …

companion: return  more accurate error status codes

---

website/src/docs/aws-s3.md

Prevents the main presigned url example from failing in many cases, as the browser does not assign a content type in many cases, but a content type is required by S3. Based on issue https://github.com/transloadit/uppy/issues/1233

Add Content-Type header to presigned url example

---

packages/@uppy/companion/src/companion.js
packages/@uppy/companion/src/server/controllers/s3.js
packages/@uppy/companion/src/standalone/helper.js
website/src/docs/companion.md

**Problem**
Companion generates presigned URLs for S3 with a fixed 5-minute expiration; as noted in #1915 and #1724, this can be problematic depending on upload size and network conditions.
**Solution**
Make the expiration configurable through companion `providerOptions`.
Ref #1915
Ref #1724

make s3 signed url expiry configurable in companion

---

packages/@uppy/companion/src/companion.js
packages/@uppy/companion/src/server/helpers/request.js
packages/@uppy/companion/test/__tests__/http-agent.js

The last release is broken for the Url plugin when the URL is an https URL. The reason is because the URLParser sets protocols as `https:` (not `https`), where as our implementation expects `https`. This PR now allows for both to be supported.
I also updated the tests to test this case.

companion: return the right httpAgent when protocol value contains ":"

---

packages/@uppy/companion/src/server/controllers/oauth-redirect.js
packages/@uppy/companion/test/mockserver.js

this was left out from [this change](https://github.com/transloadit/uppy/pull/1668/files). It wasn't spotted all this while because the controller is only called when you are running multiple instances of companion in different domains (which is not a very common use case).

companion: read state from session in oauth-redirect controller

---

website/src/examples/transloadit/app.es6

in order to have the Instagram Graph app verified by Facebook, we need to make it publicly testable. Because https://companion.uppy.io is currently using the old Instagram API, we are not able to override it with the new one, and make it testable (because the new one isn't verified yet, and won't be usable by all users).
I have hosted a companion instance [here](https://intense-meadow-61813.herokuapp.com/) which uses the new Instagram API. The repo is [here](https://github.com/ifedapoolarewaju/companion-sample). This PR now in turn adds a temporary option to point the Instagram Plugin to this companion instance which uses the new Instagram Graph API.

website: optionally point to companion with graph instagram API

---

website/src/docs/thumbnail-generator.md

Just a simple typing mistake I noticed today :)

Fix typo in thumbnail generator documentation

---

website/src/docs/companion.md

S3 uploads from Companion were failing with S3 AccessDenied errors (I noticed these in the Websocket messages). I thought I might be missing something in the config, read through the docs and then after reading through the source, I realized that the S3 ACL option is being defaulted to `public-read` [here](https://github.com/transloadit/uppy/blob/7525440229bde28241e34ba3eacf3fad77269c05/packages/%40uppy/companion/src/companion.js#L31), while I was trying to upload private files to my S3 bucket that has public objects disabled. So S3 was preventing this file with a public ACL from being uploaded.
There's already provisions to override the S3 ACL parameter, so figured it would be good to mention the existence of this option in the docs, especially since it's being defaulted to a specific …

Add S3 ACL option to companion docs

---

packages/@uppy/companion/src/companion.js

These were accidentally removed in #2030. A missing region could cause AWS to reject upload requests, and without `endpoint` uploads to alternative services like GCS or DigitalOcean Spaces were made impossible.

companion: pass `endpoint` and `region` to AWS SDK constructor

---

packages/@uppy/companion/src/standalone/index.js

in this PR, companion refrains from logging errors due to `400 (Bad Request)` when in production mode. This is to avoid unnecessarily flooding the logs with undesired output.

companion: don't log redundant errors in production

---

website/src/docs/locales.md

- Replaced incorrect link to the Dashboard docs: `http://localhost/docs/dashboard/#locale` -> `https://uppy.io/docs/dashboard/#locale`
- Replaced `here's Dashboard` with a meaningful sentence.

Docs: fix incorrect link to Dashboard in locale.md

---

package-lock.json
packages/@uppy/companion/package.json
packages/@uppy/companion/src/server/Uploader.js

We were not ending the `fs-tail-stream` correctly. `fs-tail-stream` is
also not a battle-tested package and relying on file watching is never a
fun time, so it's better if we can avoid it entirely.
One good way to do that is to axe the entire parallel download/upload
feature, and instead download files in full before uploading them, like
we do for Tus and XHR :)
@ifedapoolarewaju I see there's still some code for parallel upload/download in the Uploader class, stuff like the `duplexStream` and a bunch of if/elses related to that. do you think we can remove that? It would help to make it less complex
Fixes #1457.

companion: drop parallel down/upload for S3 multipart

---

packages/@uppy/core/types/index.d.ts
packages/@uppy/core/types/index.test-d.ts

Adds `uppy.setOptions()` and `plugin.setOptions()`. Both accept any subset of the options that can be passed to the Uppy constructor or to the plugin respectively.

core: add typings for `setOptions()`.

---

packages/@uppy/react/src/DashboardModal.d.ts
packages/@uppy/react/types/index.test-d.tsx

The DashboardModal proptypes inherited from the Dashboard proptypes, but the Dashboard proptypes excluded all the modal-specific props. So, the DashboardModal did not support modal-specific props.
Now, the DashboardModal proptypes are derived separately from the Dashboard options.

react: fix typescript proptypes for DashboardModal, fixes #2124

---

packages/@uppy/dashboard/src/index.js

From a support ticket:
> How to get rid of this JS error:
> Dashboard modal trigger not found. Make sure `trigger` is set in Dashboard options unless you are planning to call openModal() method yourself
Of course it should have been a warning all along, but maybe we shouldn’t display it at all, ie  when `trigger` not specified = you intend to call `openModal` yourself? More noise vs confusion when someone can’t figure out why the Dashboard modal won’t appear 🤔

Dashboard: Log warning instead of an error when trigger is not found

---

packages/@uppy/core/src/index.js

Fixes #2126 
With the new `addFiles()` method from https://github.com/transloadit/uppy/pull/1949, `autoProceed` was run even if no files were actually added, because of errors/restrictions. 
This PR fixes that — `_startIfAutoProceed` is only called if `newFiles > 0`.

Only _startIfAutoProceed if some files were actually added

---

website/src/docs/uppy.md

Spent hours to test it to add a relativePath and non unique ids for files with the same name but coming from different folders.
It works like it but it's confusing with the `setMeta` method.

Add meta.relativePath explicit example

---

packages/@uppy/companion/src/server/provider/drive/adapter.js
packages/@uppy/companion/src/server/provider/drive/index.js
packages/@uppy/companion/test/__mocks__/purest.js
packages/@uppy/companion/test/__tests__/http-agent.js

This PR adds support to upload GSuite files (Google Docs, Google Spreadsheet, etc.)
One issue however is that, we are unable to determine the file size of Google spreadsheet files (we are able to determine for Google docs). This prevents us from sending progress while the file is being downloaded. 
The workaround I applied for this is to initially set the file size to 10 MB (since that's the size limit supported). This allows us send upload progress immediately the download starts. This however has a confusing behaviour where the file is initially displayed as 10MB, and then it may suddenly switch to 2MB (the actual size). Please see the sample GIF below
Another alternative will be to not preset a size at all, and we'd have to wait for the file to be done downloading before we begin to …

companion: add support to download gsuite (google docs, google spreadsheet files

---

bin/locale-packs.js

This was broken by #2077. Instead of the keys and values that were
missing, it was printing things like:
```
de_DE locale has missing string: '91' that is present in en_US with value: 'exceedsSize'
```
Which is not super helpful.

Fix locale pack test output

---

website/src/docs/companion.md

The hashtag: "#Configure-Standalone" is not correct and doesn't lead to anything. Fixed that.

Fix fragment URL

---

bin/release

Since the release script could lead in failures when one has uncomitted git changes, I figured it's better to catch that case earlier on.

build: abort release script when there are uncomitted git changes

---

packages/@uppy/dashboard/src/components/FileCard/index.js
packages/@uppy/dashboard/types/index.d.ts
packages/@uppy/dashboard/types/index.test-d.ts
website/src/docs/dashboard.md

Issue #617 is related to this. It proposes the ability to set custom render functions for metadata fields. However, IMO this can be kinda overcomplicated, especially if you want to use Uppy in an app without React (which we are).
Hence, I propose the ability to set the type of input field used for the different metadata fields. This could be replaced / improved in the future by also providing the aforementioned custom render function. Currently supported fields are:
- Normal Text Input (default)
- Select (including options)
- Checkbox
I can add more, but these are the ones we would currently need :)
This change should be backwards compatible, since by default I just use the normal text input.
Let me know, if I should add any text or documentation.
Closes #2007

[Dashboard] Allow setting the input type when editing files in Dashboard plugin

---

packages/@uppy/transloadit/src/index.js

…se it was smaller than other files in the batch), complete it during post processing
Durning an internal QA of our migration to the most recent version of Uppy, we came across a bug during large batch uploads using the transloadit plugin with several assemblies. In some cases if the file sizes in the different assemblies were dramatically different, the smaller uploads would have their assembly complete before the rest of the files finished uploading. This would mean that during the postProcessing step, the assemblyWatcher would never receive a `assembly-complete`event for that assembly so the step would hang.
This is a naive attempt to remedy the bug by keeping track of what assemblies have completed and when we start postProcessing, emiting `postprocess-complete `for any that have …

transloadit: fix progress with very different Assembly runtimes

---

packages/@uppy/tus/src/index.js
packages/@uppy/xhr-upload/src/index.js

During upload instantiation, if companion returns an error, the `upload-error` even is not emitted, so the progress bar just waits infinitely.
Before this commit:
After this commit:

tus,xhr-upload: emit error when companion returns error during upload creation

---

packages/@uppy/aws-s3-multipart/src/index.js

as @arturi mentioned [here](https://github.com/transloadit/uppy/pull/2166#issuecomment-607326550), we do need it for `aws-s3-multipart`

aws-s3-multipart: emit upload-error when companion returns error during upload

---

packages/@uppy/companion/src/server/provider/facebook/index.js

This is to avoid  a case were a user may send a different root URL (e.g https://google.com) as the values of `id`, or `directory`

companion: use full URL in provider requests when the root path depends on user input

---

website/src/docs/thumbnail-generator.md

Just a simple typing mistake I noticed today :)

Fix typo in thumbnail-generator doc

---

packages/@uppy/companion/src/standalone/helper.js

in a system where the `NODE_ENV` variable is never used as part of their config variables to begin with, it'll be unsafe to assume the system is in `debug` mode by merely checking `NODE_ENV !== 'production'`

companion: set debug based on NODE_ENV only if the env var is available

---

packages/@uppy/thumbnail-generator/src/index.js

Fixes #2172 
Current build tools, including Create React App on the latest version, seem to have issues importing .cjs files. This results in thumbnail generation failing with the following error:
TypeError: exifr.orientation is not a function
`exifr/dist/mini.legacy.umd.cjs` and `exifr/dist/mini.legacy.umd.js` are identical on the current version of exifr and this fixes the issue with CRA.

Use .js import for exifr in Thumbnail Generator

---

packages/@uppy/aws-s3/src/index.js

When using native URL function (`typeof URL === 'function'`: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) the second optional parameter is causing a crash resulting in the uploading failing at 100%
According to the definition:
>`base` Optional
>A `USVString` representing the base URL to use in case URL is a relative URL. If not specified, it defaults to `''`.
Safari does not allows the usage of `undefined`, `null` or `''`. , triggering a `Type error` exception.

Fixing Safari type error

---

packages/@uppy/utils/src/findDOMElement.js

`isDOMElement` already checks if the element is typed as `object`

Remove duplicate check of element type

---

packages/@uppy/companion/src/standalone/index.js

This:
- removes unsupported value types
- replaces the possibly-unbounded-length `xxx` replacement value by a
new fixed-length `***` replacement value, similar to what #2214 does
- allows us to upgrade the express typings because the new version broke
the build :)

companion: improve obscuring sensitive values in standalone server

---

packages/@uppy/aws-s3/src/index.js

By encoding `filename` and `type` we have the upload parameters encoded twice.
`qsStringify({...})` (called at [line 143](https://github.com/romain-preston/uppy/blob/aed402aeaba6626f5a9628eb70809d27d724d66d/packages/%40uppy/aws-s3/src/index.js#L143)) already encodes the values by default according to their ([documentation](https://github.com/ljharb/qs#stringifying)):
> When stringifying, qs by default URI encodes output. 
Not encoding them before fixes the issue.

fix double encoding of the upload params

---

packages/@uppy/screen-capture/src/index.js
packages/@uppy/screen-capture/types/index.d.ts
packages/@uppy/screen-capture/types/index.test-d.ts

plugins have to be explicitly excluded in `npm run test:type` if they
don't have a type test file, so this was causing tests to fail.
updated the types to the new style capable of strict typechecking, and
made them use the actual DOM types for the Constraints options.
Looking at mdn, the `displaySurface` and similar options are actually
properties of the `constraints.video` object, so i moved them in there
in our `defaultOptions`.

screen-capture: add type tests

---

packages/@uppy/aws-s3/package.json

I received the following error message:
> ModuleNotFoundError: Module not found: Error: Package "@uppy/aws-s3@1.6.4" (via "/usr/local/share/.cache/yarn/v6/npm-@uppy-aws-s3-1.6.4-c78ef1c89fb6a97455d10fad4d7c4b6f4abca47b-integrity/node_modules/@uppy/aws-s3/lib/MiniXHRUpload.js") is trying to require the package "cuid" (via "cuid") without it being listed in its dependencies (@uppy/core, @uppy/companion-client, @uppy/utils, @uppy/xhr-upload, qs-stringify, url-parse, @uppy/aws-s3)
Commit ab764485080da1774836f34b8b345f957335873f introduced a new direct dependency to cuid

Add cuid dependency to @uppy/aws-s3

---

packages/@uppy/transloadit/types/index.d.ts
packages/@uppy/transloadit/types/index.test-d.ts

Fixes #2243
Omitting `UPPY_SERVER` because it should not be used. It will be removed
from the JS source too with the 2.0 release.

transloadit: add typings for Companion URL constants

---

CHANGELOG.md
packages/@uppy/dashboard/src/components/Dashboard.js
packages/@uppy/dashboard/src/components/FileItem/Buttons/index.js
packages/@uppy/dashboard/src/components/FileItem/index.js
packages/@uppy/dashboard/src/components/FileItem/index.scss
packages/@uppy/dashboard/src/components/FileList.js
packages/@uppy/dashboard/src/components/VirtualList.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/thumbnail-generator/src/index.js
packages/@uppy/thumbnail-generator/src/index.test.js

This patch changes the Dashboard to only render those files that are actually in view, and to only generate thumbnails for files that are in view.
When a FileItem mounts, a thumbnail is requested. There is a case where you might scroll to one place A, and then scroll to another place B before all the thumbnails were ready. Then, you might have to wait until Uppy has generated thumbnails for the files visible at A before any of the files at B start getting thumbnails. So, if a FileItem unmounts before a thumbnail is generated, we cancel the thumbnail request, which reduces that delay.
Issues:

List virtualization and lazy thumbnails

---

packages/@uppy/thumbnail-generator/src/index.js

As suggested in #2204. In my unscientific test, this is actually quite a bit faster, by about 33%!
Though not exactly configurable, I think this closes https://github.com/transloadit/uppy/issues/2204

thumbnail-generator: generate 80% quality jpegs

---

packages/@uppy/progress-bar/src/index.js

`state.totalProgress` is not `100`. It's `0` instead   
----------
To reproduce the error:  
```
.use(ProgressBar, {
target: '._progress_bar_',
fixed: false,
hideAfterFinish: true
})
```
This will set a `div` inside the `_progress_bar_` element, and this element will be visible, showing `0` to the user.
The problem is that, currently, the bar only hides when `progress === 100`, but that is never true, as `progress` resets to `0` once the upload has been completed.
That means, it is __always__ visible, and only hidden for a brief period after an upload completes (when the `progress === 100`, briefly).
This fix allows the bar to be hidden also when the progress is `0` (after and before uploads)

Hide Progressbar if no upload in progress

---

website/inject.js

when looking for the size of a plugin, I could never find it without
Ctrl+F because the order was essentially arbitrary. This change sorts
the plugins in the package size table alphabetically, while still
keeping the `uppy` and `@uppy/core` packages on top, and the
`@uppy/store-` packages at the bottom (unlikely to be interesting to
most people).

website: list robodog size, sort plugins by name

---

packages/@uppy/drag-drop/src/index.js
packages/@uppy/drag-drop/src/style.scss

Fixes #2249
Although I’m not sure if we should also stop wrapping the whole thing with a `button`, because `label+input` inside a button seems semantically incorrect.

drag-drop: Add label for the input for better a11y

---

packages/@uppy/core/src/Plugin.js

ref https://github.com/transloadit/uppy/issues/2212
If you provide a function that's _not_ a Plugin subclass, mention duplicate npm packages as a possible cause.

core: add some more suggestions to the 'incorrect `target`' warning

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
packages/@uppy/aws-s3-multipart/src/index.js
packages/@uppy/aws-s3-multipart/types/index.d.ts
packages/@uppy/aws-s3-multipart/types/index.test-d.ts
packages/@uppy/aws-s3/types/index.d.ts
packages/@uppy/aws-s3/types/index.test-d.ts
website/src/docs/aws-s3-multipart.md

Lets you provide a `getChunkSize` function to calculate the chunk size to use to split up files when doing an s3-multipart upload. We default to the old behaviour of using chunks that are as small as possible.

aws-s3-multipart: make chunk size configurable, fixes #1543

---

packages/@uppy/companion/src/companion.js
packages/@uppy/companion/src/standalone/helper.js
packages/@uppy/companion/src/standalone/index.js

this is a breaking change since the validation may throw an error

companion: validate companion options for non-standalone usage as well

---

packages/@uppy/tus/src/index.js

Fixes #2200 for tus in a similar way AwsS3 was fixed (#1650).
This fixed the issues I saw in my dev environment and didn't introduce any new failures when unit testing, e2e testing, starting and looking at dashboard, etc. as far as I could see!
If I missed some step in the process/testing process let me know @goto-bus-stop.

tus: resetUploaderRefs before emitting

---

packages/@uppy/transloadit/src/index.js

When canceling an upload, we would previously cancel all assemblies. But the Transloadit plugin state still contains Assemblies that had already finished. Instead of cancelling everything we know about, we need to only cancel Assemblies that belong to an ongoing upload. We can do that by cancelling all Assemblies that are reachable through the `uploadsAssemblies` state value.

transloadit: only cancel assemblies belonging to ongoing upload

---

packages/@uppy/locales/src/en_US.js
packages/@uppy/webcam/src/PermissionsScreen.js
packages/@uppy/webcam/src/index.js

@nqst:
> When I opened the Import from Camera screen, the access dialog didn't show up. I thought it's a Safari bug, but then realized I'm using an external display which have no camera :slightly_smiling_face:
Question: can we detect that there's no camera and show a relevant message instead?
(Tested on Safari, macOS; Display is connected to MacBook in clamshell mode)

webcam: Show “enable camera” screen if no camera device was detected

---

packages/@uppy/transloadit/src/index.js

This was causing the `ASSEMBLY_COMPLETED` Assembly statuses to be stored
under an `undefined` key, so you wouldn't actually get the final status
in the result data for the upload.

transloadit: fix property name typo

---

packages/@uppy/dashboard/src/components/FileItem/Buttons/index.js
packages/@uppy/dashboard/src/components/FileItem/FileProgress/index.js
packages/@uppy/dashboard/src/components/FileItem/index.js
packages/@uppy/dashboard/src/components/FileList.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/dashboard/types/index.d.ts
website/src/docs/dashboard.md

Closes #2131 and so many others:
>  yamifr07 commented on Mar 27
> If the library just display a delete button developers can implement their own delete logic. I really like this plugin but I must be able to edit uploaded data
Also fixes an issue which broke “copy link” functionality after #2161

Dashboard: add options to show remove button after complete

---

packages/@uppy/dashboard/src/index.js

Pass hideRetryButton and hidePauseResumeCancelButtons options to DashboardUI. They are already supported options in child components.

Pass hideRetryButton and hidePauseResumeCancelButtons options.

---

bin/make-new-versions-table

avoids [this](https://github.com/transloadit/uppy/commit/239a97b23f057c2657c9873f7506948b1cf41da5) in the future.

chores: catch custom version suffices (alpha, beta etc.)

---

packages/@uppy/drag-drop/src/index.js
packages/@uppy/drag-drop/src/style.scss

Hopefully fixes #2300 fixes #2297
I’m quite confused at what the best practice for hidden `<input type="file">` is, tried multiple things, and if we are going to hide the input with `aria-hidden` we don’t need weird CSS to hide it visually, since the point of hiding it visually was to leave it accessible for screen readers, which you don’t get with `aria-hidden`.

drag-drop: Fix the issue with click even occuring twice, try hiding the input altogether

---

packages/@uppy/companion/src/server/provider/index.js

following from [this PR](https://github.com/transloadit/uppy/pull/2310/files), it occurred to me that it don't make so much sense that users have to set [these options](https://github.com/transloadit/uppy/blob/4d54bf63633f90ac6b23456183e15d3622972805/examples/custom-provider/server/index.js#L57-L58).
Hence, in this PR, I am setting those options internally, so users won't have to set them anymore.

companion: set grant related options for custom providers

---

packages/@uppy/dropbox/src/index.js
packages/@uppy/facebook/src/index.js
packages/@uppy/google-drive/src/index.js
packages/@uppy/instagram/src/index.js
packages/@uppy/onedrive/src/index.js
packages/@uppy/provider-views/src/index.js

Once again, after [putting this tutorial together](https://github.com/transloadit/uppy/pull/2310/files) it became more obvious that Plugins shouldn't be concerned with setting state fields that is specifically used by only the `ProviderViews`. It should all be left to the `ProviderViews` to handle it.

provider-views: handle all plugin state in provider-views

---

packages/@uppy/companion/src/server/controllers/url.js
packages/@uppy/companion/src/server/helpers/request.js
packages/@uppy/companion/src/server/helpers/utils.js
packages/@uppy/companion/test/__tests__/http-agent.js

following up from [this PR](https://github.com/transloadit/uppy/pull/2083), it was reported that the SSRF issue may persist via redirects. The reason is because, even though [this custom dnsLookup](https://github.com/transloadit/uppy/blob/9355c1e3130700653179d6d7cc761e574b4a5ebd/packages/%40uppy/companion/src/server/helpers/request.js#L91-L108) is meant to prevent ips related to redirects as well, our custom [httpAgents](https://github.com/transloadit/uppy/blob/9355c1e3130700653179d6d7cc761e574b4a5ebd/packages/%40uppy/companion/src/server/helpers/request.js#L91-L108) (which contain the custom dnsLookup) get dropped whenever [the protocol of the redirect URL is different from the protocol of the original URL](https://github.com/request/request/blob/master/lib/redirect.js#L110-L113).
So in …

companion: block redirects to urls with different protocol

---

.travis.yml
packages/@uppy/companion/src/server/helpers/request.js

it seems companion.uppy.io is running on node < 10.0 where `URL` is not a global object, so it's breaking as reported here #2327 
The tests (or trying it locally) couldn't catch this because it runs on node 10+
fixes #2327

Import url

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
packages/@uppy/aws-s3-multipart/src/index.js

Do not store completed parts in state as they can be retrieved from S3 and do not need to be stored locally (this also fixes #2324)
closes #2325

S3 multipart: Do not store completed parts in state

---

packages/@uppy/dashboard/src/components/AddFiles.js
test/endtoend/chaos-monkey/main.js
test/endtoend/create-react-app/test.js
test/endtoend/wdio.local.conf.js

The chaos monkey test used `canvas.toBlob` which IE does not have.
The react test was probably broken by a Dashboard redesign, but we may not have noticed it because another was probably already broken then... I added a `data-acquirer-id` attribute to the DashboardTabs to make it a bit more robust in case there are more design tweaks in the future.
Locally the URL plugin test still fails for me with these changes, but I think that's due to some IE driver configuration, as it seems to work fine on saucelabs.

Fix end to end test failures on CI

---

packages/@uppy/companion/infra/kube/gcloud-deploy.sh

So, turns out I never checked in on the code fix for this..
Currently what happens:
```sh
docker build -t transloadit/companion:latest -t transloadit/companion:$TRAVIS_COMMIT -f packages/@uppy/companion/Dockerfile packages/@uppy/companion;
if [[ -z "${TRAVIS_TAG}" ]]; then
docker push transloadit/companion:$TRAVIS_COMMIT;
else
docker push transloadit/companion:$TRAVIS_TAG;
fi
```
So now, we have:
```sh
docker build -t transloadit/companion:latest -t transloadit/companion:$TRAVIS_COMMIT -f packages/@uppy/companion/Dockerfile packages/@uppy/companion;
if [[ ! -z "${TRAVIS_TAG}" ]]; then
docker tag transloadit/companion:$TRAVIS_COMMIT transloadit/companion:$TRAVIS_TAG;
docker push transloadit/companion:$TRAVIS_TAG;
fi
```

companion: fixes docker version tagging. fixes #1579.

---

packages/@uppy/companion-client/src/Provider.js
packages/@uppy/companion-client/types/index.d.ts
packages/@uppy/companion/src/companion.js
packages/@uppy/companion/src/config/grant.js
packages/@uppy/companion/src/server/provider/index.js
packages/@uppy/companion/src/standalone/helper.js
packages/@uppy/companion/src/standalone/index.js
packages/@uppy/google-drive/src/index.js
packages/@uppy/instagram/src/index.js

This helps minimise the inconsistency, as the providers are originally referred to as onedrive and drive (for Google Drive), it's confusing that you have to set options for _microsoft_  and _google_ instead.

companion: rename microsoft and google options to onedrive and drive respectively

---

packages/@uppy/core/src/index.js
packages/@uppy/core/src/index.test.js

fixes #2298
If there are no files to retry, short-circuit instead of running through the entire upload pipeline without any files.

core: do not create an upload in retryAll() if there were no errors

---

packages/@uppy/companion/src/server/controllers/oauth-redirect.js
packages/@uppy/companion/src/server/provider/index.js
packages/@uppy/companion/test/__tests__/companion.js
packages/@uppy/companion/test/__tests__/provider-manager.js
packages/@uppy/companion/test/mockserver.js

With this PR, all redirect_uris that will be provided to oauth dashboards can now be consistent with the pattern: 
`/${providerName}/redirect`
so for Google Drive: `/drive/redirect` previously `/connect/google/callback`
for OneDrive: `/onedrive/redirect` previously `/connect/microsoft/callback` (confusing, I know)
for Facebook: `/facebook/redirect` previously `/connect/facebook/callback`
It'll avoid confusions like [this one](https://github.com/transloadit/uppy/pull/2345#discussion_r446966856)

companion: override grant's default redirect_uri for consistent provider options

---

packages/@uppy/tus/src/index.js

We should be checking if the array _element_ exists, not if the _array_ exists.

tus: fix typo, fixes #2376

---

package-lock.json
packages/@uppy/dashboard/package.json
packages/@uppy/dashboard/src/components/Dashboard.js

Fixes #2226 
Fixes #2377 
preact-css-transition-group has specified a peerDependency on _any_ preact version.
```json
"peerDependencies": {
"preact": "*"
}
```
this means that if you have a Preact X-based app with a dependency tree like this:
```
app
- preact@10
- @uppy/dashboard
- preact@8
- preact-css-transition-group
```
npm is allowed to hoist preact-css-transition-group up like this:
```
app
- preact@10
- preact-css-transition-group
- @uppy/dashboard
- preact@8
```
Now, when preact-css-transition-group does `require('preact')`, it gets preact X and not preact 8. This way preact 8 nodes created by the Dashboard can flow into preact 10 nodes created by preact-css-transition-group.
I tried to address this by pinning the peer dependency and republishing the package as …

dashboard: preact version fun

---

packages/@uppy/aws-s3/src/index.js
packages/@uppy/aws-s3/src/isXml.js
packages/@uppy/aws-s3/src/isXml.test.js

This improves the type checking to prevent error `TypeError: rawContentType is undefined`

aws-s3: better typecheck to prevent accessing undefined var

---

packages/@uppy/locales/src/de_DE.js

If 'browseFiles' isn't defined, the default English text will show, which is ofc. undesired.

Added new string 'browseFiles' (same as 'browse')

---

packages/@uppy/utils/src/isPreviewSupported.js
packages/@uppy/utils/src/isPreviewSupported.test.js

I added support to load thumbnails when uploading AVIF images, by adding 'avif' to the regex. I also updated the unit test.
Note that support for this is dependant on browser support, and currently only Chrome 85+ and Firefox 77+ support it (Firefox requires flag to be set to allow it)
Resolves #2357

dash: Add support for AVIF images in thumbnails

---

packages/@uppy/transloadit/src/index.js

In #2239, I added a backwards compatible implementation for the `resume`
option from tus-js-client v1, but forgot to disable it again in the
Transloadit plugin.
Fixes #2382

transloadit: fully disable Tus fingerprinting

---

packages/@uppy/dashboard/src/components/AddFiles.js

Not sure how this happened—they were inverted for the legacy variants and always used the `import` string for the new variants.
Fixes #2421

dashboard: use correct strings on AddFiles UI

---

packages/@uppy/companion/package.json
packages/@uppy/companion/test/run.js

I think it's the quotes in the npm run script that are not working, so this uses a node.js script to do the spawning instead.

companion: make npm run test work on windows

---

packages/@uppy/provider-views/src/index.js

On the dashboard, when uploading a folder, if files from that folder are not successfully added, the count would still say they are there
For example, If you're using Google Drive, and upload a folder with 3 images and 2 mp3 files. If you also have a restriction set to only allow images, Dashboard would still read something like "5 Files Added", even though only 3 would be there. 
I resolved this by making the `addFile` method in the `provider-views` package return a boolean value based on whether or not the file was added successfully. I then created a count variable with the `addFolder` method and added to that count for every successful addition. Using that count instead of the total count of files in the folder fixes this problem
Resolves #2038

Fix: Incorrect File Added Count

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js

I'm creating this pull request since I have real use case when I need to upload zero-sized file and currently it's not possible to do using **aws-s3-multipart** uploader.
After fixing, I tested it and it works normally, same as it's any other file.
Also, as far as I checked, this change doesn't affect upload of other non-zero sized files.
Before commit _zero-sized_ file couldn't be uploaded successfully since _chunks_ array was always empty and `_completeUpload()` method was called immediately without reserving and uploading any part of the file.
Chunks array wasn't populated because inside `_initChunks()` method there was a size check using `<` sign, so if _zero-sized_ file comes, it would never enter the for loop.
After commit there is size check with `<=` sign, so even for _zero-sized_ …

Enable uploading zero-sized file with aws-s3-multipart-upload

---

packages/@uppy/screen-capture/src/RecordButton.js

This PR fixes the translations in the screen capture plugin which makes it work again.

fix: translations for capturing

---

packages/@uppy/aws-s3/src/MiniXHRUpload.js
packages/@uppy/aws-s3/src/index.js

I tried to cheat this a bit initially by using `Translator` instance from Uppy Core, but we do need a separate instance with proper defaults for AwsS3 to make the strings work consistently.

aws-s3: add default locale for MiniXHRUpload, fixes #2459

---

packages/@uppy/companion/src/server/Uploader.js

Hi, as described in this [PR](https://github.com/transloadit/uppy/pull/2387) `content-length` is an expected header when uploading to s3. In this PR I'm adding context-length calculation for the formData scenario. Had to factor out the http request since `form.getLength` from form-data expects a callback.

companion: add calculated content-length for formdata and body cases

---

packages/@uppy/aws-s3-multipart/src/MultipartUploader.js

Fixes #2463
There was an issue with the timing of the `_uploadParts()` call. That
function is responsible for _starting_ the upload of multiple parts of
the file. It can start up to `limit` simultaneous uploads, depending on
how many parts are currently uploading.
`_uploadParts()` was called during the completion code for an individual
part. However, the `partsInProgress` state would not be updated until
_after_ the completion code had run. So, inside `_uploadParts()`, it
would see an outdated `partsInProgress` value. Often, this worked OK (if
not optimally) because there would likely be another part in progress,
and once _that_ finished, there would be space again in the
`partsInProgress` value. However, this was _not_ the case if `limit` was
set to 1. In that case, the first part would …

aws-s3-multipart: fix stuck upload with `limit: 1`

---

packages/@uppy/companion/src/server/Uploader.js

following from this [PR](https://github.com/transloadit/uppy/pull/2466/files), I dug deeper and found that `content-length` is actually [set by the request module](https://github.com/request/request/blob/df346d8531ac4b8c360df301f228d5767d0e374e/request.js#L571-L576) for the case of form data. It is only not set for the case of read streams.
So this PR removes the FormData hack, and only sets content-length for the case of non-formdata uploads.
This PR is also important because the FormData hack actually doesn't work. It leveraged on an outdated internal behaviour of the `request` module which is no longer the same.
cc @johnnyperkins @mejiaej

companion: fix multipart upload

---

packages/@uppy/companion/src/server/provider/dropbox/index.js

Currently when DropBox fetches a list of files it includes files with `is_downloadable: false`.
This causes companion to return a `409 conflict` when trying to upload these files from DropBox.
This simple fix tells DropBox not to include these files in the fetched list.
This seems like the best fix to me although there are two alternatives:
1. Add an indicator when displaying the file so users know they can't upload the file.
This way users aren't confused to why they can't see the file.
2. Use DropBox's api to export the file to a downloadable format and upload that. [See](https://www.dropbox.com/developers/documentation/http/documentation#files-export)
If either of those two options are desirable it still seems best to merge this change as a better intermediate solution.
Showing a user …

companion:dropbox: exclude non downloadable files in fetched list

---

packages/@uppy/aws-s3/src/index.js

Added the invalid `params` to the error message so it'll be easier to understand the problem and how to fix it

Improved validateParameters() error message

---

packages/@uppy/companion/src/server/provider/zoom/adapter.js
packages/@uppy/companion/src/server/provider/zoom/index.js

This diff fixes the file uploads for closed captioning (CC VTT) files because they lack file IDs, similarly to timeline files earlier.  It also cleans up / removes code around processing timeline files because these should be omitted from results for the end user (they are json files meant for programmatic use, and omitted from Zoom's own website when showing cloud recordings to users).  Note: stopping and starting a recording produces 2 seperate sets of CC VTT files which is why we've got the additional recording start information added to the id and the query paramter 
To test this out end to end:
-  the zoom account settings need to be changed so that closed captioning is enabled under settings -> Meetings -> Closed Captioning (note this setting is not under cloud recordings, but under …

Omit timeline files and fix cc type files for zoom provider

---

packages/@uppy/companion/src/server/provider/zoom/adapter.js
packages/@uppy/companion/src/server/provider/zoom/index.js

This PR fixes an issue with the pagination when an account creation date is the same month as the date range limit.
Example scenario: user account creation date is September 20, 2018 (so just over the date range limit) if I'm querying today (September 4, 2020
- we set the default limit to start on the first of the month (prevents the awkward start date on the oldest folder on default page load)
- if the limit is set by the account creation, we keep that specific mid-month date
- if the limit is set by the account creation and it's within the same month as the range to show, we'll just tack it on
- we adjust the cursor query accordingly for pagination 
To test:
- For local testing, you should be able to modify the user account json response, or modify the limit date and handle pagination

Update the pagination limit / boundary on the zoom provider

---

packages/@uppy/locales/src/fr_FR.js

There was an issue with the translation in `fr_FR` locale where the text was in english. I fixed it with a wording similar to other translations around it but I'm wondering why the `'1'` translation is ending with an `'s'` when it's singular

Fixed translation of uploadingX in french locale

---

packages/@uppy/companion/src/server/provider/zoom/adapter.js
packages/@uppy/companion/src/server/provider/zoom/index.js

We currently have an issue where the call to retrieve files fails when a meeting UUID contains '/' character. This pr fixes this issue by double encoding the UUID
The Zoom API docs notes ( https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/recordingget) :
```To get Cloud Recordings of a meeting, provide the meeting ID or meeting UUID. If the meeting ID is provided instead of UUID,the response will be for the latest meeting instance. \n\nTo get Cloud Recordings of a webinar, provide the webinar ID or the webinar UUID. If the webinar ID is provided instead of UUID,the response will be for the latest webinar instance. \n\nIf a UUID starts with \"/\" or contains \"//\" (example: \"/ajXp112QmuoKj4854875==\"), you must **double encode** the UUID before making an API …
```

Zoom Plugin - Fix cases where a meeting UUID has slashes

---

packages/@uppy/dashboard/package.json
packages/@uppy/dashboard/src/components/AddFilesPanel.js
packages/@uppy/dashboard/src/components/Dashboard.js
packages/@uppy/dashboard/src/components/EditorPanel.js
packages/@uppy/dashboard/src/components/FileCard/index.js
packages/@uppy/dashboard/src/components/PickerPanelContent.js
packages/@uppy/dashboard/src/components/Slide.js

Unfortunately I can't figure out how to make the dependencies and
versions work out well here.
Instead, this uses a custom slide transition component. It is much more
simple than preact-css-transition-group, which supports animating groups
of components. The `<Slide />` component:
- can only support one element, that either exists or does not exist
- requires that the child element takes a `className` property, that it
passes onto its root element
- only uses `setTimeout()` for when the transition finishes
(in preact-css-transition-group, the `transitionend` event is used,
which is more _accurate_ but less _reliable_)
- hardcodes the transition duration
- hardcodes the transition name
This makes it much more limited. Hopefully the reduced complexity is
worth it.
If we have other …

dashboard: remove preact-css-transition-group

---

package-lock.json
package.json
packages/@uppy/companion/package.json
packages/@uppy/companion/src/server/provider/zoom/adapter.js
packages/@uppy/companion/src/server/provider/zoom/index.js

This PR resolves a couple issues:
- it adds moment-timezone as an explicit dependency (right now, we're relying on the fact that moment is a global js object, which is implicitly available because the "expo" dependency installs a copy) and updates the package-lock file accordingly. I wasn't sure if there were intentional edits to package-lock previously done or if it's fully auto-generated so please let me know if the package-lock update is an issue / should be omitted
- it fixes the zoom provider to use UTC time rather than the default server time, and the timezone provided by the user's zoom settings where required. In particular:
- account creation date should now be displayed in local time 
- each date range folder should correctly display meetings for that range in local time
- each …

Zoom Plugin - Fix meeting timestamp for user timezones and explicitly include moment-timezone dependency

---

packages/@uppy/provider-views/src/index.js

Continues to use cached username instead of using the updated one sent from the companion server.
To reproduce: Connect to OneDrive, then click Log out and reconnect with another account.

fix username not updating when switching OneDrive accounts

---

packages/@uppy/provider-views/src/index.js

This change updates the uppy provider views to allow for nested folders to be added when a user selects a folder (described in https://github.com/transloadit/uppy/issues/2551).
Right now, when I try to select a folder with only subfolders, I get an error that no files are present.   The intent of this pr is to support nested folder structures like shown below:
No files in top level folder, but files present in subfolders 
Files present in top level folder and subfolders
As far as I could tell, this was the only spot that needed to be updated, as `addFolder` seems to handle syncing the uppy state for folders, and add `listAllFiles` already seems to handle infinite scroll, and  file vs folder support.
I'm not sure if this was intentionally not supported because of rate limit or other issues …

Add support for uploading nested folders

---

website/src/docs/image-editor.md

The editor is unusable if you're importing stylesheets individually and leave this one out.  In line with the documentation of other plugins, I added a note to import the relevant CSS file.

Include required CSS import

---

packages/@uppy/locales/src/de_DE.js

Translations seem to be missing in all languages except en_US & zh_CN.
This pull requests adds these missing translations for camera texts in German.

Add missing camera translations to de_DE

---

packages/@uppy/core/src/index.js

A fix for this [issue](https://github.com/transloadit/uppy/issues/2534). I don't know if this is the best way to solve the bug but It works in my case. The `postprocess` property should be set up if there is any postprocessor, that way the success icon is not going to appear at the end of `upload-success`. That is possible because there is an existing [validation in a dashboard component](https://github.com/transloadit/uppy/blob/master/packages/%40uppy/dashboard/src/components/FileItem/index.js#L31) that checks for that property.
Question: Are the packages of this PR deployed somewhere? I need to use my forked version but it is becoming complicated since uppy uses mono repo and can't just simple do `yarn add https://github.com/myaccount/forked-repo` since I only need @uppy/core from my …

core: add postprocess progress when upload success

---

website/src/docs/companion.md
website/themes/uppy/source/css/_page.scss

The Companion docs page is ~broken on mobile:
I added the **inline code blocks wrapping,** significantly simplified the **Redirect URIs table,** and tweaked **some small typographic thingies** as well.
> <img width="1033" alt="image" src="https://user-images.githubusercontent.com/375537/96844117-cc771a80-1457-11eb-8313-5c9952674c39.png">
↓ ↓ ↓
> <img width="1021" alt="image" src="https://user-images.githubusercontent.com/375537/96844198-e6b0f880-1457-11eb-9771-00447f479304.png">
The page has no horizontal scroll and isn't looking broken anymore. The table is a bit wider than the container (on my iPhone XR at least), but it's easily scrollable — and doesn't affects the page.
P.S. This should solve the `Google's Mobile Usability issues detected` problem. /cc @kvz

Mobile issues fixes + compact Companion migration table

---

packages/@uppy/dashboard/src/index.js
packages/@uppy/thumbnail-generator/src/index.js
website/src/docs/thumbnail-generator.md

Follow up of https://github.com/transloadit/uppy/pull/2601
Makes the MIME Type of thumbnails configurable on the ThumbnailGenerator and on the Dashboard. Default stays `image/jpeg`. 
There is no good documentation on what MIME types canvas supports however I found this: https://kangax.github.io/jstests/toDataUrl_mime_type_test/
Not sure if you want to include a list of supported mime types in the documentation.

Support for png thumbnails

---

packages/@uppy/companion/src/server/provider/onedrive/index.js

Was using org's default Sharepoint site, instead of user's OneDrive.
You can see the difference in [MS Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) by comparing the requests "https://graph.microsoft.com/v1.0/drive/" and "https://graph.microsoft.com/v1.0/me/drive"
I'm also working on a separate PR to show all drives available to the user, which would allow them to select from either their OneDrive or from any of their org's sharepoint drives.

onedrive: fix OneDrive for Business

---

packages/@uppy/dashboard/src/components/FileItem/Buttons/index.js
packages/@uppy/dashboard/src/components/FileItem/index.js
packages/@uppy/dashboard/src/components/FileList.js
packages/@uppy/dashboard/src/index.js

If Dashboard isn’t passed `metaFields`, but the Image Editor is used, the edit icon that usually opens the meta field editor will now take you straight to the image editor.
Fixes #2604

image-editor: show “edit” icon even when metaFields are not specified

---

packages/@uppy/companion/src/server/provider/dropbox/index.js

sometimes fetching a dropbox user's details may return a failed status code, we should be catching that too.

companion: catch errors when fetching dropbox user email

---

package-lock.json
packages/@uppy/tus/src/index.js

The onBeforeRequest callback cant be changed by Tus options after the changes on the issue #2518 
In this case, I think that we could skip the default callback definition if the callbacck was passed through Tus options

tus: add `onBeforeRequest` option

---

packages/@uppy/xhr-upload/types/index.d.ts

`withCredentials` and `responseType` are available options when using `XHRUpload`, but they are not included in the type signature of `XHRUploadOptions`.

Add missing option types to XHRUploadOptions

---

website/src/docs/uppy.md

Removed a comment no longer relevant since the parameter was added in #2594

Update Docs - Remove no longer relevant prerelease note on maxTotalFileSize

---

website/src/docs/uppy.md

I recently posted https://github.com/transloadit/uppy/issues/2633 regarding total upload progress, asking for this feature. Turns total upload progress exists and is just undocumented. 
I have added the the progress event to the uppy website documentation in hopes that it could help another person in the future.

Updated website docs added total upload progress event

---

packages/@uppy/companion/src/server/helpers/jwt.js

Now it is not possible to build companion locally, because required parameters can't follow optional ones

fix: jwt helper optional parameters

---

packages/@uppy/aws-s3/src/index.js

I had quite a hard time figuring my backend pre-sign function was returning the wrong method, because the displayed error was pointing me in the wrong direction. Added this for the sake of clarity.

S3 validate parameters: display correct error for wrong method

---

website/src/docs/react-initializing.md

Based on #2509 updating `useMemo` to `useRef` and updating the `useUppy` example hook to reflect that change.
In the hooks example, I chose to expose `uppy.current` from the hook as opposed to the ref directly and relying on the caller to remember to use `.current`. This felt like a good encapsulation and less likely for a caller to forget to include `.current` - but open to thoughts on this if there's a good reason to expose the ref directly I'm missing.

For React Initialization Docs, update useMemo to useRef

---

BACKLOG.md
CHANGELOG.md

Hi!
I would like to make the suggestion to keep the backlog in a separate file. I always use the changelog file to keep up-to-date with a project and also to see what developers have been up to. Uppy is the exception where you have to scroll down quite a lot to find the right information. Of course, it's great to have a documented backlog but to my mind it would be better to have it separate. This would also serve as an example to other projects and perhaps eventually establish it as a good development practice just like the idea of a changelog file.
I made some slight changes to the phrasing of the sentences. Feel free to make changes.
Hope you like my idea!

Separate backlog from CHANGELOG.md into BACKLOG.md

---

packages/@uppy/core/src/index.js

Fixes #2647
Without this, `restrictions.maxNumberOfFiles` were ignored when bulk-adding files via `uppy.addFiles`. Thanks so much @NermienBarakat for reporting!
@goto-bus-stop can we use `Object.values`? Not supported in IE10-11, got confused, seems like we’d need core-js, so overkill? https://babeljs.io/docs/en/babel-preset-env#usebuiltins

core: pass files array to _checkRestrictions

---

bin/upload-to-cdn.js

Due to some missing changes from #2608, the domain for CDN releases was messed up. For example, the domain should've been `https://releases.transloadit.com/uppy/v1.23.2/uppy.min.js`, but was instead `http://releases.transloadit.com/uppy/releases/uppy/v1.23.2/uppy.min.js`. This was artifact from using `edgly.net ` domains, which included `/releases/` in the path.
This was also tested locally and should work correctly

fix: Fixed CDN Upload path

---

bin/remove-accidental-git-tags.sh

I noticed this while reviewing the [Box PR](https://github.com/transloadit/uppy/pull/2549/files#diff-2897b0f6ed6ab54d616e19406de98703f303bc91e913a8cb64d1efc2ba1444ecR8)

build: add zoom to "remove-accidental-tags" script

---

.eslintrc.json
packages/@uppy/provider-views/src/ProviderView/ProviderView.js
packages/@uppy/transloadit/src/Client.js
packages/@uppy/tus/src/index.js
website/build-examples.js

Since the Github Actions switch, lint warnings show up in the PR UI, so things will be less cluttered if we just fix all existing ones.

silence or fix lint warnings

---

package-lock.json
packages/@uppy/thumbnail-generator/package.json

I think the thumbnail rotation issue mentioned in #2309 was already fixed in exifr 5.0.5, which is within our accepted version range, but which may not be auto installed for users who have a lockfile with an older version.
So this version bump is not necessary to fix anything, but will opt us in to future improvements to the exifr library.

thumbnail-generator: upgrade exifr to v6

---

packages/@uppy/companion/src/server/Uploader.js

Hi, as described in this [issue](https://github.com/transloadit/uppy/issues/2682). I want to avoid any potential `fs.stat` delay which can be caused by infrastructure such as EFS. The best way to do it is to remove any potential delay between the creation of the `readStream` and the HTTP request to the destination.
I found that `this.bytesWritten` contains the number of bytes of the file downloaded from a provider(google drive, one drive, etc.). And, because companion uploads that same file it is safe to use it as `content-length` when uploading. In fact, the code already [uses this.bytesWritten as a synonym of `bytesTotal`](https://github.com/transloadit/uppy/blob/master/packages/%40uppy/companion/src/server/Uploader.js#L331)
please let me know if there is anything that I didn't clearly …

Remove fs stat and use bytesWritten as content length

---

packages/@uppy/unsplash/package.json

This is because we added some new i18n keys to core when we implemented unsplash

unsplash: unsplash needs uppy/core to be 1.13.3 or higher

---

package-lock.json
packages/@uppy/companion/package.json
packages/@uppy/companion/src/standalone/index.js

express-prom-bundle 5 requires prom-client 11, but we had already upgraded to prom-client 12. For prom-client 12, we must also upgrade to express-prom-bundle 6.
should fix
```
npm ERR! peer dep missing: prom-client@^11.1.2, required by express-prom-bundle@5.0.0
```
This is blocking dockerhub releases and causing invalid install trees for users, so it would be good to get this change published ASAP 😄

companion: upgrade express-prom-bundle to v6

---

packages/@uppy/status-bar/types/index.d.ts

Not all of the documented options were in the types file, this fixes that. Added types:
- `hideRetryButton`
- `hidePauseResumeButton`
- `hideCancelButton`
- `doneButtonHandler`
Closes #2694

types: Corrected StatusBar types

---

packages/@uppy/core/src/index.js
packages/@uppy/dashboard/src/index.js
packages/@uppy/image-editor/src/style.scss
website/src/docs/dashboard.md
website/src/docs/uppy.md

Changes:
- New `@uppy/core` event: `final-file-added`
- New Dashboard option: `autoOpenFileEditor` — if `true`, Dashboard will open the image editor once `final-file-added` is fired
- More visible crop area for the Image Editor

dashboard: add autoopen for file editors (image-editor)

---

website/src/docs/aws-s3.md

Issue it's referring to was closed in https://github.com/transloadit/uppy/pull/2060

Remove warning about multiple uploads on S3 which is now fixed

---

packages/@uppy/dashboard/src/components/FileCard/index.js
packages/@uppy/dashboard/src/components/FileItem/Buttons/index.js
packages/@uppy/dashboard/src/index.js
website/src/docs/dashboard.md

Builds on what @lacieri started in https://github.com/transloadit/uppy/pull/2728, following the conversation in https://github.com/transloadit/uppy/issues/2340.

Dashboard: emit fileId on both file-edit-start and file-edit-complete events

---

packages/@uppy/companion/Dockerfile

Using a multi-stage build so that the build dependencies do not end up in the final image. Saves a bit on the image size as well.

use multi-stage docker build

---

packages/@uppy/companion/src/server/controllers/s3.js

I assumed `Expires` had to do with signed URL expiration, but in the
case of `createMultipartUpload`, it affects the _uploaded file itself_.
Those files are not automatically removed but no longer cacheable after
the expiration time, which is still bad.
Thanks to @Dock1100 for raising this! Fixes #2483.

companion: remove incorrect `Expires` option

---

packages/@uppy/transloadit/src/index.js

Another small fix from the bottom of my assigned issues list!
This one is for functionality that was broken for apparently many months 😬 
The Transloadit plugin has an `importFromUploadURLs` option that lets you use a separate uploader plugin like AwsS3Multipart, and then import those files into transloadit. To do that we first tell Transloadit how many files to expect with this `reserveFile()` function. That function should receive an Assembly status object, but we were passing it a wrapper for that object. This patch unbreaks it.

transloadit: fix #2626

---

packages/@uppy/xhr-upload/src/index.js
packages/@uppy/xhr-upload/src/index.test.js
packages/@uppy/xhr-upload/types/index.d.ts
website/src/docs/xhrupload.md

With this patch you can do
```js
uppy.use(XHRUpload, {
headers: file => ({
'authorization': `bearer ${global.userToken}`,
'header-name': file.meta.someMetaValue
})
})
```
to determine file-specific headers.
The function syntax for `headers` is only available if the `bundle`
option is `false` (the default). `bundle` uploads only use one set of
headers.
Closes #2299
Closes #2522

xhr-upload: accept a `headers: (file) => {}` function

---

packages/@uppy/core/src/index.js
packages/@uppy/transloadit/src/index.js

When the Transloadit plugin can't connect to Transloadit's WebSocket endpoints, it falls back to polling the Assembly status endpoint.
The polling interval was only cleared if the *WebSocket* told us the Assembly finished. So if the WebSocket connection was never set up, we would keep polling the Assembly status endpoints after the upload had finished. Doesn't cause any crashes or bugs but it does waste a lot of bandwidth over time. Now the polling interval is always cleared by calling `assembly.stop()` after the Assembly has finished.
There was a case where the UI would show the postprocessing state while the upload had already completed. I've tried to explain the details in a code comment.

transloadit: fix polling fallback bugs

---

packages/@uppy/dashboard/src/style.scss
packages/@uppy/status-bar/src/style.scss

The DOM changed to accomodate RTL scripts, but this CSS rule was not
changed accordingly.
The StatusBar does not know its own width, so a standalone StatusBar
would never have an `.uppy-size--md` parent element. You only get that
with the Dashboard. So I've moved the rule to the Dashboard plugin, and
the selector now checks for `.uppy-Dashboard`. That element also has the
size classes.
The standalone StatusBar does not auto-hide progress details on narrow
screens. I think that's probably fine, if you're using it directly and
explicitly asking for progress details you might want to always see
them…

dashboard: fix showing showProgressDetails on md and up

---

packages/@uppy/utils/src/getFileTypeExtension.js
packages/@uppy/utils/src/getFileTypeExtension.test.js

Safari 14.0 on Mac records audio (using the Webcam Uppy component) with MIME type ‘audio/mp4’, which isn't a recognised MIME type in Uppy. 
This fix updates the file extensions checker to add this MIME type, as otherwise audio cannot be recorded with Safari.

[FIX] Safari 14.0 on Mac records audio using audio/mp4 MIME type which isn't currently recognised by Uppy

---

packages/@uppy/locales/src/nl_NL.js

Verb grammatical mistake: `-dt` -> `-d`

Fix Dutch spelling mistake

---

packages/@uppy/transloadit/src/Client.js

Currently if you provide the following service URLs for the `Transloadit` plugin, any uploads will fail. 
1. https://api2-ap-southeast-1.transloadit.com/
2. https://api2-eu-west-1.transloadit.com/
3. https://api2-us-east-1.transloadit.com/
This is because our concatenation introduces a double //. A user could get these URLs from https://transloaditstatus.com/ by doing the following:

Make url concatenation more robust

---

packages/@uppy/core/src/index.js
packages/@uppy/provider-views/src/ProviderView/ProviderView.js
packages/@uppy/utils/src/RateLimitedQueue.js
packages/@uppy/utils/src/findIndex.js
packages/@uppy/utils/src/findIndex.test.js

`uppy.removePlugin()` started failing to do its job when used in a Vue3 component https://github.com/transloadit/uppy/pull/2755, because [Vue3 started using](https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes) [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy):
> When you pass a plain JavaScript object to an application or component instance as its data option, Vue will walk through all of its properties and convert them to Proxies using a handler with getters and setters. 
So when we did `const index = list.indexOf(instance)` it would always return `-1`, because `Obj !== ObjProxy`, and the plugin was not removed from Uppy, and its `render` was being called even when its `pluginState` was emptied out, resulting in:
``` …
```

Use Array.findIndex instead of Array.indexOf in uppy.removePlugin

---

packages/@uppy/companion/src/server/controllers/s3.js

I thought of this as a server-side issue when initially writing it, but
if you don't have S3 uploads configured, users can still target the
endpoint. So that endpoint should never crash the process.
With this change users get a 400 response when trying to start an S3 upload
of remote files if their Companion server does not support it.

companion: fix crash when S3 is not configured

---

website/src/docs/providers.md

The providers page in the documentation lists an older set of supported services, rather than the current, fuller list (as far as I can tell).
This PR doesn't tweak the list at the top of the page, which says 'such as' before jumping into a list.

Update providers.md with the full set of services

---

BUNDLE-README.md
bin/build-bundle.js

The idea here is that someone that downloads https://releases.transloadit.com/uppy/v1.9.3/uppy-v1.9.3.zip and extracts it, then has a easier time adding it to their e.g. php/jquery app. 
Or let's say maybe you ship a product similar to Nextcloud and you don't use npm (contrived).

Add a README.md specific to bundles

---

packages/@uppy/dashboard/types/index.d.ts

Added missing type to dashboard which is present in the documentation: https://uppy.io/docs/dashboard/#doneButtonHandler
`doneButtonHandler`

Add missing doneButtonHandler type to dashboard
